import re

# 中文词汇到英文的映射
chinese_to_english = {
    "人际关系": "interpersonal relationships",
    "科技": "technology",
    "科技与人际关系": "technology and interpersonal relationships",
    "电视暴力影响": "television violence",
    "广告的影响": "advertising impact",
    "名人崇拜": "celebrity culture",
    "动物权利": "animal rights",
    "网络隐私": "online privacy",
    "家庭教育": "family education",
    "艺术价值": "artistic value",
    "纸质书籍": "printed books",
    "传统节日": "traditional festivals",
    "生活平衡": "life balance",
    "工作": "work",
    "工作与生活平衡": "work-life balance",
    "全球化文化": "globalization and culture",
    "友谊": "friendships",
    "社交媒体": "social media",
    "社交媒体与友谊": "social media and friendships",
    "幸福": "happiness",
    "金钱": "money",
    "金钱与幸福": "money and happiness",
    "标准化教育": "standardized education",
    "移民影响": "immigration impact",
    "科技依赖": "technological dependence",
    "快餐文化": "fast food culture",
    "环境保护": "environmental protection",
    "城市化": "urbanization",
    "交通问题": "traffic problems",
    "医疗保健": "healthcare",
    "教育质量": "education quality",
    "犯罪率": "crime rate",
    "能源危机": "energy crisis",
    "文化传承": "cultural heritage",
    "多元文化": "multiculturalism",
    "信息时代": "information age",
    "人工智能": "artificial intelligence",
    "自动化": "automation",
    "气候变化": "climate change",
    "可再生能源": "renewable energy",
    "经济发展": "economic development",
    "贫富差距": "wealth gap",
    "社会福利": "social welfare",
    "公共服务": "public services",
    "职业发展": "career development",
    "心理健康": "mental health",
    "体育锻炼": "physical exercise",
    "饮食习惯": "eating habits",
    "媒体影响": "media influence",
    "新闻自由": "freedom of press",
    "言论自由": "freedom of speech",
    "民主制度": "democratic system",
    "政府职能": "government functions",
    "国际关系": "international relations",
    "全球合作": "global cooperation",
    "贸易往来": "trade relations",
    "文化交流": "cultural exchange",
    "旅游发展": "tourism development",
    "历史遗迹": "historical sites",
    "自然资源": "natural resources",
    "生态平衡": "ecological balance",
    "物种保护": "species conservation",
    "环境污染": "environmental pollution",
    "垃圾处理": "waste management",
    "资源短缺": "resource shortage",
    "人口增长": "population growth",
    "老龄化": "aging population",
    "性别平等": "gender equality",
    "种族歧视": "racial discrimination",
    "社会公平": "social justice",
    "道德伦理": "ethics and morality",
    "职业道德": "professional ethics",
    "诚信问题": "integrity issues",
    "学术造假": "academic fraud",
    "知识产权": "intellectual property",
    "网络安全": "cybersecurity",
    "数据隐私": "data privacy",
    "电子商务": "e-commerce",
    "在线教育": "online education",
    "远程办公": "remote work",
    "共享经济": "sharing economy",
    "创业精神": "entrepreneurship",
    "创新能力": "innovation capability",
    "竞争力": "competitiveness",
    "市场机制": "market mechanism",
    "政府干预": "government intervention",
    "经济政策": "economic policy",
    "货币政策": "monetary policy",
    "财政政策": "fiscal policy",
    "税收制度": "tax system",
    "社会保障": "social security",
    "医疗保险": "health insurance",
    "养老保险": "pension system",
    "教育制度": "education system",
    "高等教育": "higher education",
    "职业培训": "vocational training",
    "技能发展": "skill development",
    "人才流失": "brain drain",
    "就业问题": "employment issues",
    "失业问题": "unemployment issues",
    "劳动权益": "labor rights",
    "工作环境": "work environment",
    "职业安全": "occupational safety",
    "企业文化": "corporate culture",
    "团队合作": "teamwork",
    "领导力": "leadership",
    "管理模式": "management model",
    "组织结构": "organizational structure",
    "市场营销": "marketing",
    "品牌建设": "brand building",
    "客户服务": "customer service",
    "产品质量": "product quality",
    "消费者权益": "consumer rights",
    "市场竞争": "market competition",
    "商业道德": "business ethics",
    "社会责任": "corporate social responsibility",
    "可持续发展": "sustainable development",
    "绿色经济": "green economy",
    "低碳生活": "low-carbon lifestyle",
    "节能减排": "energy conservation and emission reduction",
    "循环经济": "circular economy",
    "智慧城市": "smart city",
    "数字城市": "digital city",
    "智能交通": "intelligent transportation",
    "物联网": "Internet of Things",
    "大数据": "big data",
    "云计算": "cloud computing",
    "虚拟现实": "virtual reality",
    "增强现实": "augmented reality",
    "区块链": "blockchain",
    "5G技术": "5G technology",
    "量子计算": "quantum computing",
    "生物技术": "biotechnology",
    "基因编辑": "gene editing",
    "医疗科技": "medical technology",
    "航天技术": "space technology",
    "新能源汽车": "new energy vehicles",
    "自动驾驶": "autonomous driving",
    "智能机器人": "intelligent robots",
    "无人机": "drones",
    "智能家居": "smart home",
    "智能穿戴": "wearable technology",
    "移动支付": "mobile payment",
    "电子政务": "e-government",
    "数字鸿沟": "digital divide",
    "数字素养": "digital literacy",
    "信息安全": "information security",
    "网络犯罪": "cybercrime",
    "网络欺凌": "cyberbullying",
    "虚假信息": "misinformation",
    "信息过载": "information overload",
    "注意力经济": "attention economy",
    "算法推荐": "algorithm recommendation",
    "内容创作": "content creation",
    "自媒体": "self-media",
    "直播带货": "live commerce",
    "短视频": "short videos",
    "社交媒体营销": "social media marketing",
    "网红经济": "influencer economy",
    "粉丝经济": "fan economy",
    "知识付费": "knowledge payment",
    "在线学习": "online learning",
    "慕课": "MOOC",
    "翻转课堂": "flipped classroom",
    "教育科技": "edtech",
    "学习平台": "learning platforms",
    "教育公平": "education equity",
    "素质教育": "quality-oriented education",
    "应试教育": "exam-oriented education",
    "教育改革": "education reform",
    "终身学习": "lifelong learning",
    "职业教育": "vocational education",
    "成人教育": "adult education",
    "家庭教育": "family education",
    "学校教育": "school education",
    "社会教育": "social education",
    "教育资源": "educational resources",
    "教育投资": "education investment",
    "教育评估": "education assessment",
    "教育质量": "education quality",
    "教育国际化": "education internationalization",
    "留学": "studying abroad",
    "交换生": "exchange students",
    "国际合作": "international cooperation",
    "文化冲突": "cultural conflict",
    "文化融合": "cultural integration",
    "文化多样性": "cultural diversity",
    "文化认同": "cultural identity",
    "文化遗产": "cultural heritage",
    "非物质文化遗产": "intangible cultural heritage",
    "文化保护": "cultural preservation",
    "文化创新": "cultural innovation",
    "文化产业": "cultural industry",
    "创意产业": "creative industry",
    "文化旅游": "cultural tourism",
    "民俗文化": "folk culture",
    "传统艺术": "traditional arts",
    "现代艺术": "modern art",
    "流行文化": "popular culture",
    "大众文化": "mass culture",
    "精英文化": "elite culture",
    "高雅艺术": "high art",
    "通俗艺术": "popular art",
    "艺术教育": "art education",
    "艺术鉴赏": "art appreciation",
    "艺术市场": "art market",
    "艺术品收藏": "art collection",
    "艺术创作": "art creation",
    "艺术表达": "artistic expression",
    "艺术风格": "artistic style",
    "艺术流派": "art movements",
    "艺术批评": "art criticism",
    "艺术史": "art history",
    "文学作品": "literary works",
    "文学创作": "literary creation",
    "文学批评": "literary criticism",
    "文学史": "literary history",
    "诗歌": "poetry",
    "小说": "novels",
    "散文": "prose",
    "戏剧": "drama",
    "电影": "film",
    "音乐": "music",
    "绘画": "painting",
    "雕塑": "sculpture",
    "建筑": "architecture",
    "摄影": "photography",
    "设计": "design",
    "时尚": "fashion",
    "美食": "cuisine",
    "旅游": "tourism",
    "旅行": "travel",
    "景点": "attractions",
    "酒店": "hotels",
    "餐饮": "food and beverage",
    "购物": "shopping",
    "娱乐": "entertainment",
    "休闲": "leisure",
    "运动": "sports",
    "健身": "fitness",
    "游戏": "games",
    "电子竞技": "esports",
    "影视娱乐": "film and television entertainment",
    "音乐娱乐": "music entertainment",
    "文化娱乐": "cultural entertainment",
    "休闲娱乐": "leisure entertainment",
    "娱乐产业": "entertainment industry",
    "媒体娱乐": "media entertainment",
    "数字娱乐": "digital entertainment",
    "虚拟现实娱乐": "virtual reality entertainment",
    "在线娱乐": "online entertainment",
    "社交娱乐": "social entertainment",
    "游戏娱乐": "gaming entertainment",
    "直播娱乐": "live entertainment",
    "短视频娱乐": "short video entertainment",
    "综艺节目": "variety shows",
    "真人秀": "reality shows",
    "选秀节目": "talent shows",
    "电视剧": "TV dramas",
    "电影": "movies",
    "纪录片": "documentaries",
    "动画片": "animation",
    "动漫": "anime",
    "漫画": "comics",
    "小说改编": "novel adaptations",
    "IP开发": "IP development",
    "影视制作": "film production",
    "影视发行": "film distribution",
    "影视投资": "film investment",
    "影视市场": "film market",
    "票房": "box office",
    "收视率": "ratings",
    "流媒体": "streaming media",
    "点播": "video on demand",
    "网络剧": "web dramas",
    "网络电影": "web movies",
    "短视频平台": "short video platforms",
    "直播平台": "live streaming platforms",
    "社交媒体平台": "social media platforms",
    "内容平台": "content platforms",
    "视频平台": "video platforms",
    "音乐平台": "music platforms",
    "阅读平台": "reading platforms",
    "游戏平台": "gaming platforms",
    "电商平台": "e-commerce platforms",
    "外卖平台": "food delivery platforms",
    "出行平台": "ride-hailing platforms",
    "生活服务平台": "lifestyle service platforms",
    "共享平台": "sharing platforms",
    "社交平台": "social platforms",
    "通讯平台": "communication platforms",
    "办公平台": "office platforms",
    "协作平台": "collaboration platforms",
    "云服务平台": "cloud service platforms",
    "大数据平台": "big data platforms",
    "人工智能平台": "AI platforms",
    "区块链平台": "blockchain platforms",
    "物联网平台": "IoT platforms",
    "平台经济": "platform economy",
    "共享经济": "sharing economy",
    "零工经济": "gig economy",
    "数字经济": "digital economy",
    "新经济": "new economy",
    "实体经济": "real economy",
    "虚拟经济": "virtual economy",
    "绿色经济": "green economy",
    "低碳经济": "low-carbon economy",
    "循环经济": "circular economy",
    "知识经济": "knowledge economy",
    "创意经济": "creative economy",
    "服务经济": "service economy",
    "体验经济": "experience economy",
    "消费经济": "consumer economy",
    "信用经济": "credit economy",
    "共享经济": "sharing economy",
    "平台经济": "platform economy",
    "数字经济": "digital economy",
    "互联网经济": "internet economy",
    "移动经济": "mobile economy",
    "智能经济": "smart economy",
    "数据经济": "data economy",
    "信息经济": "information economy",
    "网络经济": "network economy",
    "电子商务": "e-commerce",
    "电子政务": "e-government",
    "电子金融": "e-finance",
    "电子医疗": "e-health",
    "电子教育": "e-education",
    "电子娱乐": "e-entertainment",
    "电子出版": "e-publishing",
    "电子媒体": "e-media",
    "数字化": "digitalization",
    "信息化": "informatization",
    "智能化": "intelligentization",
    "自动化": "automation",
    "网络化": "networking",
    "全球化": "globalization",
    "国际化": "internationalization",
    "区域化": "regionalization",
    "本地化": "localization",
    "城市化": "urbanization",
    "郊区化": "suburbanization",
    "逆城市化": "counter-urbanization",
    "城乡一体化": "urban-rural integration",
    "城市规划": "urban planning",
    "城市管理": "urban management",
    "城市建设": "urban construction",
    "城市发展": "urban development",
    "智慧城市": "smart city",
    "生态城市": "eco-city",
    "低碳城市": "low-carbon city",
    "海绵城市": "sponge city",
    "韧性城市": "resilient city",
    "宜居城市": "livable city",
    "文明城市": "civilized city",
    "卫生城市": "hygienic city",
    "园林城市": "garden city",
    "旅游城市": "tourism city",
    "工业城市": "industrial city",
    "商业城市": "commercial city",
    "文化城市": "cultural city",
    "科技城市": "tech city",
    "教育城市": "education city",
    "医疗城市": "medical city",
    "交通枢纽": "transportation hub",
    "物流中心": "logistics center",
    "金融中心": "financial center",
    "贸易中心": "trade center",
    "会展中心": "convention center",
    "体育中心": "sports center",
    "文化中心": "cultural center",
    "科技中心": "technology center",
    "创新中心": "innovation center",
    "研发中心": "R&D center",
    "工业园区": "industrial park",
    "科技园区": "technology park",
    "创业园区": "startup park",
    "孵化园区": "incubation park",
    "自由贸易区": "free trade zone",
    "经济特区": "special economic zone",
    "开发区": "development zone",
    "高新区": "high-tech zone",
    "保税区": "bonded zone",
    "出口加工区": "export processing zone",
    "边境经济合作区": "border economic cooperation zone",
    "跨境电商综合试验区": "cross-border e-commerce comprehensive pilot zone",
    "综合保税区": "comprehensive bonded zone",
    "临空经济区": "airport economic zone",
    "临港经济区": "port economic zone",
    "高铁经济区": "high-speed rail economic zone",
    "生态经济区": "ecological economic zone",
    "循环经济示范区": "circular economy demonstration zone",
    "可持续发展实验区": "sustainable development experimental zone",
    "生态文明先行示范区": "ecological civilization demonstration zone",
    "低碳试点城市": "low-carbon pilot city",
    "智慧城市试点": "smart city pilot",
    "海绵城市试点": "sponge city pilot",
    "城市双修试点": "urban restoration and ecological restoration pilot",
    "特色小镇": "characteristic towns",
    "美丽乡村": "beautiful countryside",
    "乡村振兴": "rural revitalization",
    "精准扶贫": "targeted poverty alleviation",
    "脱贫攻坚": "poverty alleviation",
    "全面小康": "moderate prosperity in all respects",
    "现代化": "modernization",
    "中华民族伟大复兴": "great rejuvenation of the Chinese nation",
    "中国梦": "Chinese Dream",
    "一带一路": "Belt and Road Initiative",
    "人类命运共同体": "community with a shared future for mankind",
    "可持续发展目标": "Sustainable Development Goals",
    "全球治理": "global governance",
    "多边主义": "multilateralism",
    "单边主义": "unilateralism",
    "保护主义": "protectionism",
    "贸易战": "trade war",
    "经济全球化": "economic globalization",
    "逆全球化": "de-globalization",
    "区域经济一体化": "regional economic integration",
    "自由贸易协定": "free trade agreement",
    "关税同盟": "customs union",
    "共同市场": "common market",
    "经济联盟": "economic union",
    "货币联盟": "monetary union",
    "欧元区": "Eurozone",
    "东盟": "ASEAN",
    "欧盟": "EU",
    "北美自由贸易区": "NAFTA",
    "亚太经合组织": "APEC",
    "二十国集团": "G20",
    "金砖国家": "BRICS",
    "上海合作组织": "SCO",
    "世界贸易组织": "WTO",
    "国际货币基金组织": "IMF",
    "世界银行": "World Bank",
    "联合国": "UN",
    "国际组织": "international organizations",
    "外交政策": "foreign policy",
    "国际关系": "international relations",
    "地缘政治": "geopolitics",
    "国际安全": "international security",
    "反恐": "counter-terrorism",
    "核扩散": "nuclear proliferation",
    "气候变化": "climate change",
    "环境保护": "environmental protection",
    "可持续发展": "sustainable development",
    "绿色发展": "green development",
    "低碳发展": "low-carbon development",
    "循环发展": "circular development",
    "生态文明": "ecological civilization",
    "美丽中国": "Beautiful China",
    "绿水青山": "lucid waters and lush mountains",
    "金山银山": "gold mountains and silver mountains",
    "环境治理": "environmental governance",
    "污染防治": "pollution prevention and control",
    "生态保护": "ecological protection",
    "生物多样性": "biodiversity",
    "自然保护区": "nature reserves",
    "国家公园": "national parks",
    "森林公园": "forest parks",
    "湿地公园": "wetland parks",
    "地质公园": "geoparks",
    "海洋公园": "marine parks",
    "野生动物保护": "wildlife protection",
    "濒危物种": "endangered species",
    "生态修复": "ecological restoration",
    "退耕还林": "returning farmland to forests",
    "退牧还草": "returning grazing land to grasslands",
    "水土保持": "soil and water conservation",
    "荒漠化防治": "desertification control",
    "石漠化治理": "rocky desertification control",
    "风沙治理": "sandstorm control",
    "水污染防治": "water pollution control",
    "大气污染防治": "air pollution control",
    "土壤污染防治": "soil pollution control",
    "噪声污染防治": "noise pollution control",
    "固体废弃物污染防治": "solid waste pollution control",
    "危险废物管理": "hazardous waste management",
    "垃圾分类": "garbage classification",
    "垃圾处理": "waste disposal",
    "垃圾焚烧": "waste incineration",
    "垃圾填埋": "landfill",
    "资源回收": "resource recycling",
    "再生资源": "recycled resources",
    "循环利用": "recycling",
    "节能减排": "energy conservation and emission reduction",
    "清洁生产": "clean production",
    "绿色制造": "green manufacturing",
    "绿色建筑": "green building",
    "绿色交通": "green transportation",
    "新能源": "new energy",
    "可再生能源": "renewable energy",
    "太阳能": "solar energy",
    "风能": "wind energy",
    "水能": "hydropower",
    "核能": "nuclear energy",
    "生物质能": "biomass energy",
    "地热能": "geothermal energy",
    "海洋能": "ocean energy",
    "氢能": "hydrogen energy",
    "储能技术": "energy storage technology",
    "智能电网": "smart grid",
    "电动汽车": "electric vehicles",
    "充电桩": "charging piles",
    "新能源汽车": "new energy vehicles",
    "无人驾驶": "autonomous driving",
    "智能交通": "intelligent transportation",
    "车联网": "internet of vehicles",
    "共享出行": "shared mobility",
    "网约车": "ride-hailing",
    "共享单车": "shared bikes",
    "共享汽车": "shared cars",
    "公共交通": "public transportation",
    "地铁": "metro",
    "轻轨": "light rail",
    "高铁": "high-speed rail",
    "磁悬浮": "maglev",
    "航空": "aviation",
    "航运": "shipping",
    "物流": "logistics",
    "快递": "express delivery",
    "冷链物流": "cold chain logistics",
    "供应链": "supply chain",
    "产业链": "industrial chain",
    "价值链": "value chain",
    "创新链": "innovation chain",
    "人才链": "talent chain",
    "资金链": "capital chain",
    "信息链": "information chain",
    "技术链": "technology chain",
    "产业链供应链": "industrial and supply chains",
    "产业升级": "industrial upgrading",
    "产业转型": "industrial transformation",
    "产业融合": "industrial integration",
    "产业集聚": "industrial agglomeration",
    "产业园区": "industrial parks",
    "产业基地": "industrial bases",
    "产业集群": "industrial clusters",
    "龙头企业": "leading enterprises",
    "中小企业": "small and medium-sized enterprises",
    "小微企业": "micro and small enterprises",
    "民营企业": "private enterprises",
    "国有企业": "state-owned enterprises",
    "外资企业": "foreign-invested enterprises",
    "合资企业": "joint ventures",
    "跨国公司": "multinational corporations",
    "总部经济": "headquarters economy",
    "独角兽企业": "unicorn enterprises",
    "瞪羚企业": "gazelle enterprises",
    "隐形冠军": "hidden champions",
    "专精特新": "specialized, sophisticated, unique, and new enterprises",
    "科技创新": "scientific and technological innovation",
    "技术创新": "technological innovation",
    "产品创新": "product innovation",
    "服务创新": "service innovation",
    "商业模式创新": "business model innovation",
    "管理创新": "management innovation",
    "制度创新": "institutional innovation",
    "创新驱动": "innovation-driven",
    "大众创业万众创新": "mass entrepreneurship and innovation",
    "双创": "mass entrepreneurship and innovation",
    "孵化器": "incubators",
    "加速器": "accelerators",
    "众创空间": "makerspaces",
    "科技成果转化": "commercialization of scientific and technological achievements",
    "产学研合作": "industry-university-research cooperation",
    "科研机构": "research institutions",
    "高等院校": "institutions of higher education",
    "企业研发": "enterprise R&D",
    "国家实验室": "national laboratories",
    "重点实验室": "key laboratories",
    "工程技术研究中心": "engineering technology research centers",
    "产业技术研究院": "industrial technology research institutes",
    "创新平台": "innovation platforms",
    "科技园区": "science and technology parks",
    "高新技术产业开发区": "high-tech industrial development zones",
    "经济技术开发区": "economic and technological development zones",
    "国家自主创新示范区": "national independent innovation demonstration zones",
    "全面创新改革试验区": "comprehensive innovation reform experimental zones",
    "知识产权保护": "intellectual property protection",
    "专利": "patents",
    "商标": "trademarks",
    "著作权": "copyright",
    "商业秘密": "trade secrets",
    "知识产权运营": "intellectual property operation",
    "知识产权服务": "intellectual property services",
    "知识产权交易": "intellectual property transactions",
    "知识产权质押": "intellectual property pledge",
    "科技金融": "tech finance",
    "风险投资": "venture capital",
    "天使投资": "angel investment",
    "私募股权投资": "private equity",
    "创业投资": "venture capital",
    "科技保险": "tech insurance",
    "科技信贷": "tech credit",
    "科技担保": "tech guarantee",
    "科创板": "STAR Market",
    "创业板": "ChiNext",
    "新三板": "New Third Board",
    "区域股权市场": "regional equity markets",
    "科技型中小企业": "technology-based SMEs",
    "科技领军企业": "leading tech enterprises",
    "数字经济核心产业": "core digital economy industries",
    "战略性新兴产业": "strategic emerging industries",
    "高技术产业": "high-tech industries",
    "装备制造业": "equipment manufacturing",
    "智能制造": "intelligent manufacturing",
    "服务型制造": "service-oriented manufacturing",
    "绿色制造": "green manufacturing",
    "军民融合": "civil-military integration",
    "国防科技": "defense technology",
    "军工企业": "military-industrial enterprises",
    "信息化": "informatization",
    "数字化": "digitalization",
    "智能化": "intelligentization",
    "网络化": "networking",
    "数据化": "datafication",
    "平台化": "platformization",
    "生态化": "ecologization",
    "数字化转型": "digital transformation",
    "数字政府": "digital government",
    "数字社会": "digital society",
    "数字经济": "digital economy",
    "数字贸易": "digital trade",
    "数字金融": "digital finance",
    "数字文化": "digital culture",
    "数字教育": "digital education",
    "数字医疗": "digital healthcare",
    "数字农业": "digital agriculture",
    "数字工业": "digital industry",
    "数字服务": "digital services",
    "数字创新": "digital innovation",
    "数字治理": "digital governance",
    "数字基础设施": "digital infrastructure",
    "信息基础设施": "information infrastructure",
    "融合基础设施": "integrated infrastructure",
    "创新基础设施": "innovation infrastructure",
    "5G基站": "5G base stations",
    "数据中心": "data centers",
    "云计算": "cloud computing",
    "大数据": "big data",
    "人工智能": "artificial intelligence",
    "物联网": "Internet of Things",
    "区块链": "blockchain",
    "虚拟现实": "virtual reality",
    "增强现实": "augmented reality",
    "混合现实": "mixed reality",
    "边缘计算": "edge computing",
    "量子计算": "quantum computing",
    "量子通信": "quantum communication",
    "卫星互联网": "satellite internet",
    "工业互联网": "industrial internet",
    "车联网": "internet of vehicles",
    "医疗互联网": "medical internet",
    "教育互联网": "education internet",
    "能源互联网": "energy internet",
    "金融科技": "fintech",
    "监管科技": "regtech",
    "保险科技": "insurtech",
    "医疗科技": "medtech",
    "教育科技": "edtech",
    "农业科技": "agritech",
    "物流科技": "logtech",
    "零售科技": "retailtech",
    "餐饮科技": "foodtech",
    "出行科技": "mobility tech",
    "房产科技": "proptech",
    "法律科技": "legaltech",
    "人力资源科技": "hrtech",
    "营销科技": "martech",
    "广告科技": "adtech",
    "媒体科技": "mediatech",
    "娱乐科技": "entertainment tech",
    "游戏科技": "gaming tech",
    "社交科技": "social tech",
    "电商科技": "e-commerce tech",
    "支付科技": "payment tech",
    "安全科技": "security tech",
    "隐私科技": "privacy tech",
    "身份科技": "identity tech",
    "认证科技": "authentication tech",
    "加密科技": "cryptotech",
    "风控科技": "risk control tech",
    "反欺诈": "anti-fraud",
    "信用评分": "credit scoring",
    "大数据分析": "big data analytics",
    "机器学习": "machine learning",
    "深度学习": "deep learning",
    "自然语言处理": "natural language processing",
    "计算机视觉": "computer vision",
    "语音识别": "speech recognition",
    "图像识别": "image recognition",
    "视频分析": "video analytics",
    "推荐系统": "recommendation systems",
    "知识图谱": "knowledge graphs",
    "智能客服": "intelligent customer service",
    "智能助手": "intelligent assistants",
    "智能机器人": "intelligent robots",
    "自动驾驶": "autonomous driving",
    "智能交通": "intelligent transportation",
    "智慧医疗": "smart healthcare",
    "智慧教育": "smart education",
    "智慧金融": "smart finance",
    "智慧零售": "smart retail",
    "智慧物流": "smart logistics",
    "智慧能源": "smart energy",
    "智慧农业": "smart agriculture",
    "智慧环保": "smart environmental protection",
    "智慧政务": "smart government",
    "智慧社区": "smart communities",
    "智慧家庭": "smart homes",
    "智慧城市": "smart cities",
    "数字孪生": "digital twins",
    "元宇宙": "metaverse",
    "Web3.0": "Web3.0",
    "去中心化": "decentralization",
    "分布式": "distributed",
    "共识机制": "consensus mechanisms",
    "智能合约": "smart contracts",
    "NFT": "NFT",
    "DAO": "DAO",
    "DeFi": "DeFi",
    "加密货币": "cryptocurrency",
    "区块链技术": "blockchain technology",
    "数字货币": "digital currency",
    "央行数字货币": "central bank digital currency",
    "数字人民币": "digital yuan",
    "跨境支付": "cross-border payments",
    "移动支付": "mobile payments",
    "电子钱包": "e-wallets",
    "数字银行": "digital banking",
    "虚拟银行": "virtual banking",
    "开放银行": "open banking",
    "普惠金融": "inclusive finance",
    "绿色金融": "green finance",
    "科技金融": "tech finance",
    "金融创新": "financial innovation",
    "监管沙盒": "regulatory sandbox",
    "金融稳定": "financial stability",
    "系统性风险": "systemic risk",
    "金融监管": "financial regulation",
    "宏观审慎": "macro-prudential",
    "货币政策": "monetary policy",
    "财政政策": "fiscal policy",
    "税收政策": "tax policy",
    "产业政策": "industrial policy",
    "区域政策": "regional policy",
    "创新政策": "innovation policy",
    "人才政策": "talent policy",
    "开放政策": "opening-up policy",
    "改革政策": "reform policy",
    "发展政策": "development policy",
    "政策工具": "policy tools",
    "政策协同": "policy coordination",
    "政策评估": "policy evaluation",
    "政策效果": "policy effects",
    "政策导向": "policy orientation",
    "政策支持": "policy support",
    "政策激励": "policy incentives",
    "政策约束": "policy constraints",
    "政策法规": "policies and regulations",
    "法律法规": "laws and regulations",
    "法治建设": "rule of law construction",
    "依法行政": "law-based administration",
    "政务公开": "government transparency",
    "简政放权": "streamlining administration and delegating power",
    "放管服": "delegating power, improving regulation, and optimizing services",
    "一网通办": "one-stop online services",
    "最多跑一次": "run once at most",
    "跨省通办": "inter-provincial services",
    "电子证照": "electronic certificates",
    "数据共享": "data sharing",
    "政务数据": "government data",
    "开放数据": "open data",
    "数据治理": "data governance",
    "数据安全": "data security",
    "个人信息保护": "personal information protection",
    "网络安全法": "Cybersecurity Law",
    "数据安全法": "Data Security Law",
    "个人信息保护法": "Personal Information Protection Law",
    "国家安全": "national security",
    "网络安全": "cybersecurity",
    "信息安全": "information security",
    "公共安全": "public security",
    "应急管理": "emergency management",
    "防灾减灾": "disaster prevention and mitigation",
    "安全生产": "work safety",
    "食品药品安全": "food and drug safety",
    "产品质量安全": "product quality and safety",
    "交通安全": "traffic safety",
    "消防安全": "fire safety",
    "校园安全": "campus safety",
    "社会治安": "public order",
    "扫黑除恶": "crackdown on gang crime",
    "反腐败": "anti-corruption",
    "廉洁政府": "clean government",
    "政务诚信": "government integrity",
    "社会信用体系": "social credit system",
    "信用监管": "credit supervision",
    "失信惩戒": "punishment for untrustworthy behavior",
    "守信激励": "incentives for trustworthy behavior",
    "营商环境": "business environment",
    "市场化": "marketization",
    "法治化": "rule of law",
    "国际化": "internationalization",
    "便利化": "facilitation",
    "放管服改革": "reform of delegating power, improving regulation, and optimizing services",
    "行政审批": "administrative approval",
    "商事制度改革": "business registration system reform",
    "证照分离": "separation of permits and licenses",
    "一网通办": "one-stop online services",
    "互联网+政务服务": "Internet Plus government services",
    "数字政府": "digital government",
    "智慧政务": "smart government",
    "政务服务": "government services",
    "公共服务": "public services",
    "基本公共服务": "basic public services",
    "公共服务均等化": "equalization of public services",
    "教育服务": "education services",
    "医疗服务": "medical services",
    "养老服务": "elderly care services",
    "就业服务": "employment services",
    "社会保障": "social security",
    "社会救助": "social assistance",
    "社会福利": "social welfare",
    "慈善事业": "charity",
    "志愿服务": "volunteer services",
    "社区服务": "community services",
    "便民服务": "convenience services",
    "生活服务": "lifestyle services",
    "家政服务": "housekeeping services",
    "养老服务": "elderly care services",
    "托育服务": "childcare services",
    "健康服务": "health services",
    "体育服务": "sports services",
    "文化服务": "cultural services",
    "旅游服务": "tourism services",
    "法律服务": "legal services",
    "金融服务": "financial services",
    "科技服务": "technology services",
    "信息服务": "information services",
    "物流服务": "logistics services",
    "商务服务": "business services",
    "专业服务": "professional services",
    "咨询服务": "consulting services",
    "中介服务": "intermediary services",
    "平台服务": "platform services",
    "共享服务": "sharing services",
    "外包服务": "outsourcing services",
    "跨境服务": "cross-border services",
    "服务贸易": "trade in services",
    "数字服务": "digital services",
    "服务创新": "service innovation",
    "服务质量": "service quality",
    "服务标准": "service standards",
    "服务认证": "service certification",
    "服务品牌": "service brands",
    "服务经济": "service economy",
    "服务业": "service industry",
    "生产性服务业": "producer services",
    "生活性服务业": "consumer services",
    "现代服务业": "modern service industry",
    "高端服务业": "high-end services",
    "知识密集型服务业": "knowledge-intensive services",
    "技术密集型服务业": "technology-intensive services",
    "劳动密集型服务业": "labor-intensive services",
    "服务业开放": "opening up of the service sector",
    "服务业创新": "service industry innovation",
    "服务业发展": "service industry development",
    "产业结构": "industrial structure",
    "产业布局": "industrial layout",
    "产业政策": "industrial policy",
    "产业规划": "industrial planning",
    "产业升级": "industrial upgrading",
    "产业转型": "industrial transformation",
    "产业融合": "industrial integration",
    "产业集聚": "industrial agglomeration",
    "产业转移": "industrial transfer",
    "产业承接": "industrial undertaking",
    "产业园区": "industrial parks",
    "产业基地": "industrial bases",
    "产业集群": "industrial clusters",
    "产业链": "industrial chain",
    "供应链": "supply chain",
    "价值链": "value chain",
    "创新链": "innovation chain",
    "产业生态": "industrial ecosystem",
    "产业数字化": "industrial digitalization",
    "数字产业化": "digital industrialization",
    "两化融合": "integration of informatization and industrialization",
    "智能制造": "intelligent manufacturing",
    "绿色制造": "green manufacturing",
    "服务型制造": "service-oriented manufacturing",
    "质量强国": "quality power",
    "制造强国": "manufacturing power",
    "网络强国": "cyber power",
    "科技强国": "scientific and technological power",
    "文化强国": "cultural power",
    "教育强国": "education power",
    "人才强国": "talent power",
    "体育强国": "sports power",
    "健康中国": "Healthy China",
    "美丽中国": "Beautiful China",
    "平安中国": "Safe China",
    "法治中国": "Rule of Law China",
    "数字中国": "Digital China",
    "智慧中国": "Smart China",
    "创新中国": "Innovative China",
    "开放中国": "Open China",
    "和谐中国": "Harmonious China",
    "幸福中国": "Happy China",
    "中国梦": "Chinese Dream",
    "中华民族伟大复兴": "great rejuvenation of the Chinese nation",
    "两个一百年": "Two Centenary Goals",
    "全面建设社会主义现代化国家": "comprehensive construction of a modern socialist country",
    "中国式现代化": "Chinese-style modernization",
    "共同富裕": "common prosperity",
    "高质量发展": "high-quality development",
    "新发展理念": "new development philosophy",
    "新发展格局": "new development pattern",
    "双循环": "dual circulation",
    "供给侧结构性改革": "supply-side structural reform",
    "需求侧管理": "demand-side management",
    "现代化经济体系": "modern economic system",
    "实体经济": "real economy",
    "科技创新": "scientific and technological innovation",
    "改革开放": "reform and opening up",
    "社会主义市场经济": "socialist market economy",
    "公有制为主体": "public ownership as the mainstay",
    "多种所有制经济共同发展": "common development of multiple forms of ownership",
    "按劳分配为主体": "distribution according to work as the mainstay",
    "多种分配方式并存": "coexistence of multiple distribution methods",
    "社会主义基本经济制度": "basic socialist economic system",
    "国家治理体系和治理能力现代化": "modernization of the national governance system and governance capacity",
    "全面深化改革": "comprehensively deepen reform",
    "全面依法治国": "comprehensively govern the country by law",
    "全面从严治党": "comprehensively and strictly govern the Party",
    "党的建设": "Party building",
    "意识形态工作": "ideological work",
    "社会主义核心价值观": "core socialist values",
    "精神文明建设": "cultural and ethical progress",
    "生态文明建设": "ecological civilization construction",
    "社会建设": "social construction",
    "民生保障": "people's wellbeing",
    "脱贫攻坚": "poverty alleviation",
    "乡村振兴": "rural revitalization",
    "区域协调发展": "coordinated regional development",
    "新型城镇化": "new-type urbanization",
    "一带一路": "Belt and Road Initiative",
    "人类命运共同体": "community with a shared future for mankind",
    "和平发展道路": "path of peaceful development",
    "独立自主的和平外交政策": "independent foreign policy of peace",
    "多边主义": "multilateralism",
    "全球治理": "global governance",
    "可持续发展": "sustainable development",
    "气候变化": "climate change",
    "环境保护": "environmental protection",
    "生态安全": "ecological security",
    "粮食安全": "food security",
    "能源安全": "energy security",
    "资源安全": "resource security",
    "网络安全": "cybersecurity",
    "科技安全": "technology security",
    "产业链供应链安全": "industrial and supply chain security",
    "国家安全": "national security",
    "总体国家安全观": "overall national security concept",
    "国防和军队现代化": "modernization of national defense and the military",
    "强军目标": "goal of building a strong military",
    "军民融合": "civil-military integration",
    "新时代": "new era",
    "新征程": "new journey",
    "新发展阶段": "new development stage",
    "新发展理念": "new development philosophy",
    "新发展格局": "new development pattern",
    "高质量发展": "high-quality development",
    "共同富裕": "common prosperity",
    "中国式现代化": "Chinese-style modernization",
    "人类文明新形态": "new form of human civilization",
    "全过程人民民主": "whole-process people's democracy",
    "社会主义民主政治": "socialist democratic politics",
    "人民当家作主": "people being the masters of the country",
    "依法治国": "governing the country by law",
    "法治政府": "law-based government",
    "法治社会": "law-based society",
    "公平正义": "fairness and justice",
    "社会治理": "social governance",
    "共建共治共享": "joint contribution, joint governance, and shared benefits",
    "基层治理": "grassroots governance",
    "社区治理": "community governance",
    "数字治理": "digital governance",
    "智慧治理": "smart governance",
    "治理能力": "governance capacity",
    "治理体系": "governance system",
    "现代化治理": "modern governance",
    "国家治理": "national governance",
    "全球治理": "global governance",
    "治理创新": "governance innovation",
    "治理效能": "governance effectiveness",
    "治理现代化": "governance modernization",
    "制度优势": "institutional advantages",
    "制度创新": "institutional innovation",
    "制度自信": "confidence in institutions",
    "道路自信": "confidence in the path",
    "理论自信": "confidence in the theory",
    "文化自信": "confidence in culture",
    "四个自信": "Four Confidences",
    "两个维护": "Two Upholds",
    "四个意识": "Four Consciousnesses",
    "四个全面": "Four Comprehensives",
    "五位一体": "Five-Sphere Integrated Plan",
    "新发展理念": "new development philosophy",
    "高质量发展": "high-quality development",
    "创新驱动发展": "innovation-driven development",
    "协调发展": "coordinated development",
    "绿色发展": "green development",
    "开放发展": "open development",
    "共享发展": "shared development",
    "发展质量": "development quality",
    "发展效率": "development efficiency",
    "发展公平": "development fairness",
    "发展安全": "development security",
    "发展平衡": "development balance",
    "发展协调": "development coordination",
    "发展可持续": "development sustainability",
    "发展韧性": "development resilience",
    "发展潜力": "development potential",
    "发展动能": "development momentum",
    "发展活力": "development vitality",
    "发展环境": "development environment",
    "发展机遇": "development opportunities",
    "发展挑战": "development challenges",
    "发展趋势": "development trends",
    "发展前景": "development prospects",
    "发展道路": "development path",
    "发展模式": "development model",
    "发展战略": "development strategy",
    "发展规划": "development planning",
    "发展目标": "development goals",
    "发展任务": "development tasks",
    "发展措施": "development measures",
    "发展成效": "development results",
    "发展经验": "development experience",
    "发展规律": "development laws",
    "发展理论": "development theory",
    "发展思想": "development ideology",
    "发展观": "development concept",
    "科学发展观": "Scientific Outlook on Development",
    "可持续发展观": "sustainable development concept",
    "绿色发展观": "green development concept",
    "协调发展观": "coordinated development concept",
    "创新发展观": "innovative development concept",
    "开放发展观": "open development concept",
    "共享发展观": "shared development concept",
    "高质量发展观": "high-quality development concept",
    "新发展观": "new development concept",
    "现代化发展观": "modernization development concept",
    "中国式发展观": "Chinese-style development concept",
    "人类发展观": "human development concept",
    "全面发展观": "comprehensive development concept",
    "均衡发展观": "balanced development concept",
    "和谐发展观": "harmonious development concept",
    "包容性发展观": "inclusive development concept",
    "可持续发展战略": "sustainable development strategy",
    "科教兴国战略": "strategy of developing the country through science and education",
    "人才强国战略": "talent power strategy",
    "创新驱动发展战略": "innovation-driven development strategy",
    "乡村振兴战略": "rural revitalization strategy",
    "区域协调发展战略": "coordinated regional development strategy",
    "可持续发展战略": "sustainable development strategy",
    "健康中国战略": "Healthy China strategy",
    "文化强国战略": "cultural power strategy",
    "体育强国战略": "sports power strategy",
    "制造强国战略": "manufacturing power strategy",
    "网络强国战略": "cyber power strategy",
    "质量强国战略": "quality power strategy",
    "数字中国战略": "Digital China strategy",
    "智慧中国战略": "Smart China strategy",
    "美丽中国战略": "Beautiful China strategy",
    "平安中国战略": "Safe China strategy",
    "法治中国战略": "Rule of Law China strategy",
    "开放发展战略": "open development strategy",
    "互利共赢战略": "mutually beneficial strategy",
    "和平发展战略": "peaceful development strategy",
    "总体国家安全战略": "overall national security strategy",
    "军民融合发展战略": "civil-military integration development strategy",
    "国防和军队现代化战略": "national defense and military modernization strategy",
    "国家发展战略": "national development strategy",
    "全球发展战略": "global development strategy",
    "国际合作战略": "international cooperation strategy",
    "区域合作战略": "regional cooperation strategy",
    "双边合作战略": "bilateral cooperation strategy",
    "多边合作战略": "multilateral cooperation strategy",
    "经济合作战略": "economic cooperation strategy",
    "贸易合作战略": "trade cooperation strategy",
    "投资合作战略": "investment cooperation strategy",
    "技术合作战略": "technology cooperation strategy",
    "文化合作战略": "cultural cooperation strategy",
    "教育合作战略": "education cooperation strategy",
    "科技合作战略": "science and technology cooperation strategy",
    "能源合作战略": "energy cooperation strategy",
    "环境合作战略": "environmental cooperation strategy",
    "卫生合作战略": "health cooperation strategy",
    "安全合作战略": "security cooperation strategy",
    "反恐合作战略": "counter-terrorism cooperation strategy",
    "维和合作战略": "peacekeeping cooperation strategy",
    "发展合作战略": "development cooperation strategy",
    "援助合作战略": "aid cooperation strategy",
    "南南合作战略": "South-South cooperation strategy",
    "南北合作战略": "North-South cooperation strategy",
    "多边外交战略": "multilateral diplomacy strategy",
    "双边外交战略": "bilateral diplomacy strategy",
    "大国外交战略": "major-country diplomacy strategy",
    "周边外交战略": "neighborhood diplomacy strategy",
    "发展中国家外交战略": "developing countries diplomacy strategy",
    "多边主义外交战略": "multilateralism diplomacy strategy",
    "全球治理外交战略": "global governance diplomacy strategy",
    "人类命运共同体外交战略": "community with a shared future for mankind diplomacy strategy",
    "一带一路外交战略": "Belt and Road Initiative diplomacy strategy",
    "新型国际关系外交战略": "new-type international relations diplomacy strategy",
    "互利共赢外交战略": "mutually beneficial diplomacy strategy",
    "和平发展外交战略": "peaceful development diplomacy strategy",
    "独立自主外交战略": "independent diplomacy strategy",
    "不结盟外交战略": "non-aligned diplomacy strategy",
    "全方位外交战略": "all-round diplomacy strategy",
    "多层次外交战略": "multi-level diplomacy strategy",
    "宽领域外交战略": "wide-ranging diplomacy strategy",
    "立体化外交战略": "multi-dimensional diplomacy strategy",
    "网络化外交战略": "networked diplomacy strategy",
    "数字化外交战略": "digital diplomacy strategy",
    "智能化外交战略": "intelligent diplomacy strategy",
    "绿色外交战略": "green diplomacy strategy",
    "人文外交战略": "people-to-people diplomacy strategy",
    "公共外交战略": "public diplomacy strategy",
    "文化外交战略": "cultural diplomacy strategy",
    "教育外交战略": "education diplomacy strategy",
    "科技外交战略": "science and technology diplomacy strategy",
    "体育外交战略": "sports diplomacy strategy",
    "旅游外交战略": "tourism diplomacy strategy",
    "媒体外交战略": "media diplomacy strategy",
    "智库外交战略": "think tank diplomacy strategy",
    "企业外交战略": "enterprise diplomacy strategy",
    "城市外交战略": "city diplomacy strategy",
    "地方外交战略": "local diplomacy strategy",
    "民间外交战略": "people-to-people diplomacy strategy",
    "青年外交战略": "youth diplomacy strategy",
    "妇女外交战略": "women's diplomacy strategy",
    "环保外交战略": "environmental diplomacy strategy",
    "气候外交战略": "climate diplomacy strategy",
    "能源外交战略": "energy diplomacy strategy",
    "粮食外交战略": "food diplomacy strategy",
    "卫生外交战略": "health diplomacy strategy",
    "安全外交战略": "security diplomacy strategy",
    "反恐外交战略": "counter-terrorism diplomacy strategy",
    "核外交战略": "nuclear diplomacy strategy",
    "军控外交战略": "arms control diplomacy strategy",
    "裁军外交战略": "disarmament diplomacy strategy",
    "人权外交战略": "human rights diplomacy strategy",
    "法治外交战略": "rule of law diplomacy strategy",
    "多边贸易外交战略": "multilateral trade diplomacy strategy",
    "区域贸易外交战略": "regional trade diplomacy strategy",
    "双边贸易外交战略": "bilateral trade diplomacy strategy",
    "投资外交战略": "investment diplomacy strategy",
    "金融外交战略": "financial diplomacy strategy",
    "货币外交战略": "monetary diplomacy strategy",
    "汇率外交战略": "exchange rate diplomacy strategy",
    "债务外交战略": "debt diplomacy strategy",
    "援助外交战略": "aid diplomacy strategy",
    "发展合作外交战略": "development cooperation diplomacy strategy",
    "全球发展倡议外交战略": "Global Development Initiative diplomacy strategy",
    "全球安全倡议外交战略": "Global Security Initiative diplomacy strategy",
    "全球文明倡议外交战略": "Global Civilization Initiative diplomacy strategy",
    "人类命运共同体外交战略": "community with a shared future for mankind diplomacy strategy",
    "一带一路倡议外交战略": "Belt and Road Initiative diplomacy strategy",
    "新型全球化外交战略": "new-type globalization diplomacy strategy",
    "包容性全球化外交战略": "inclusive globalization diplomacy strategy",
    "公平全球化外交战略": "fair globalization diplomacy strategy",
    "可持续全球化外交战略": "sustainable globalization diplomacy strategy",
    "多边主义外交战略": "multilateralism diplomacy strategy",
    "全球治理改革外交战略": "global governance reform diplomacy strategy",
    "国际秩序改革外交战略": "international order reform diplomacy strategy",
    "联合国改革外交战略": "UN reform diplomacy strategy",
    "WTO改革外交战略": "WTO reform diplomacy strategy",
    "IMF改革外交战略": "IMF reform diplomacy strategy",
    "世界银行改革外交战略": "World Bank reform diplomacy strategy",
    "区域合作组织改革外交战略": "regional cooperation organization reform diplomacy strategy",
    "新型国际合作外交战略": "new-type international cooperation diplomacy strategy",
    "互利共赢国际合作外交战略": "mutually beneficial international cooperation diplomacy strategy",
    "开放型世界经济外交战略": "open world economy diplomacy strategy",
    "经济全球化外交战略": "economic globalization diplomacy strategy",
    "贸易自由化外交战略": "trade liberalization diplomacy strategy",
    "投资便利化外交战略": "investment facilitation diplomacy strategy",
    "服务贸易自由化外交战略": "trade in services liberalization diplomacy strategy",
    "数字贸易外交战略": "digital trade diplomacy strategy",
    "绿色贸易外交战略": "green trade diplomacy strategy",
    "低碳贸易外交战略": "low-carbon trade diplomacy strategy",
    "循环经济外交战略": "circular economy diplomacy strategy",
    "可持续发展外交战略": "sustainable development diplomacy strategy",
    "气候变化外交战略": "climate change diplomacy strategy",
    "环境保护外交战略": "environmental protection diplomacy strategy",
    "生态合作外交战略": "ecological cooperation diplomacy strategy",
    "生物多样性外交战略": "biodiversity diplomacy strategy",
    "海洋合作外交战略": "maritime cooperation diplomacy strategy",
    "极地合作外交战略": "polar cooperation diplomacy strategy",
    "空间合作外交战略": "space cooperation diplomacy strategy",
    "科技合作外交战略": "science and technology cooperation diplomacy strategy",
    "创新合作外交战略": "innovation cooperation diplomacy strategy",
    "数字合作外交战略": "digital cooperation diplomacy strategy",
    "人工智能合作外交战略": "artificial intelligence cooperation diplomacy strategy",
    "数据合作外交战略": "data cooperation diplomacy strategy",
    "网络安全合作外交战略": "cybersecurity cooperation diplomacy strategy",
    "信息安全合作外交战略": "information security cooperation diplomacy strategy",
    "知识产权合作外交战略": "intellectual property cooperation diplomacy strategy",
    "教育合作外交战略": "education cooperation diplomacy strategy",
    "文化合作外交战略": "cultural cooperation diplomacy strategy",
    "人文交流外交战略": "people-to-people exchanges diplomacy strategy",
    "青年交流外交战略": "youth exchanges diplomacy strategy",
    "学术交流外交战略": "academic exchanges diplomacy strategy",
    "媒体交流外交战略": "media exchanges diplomacy strategy",
    "智库交流外交战略": "think tank exchanges diplomacy strategy",
    "地方交流外交战略": "local exchanges diplomacy strategy",
    "城市交流外交战略": "city exchanges diplomacy strategy",
    "企业交流外交战略": "enterprise exchanges diplomacy strategy",
    "民间交流外交战略": "people-to-people exchanges diplomacy strategy",
    "非政府组织交流外交战略": "NGO exchanges diplomacy strategy",
    "国际组织交流外交战略": "international organization exchanges diplomacy strategy",
    "多边机制交流外交战略": "multilateral mechanism exchanges diplomacy strategy",
    "双边机制交流外交战略": "bilateral mechanism exchanges diplomacy strategy",
    "区域机制交流外交战略": "regional mechanism exchanges diplomacy strategy",
    "全球机制交流外交战略": "global mechanism exchanges diplomacy strategy",
    "外交政策制定": "foreign policy formulation",
    "外交决策": "foreign policy decision-making",
    "外交执行": "foreign policy implementation",
    "外交评估": "foreign policy evaluation",
    "外交调整": "foreign policy adjustment",
    "外交创新": "foreign policy innovation",
    "外交现代化": "foreign policy modernization",
    "外交数字化": "foreign policy digitalization",
    "外交智能化": "foreign policy intelligentization",
    "外交绿色化": "foreign policy greening",
    "外交人文化": "foreign policy humanization",
    "外交法治化": "foreign policy legalization",
    "外交国际化": "foreign policy internationalization",
    "外交专业化": "foreign policy professionalization",
    "外交规范化": "foreign policy standardization",
    "外交透明化": "foreign policy transparency",
    "外交公开化": "foreign policy openness",
    "外交民主化": "foreign policy democratization",
    "外交科学化": "foreign policy scientization",
    "外交精细化": "foreign policy refinement",
    "外交精准化": "foreign policy precision",
    "外交高效化": "foreign policy efficiency",
    "外交协同化": "foreign policy coordination",
    "外交一体化": "foreign policy integration",
    "外交系统化": "foreign policy systematization",
    "外交战略化": "foreign policy strategization",
    "外交全局化": "foreign policy holistic approach",
    "外交长远化": "foreign policy long-term approach",
    "外交可持续化": "foreign policy sustainability",
    "外交包容性": "foreign policy inclusiveness",
    "外交开放性": "foreign policy openness",
    "外交合作性": "foreign policy cooperation",
    "外交互利性": "foreign policy mutual benefit",
    "外交和平性": "foreign policy peacefulness",
    "外交公正性": "foreign policy fairness",
    "外交合理性": "foreign policy rationality",
    "外交合法性": "foreign policy legitimacy",
    "外交权威性": "foreign policy authority",
    "外交影响力": "foreign policy influence",
    "外交话语权": "foreign policy discourse power",
    "外交软实力": "foreign policy soft power",
    "外交硬实力": "foreign policy hard power",
    "外交巧实力": "foreign policy smart power",
    "外交综合实力": "foreign policy comprehensive power",
    "外交国际地位": "foreign policy international status",
    "外交国际形象": "foreign policy international image",
    "外交国际声誉": "foreign policy international reputation",
    "外交国际信任": "foreign policy international trust",
    "外交国际合作": "foreign policy international cooperation",
    "外交国际协调": "foreign policy international coordination",
    "外交国际共识": "foreign policy international consensus",
    "外交国际规则": "foreign policy international rules",
    "外交国际秩序": "foreign policy international order",
    "外交全球化": "foreign policy globalization",
    "外交区域化": "foreign policy regionalization",
    "外交多边化": "foreign policy multilateralization",
    "外交双边化": "foreign policy bilateralization",
    "外交多元化": "foreign policy diversification",
    "外交均衡化": "foreign policy balance",
    "外交协调化": "foreign policy coordination",
    "外交一体化": "foreign policy integration",
    "外交系统化": "foreign policy systematization",
    "外交战略化": "foreign policy strategization",
    "外交全局化": "foreign policy holistic approach",
    "外交长远化": "foreign policy long-term approach",
    "外交可持续化": "foreign policy sustainability",
    "外交包容性": "foreign policy inclusiveness",
    "外交开放性": "foreign policy openness",
    "外交合作性": "foreign policy cooperation",
    "外交互利性": "foreign policy mutual benefit",
    "外交和平性": "foreign policy peacefulness",
    "外交公正性": "foreign policy fairness",
    "外交合理性": "foreign policy rationality",
    "外交合法性": "foreign policy legitimacy",
    "外交权威性": "foreign policy authority",
    "外交影响力": "foreign policy influence",
    "外交话语权": "foreign policy discourse power",
    "外交软实力": "foreign policy soft power",
    "外交硬实力": "foreign policy hard power",
    "外交巧实力": "foreign policy smart power",
    "外交综合实力": "foreign policy comprehensive power",
    "外交国际地位": "foreign policy international status",
    "外交国际形象": "foreign policy international image",
    "外交国际声誉": "foreign policy international reputation",
    "外交国际信任": "foreign policy international trust",
    "外交国际合作": "foreign policy international cooperation",
    "外交国际协调": "foreign policy international coordination",
    "外交国际共识": "foreign policy international consensus",
    "外交国际规则": "foreign policy international rules",
    "外交国际秩序": "foreign policy international order",
    "外交全球化": "foreign policy globalization",
    "外交区域化": "foreign policy regionalization",
    "外交多边化": "foreign policy multilateralization",
    "外交双边化": "foreign policy bilateralization",
    "外交多元化": "foreign policy diversification",
    "外交均衡化": "foreign policy balance",
}

# 读取文件
with open('src/data/writing.ts', 'r', encoding='utf-8') as f:
    content = f.read()

# 替换所有中文词汇为英文
for chinese, english in chinese_to_english.items():
    content = content.replace(chinese, english)

# 写入文件
with open('src/data/writing.ts', 'w', encoding='utf-8') as f:
    f.write(content)

print("替换完成！")
