import re

# 更完整的中文词汇到英文映射
chinese_to_english = {
    # 常见中文词汇
    "达沃斯": "Davos",
    "就业": "employment",
    "议题": "topic",
    "研究报告": "research report",
    "核心发现": "core finding",
    "研究": "research",
    "提供": "provides",
    "适应策略": "adaptation strategies",
    "方法": "approach",
    "数据": "data",
    "预测": "prediction",
    "趋势": "trend",
    "专家建议": "expert advice",
    "方向": "direction",
    "总结": "summary",
    "核心理念": "core concept",
    "成就": "achievements",
    "中国国际电视台": "China Global Television Network",
    "官方": "official",
    "英文媒体": "English media",
    "发展成就型": "development achievements style",
    "强调": "emphasizes",
    "制度优势": "institutional advantages",
    "精准扶贫": "targeted poverty alleviation",
    "项目": "project",
    "实施": "implementation",
    "面临": "faces",
    "挑战": "challenges",
    "分析": "analysis",
    "指出": "points out",
    "问题": "problems",
    "总体而言": "Overall",
    "启示": "enlightenment",
    "更广泛意义": "broader significance",
    "慈善": "philanthropy",
    "全球健康": "global health",
    "比尔及梅琳达·盖茨基金会": "Bill & Melinda Gates Foundation",
    "联合主席": "co-chair",
    "技术": "technology",
    "慈善型": "philanthropic style",
    "数据驱动": "data-driven",
    "分析方法": "analytical approach",
    "杠杆效应": "leverage effect",
    "关注": "focus on",
    "最脆弱": "most vulnerable",
    "反复思考": "repeatedly thinks about",
    "理由": "reasons",
    "案例": "case",
    "展示": "demonstrates",
    "反对意见": "opposing views",
    "个人观点": "personal view",
    "信念": "belief",
    "解决方案": "solutions",
    "气候投资": "climate investment",
    "专家": "expert",
    "创新务实型": "innovative and pragmatic style",
    "专注": "focuses on",
    "清洁能源": "clean energy",
    "创新需求": "innovation needs",
    "领域": "field",
    "呼吁": "call",
    "教育": "education",
    "女性权益": "women's rights",
    "诺贝尔和平奖": "Nobel Peace Prize",
    "得主": "laureate",
    "人道主义型": "humanitarian style",
    "亲身经历": "personal experience",
    "赋予": "gives",
    "话语力量": "power to words",
    "简洁有力": "concise and powerful",
    "坚定而不激进": "firm but not radical",
    "边缘": "marginalized",
    "名言": "famous quote",
    "使命": "mission",
    "力量": "empowers",
    "群体": "group",
    "现象": "phenomenon",
    "完全同意": "completely agree",
    "勇气": "courage",
    "和平": "peace",
    "行动号召型": "call to action style",
    "倡导": "advocates",
    "具体可行": "concrete and feasible",
    "建议": "suggestions",
    "强调": "emphasizes",
    "政策": "policies",
    "毕生奋斗": "lifelong struggle",
    "目标": "goal",
    "全球": "global",
    "数百万": "millions",
    "儿童": "children",
    "失学": "out of school",
    "事实": "facts",
    "现状": "current situation",
    "必要措施": "necessary measures",
    "价值观": "values",
    "愿景": "vision",
    "气候行动": "climate action",
    "活动家": "activist",
    "直接质问型": "direct questioning style",
    "毫不妥协": "uncompromising",
    "引用": "cites",
    "科学数据": "scientific data",
    "批判": "criticizes",
    "虚伪": "hypocrisy",
    "拖延": "delay",
    "道德权威": "moral authority",
    "行动": "action",
    "信息": "message",
    "传达": "conveys",
    "科学事实": "scientific facts",
    "行动的重要性": "importance of action",
    "同意程度": "degree of agreement",
    "坚持": "persistence",
    "气候正义": "climate justice",
    "青年动员型": "youth mobilization style",
    "身体力行": "practices what preaches",
    "非暴力不合作": "non-violent non-cooperation",
    "精神": "spirit",
    "打破": "breaks",
    "政治冷漠": "political apathy",
    "团结": "unity",
    "分裂": "division",
    "个人行动": "personal action",
    "发展": "develops",
    "全球运动": "global movement",
    "方式": "method",
    "可能性": "possibilities",
    "经验": "experience",
    "号召": "calls for",
    "未来工作": "future work",
    "世界经济论坛": "World Economic Forum",
    "趋势分析型": "trend analysis style",
    "多学科": "multidisciplinary",
    "专家视角": "expert perspectives",
    "长期": "long-term",
    "结构性变化": "structural changes",
    "平衡": "balance",
    "新冠疫情": "COVID-19 pandemic",
    "焦点": "focus",
    "远程工作": "remote work",
    "优势": "advantages",
    "好处": "benefits",
    "债务": "debt",
    "发展": "development",
    "国际金融机构": "international financial institutions",
    "政策专业型": "policy professional style",
    "严谨": "rigorous",
    "经济学框架": "economic framework",
    "跨国比较": "cross-country comparison",
    "平衡": "balance",
    "债权人": "creditors",
    "债务人": "debtors",
    "管理策略": "management strategies",
    "创业者精神": "entrepreneurship",
    "马云": "Jack Ma",
    "阿里巴巴": "Alibaba",
    "创始人": "founder",
    "励志经验型": "inspirational experience style",
    "分享": "shares",
    "失败": "failure",
    "坦诚": "frankly",
    "多次": "multiple times",
    "视...为": "regards...as",
    "学习机会": "learning opportunity",
    "强调": "emphasizes",
    "坚持": "persistence",
    "经历": "experiences",
    "故事": "story",
    "教会": "teaches",
    "教训": "lessons",
    "培养": "cultivates",
    "能力": "abilities",
    "一带一路": "Belt and Road Initiative",
    "发展合作型": "development cooperation style",
    "带来": "brings",
    "关切": "concerns",
    "人类发展": "human development",
    "UN开发计划署": "UN Development Programme",
    "UN专门机构": "UN specialized agency",
    "发展人文型": "development and humanities style",
    "多维度": "multidimensional",
    "发展指标": "development indicators",
    "边缘化群体": "marginalized groups",
    "倡导": "advocates",
    "包容性发展": "inclusive development",
    "赋权": "empowerment",
    "超越": "beyond",
    "单一": "single",
    "GDP": "GDP",
    "社交媒体": "social media",
    "心理健康": "mental health",
    "跨学科分析型": "interdisciplinary analysis style",
    "综合": "integrates",
    "心理": "psychology",
    "社会": "society",
    "多角度": "multiple perspectives",
    "多方": "multiple parties",
    "应对策略": "response strategies",
    "全部": "All",
    "cause": "cause",
    "effect": "effect",
    "comparison": "comparison",
    "example": "example",
    "conclusion": "conclusion",
    # 补充更多常见中文词汇
    "议题": "issue",
    "研究": "study",
    "数据": "statistics",
    "趋势": "tendency",
    "建议": "recommendations",
    "方向": "approach",
    "总结": "conclusion",
    "理念": "philosophy",
    "成就": "accomplishments",
    "官方": "government",
    "媒体": "media",
    "发展": "development",
    "强调": "highlights",
    "优势": "strengths",
    "项目": "program",
    "实施": "execution",
    "挑战": "obstacles",
    "分析": "analysis",
    "问题": "issues",
    "启示": "implications",
    "意义": "significance",
    "慈善": "charity",
    "健康": "health",
    "技术": "tech",
    "驱动": "driven",
    "方法": "methodology",
    "效应": "effect",
    "关注": "addresses",
    "脆弱": "vulnerable",
    "思考": "contemplates",
    "理由": "rationale",
    "案例": "examples",
    "展示": "illustrates",
    "意见": "perspectives",
    "观点": "perspective",
    "信念": "conviction",
    "方案": "approaches",
    "投资": "investment",
    "创新": "innovation",
    "务实": "pragmatic",
    "能源": "energy",
    "需求": "needs",
    "领域": "areas",
    "呼吁": "advocacy",
    "教育": "education",
    "权益": "rights",
    "和平": "peace",
    "人道主义": "humanitarian",
    "经历": "experiences",
    "力量": "strength",
    "简洁": "concise",
    "坚定": "resolute",
    "激进": "radical",
    "边缘": "peripheral",
    "名言": "quotes",
    "使命": "calling",
    "群体": "groups",
    "现象": "phenomena",
    "同意": "agree",
    "勇气": "bravery",
    "行动": "actions",
    "具体": "specific",
    "可行": "feasible",
    "政策": "policy",
    "奋斗": "endeavor",
    "目标": "objective",
    "全球": "worldwide",
    "数百万": "millions of",
    "儿童": "kids",
    "失学": "deprived of education",
    "事实": "truths",
    "现状": "reality",
    "措施": "measures",
    "价值观": "principles",
    "愿景": "aspiration",
    "行动": "action",
    "活动家": "campaigner",
    "质问": "challenge",
    "妥协": "compromise",
    "引用": "referencing",
    "科学": "scientific",
    "批判": "criticize",
    "虚伪": "hypocrisy",
    "拖延": "procrastination",
    "道德": "moral",
    "权威": "authority",
    "信息": "information",
    "传达": "communicates",
    "重要性": "significance",
    "程度": "extent",
    "坚持": "tenacity",
    "正义": "justice",
    "动员": "mobilization",
    "力行": "practice",
    "非暴力": "non-violent",
    "冷漠": "indifference",
    "团结": "solidarity",
    "分裂": "division",
    "运动": "movement",
    "方式": "approach",
    "可能性": "potential",
    "经验": "lessons",
    "号召": "rallying",
    "未来": "future",
    "工作": "work",
    "经济": "economic",
    "论坛": "forum",
    "趋势": "trends",
    "学科": "disciplinary",
    "视角": "perspectives",
    "结构": "structural",
    "变化": "changes",
    "疫情": "pandemic",
    "焦点": "priority",
    "远程": "remote",
    "优势": "merits",
    "好处": "advantages",
    "债务": "debts",
    "金融": "financial",
    "机构": "institutions",
    "政策": "policies",
    "专业": "professional",
    "严谨": "rigorous",
    "框架": "framework",
    "跨国": "cross-national",
    "比较": "comparative",
    "债权人": "lenders",
    "债务人": "borrowers",
    "策略": "strategies",
    "创业": "entrepreneurial",
    "精神": "spirit",
    "励志": "inspirational",
    "分享": "shares",
    "失败": "failures",
    "坦诚": "openly",
    "多次": "numerous",
    "机会": "opportunity",
    "坚持": "perseverance",
    "经历": "journey",
    "故事": "narratives",
    "教训": "takeaways",
    "培养": "develops",
    "能力": "capabilities",
    "合作": "cooperation",
    "带来": "delivers",
    "关切": "concerns",
    "人类": "human",
    "维度": "dimensions",
    "指标": "metrics",
    "包容": "inclusive",
    "赋权": "empowerment",
    "超越": "transcend",
    "单一": "sole",
    "社会": "social",
    "心理": "psychological",
    "多方": "stakeholders",
    "应对": "address",
}

# 读取文件
with open('src/data/writing.ts', 'r', encoding='utf-8') as f:
    content = f.read()

# 替换所有中文词汇为英文
for chinese, english in chinese_to_english.items():
    content = content.replace(chinese, english)

# 写入文件
with open('src/data/writing.ts', 'w', encoding='utf-8') as f:
    f.write(content)

print("替换完成！")

# 检查是否还有剩余的中文
remaining_chinese = re.findall(r'[\u4e00-\u9fff]', content)
if remaining_chinese:
    print(f"仍有 {len(remaining_chinese)} 个中文字符未替换")
else:
    print("所有中文词汇已成功替换！")
