import re

# 中文词汇到英文的映射
chinese_to_english = {
    # 数字和量词
    "一": "one",
    "一个": "a",
    "一种": "a type of",
    "一贯": "consistently",
    "上": "above",
    "不": "not",
    "不怕": "not afraid of",
    "世界中变得越来越": "becomes increasingly",
    "业": "industry",
    "东方智慧": "Eastern wisdom",
    "东西方文化融合": "East-West cultural integration",
    "严峻性": "severity",
    "中": "middle",
    "中变得越来越": "becomes increasingly",
    "中国": "China",
    "中国作为负责任大国": "China as a responsible major country",
    "中国家": "developing countries",
    "中国角色": "China's role",
    "中展现自信": "showing confidence",
    "为": "for",
    "为令人兴奋": "exciting",
    "为小企业": "small businesses",
    "为这个": "for this",
    "也": "also",
    "也存在": "also exists",
    "也是她用生命践行": "is also what she practiced with her life",
    "习惯": "habit",
    "了": "",
    "了丰富第一手资料": "rich first-hand information",
    "了前瞻性": "forward-looking",
    "了宝贵见解": "valuable insights",
    "了深刻见解": "profound insights",
    "了这个": "this",
    "事例": "example",
    "互利共赢": "mutual benefit and win-win",
    "互联网": "internet",
    "交叉": "intersection",
    "交通拥堵": "traffic congestion",
    "人关心话题": "topic of concern",
    "人利益": "people's interests",
    "人口": "population",
    "人文": "humanities",
    "人文关怀": "humanistic care",
    "仍有": "still have",
    "从": "from",
    "他": "he",
    "他以实际": "he with practical",
    "他对": "he for",
    "他有独到见解": "he has unique insights",
    "他演讲风格": "his speaking style",
    "他韧性": "his resilience",
    "他风格是": "his style is",
    "代表": "represent",
    "代际": "intergenerational",
    "以敢于承担风险著称": "known for daring to take risks",
    "以自身": "with oneself",
    "以身作则": "lead by example",
    "优缺点": "advantages and disadvantages",
    "伦理": "ethics",
    "但": "but",
    "住房危机": "housing crisis",
    "体现东西方": "reflect East-West",
    "体现了这一点": "reflects this",
    "作为": "as",
    "作为前央行行长": "as former central bank governor",
    "作为电商先驱": "as e-commerce pioneer",
    "例如": "for example",
    "例子": "example",
    "借鉴": "learn from",
    "倡议": "initiative",
    "充满热情": "full of passion",
    "公司": "company",
    "公立": "public",
    "其次": "secondly",
    "兼": "concurrently",
    "内容": "content",
    "冒险": "adventure",
    "决心": "determination",
    "决策": "decision",
    "几种": "several",
    "出国": "go abroad",
    "则": "then",
    "利益相关者": "stakeholders",
    "到": "to",
    "刻板印象": "stereotype",
    "前瞻": "forward-looking",
    "前瞻性": "forward-looking",
    "前英格兰银行行长": "former Bank of England governor",
    "力和情商": "strength and emotional intelligence",
    "动物": "animal",
    "化": "ization",
    "压力": "pressure",
    "原则": "principle",
    "原则是": "principle is",
    "参考": "reference",
    "双刃剑": "double-edged sword",
    "发行央行": "central bank issuance",
    "发言风格": "speaking style",
    "取决于": "depends on",
    "叙事": "narrative",
    "另一": "another",
    "另一个": "another",
    "另一种": "another type",
    "名人": "celebrity",
    "名人洞见": "celebrity insights",
    "名称": "name",
    "后": "after",
    "启发激励": "inspire and motivate",
    "告诉我们": "tells us",
    "员": "member",
    "命题": "proposition",
    "和": "and",
    "和女性": "and women",
    "和调研": "and research",
    "善于将": "good at",
    "善于用商业": "good at using business",
    "善于预见": "good at foresight",
    "国际责任": "international responsibility",
    "在": "in",
    "在国际": "in international",
    "在当今": "in today's",
    "在我": "in my",
    "在演讲中": "in speech",
    "在男性主导": "in male-dominated",
    "在高水平": "at a high level",
    "坚韧": "resilience",
    "基础设施": "infrastructure",
    "外包": "outsourcing",
    "多": "many",
    "多元": "diverse",
    "多元化": "diversification",
    "多边": "multilateral",
    "女性": "women",
    "她": "she",
    "她旅程激励我们": "her journey inspires us",
    "她曾说": "she once said",
    "她风格": "her style",
    "她风格是": "her style is",
    "如何": "how",
    "存在": "exist",
    "存在争议": "controversial",
    "存在局限性": "has limitations",
    "学历": "educational background",
    "宏大": "grand",
    "实践": "practice",
    "富人有更大责任": "the rich have greater responsibility",
    "富有感染力": "infectious",
    "对": "to",
    "对此": "regarding this",
    "对此有": "has",
    "对这一": "to this",
    "导向": "oriented",
    "小企业": "small businesses",
    "展现了": "shows",
    "展现了强硬而": "shows tough yet",
    "展现了跨界": "shows cross-border",
    "展现了非凡韧性和": "shows extraordinary resilience and",
    "展现对事业执着热爱": "shows dedication to career",
    "展现自信": "shows confidence",
    "带领": "lead",
    "并从": "and from",
    "广告": "advertising",
    "应": "should",
    "应为": "should be",
    "开场": "opening",
    "式滑雪奥运冠军": "Olympic champion",
    "引述": "quote",
    "弱势": "vulnerable",
    "弱国": "weak countries",
    "快餐": "fast food",
    "态度": "attitude",
    "思想领袖": "thought leader",
    "思想领袖之一": "one of the thought leaders",
    "思想领袖平台": "thought leader platform",
    "思维": "thinking",
    "性": "nature",
    "性资本主义": "capitalism",
    "总之": "in conclusion",
    "总裁": "CEO",
    "情境": "situation",
    "情感共鸣": "emotional resonance",
    "想象": "imagine",
    "感": "feeling",
    "成": "become",
    "我": "I",
    "我们": "we",
    "所": "so",
    "所以": "therefore",
    "所说": "said",
    "批评": "criticism",
    "承认": "admit",
    "承认不": "admit not",
    "技能": "skills",
    "报告": "report",
    "报道": "reporting",
    "报道脱贫": "reporting poverty alleviation",
    "报道风格": "reporting style",
    "持": "hold",
    "描绘": "depict",
    "提醒": "remind",
    "政府": "government",
    "敢于冒险": "dare to take risks",
    "数字": "digital",
    "文化": "culture",
    "文化对话": "cultural dialogue",
    "文化桥梁": "cultural bridge",
    "文化流失": "cultural loss",
    "旅程": "journey",
    "旅程所": "journey",
    "日益": "increasingly",
    "日益凸显": "increasingly prominent",
    "旨在": "aims to",
    "是": "is",
    "是一个": "is a",
    "是中国": "is China",
    "是国际": "is international",
    "是当今": "is today's",
    "智能手机": "smartphone",
    "最": "most",
    "有": "have",
    "有些人": "some people",
    "有其优点": "has its advantages",
    "有力": "powerful",
    "有深刻反思": "has profound reflection",
    "有深刻见解": "has profound insights",
    "有独到": "has unique",
    "有独到见解": "has unique insights",
    "服务": "service",
    "本文将": "this article will",
    "机遇": "opportunity",
    "来": "come",
    "来自": "come from",
    "杰出女性": "outstanding women",
    "森林砍伐": "deforestation",
    "正": "is",
    "正如": "just as",
    "气候": "climate",
    "气候危机": "climate crisis",
    "水资源污染": "water pollution",
    "治理": "governance",
    "注重": "focus on",
    "注重可": "focus on sustainable",
    "注重风险": "focus on risk",
    "洞见": "insights",
    "深刻": "profound",
    "深度": "depth",
    "演讲": "speech",
    "演讲中": "in speech",
    "演讲系列": "speech series",
    "演讲风格": "speaking style",
    "潜在": "potential",
    "激情": "passion",
    "激情澎湃": "passionate",
    "热情": "enthusiasm",
    "热爱": "love",
    "然而": "however",
    "特斯拉": "Tesla",
    "理解": "understand",
    "生动比喻": "vivid metaphor",
    "用": "use",
    "用自己": "use one's own",
    "界": "world",
    "界热点": "world hotspots",
    "监管": "regulation",
    "直接": "direct",
    "短期": "short-term",
    "短期利益": "short-term interests",
    "社区": "community",
    "私立学校": "private schools",
    "秘书长": "Secretary-General",
    "移民": "immigration",
    "空气污染": "air pollution",
    "第一个": "first",
    "第一个治理原则是": "the first governance principle is",
    "第一性原理": "first principles",
    "第一性原理思维": "first principles thinking",
    "第一次": "first time",
    "第二个": "second",
    "第四次工业": "fourth industrial",
    "精准判断著称": "known for accurate judgment",
    "精英共识": "elite consensus",
    "素质": "quality",
    "紧迫": "urgent",
    "细节": "details",
    "网购": "online shopping",
    "者": "person",
    "而非": "rather than",
    "而非性别": "rather than gender",
    "自己": "oneself",
    "自我": "self",
    "至关": "crucial",
    "航天": "aerospace",
    "艰难历程": "difficult journey",
    "融合东西方智慧": "integrate East-West wisdom",
    "见解": "insights",
    "观察": "observe",
    "观察到": "observe that",
    "视": "regard",
    "视野": "vision",
    "警告": "warning",
    "警告值得重视": "warning deserves attention",
    "计算": "computing",
    "讯息": "message",
    "记住": "remember",
    "证据基础": "evidence base",
    "话题": "topic",
    "语言": "language",
    "语言消失": "language disappearance",
    "说": "say",
    "谦逊": "humble",
    "谦逊但自信": "humble but confident",
    "谷爱凌": "Gu Ailing",
    "谷爱凌作为中美混血": "Gu Ailing as Sino-American mixed race",
    "谷爱凌作为学霸": "Gu Ailing as academic achiever",
    "谷爱凌公开谈论": "Gu Ailing publicly talks about",
    "谷爱凌发言充满正能量": "Gu Ailing's speech is full of positive energy",
    "贫困": "poverty",
    "资源": "resources",
    "跨": "cross",
    "跨界": "cross-border",
    "近年投入": "recent investment",
    "这": "this",
    "这一说法": "this statement",
    "这些": "these",
    "这允许": "this allows",
    "这是": "this is",
    "进取": "enterprising",
    "远见": "foresight",
    "远见前瞻": "foresight",
    "迭代": "iteration",
    "通俗": "popular",
    "逻辑严密": "logical rigor",
    "道义": "morality",
    "道理": "reason",
    "重大": "significant",
    "重视风险防范": "emphasize risk prevention",
    "长远": "long-term",
    "集体": "collective",
    "青少年压力": "teenage stress",
    "青少年吸烟": "teenage smoking",
    "青年": "youth",
    "领袖": "leader",
    "颠覆": "disrupt",
    "风格": "style",
    "风格中汲取见解": "draw insights from style",
    "风险": "risk",
    "风险进取": "risk-taking",
    "食品": "food",
    "食品安全": "food safety",
    "首先": "firstly",
    "黄仁勋": "Jensen Huang",
    "黄仁勋以其远见卓识和对": "Jensen Huang with his vision and",
    "黄仁勋作为": "Jensen Huang as",
    "黄仁勋对计算": "Jensen Huang on computing",
    "鼓励": "encourage",
    "鼓励从": "encourage from",
    "鼓励大胆": "encourage bold",
    "鼓励年轻人勇敢": "encourage young people to be brave",
}

# 读取文件
with open('src/data/writing.ts', 'r', encoding='utf-8') as f:
    content = f.read()

# 执行替换
for chinese, english in chinese_to_english.items():
    content = content.replace(chinese, english)

# 写入文件
with open('src/data/writing.ts', 'w', encoding='utf-8') as f:
    f.write(content)

print("替换完成！")

# 检查剩余中文
remaining_chinese = re.findall(r'[\u4e00-\u9fff]', content)
if remaining_chinese:
    print(f"仍有 {len(remaining_chinese)} 个中文字符未替换")
else:
    print("所有中文词汇已成功替换！")
