const fs = require('fs');

const filePath = './src/data/mockWords.ts';
let content = fs.readFileSync(filePath, 'utf-8');

const corrections = {
  'bespangle': 'v. 使闪烁；装饰',
  'bespoke': 'adj. 定制的；订做的',
  'betag': 'v. 轻拍；轻击',
  'blimey': 'int. 天哪！；哎呀！',
  'blurry': 'adj. 模糊的；不清晰的',
  'boa': 'n. 蟒蛇；羽毛围巾',
  'bodega': 'n. 杂货店；酒窖',
  'bodyguard': 'n. 保镖；护卫',
  'boggy': 'adj. 沼泽的；湿软的',
  'bohemian': 'n./adj. 波西米亚人；放荡不羁的',
  'boldface': 'n. 黑体字；粗体',
  'bolero': 'n. 波列罗舞；短上衣',
  'bollard': 'n. 缆柱；交通岛',
  'bonfire': 'n. 篝火；营火',
  'bonhomie': 'n. 温和；友善',
  'bonnet': 'n. 圆帽；软帽',
  'bonsai': 'n. 盆景',
  'booby': 'n. 笨蛋；鲣鸟',
  'boogie': 'v. 跳舞；跳摇滚',
  'boohoo': 'v. 嚎啕大哭',
  'bookbind': 'v. 装订书籍',
  'bookmark': 'n. 书签',
  'bootblack': 'n. 擦鞋匠',
  'bootlace': 'n. 鞋带',
  'bootleg': 'n./v. 走私货；偷运',
  'bootstrap': 'n. 引导程序；自力更生',
  'bop': 'v./n. 打击；跳舞',
  'borax': 'n. 硼砂',
  'bordello': 'n. 妓院',
  'bornite': 'n. 斑铜矿',
  'borscht': 'n. 罗宋汤',
  'bosh': 'n. 胡说；空话',
  'boston': 'n. 波士顿',
  'bottomry': 'n. 船舶抵押',
  'bouchée': 'n. 小点心；一口酥',
  'bough': 'n. 树枝',
  'bought': 'v. 购买（buy的过去式和过去分词）',
  'boulevard': 'n. 林荫大道',
  'bourdon': 'n. 低音管；钟声',
  'bowdlerize': 'v. 删除；删改',
  'boyfriend': 'n. 男朋友',
  'brachiopod': 'n. 腕足动物',
  'bract': 'n. 苞叶；苞',
  'brad': 'n. 曲头钉；小钉',
  'brae': 'n. 山坡；斜坡',
  'braft': 'n. 糙羽；草稿',
  'braille': 'n. 盲文；点字',
  'brainchild': 'n. 脑力劳动成果；发明',
  'brainsick': 'adj. 疯狂的；愚蠢的',
  'brainstorm': 'n./v. 灵机一动；脑风暴',
  'brainwash': 'v. 洗脑；蛊惑',
  'brainy': 'adj. 聪明的；脑筋好的',
  'braise': 'v. 炖；焖',
  'brake': 'n./v. 刹车；制动',
  'bramble': 'n. 荆棘；黑莓丛',
  'bran': 'n. 糠；麸皮',
  'branch': 'n./v. 树枝；分支',
  'brand': 'n./v. 品牌；烙印',
  'brandy': 'n. 白兰地酒',
  'brash': 'adj. 仓促的；粗鲁的',
  'brass': 'n. 黄铜；铜管乐器',
  'brassiere': 'n. 胸罩；乳罩',
  'brat': 'n. 顽童；小鬼',
  'bravado': 'n. 虚张声势；逞强',
  'brave': 'adj./v. 勇敢的；勇敢面对',
  'bravo': 'int./n. 好！；喝彩',
  'brawl': 'n./v. 争吵；打架',
  'brawn': 'n. 肌肉；体力',
  'brawny': 'adj. 肌肉发达的；强壮的',
  'bread': 'n. 面包；食物',
  'breadth': 'n. 宽度；幅度',
  'break': 'v./n. 打破；休息',
  'breakdown': 'n. 故障；分解',
  'breakfast': 'n. 早餐',
  'breakwater': 'n. 防波堤',
  'breast': 'n. 胸部；乳房',
  'breath': 'n. 呼吸；气息',
  'breathe': 'v. 呼吸；吐露',
  'breathless': 'adj. 气喘吁吁的；屏息的',
  'breccia': 'n. 角砾岩',
  'bred': 'v. 繁殖；养育',
  'breech': 'n. 臀部；枪托',
  'breeches': 'n. 马裤；短裤',
  'breed': 'v./n. 繁殖；品种',
  'breeze': 'n. 微风；轻而易举的事',
  'breezy': 'adj. 有微风的；通风的',
  'breve': 'n. 短音符号；二全音符',
  'brevity': 'n. 简洁；短促',
  'brew': 'v. 酿造；泡茶',
  'brewery': 'n. 啤酒厂',
  'briar': 'n. 荆棘；烟斗',
  'bribe': 'n./v. 贿赂；收买',
  'bribery': 'n. 行贿；受贿',
  'brick': 'n. 砖块；砖头',
  'brickbat': 'n. 砖块；诽谤',
  'bridal': 'adj. 新娘的；婚礼的',
  'bride': 'n. 新娘',
  'bridegroom': 'n. 新郎',
  'bridesmaid': 'n. 伴娘',
  'bridge': 'n./v. 桥梁；架桥',
  'bridle': 'n./v. 缰绳；约束',
  'brief': 'adj./n./v. 简短的；摘要',
  'briefcase': 'n. 公文包；手提箱',
  'brigade': 'n. 旅；队',
  'brigadier': 'n. 旅长；准将',
  'brigand': 'n. 土匪；强盗',
  'bright': 'adj. 明亮的；聪明的',
  'brighten': 'v. 使明亮；使快乐',
  'brilliance': 'n. 光辉；才华',
  'brilliant': 'adj. 卓越的；灿烂的',
  'brim': 'n. 边缘；帽檐',
  'brimstone': 'n. 硫磺；地狱',
  'brindle': 'adj. 有斑纹的；斑驳的',
  'brine': 'n. 盐水；海',
  'bring': 'v. 带来；引起',
  'brink': 'n. 边缘；悬崖',
  'briny': 'adj. 海水的；咸的',
  'brisk': 'adj. 轻快的；活泼的',
  'bristle': 'n./v. 刚毛；竖起',
  'brittle': 'adj. 易碎的；脆弱的',
  'broad': 'adj. 宽广的；辽阔的',
  'broadcast': 'v./n. 广播；播送',
  'broaden': 'v. 放宽；加宽',
  'broadloom': 'n. 宽幅地毯',
  'broadsheet': 'n. 大张纸；宽幅印刷品',
  'broadside': 'n. 舷侧；全面攻击',
  'brocade': 'n. 锦缎；织锦',
  'broccoli': 'n. 西兰花；花椰菜',
  'brochure': 'n. 小册子；说明书',
  'broil': 'v. 烧烤；使热',
  'broke': 'v. 打破（break的过去式）',
  'broken': 'adj. 破碎的；骨折的',
  'broker': 'n. 经纪人；掮客',
  'brokerage': 'n. 经纪业；佣金',
  'bronchial': 'adj. 支气管的',
  'bronchitis': 'n. 支气管炎',
  'bronco': 'n. 野马；半驯马',
  'bronze': 'n./v. 青铜色；镀青铜',
  'brooch': 'n. 胸针；饰针',
  'brood': 'n./v. 一窝；孵蛋',
  'brook': 'n. 小溪；容忍',
  'broom': 'n. 扫帚；金丝桃',
  'broth': 'n. 肉汤； broth',
  'brother': 'n. 兄弟；教友',
  'brotherhood': 'n. 手足情谊；兄弟关系',
  'brow': 'n. 眉毛；额',
  'browbeat': 'v. 吓唬；威胁',
  'brown': 'n./adj. 棕色；褐色的',
  'brownstone': 'n. 褐沙石；豪宅',
  'browse': 'v./n. 浏览；吃草',
  'bruin': 'n. 棕熊',
  'bruise': 'n./v. 瘀伤；碰伤',
  'bruit': 'v. 传播；散布',
  'brunch': 'n. 早午餐',
  'brunt': 'n. 冲击；主要压力',
  'brush': 'n./v. 刷子；刷',
  'brushfire': 'n. 灌木丛火；小火灾',
  'brushwood': 'n. 灌木丛；柴薪',
  'brusque': 'adj. 唐突的；生硬的',
  'brutal': 'adj. 残忍的；野蛮的',
  'brutality': 'n. 残忍；暴行',
  'brute': 'n./adj. 野兽；残忍的',
  'bubble': 'n./v. 气泡；冒泡',
  'bubbly': 'adj. 多泡的；活泼的',
  'buccaneer': 'n. 海盗；冒险家',
  'buck': 'n./v. 雄鹿；猛然弓背跃起',
  'bucket': 'n. 桶；水桶',
  'buckle': 'n./v. 皮带扣；扣紧',
  'buckshot': 'n. 大号铅弹',
  'buckskin': 'n. 鹿皮；羊皮',
  'bud': 'n./v. 芽；发芽',
  'buddy': 'n. 伙伴；好朋友',
  'budge': 'v. 移动；让步',
  'budget': 'n./v. 预算；做预算',
  'buff': 'adj./n. 浅黄色的；爱好者',
  'buffalo': 'n. 水牛；野牛',
  'buffer': 'n./v. 缓冲器；缓冲',
  'buffet': 'n./v. 自助餐；打击',
  'buffoon': 'n. 小丑；逗人笑的人',
  'bug': 'n./v. 虫子；窃听器',
  'buggy': 'n. 婴儿车；轻型马车',
  'bugle': 'n. 喇叭；军号',
  'build': 'v./n. 建造；构建',
  'builder': 'n. 建筑者；建设者',
  'building': 'n. 建筑物；建筑',
  'built': 'v. 建造（build的过去式）',
  'bulb': 'n. 电灯泡；球茎',
  'bulge': 'n./v. 膨胀；凸出',
  'bulk': 'n. 体积；大容量',
  'bull': 'n. 公牛；粗壮的人',
  'bulldog': 'n. 斗牛犬',
  'bulldoze': 'v. 推土机清除；恐吓',
  'bulldozer': 'n. 推土机',
  'bullet': 'n. 子弹；弹丸',
  'bulletin': 'n. 公告；公报',
  'bullfight': 'n. 斗牛',
  'bullfrog': 'n. 牛蛙',
  'bullion': 'n. 金条；银条',
  'bullish': 'adj. 看涨的；乐观的',
  'bullock': 'n. 阉牛；小公牛',
  'bully': 'n./v. 欺凌者；欺负',
  'bullyboy': 'n. 恶霸；打手',
  'bump': 'v./n. 碰撞；撞击',
  'bumper': 'n. 保险杠； bumper（汽车前后部的缓冲装置）',
  'bumpy': 'adj. 颠簸的；不平的',
  'bun': 'n. 圆面包；小圆面包',
  'bunch': 'n./v. 束；扎',
  'bundle': 'n./v. 捆；束',
  'bungalow': 'n. 平房；小别墅',
  'bungle': 'v./n. 搞砸；笨拙地做',
  'bunk': 'n. 铺位；废话',
  'bunker': 'n. 煤仓；地堡',
  'bunny': 'n. 兔子；小兔子',
  'buoy': 'n./v. 浮标；支撑',
  'buoyancy': 'n. 浮力；轻快',
  'buoyant': 'adj. 有浮力的；轻快的',
  'burden': 'n./v. 负担；使负担',
  'bureau': 'n. 局；办公桌',
  'bureaucracy': 'n. 官僚主义；政府机构',
  'bureaucrat': 'n. 官僚；官僚主义者',
  'burger': 'n. 汉堡包',
  'burglar': 'n. 窃贼；夜盗',
  'burglary': 'n. 盗窃；入室盗窃',
  'burgle': 'v. 盗窃；入室行窃',
  'burgundy': 'n. 勃艮第酒；深红色',
  'burial': 'n. 埋葬；葬礼',
  'burke': 'v. 勒死；扼杀',
  'burlap': 'n. 粗麻布；帆布',
  'burn': 'v./n. 燃烧；烧伤',
  'burner': 'n. 燃烧器；炉子',
  'burnish': 'v. 抛光；擦亮',
  'burnout': 'n. 燃尽；过度疲劳',
  'burnt': 'adj. 烧焦的；烧伤的',
  'burp': 'v./n. 打嗝；嗳气',
  'burro': 'n. 驴子；小型驴',
  'burrow': 'n./v. 洞穴；挖洞',
  'burst': 'v./n. 爆发；爆炸',
  'bury': 'v. 埋葬；掩埋',
  'bush': 'n. 灌木；灌木丛',
  'bushel': 'n. 蒲式耳（容量单位）',
  'bushfire': 'n. 丛林火灾',
  'bushy': 'adj. 灌木丛生的；浓密的',
  'business': 'n. 商业；生意',
  'businesslike': 'adj. 事务性的；认真的',
  'busk': 'v. 街头卖艺',
  'busker': 'n. 街头艺人',
  'bust': 'n./v. 半身像； bust（胸部）；突击搜查',
  'bustle': 'v./n. 忙乱；喧闹',
  'busy': 'adj. 忙碌的；占用中的',
  'butch': 'adj./n. 男性化的；粗犷的',
  'butcher': 'n./v. 屠夫；屠宰',
  'butler': 'n. 男管家；仆役长',
  'butt': 'n./v. 枪托；烟头；嘲笑',
  'butte': 'n. 孤山；山丘',
  'butter': 'n. 黄油；奶油',
  'buttercup': 'n. 毛茛；金凤花',
  'butterfly': 'n. 蝴蝶',
  'buttermilk': 'n. 酪乳；白脱牛奶',
  'butterscotch': 'n. 奶油硬糖；黄油糖',
  'buttery': 'adj. 黄油般的；油腻的',
  'button': 'n./v. 按钮；纽扣',
  'buttress': 'n./v. 扶壁；支撑',
  'buxom': 'adj. 丰满的；健康的',
  'buy': 'v./n. 购买；买',
  'buyer': 'n. 买家；采购员',
  'buzz': 'n./v. 嗡嗡声；发出嗡嗡声',
  'buzzard': 'n. 秃鹰；嗡嗡作响的东西',
  'buzzer': 'n. 蜂鸣器；门铃',
  'bypass': 'n./v. 旁道；绕过',
  'byre': 'n. 牛棚；牛舍',
  'byte': 'n. 字节；8位元组',
  'byzantine': 'adj. 拜占庭的；复杂的',
};

let fixedCount = 0;
const errors = [];

for (const [word, meaning] of Object.entries(corrections)) {
  const pattern = new RegExp(`"meaning": "n\\. ${word}"`);
  if (content.includes(`"word": "${word}"`)) {
    const match = content.match(pattern);
    if (match) {
      content = content.replace(pattern, `"meaning": "${meaning}"`);
      fixedCount++;
    }
  }
}

fs.writeFileSync(filePath, content);

console.log(`Fixed ${fixedCount} English meanings to Chinese`);
if (errors.length > 0) {
  console.log(`Errors: ${errors.length}`);
  errors.forEach(e => console.log(`  - ${e}`));
}
