const fs = require('fs');

const filePath = './src/data/mockWords.ts';
let content = fs.readFileSync(filePath, 'utf-8');

const corrections = {
  'befit': 'v. 适合；适宜',
  'befog': 'v. 使模糊；使困惑',
  'befool': 'v. 欺骗；愚弄',
  'beget': 'v. 产生；引起',
  'beggar': 'n. 乞丐；穷人',
  'begrime': 'v. 弄脏；使灰暗',
  'begun': 'v. 开始（begin的过去分词）',
  'behead': 'v. 斩首；砍头',
  'behest': 'n. 命令；训示',
  'behold': 'v. 看；注视',
  'beholden': 'adj. 感激的；蒙恩的',
  'behove': 'v. 应当；理应',
  'belay': 'v. 绑紧；使固定',
  'belch': 'v. 打嗝；喷出',
  'bellboy': 'n. 旅馆侍者；行李员',
  'beltway': 'n. 环城公路； belt道路',
  'benchmark': 'n. 基准；标准',
  'benefice': 'n. 圣俸；牧师俸禄',
  'benison': 'n. 祝福；恩赐',
  'benthamite': 'n. 边沁主义者；功利主义者',
  'bequest': 'n. 遗产；遗赠',
  'beret': 'n. 贝雷帽',
  'beriberi': 'n. 脚气病',
  'berserk': 'adj./n. 疯狂的；狂战士',
  'beryl': 'n. 绿宝石；绿柱石',
  'beryllium': 'n. 铍',
  'beshrew': 'v. 诅咒；咒骂',
  'besmear': 'v. 涂抹；弄脏',
  'besom': 'n. 扫帚；长柄扫帚',
  'besot': 'v. 使沉醉；使痴迷',
  'beseech': 'v. 恳求；哀求',
  'besiege': 'v. 围攻；包围',
  'besmirch': 'v. 弄脏；损害名誉',
  'bespatter': 'v. 溅污；诽谤',
  'bestow': 'v. 授予；使用',
  'bestrew': 'v. 撒满；布满',
  'bestride': 'v. 跨越；骑',
  'betake': 'v. 使去；使致力于',
  'bethink': 'v. 使思考；使想起',
  'betide': 'v. 发生；降临',
  'betoken': 'v. 预示；表示',
  'betray': 'v. 背叛；辜负',
  'betroth': 'v. 订婚；许配',
  'better': 'adj./adv./v. 更好的；更好地；改善',
  'bevel': 'n./v. 斜角；使成斜角',
  'beverage': 'n. 饮料',
  'bewail': 'v. 悲悼；哀泣',
  'beware': 'v. 谨防；注意',
  'bewilder': 'v. 使困惑；使为难',
  'bewitch': 'v. 施魔法；使着迷',
  'beyond': 'prep./adv. 超过；在...之上',
  'biannual': 'adj. 一年两次的',
  'bias': 'n./v. 偏见；使有偏见',
  'bib': 'n. 围嘴；围裙',
  'bible': 'n. 圣经；权威书籍',
  'bicycle': 'n. 自行车',
  'bid': 'v./n. 出价；投标',
  'biddy': 'n. 鸡；小妇人',
  'bide': 'v. 居住；等待',
  'biennial': 'adj. 两年一次的',
  'bier': 'n. 棺材架；灵柩',
  'biff': 'n./v. 一击；殴打',
  'bifocals': 'n. 双光眼镜',
  'big': 'adj. 大的；重要的',
  'bigamy': 'n. 重婚罪',
  'bight': 'n. 绳环；海湾',
  'bigot': 'n. 固执己见者；盲信者',
  'bilge': 'n. 舱水；废话',
  'biliary': 'adj. 胆汁的；胆管的',
  'bilk': 'v. 欺骗；赖账',
  'bill': 'n./v. 账单；发票',
  'billboard': 'n. 广告牌；招贴板',
  'billet': 'n./v.  billet（入伍令）；安排住宿',
  'billow': 'n./v. 巨浪；波涛汹涌',
  'billy': 'n. 警棍；伙伴',
  'bimonthly': 'adj./adv. 两月一次的',
  'bin': 'n. 箱子；仓',
  'binary': 'adj. 二进制的；双的',
  'bind': 'v. 绑；包扎',
  'binder': 'n. 包扎者；活页夹',
  'binding': 'n./adj. 封面；约束的',
  'bine': 'n. 藤；蔓',
  'binge': 'n./v. 狂饮；狂欢',
  'bingo': 'n. 宾果游戏',
  'biochemistry': 'n. 生物化学',
  'biography': 'n. 传记；个人经历',
  'biology': 'n. 生物学',
  'bionic': 'adj. 仿生学的',
  'biopsy': 'n. 活组织检查',
  'biosphere': 'n. 生物圈',
  'biotechnology': 'n. 生物技术',
  'bipartisan': 'adj. 两党连立的',
  'birch': 'n. 桦树；桦木',
  'bird': 'n. 鸟；鸟类',
  'birdie': 'n. 小鸟；少女',
  'birth': 'n. 出生；分娩',
  'birthday': 'n. 生日；诞辰',
  'birthplace': 'n. 出生地；发源地',
  'biscuit': 'n. 饼干；软烤饼',
  'bisect': 'v. 平分；分为二',
  'bishop': 'n. 主教；象棋中的象',
  'bistro': 'n. 小餐馆；酒吧',
  'bit': 'n. 一点；比特',
  'bite': 'v./n. 咬；叮',
  'biting': 'adj. 刺骨的；尖锐的',
  'bitmap': 'n. 位图',
  'bitten': 'v. 咬伤（bite的过去分词）',
  'bitter': 'adj. 苦的；痛苦的',
  'bittern': 'n. 苦鹬；麻鹬',
  'bitumen': 'n. 沥青；柏油',
  'bivalve': 'n. 双壳类动物',
  'bivouac': 'n./v. 露营；临时宿营',
  'bizarre': 'adj. 奇异的；古怪的',
  'blab': 'v. 泄露；胡说',
  'black': 'adj. 黑色的；黑暗的',
  'blackball': 'v. 排斥；投票反对',
  'blackberry': 'n. 黑莓',
  'blackbird': 'n. 画眉；乌鸫',
  'blackboard': 'n. 黑板',
  'blackcock': 'n. 黑松鸡',
  'blacken': 'v. 使变黑；诽谤',
  'blackhead': 'n. 黑头粉刺；黑顶鸟',
  'blackjack': 'n. 二十一点；皮鞭',
  'blackleg': 'n. 骗子；叛徒',
  'blackmail': 'n./v. 勒索；敲诈',
  'blackout': 'n. 灯火管制；停电',
  'blacksmith': 'n. 铁匠',
  'blackthorn': 'n. 黑刺李；黑荆棘',
  'bladder': 'n. 膀胱；气泡',
  'blade': 'n. 刀刃；叶片',
  'blame': 'v./n. 责备；归咎于',
  'blanch': 'v. 漂白；使变白',
  'bland': 'adj. 温和的；枯燥的',
  'blank': 'adj./n. 空白的；空格',
  'blanket': 'n. 毯子；覆盖层',
  'blare': 'v. 高声鸣叫；闪耀',
  'blarney': 'n. 奉承；谄媚',
  'blasé': 'adj. 厌倦的；玩腻了的',
  'blaspheme': 'v. 亵渎；咒骂',
  'blast': 'n./v. 爆炸；冲击',
  'blaze': 'n./v. 火焰；燃烧',
  'blaz': 'n. 火焰；光辉',
  'bleach': 'v. 漂白；使褪色',
  'bleak': 'adj. 荒凉的；凄凉的',
  'bleat': 'v./n. 羊叫；哀声',
  'bleed': 'v. 流血；渗出',
  'blemish': 'n./v. 污点；损害',
  'blend': 'v. 混合；融合',
  'bless': 'v. 祝福；保佑',
  'blessing': 'n. 祝福；恩赐',
  'blight': 'n./v. 枯萎病；毁坏',
  'blimp': 'n. 软式飞艇',
  'blind': 'adj./v. 失明的；蒙蔽',
  'blink': 'v. 眨眼；闪烁',
  'bliss': 'n. 极乐；天赐之福',
  'blister': 'n./v. 水泡；使起泡',
  'blithe': 'adj. 快乐的；无忧无虑的',
  'blitz': 'n./v. 闪电战；空袭',
  'blizzard': 'n. 暴风雪',
  'bloat': 'v. 使肿胀；使得意',
  'blob': 'n. 一滴；斑点',
  'bloc': 'n. 集团；阵营',
  'block': 'n./v. 块；阻碍',
  'blockade': 'n./v. 封锁；阻挡',
  'blockage': 'n. 阻塞；封锁状态',
  'blog': 'n. 博客；网络日志',
  'bloke': 'n. 男人；家伙',
  'blond': 'adj./n. 金色的；白肤金发的人',
  'blood': 'n. 血；血液',
  'bloodhound': 'n. 侦探；猎犬',
  'bloodshed': 'n. 流血；杀戮',
  'bloodshot': 'adj. 充血的；布满血丝的',
  'bloodsport': 'n. 流血运动',
  'bloodstain': 'n. 血迹；血污',
  'bloodstream': 'n. 血流；血管',
  'bloodthirsty': 'adj. 嗜血的；残忍的',
  'bloody': 'adj./v. 血淋淋的；使出血',
  'bloom': 'n./v. 花；开花',
  'blossom': 'n./v. 花；开花',
  'blot': 'n./v. 污点；弄脏',
  'blotch': 'n. 斑点；污点',
  'blotto': 'adj. 烂醉的',
  'blouse': 'n. 女衬衫；童衫',
  'blow': 'n./v. 吹；打击',
  'blowgun': 'n. 吹箭筒；吹枪',
  'blowhole': 'n. 呼吸孔；鲸鱼喷水孔',
  'blowlamp': 'n. 喷灯',
  'blowpipe': 'n. 吹管；吹箭筒',
  'blowtorch': 'n. 喷灯；气炬',
  'blowzy': 'adj. 红润的；不整洁的',
  'blue': 'adj./n. 蓝色的；忧郁的',
  'bluebell': 'n. 野风信子；蓝铃花',
  'blueberry': 'n. 蓝莓',
  'bluebird': 'n. 蓝知更鸟',
  'bluebook': 'n. 蓝皮书；学生用空白练习册',
  'blues': 'n. 布鲁斯音乐；忧郁',
  'bluff': 'v./n. 诈骗；吓唬',
  'blunder': 'n./v. 失误；跌跌撞撞',
  'blunderbuss': 'n. 老式大口径短枪；蠢人',
  'blur': 'v./n. 模糊；使模糊',
  'blurt': 'v. 突然说出；脱口而出',
  'blush': 'v./n. 脸红；羞愧',
  'bluster': 'v./n. 咆哮；吓唬',
  'boar': 'n. 野猪；公猪',
  'board': 'n./v. 木板；董事会',
  'boardroom': 'n. 会议室；董事会会议室',
  'boast': 'v./n. 自夸；吹嘘',
  'boat': 'n. 船；小船',
  'boatman': 'n. 船夫；船家',
  'boaty': 'n. 船（通常指小船）',
  'boatyard': 'n. 船坞；造船厂',
  'bob': 'v./n. 上下跳动；短截',
  'bobbin': 'n. 线轴；纺纱筒',
  'bobby': 'n. 警察；小罗伯特',
  'bobcat': 'n. 山猫；短毛猫',
  'bode': 'v. 预示；为...的兆头',
  'bodge': 'v. 笨拙地修；搞糟',
  'bog': 'n. 沼泽；泥塘',
  'bogey': 'n. 鬼怪；令人恐惧的事物',
  'boggle': 'v. 犹豫；吃惊',
  'bogus': 'adj. 假的；伪造的',
  'boil': 'v. 沸腾；煮沸',
  'boiler': 'n. 锅炉；热水器',
  'boiling': 'adj. 沸腾的；激昂的',
};

let fixedCount = 0;
const errors = [];

for (const [word, meaning] of Object.entries(corrections)) {
  const pattern = new RegExp(`"meaning": "n\\. ${word}"`);
  if (content.includes(`"word": "${word}"`)) {
    const match = content.match(pattern);
    if (match) {
      content = content.replace(pattern, `"meaning": "${meaning}"`);
      fixedCount++;
    }
  }
}

fs.writeFileSync(filePath, content);

console.log(`Fixed ${fixedCount} English meanings to Chinese`);
if (errors.length > 0) {
  console.log(`Errors: ${errors.length}`);
  errors.forEach(e => console.log(`  - ${e}`));
}
