const fs = require('fs');

const commonMeanings = {
  abandon: 'v. 放弃；抛弃；离开',
  ability: 'n. 能力；才能',
  able: 'adj. 能干的；能够的',
  aboard: 'adv./prep. 在船（飞机、火车）上；上船',
  about: 'prep. 关于；大约 adv. 关于；到处',
  above: 'prep. 在...上面 adj. 上面的 adv. 在上面',
  abroad: 'adv. 到国外；在国外',
  absence: 'n. 缺席；缺乏；不存在',
  absolute: 'adj. 绝对的；完全的',
  absorb: 'v. 吸收；吸引；理解',
  abstract: 'adj. 抽象的 n. 摘要 v. 提取',
  academic: 'adj. 学术的；学院的 n. 学者',
  accept: 'v. 接受；承认；认可',
  access: 'n. 进入；访问；通道 v. 访问',
  accident: 'n. 事故；意外事件',
  accomplish: 'v. 完成；实现；达到',
  account: 'n. 账户；说明 v. 解释；占',
  accurate: 'adj. 准确的；精确的',
  achieve: 'v. 完成；达到；实现',
  acknowledge: 'v. 承认；确认；感谢',
  acquire: 'v. 获得；学到；收购',
  across: 'prep. 穿过 adv. 到对面',
  active: 'adj. 积极的；活跃的；主动的',
  activity: 'n. 活动；行动',
  actual: 'adj. 实际的；真实的',
  adapt: 'v. 适应；改编；改写',
  add: 'v. 添加；增加；补充',
  address: 'n. 地址；演讲 v. 解决；向...讲话',
  adequate: 'adj. 足够的；适当的；勉强够的',
  adjust: 'v. 调整；适应；调节',
  administration: 'n. 管理；行政；政府',
  admire: 'v. 钦佩；欣赏；赞美',
  admit: 'v. 承认；准许进入；容纳',
  adopt: 'v. 采取；收养；采纳',
  adult: 'n. 成年人 adj. 成年的',
  advance: 'v. 前进；推进；上涨 n. 进展',
  advantage: 'n. 优势；好处；利益',
  adventure: 'n. 冒险；奇遇 v. 冒险',
  advertise: 'v. 做广告；宣传；公布',
  advice: 'n. 建议；劝告；通知',
  advise: 'v. 建议；劝告；通知',
  affair: 'n. 事件；事务；风流韵事',
  affect: 'v. 影响；感动；假装',
  afford: 'v. 负担得起；提供；抽出',
  afraid: 'adj. 害怕的；担心的；恐怕',
  age: 'n. 年龄；时代 v. 变老；老化',
  agency: 'n. 代理；机构；中介',
  agent: 'n. 代理人；经纪人；特工',
  aggressive: 'adj. 侵略性的；进取的；积极的',
  agree: 'v. 同意；赞成；适合',
  agriculture: 'n. 农业；农学',
  ahead: 'adv. 在前面；提前；向前',
  aid: 'v. 帮助；援助 n. 帮助；助手',
  aim: 'v. 瞄准；致力于 n. 目标；目的',
  air: 'n. 空气；天空；气氛 v. 通风；广播',
  aircraft: 'n. 飞机；航空器',
  airline: 'n. 航空公司；航线',
  airport: 'n. 机场；航空站',
  alarm: 'n. 警报；惊恐 v. 警告；使恐慌',
  album: 'n. 相册；专辑；集邮册',
  alcohol: 'n. 酒精；酒；乙醇',
  alike: 'adj. 相同的；相似的 adv. 相同地',
  alive: 'adj. 活着的；活跃的；存在的',
  allow: 'v. 允许；给予；承认',
  almost: 'adv. 几乎；差不多；将近',
  alone: 'adj. 单独的；孤独的 adv. 独自',
  along: 'prep. 沿着 adv. 向前；一起',
  already: 'adv. 已经；早已',
  also: 'adv. 也；同样；而且',
  alter: 'v. 改变；修改；更改',
  alternative: 'n. 选择；替代物 adj. 替代的',
  although: 'conj. 虽然；尽管；然而',
  always: 'adv. 总是；一直；永远',
  amaze: 'v. 使惊奇；使惊讶',
  ambition: 'n. 雄心；抱负；野心',
  ambulance: 'n. 救护车；野战医院',
  among: 'prep. 在...之中；其中',
  amount: 'n. 数量；总额 v. 合计；相当于',
  amuse: 'v. 娱乐；使愉快；使发笑',
  analyse: 'v. 分析；分解',
  analysis: 'n. 分析；分解；解析',
  ancient: 'adj. 古代的；古老的 n. 古人',
  angle: 'n. 角度；观点；角落 v. 钓鱼',
  angry: 'adj. 生气的；愤怒的；疼痛的',
  animal: 'n. 动物 adj. 动物的',
  announce: 'v. 宣布；通知；播报',
  annoy: 'v. 使烦恼；打扰；使生气',
  annual: 'adj. 年度的；每年的 n. 年刊',
  another: 'adj. 另一；再一 pron. 另一个',
  answer: 'v. 回答；答复 n. 答案；回答',
  anticipate: 'v. 预期；预见；期待',
  anxiety: 'n. 焦虑；担心；渴望',
  anxious: 'adj. 焦虑的；担心的；渴望的',
  any: 'adj. 任何；任一 pron. 任何一个',
  anyone: 'pron. 任何人；无论谁',
  anything: 'pron. 任何事；某事',
  anyway: 'adv. 无论如何；总之',
  anywhere: 'adv. 在任何地方 n. 任何地方',
  apart: 'adv. 分开；分别 adj. 分离的',
  apologize: 'v. 道歉；谢罪；辩解',
  apparent: 'adj. 明显的；表面的；貌似的',
  appeal: 'v. 呼吁；吸引；上诉 n. 吸引力',
  appear: 'v. 出现；似乎；显得',
  appetite: 'n. 食欲；胃口；欲望',
  apple: 'n. 苹果；苹果树',
  apply: 'v. 申请；应用；涂；适用',
  appoint: 'v. 任命；指定；约定',
  appreciate: 'v. 欣赏；感激；领会；涨价',
  approach: 'v. 接近；靠近 n. 方法；途径',
  appropriate: 'adj. 适当的；合适的 v. 拨款',
  approve: 'v. 批准；赞成；认可',
  approximate: 'adj. 大约的；近似的 v. 近似',
  architect: 'n. 建筑师；设计师',
  architecture: 'n. 建筑学；建筑设计',
  area: 'n. 区域；面积；领域',
  argue: 'v. 争论；辩论；主张',
  argument: 'n. 争论；论据；论证',
  arise: 'v. 出现；产生；起身',
  arm: 'n. 手臂；武器 v. 武装；装备',
  army: 'n. 军队；陆军；大群',
  around: 'prep. 围绕；到处 adv. 周围',
  arrange: 'v. 安排；筹备；整理',
  arrest: 'v. 逮捕；拘留；阻止 n. 逮捕',
  arrival: 'n. 到达；到来；抵达',
  arrive: 'v. 到达；抵达；成功',
  article: 'n. 文章；物品；条款',
  artificial: 'adj. 人造的；假的；虚伪的',
  artist: 'n. 艺术家；美术家',
  artistic: 'adj. 艺术的；精美的',
  aside: 'adv. 在一边；离开；向旁边',
  ask: 'v. 问；要求；邀请',
  asleep: 'adj. 睡着的；熟睡的',
  aspect: 'n. 方面；外观；朝向',
  assert: 'v. 断言；主张；维护',
  assess: 'v. 评估；评定；估算',
  asset: 'n. 资产；财产；优点',
  assign: 'v. 分配；指派；布置',
  assist: 'v. 帮助；协助 n. 帮助',
  assistance: 'n. 协助；帮助；辅助',
  associate: 'v. 联系；交往 n. 同事 adj. 副的',
  association: 'n. 协会；联盟；关联',
  assume: 'v. 假设；假定；承担',
  assure: 'v. 保证；使确信；保险',
  attach: 'v. 附上；贴上；使依附',
  attack: 'v. 攻击；进攻 n. 攻击；抨击',
  attempt: 'v. 尝试；企图 n. 试图；努力',
  attend: 'v. 参加；照顾；注意',
  attitude: 'n. 态度；看法；姿势',
  attract: 'v. 吸引；引起；诱惑',
  audience: 'n. 观众；听众；读者',
  author: 'n. 作者；作家 v. 写作',
  authority: 'n. 权威；权力；当局',
  automatic: 'adj. 自动的；无意识的 n. 自动装置',
  available: 'adj. 可用的；可获得的；有空的',
  average: 'n. 平均；平均水平 adj. 平均的',
  avoid: 'v. 避免；避开；取消',
  award: 'n. 奖励；奖品 v. 授予；判定',
  aware: 'adj. 意识到的；知道的',
  away: 'adv. 离开；在远处；向远处',
  awful: 'adj. 可怕的；极坏的；糟糕的',
  awkward: 'adj. 尴尬的；笨拙的；棘手的',
  baby: 'n. 婴儿；宝贝 v. 娇养',
  back: 'n. 背部；后面 adj. 后面的 adv. 向后',
  background: 'n. 背景；经历；后台',
  bacteria: 'n. 细菌',
  bad: 'adj. 坏的；差的；严重的',
  balance: 'n. 平衡；天平 v. 权衡；均衡',
  ban: 'v. 禁止；取缔 n. 禁令；禁止',
  band: 'n. 乐队；带；波段 v. 联合',
  bank: 'n. 银行；河岸 v. 存钱',
  barrier: 'n. 障碍；屏障；栅栏',
  base: 'n. 基础；基地 v. 基于 adj. 卑鄙的',
  basic: 'adj. 基本的；基础的 n. 基础',
  basis: 'n. 基础；根据；主要成分',
  basket: 'n. 篮子；一篮',
  battery: 'n. 电池；一系列；炮台',
  battle: 'n. 战斗；战役 v. 斗争；搏斗',
  beach: 'n. 海滩；湖滨 v. 搁浅',
  bear: 'v. 承受；忍受；结果 n. 熊',
  beast: 'n. 野兽；畜生；人面兽心',
  beat: 'v. 打；打败；搅拌 n. 拍子 adj. 疲惫的',
  beautiful: 'adj. 美丽的；美好的；出色的',
  beauty: 'n. 美丽；美人；精华',
  become: 'v. 变成；成为；适合',
  beef: 'n. 牛肉 v. 抱怨；加强',
  beer: 'n. 啤酒',
  before: 'prep. 在...之前 conj. 在...以前',
  begin: 'v. 开始；启动；起始',
  behavior: 'n. 行为；举止；表现',
  behind: 'prep. 在...后面 adv. 在后；落后',
  belief: 'n. 信念；信仰；信任',
  believe: 'v. 相信；认为；信任',
  bell: 'n. 钟；铃；铃声',
  belong: 'v. 属于；应归入；适应',
  below: 'prep. 在...下面 adv. 在下面',
  bench: 'n. 长凳；工作台；法官席',
  benefit: 'n. 利益；好处 v. 有益于；受益',
  beside: 'prep. 在...旁边；与...相比',
  besides: 'adv. 此外；而且 prep. 除...之外',
  best: 'adj. 最好的 adv. 最好地 n. 最好的人',
  better: 'adj. 更好的 adv. 更好 v. 改善',
  between: 'prep. 在...之间 adv. 在中间',
  beyond: 'prep. 超过；在...那边 adv. 在远处',
  bicycle: 'n. 自行车 v. 骑自行车',
  big: 'adj. 大的；重要的；重大的',
  bike: 'n. 自行车 v. 骑自行车',
  bill: 'n. 账单；钞票；法案 v. 给...开账单',
  billion: 'num. 十亿 n. 大量',
  bind: 'v. 捆绑；装订；约束 n. 捆绑',
  biology: 'n. 生物学；生态学',
  bird: 'n. 鸟；禽类',
  birth: 'n. 出生；起源；诞生',
  birthday: 'n. 生日；诞辰',
  biscuit: 'n. 饼干；小面包',
  bit: 'n. 一点；一些；比特 v. 咬',
  bite: 'v. 咬；叮；刺穿 n. 咬；咬伤',
  black: 'adj. 黑色的；黑暗的 n. 黑色',
  blade: 'n. 刀片；叶片；剑',
  blame: 'v. 责备；归咎于 n. 责任；责备',
  blank: 'adj. 空白的；茫然的 n. 空白；空格',
  blanket: 'n. 毯子；覆盖层 v. 覆盖',
  blast: 'n. 爆炸；一阵 v. 炸毁；摧毁',
  blend: 'v. 混合；融合 n. 混合物',
  bless: 'v. 祝福；保佑；赞美',
  blind: 'adj. 瞎的；盲目的 v. 使失明 n. 窗帘',
  block: 'n. 块；街区 v. 阻塞；阻止',
  blood: 'n. 血；血液；血统 v. 出血',
  bloom: 'n. 花；开花 v. 开花；繁荣',
  blow: 'v. 吹；风吹；打击 n. 吹；打击',
  blue: 'adj. 蓝色的；忧郁的 n. 蓝色',
  board: 'n. 木板；甲板；董事会 v. 上船；寄宿',
  boat: 'n. 船；小船 v. 划船',
  body: 'n. 身体；主体；尸体',
  boil: 'v. 煮沸；沸腾 n. 沸腾；煮',
  bold: 'adj. 大胆的；粗体的；冒失的',
  bolt: 'n. 螺栓；门闩 v. 闩住；逃跑',
  bomb: 'n. 炸弹 v. 轰炸；投弹',
  bond: 'n. 债券；纽带；结合 v. 结合',
  bone: 'n. 骨头；骨骼 v. 剔骨',
  book: 'n. 书；本子 v. 预订；登记',
  boom: 'n. 繁荣；隆隆声 v. 繁荣；急速发展',
  boost: 'v. 促进；提高；增加 n. 推动',
  boot: 'n. 靴子；启动 v. 启动；踢',
  border: 'n. 边界；边境 v. 接近；与...接壤',
  bore: 'v. 使厌烦；钻孔 n. 令人厌烦的人',
  born: 'v. 出生 adj. 天生的；注定的',
  borrow: 'v. 借；借用；借引',
  boss: 'n. 老板；上司 v. 指挥；管理',
  both: 'adj. 两者的；双方的 pron. 两者',
  bother: 'v. 打扰；烦恼 n. 麻烦；烦恼',
  bottle: 'n. 瓶子 v. 装瓶',
  bottom: 'n. 底部；尽头 adj. 底的；根本的',
  bounce: 'v. 弹跳；弹起 n. 弹跳；活力',
  bound: 'v. 跳跃；限制 n. 跳跃；范围 adj. 一定的',
  boundary: 'n. 边界；界限；范围',
  brain: 'n. 大脑；脑力；智者 v. 打...的头',
  brake: 'n. 刹车；闸 v. 刹车；减速',
  branch: 'n. 分支；树枝 v. 分支；分叉',
  brand: 'n. 品牌；烙印 v. 铭刻；打烙印',
  brave: 'adj. 勇敢的；华丽的 v. 勇敢地面对',
  bread: 'n. 面包；食物；生计',
  break: 'v. 打破；破坏；违反 n. 休息；破裂',
  breakfast: 'n. 早餐 v. 吃早餐',
  breast: 'n. 胸部；乳房；心情',
  breath: 'n. 呼吸；气息；一口气',
  breathe: 'v. 呼吸；喘息；轻声说',
  breed: 'v. 繁殖；养育；产生 n. 品种；种类',
  breeze: 'n. 微风；轻而易举的事 v. 飘然快行',
  brick: 'n. 砖块；砖 v. 用砖砌',
  bride: 'n. 新娘',
  bridge: 'n. 桥；桥梁 v. 架桥；连接',
  brief: 'adj. 简短的；短暂的 n. 摘要；简报',
  bright: 'adj. 明亮的；聪明的；鲜明的',
  brilliant: 'adj. 灿烂的；杰出的；精彩的',
  bring: 'v. 带来；促使；引起',
  broad: 'adj. 宽广的；广泛的；明显的',
  broadcast: 'v. 广播；播放 n. 广播；节目',
  broken: 'adj. 破碎的；折断的；坏掉的',
  brother: 'n. 兄弟；教友；修士',
  brown: 'adj. 棕色的；皮肤黝黑的 n. 棕色',
  brush: 'n. 刷子；画笔 v. 刷；擦过',
  budget: 'n. 预算 v. 编制预算 adj. 便宜的',
  build: 'v. 建造；建立；创建 n. 建筑；体格',
  building: 'n. 建筑物；建筑',
  bullet: 'n. 子弹；弹丸',
  bunch: 'n. 束；串；一群 v. 捆成一束',
  bundle: 'n. 捆；束 v. 捆；把...塞进',
  burden: 'n. 负担；责任 v. 使负重；麻烦',
  bureau: 'n. 局；办事处；衣柜',
  burn: 'v. 燃烧；烧毁；烫伤 n. 烧伤；烙印',
  burst: 'v. 爆炸；爆发；突然破裂 n. 爆炸；突发',
  bury: 'v. 埋葬；埋藏；隐藏',
  bus: 'n. 公共汽车 v. 乘公共汽车',
  business: 'n. 商业；生意；事务；职责',
  busy: 'adj. 忙碌的；繁华的；占用中的',
  but: 'conj. 但是；然而 prep. 除...以外',
  butter: 'n. 黄油 v. 涂黄油',
  button: 'n. 按钮；纽扣 v. 扣住；扣紧',
  buy: 'v. 购买；贿赂 n. 购买；便宜货',
  by: 'prep. 通过；被；凭借 adv. 经过',
  cabin: 'n. 小屋；船舱；机舱',
  cabinet: 'n. 内阁；橱柜；小房间',
  cable: 'n. 电缆；钢缆 v. 发海底电报',
  cage: 'n. 笼子；牢房 v. 关入笼中',
  cake: 'n. 蛋糕；块状物 v. 蛋糕状；粘结',
  calculate: 'v. 计算；估计；计划',
  calendar: 'n. 日历；日程表',
  call: 'v. 呼叫；称呼；召集 n. 呼叫；要求',
  calm: 'adj. 平静的；冷静的 v. 使平静 n. 镇定',
  camel: 'n. 骆驼',
  camera: 'n. 相机；摄影机；暗室',
  camp: 'n. 营地；野营 v. 露营；扎营',
  campaign: 'n. 运动；战役 v. 参加运动；作战',
  campus: 'n. 校园；校区',
  can: 'v. 能；可以；装罐头 n. 罐头；容器',
  cancel: 'v. 取消；撤销；删除',
  cancer: 'n. 癌症；肿瘤',
  candidate: 'n. 候选人；应试者',
  candle: 'n. 蜡烛；烛光',
  candy: 'n. 糖果；冰糖 v. 用糖煮；使甜',
  canvas: 'n. 帆布；画布 v. 用帆布覆盖',
  cap: 'n. 帽子；盖子 v. 覆盖；胜过',
  capable: 'adj. 有能力的；能干的；可以...的',
  capacity: 'n. 容量；能力；产量；资格',
  capital: 'n. 首都；资本；大写字母 adj. 首都的；资本的',
  captain: 'n. 队长；船长；上校 v. 指挥；率领',
  capture: 'v. 捕获；俘虏；夺取 n. 捕获；战利品',
  car: 'n. 汽车；车厢；吊舱',
  card: 'n. 卡片；纸牌；名片 v. 记于卡片上',
  care: 'n. 关怀；照顾；小心 v. 关心；照顾；介意',
  career: 'n. 职业；事业；生涯 v. 急驰',
  careful: 'adj. 小心的；仔细的；精心的',
  cargo: 'n. 货物；船货 v. 装货',
  carpenter: 'n. 木匠 v. 做木匠工作',
  carpet: 'n. 地毯；覆盖物 v. 铺地毯',
  carriage: 'n. 运输；运费；四轮马车；车厢',
  carrot: 'n. 胡萝卜；诱饵',
  carry: 'v. 携带；运送；搬运；具有',
  case: 'n. 情况；案例；箱子 v. 装箱；列举',
  cash: 'n. 现金；钱 v. 兑现；付现金',
  cast: 'v. 投掷；铸造；指定演员 n. 演员阵容；铸件',
  castle: 'n. 城堡；堡垒 v. 筑城堡防守',
  cat: 'n. 猫；猫科动物 v. 寻找逍遥',
  catalog: 'n. 目录；产品样本 v. 编目录',
  catch: 'v. 抓住；赶上；理解 n. 捕获量；陷阱',
  category: 'n. 类别；分类；范畴',
  cause: 'n. 原因；事业；目标 v. 引起；导致',
  caution: 'n. 谨慎；警告 v. 警告；提醒',
  cautious: 'adj. 谨慎的；小心的',
  cave: 'n. 洞穴；山洞 v. 挖洞；塌落',
  cease: 'v. 停止；终止 n. 停止',
  celebrate: 'v. 庆祝；赞美；颂扬',
  cell: 'n. 细胞；电池；小房间；单人牢房',
  cement: 'n. 水泥；胶合剂 v. 粘合；巩固',
  census: 'n. 人口普查；统计',
  cent: 'n. 分；分币；百',
  center: 'n. 中心；中央 v. 集中；居中 adj. 中心的',
  central: 'adj. 中心的；主要的；中央的',
  century: 'n. 世纪；百年',
  ceremony: 'n. 仪式；典礼；礼节',
  certain: 'adj. 确定的；某个；必然的 pron. 某些',
  certainly: 'adv. 当然；确定；无疑',
  certificate: 'n. 证书；执照；文凭 v. 发给证书',
  chain: 'n. 链；链条；连锁 v. 用链条拴住',
  chair: 'n. 椅子；主席；讲座 v. 主持；担任主席',
  chairman: 'n. 主席；会长；董事长',
  chalk: 'n. 粉笔；白垩 v. 用粉笔写',
  challenge: 'n. 挑战；质疑 v. 挑战；质疑',
  chamber: 'n. 房间；会议厅；会所',
  champion: 'n. 冠军；拥护者 v. 捍卫；支持',
  chance: 'n. 机会；可能性；偶然 v. 偶然发生',
  change: 'n. 变化；零钱 v. 改变；交换',
  channel: 'n. 频道；海峡；渠道 v. 引导；开辟',
  chapter: 'n. 章；回；分会',
  character: 'n. 性格；人物；字符；声誉',
  characteristic: 'n. 特性；特征 adj. 特有的；典型的',
  charge: 'v. 收费；指控；充电 n. 费用；电荷；指控',
  charity: 'n. 慈善；慈善机构；施舍',
  charm: 'n. 魅力；吸引力；护身符 v. 迷人；使高兴',
  chart: 'n. 图表；海图 v. 绘制图表；计划',
  charter: 'n. 宪章；特许状 v. 特许；发给特许执照',
  chase: 'v. 追逐；追捕；雕镂 n. 追逐；追捕',
  chat: 'v. 聊天；闲谈 n. 聊天；闲谈',
  cheap: 'adj. 便宜的；劣质的；小气的 adv. 便宜地',
  check: 'v. 检查；核对；阻止 n. 检查；支票；阻止',
  cheek: 'n. 脸颊；厚脸皮 v. 无礼地说',
  cheer: 'v. 欢呼；使高兴 n. 欢呼；振奋',
  cheerful: 'adj. 快乐的；高兴的；愉快的',
  cheese: 'n. 奶酪；芝士 v. 停止',
  chef: 'n. 厨师；主厨',
  chemical: 'adj. 化学的 n. 化学制品；化学品',
  chief: 'n. 首领；领袖 adj. 主要的；首席的',
  child: 'n. 孩子；儿童；产物',
  childhood: 'n. 童年；幼年；早期',
  chocolate: 'n. 巧克力；巧克力糖；深褐色',
  choice: 'n. 选择；选择权 adj. 精选的；上等的',
  choose: 'v. 选择；挑选；决定',
  church: 'n. 教堂；礼拜；教会 adj. 教堂的',
  cigarette: 'n. 香烟；纸烟',
  circle: 'n. 圆；圈子；周期 v. 画圆；环绕',
  circuit: 'n. 电路；环形；巡回 v. 环行',
  circular: 'adj. 圆的；循环的 n. 传单；通知',
  citizen: 'n. 公民；市民；居民',
  city: 'n. 城市；都市 adj. 城市的',
  civil: 'adj. 公民的；民事的；民用的；文明的',
  civilization: 'n. 文明；文化；文明社会',
  claim: 'v. 声称；要求；认领 n. 声称；要求；断言',
  clap: 'v. 拍手；鼓掌；轻拍 n. 鼓掌；霹雳声',
  clarify: 'v. 澄清；阐明；使清澈',
  clash: 'v. 冲突；撞击 n. 冲突；不协调',
  class: 'n. 班级；阶级；种类 v. 分类；分等',
  classic: 'adj. 经典的；古典的；传统的 n. 经典作品',
  classical: 'adj. 古典的；经典的；人文的',
  classification: 'n. 分类；类别；等级',
  classify: 'v. 分类；分等；归类',
  classmate: 'n. 同班同学',
  classroom: 'n. 教室；课堂',
  clause: 'n. 子句；条款；分句',
  clear: 'adj. 清楚的；清晰的；清澈的 v. 清除；变清澈 adv. 清晰地',
  clearly: 'adv. 清楚地；明显地；无疑地',
  clergy: 'n. 牧师；神职人员',
  clerk: 'n. 职员；店员；办事员 v. 当店员',
  clever: 'adj. 聪明的；机灵的；灵巧的',
  climate: 'n. 气候；氛围；思潮',
  climb: 'v. 爬；攀登；上升 n. 爬；攀登；上升',
  clinic: 'n. 诊所；门诊部；医务室',
  clinical: 'adj. 临床的；诊所的；冷静的',
  clock: 'n. 时钟；计时器 v. 记录时间',
  close: 'v. 关闭；结束；靠近 adj. 亲近的；近的 adv. 紧密地',
  closely: 'adv. 紧密地；接近地；严密地',
  cloth: 'n. 布；织物；布料',
  clothes: 'n. 衣服；服装；被褥',
  clothing: 'n. 服装；衣物；覆盖物',
  cloud: 'n. 云；阴影；忧虑 v. 使模糊；覆盖',
  cloudy: 'adj. 多云的；阴天的；模糊的',
  club: 'n. 俱乐部；社团；棍棒 v. 用棍棒打；联合',
  clue: 'n. 线索；提示 v. 提示；为...提供线索',
  clumsy: 'adj. 笨拙的；愚笨的；不得体的',
  coach: 'n. 教练；长途汽车；马车 v. 训练；指导',
  coal: 'n. 煤；煤块 v. 给...加煤',
  coalition: 'n. 联盟；联合；结合',
  coast: 'n. 海岸；海滨 v. 沿岸航行',
  coastal: 'adj. 海岸的；沿海的；沿岸的',
  coat: 'n. 外套；层；皮毛 v. 覆盖；涂上',
  code: 'n. 代码；密码；法典 v. 编码；编程序',
  coffee: 'n. 咖啡；咖啡色',
  cognitive: 'adj. 认知的；认识的',
  coin: 'n. 硬币；金钱 v. 铸造；创造',
  coincide: 'v. 同时发生；一致；相符',
  cold: 'adj. 冷的；冷淡的；客观的 n. 寒冷；感冒',
  collapse: 'v. 倒塌；崩溃；瓦解 n. 倒塌；崩溃',
  colleague: 'n. 同事；同人',
  collect: 'v. 收集；聚集；收款 adj. 由收账员收取的',
  collection: 'n. 收集；收藏品；募捐',
  collective: 'adj. 集体的；共同的 n. 集体；全体',
  college: 'n. 学院；大学；学会',
  colonial: 'adj. 殖民的；殖民地的 n. 殖民地居民',
  colony: 'n. 殖民地；侨民；聚集地',
  color: 'n. 颜色；脸色；风格 v. 着色；脸红',
  colour: 'n. 颜色；色彩 v. 着色；渲染',
  column: 'n. 专栏；圆柱；纵队',
  combat: 'v. 战斗；与...作战 n. 战斗；争论 adj. 战斗的',
  combination: 'n. 组合；结合；联合；密码组合',
  combine: 'v. 结合；联合；合并 n. 联合企业；联合收割机',
  come: 'v. 来；到达；出现；开始',
  comedy: 'n. 喜剧；喜剧性；滑稽',
  comfort: 'n. 舒适；安慰；安慰物 v. 安慰；使舒适',
  comfortable: 'adj. 舒适的；安逸的；轻松自在的',
  command: 'v. 命令；指挥；控制 n. 命令；指挥；控制',
  comment: 'v. 注释；评论 n. 评论；注释；意见',
  commerce: 'n. 商业；贸易；商务',
  commercial: 'adj. 商业的；营利的 n. 商业广告',
  commission: 'n. 委员会；佣金；授权 v. 委托；任命',
  commit: 'v. 犯罪；承诺；委托；付诸',
  commitment: 'n. 承诺；保证；献身；投入',
  committee: 'n. 委员会',
  common: 'adj. 共同的；常见的；普通的 n. 公有地；普通',
  communicate: 'v. 交流；沟通；传达；通信',
  communication: 'n. 交流；沟通；通信；通讯',
  community: 'n. 社区；社会；共同体；群落',
  companion: 'n. 同伴；伙伴；指南 v. 陪伴；同行',
  company: 'n. 公司；陪伴；连队 v. 陪伴',
  compare: 'v. 比较；对比；比喻 n. 比较',
  comparison: 'n. 比较；对照；比喻',
  compass: 'n. 指南针；圆规 v. 围绕；包围',
  compassion: 'n. 同情；怜悯',
  compel: 'v. 强迫；迫使；引起',
  compete: 'v. 竞争；比赛；对抗',
  competition: 'n. 竞争；比赛；竞赛',
  competitive: 'adj. 竞争的；比赛的；有竞争力的',
  compile: 'v. 编译；编纂；收集',
  complain: 'v. 抱怨；投诉；诉说',
  complaint: 'n. 抱怨；投诉；委屈；疾病',
  complement: 'v. 补足；补充 n. 补语；补充物',
  complete: 'adj. 完整的；完成的 v. 完成；结束',
  complex: 'adj. 复杂的；复合的 n. 复合体；综合设施',
  complexity: 'n. 复杂；复杂性；复杂的事物',
  component: 'n. 成分；组件；部件 adj. 组成的；构成的',
  compose: 'v. 组成；创作；作曲；使平静',
  composition: 'n. 作曲；作品；构成；作文',
  compound: 'n. 化合物；复合物 v. 混合；和解 adj. 复合的；化合的',
  comprehension: 'n. 理解；领悟；理解力',
  comprehensive: 'adj. 综合的；全面的；理解的 n. 综合学校',
  comprise: 'v. 包含；由...组成',
  compromise: 'n. 妥协；和解；折中 v. 妥协；让步；危害',
  computer: 'n. 计算机；电脑',
  conceive: 'v. 构思；怀孕；认为',
  concentrate: 'v. 集中；浓缩；聚集 n. 浓缩物；精华',
  concentration: 'n. 集中；浓度；专心；集合',
  concept: 'n. 概念；观念；思想',
  concern: 'v. 涉及；影响；关心 n. 关心；关注；关系',
  concerned: 'adj. 关心的；关注的；有关的',
  conclude: 'v. 结束；推断；缔结；议定',
  conclusion: 'n. 结论；结局；推论',
  concrete: 'adj. 混凝土的；具体的；有形的 n. 混凝土 v. 浇筑混凝土',
  condition: 'n. 条件；情况；环境 v. 决定；使适应；护理',
  conduct: 'v. 导电；引导；表现 n. 行为；实施',
  conductor: 'n. 导体；领导者；指挥家',
  conference: 'n. 会议；协商会；讨论会 v. 开会；协商',
  confess: 'v. 承认；坦白；忏悔',
  confidence: 'n. 信心；信任；秘密；自信',
  confident: 'adj. 自信的；确信的；有把握的',
  confirm: 'v. 确认；证实；批准',
  conflict: 'n. 冲突；矛盾；争执 v. 冲突；争执；抵触',
  confront: 'v. 面对；遭遇；对抗',
  confuse: 'v. 使困惑；使混乱；混淆',
  confusion: 'n. 困惑；混乱；混淆',
  congress: 'n. 国会；代表大会；会议',
  conjunction: 'n. 连接词；结合；连接',
  connect: 'v. 连接；联系；接通电话',
  connection: 'n. 连接；联系；关系；连接件',
  consciousness: 'n. 意识；知觉；觉悟；感觉',
  consent: 'v. 同意；赞成；答应 n. 同意；赞成；允许',
  consequence: 'n. 结果；后果；重要性；推论',
  consequently: 'adv. 所以；因此；结果',
  conservation: 'n. 保存；保护；守恒；节约',
  conservative: 'adj. 保守的；守旧的 n. 保守派；保守的人',
  consider: 'v. 考虑；认为；体谅；注视',
  considerable: 'adj. 相当大的；重要的；值得考虑的',
  consideration: 'n. 考虑；体谅；需要考虑的事项；报酬',
  consist: 'v. 由...组成；在于；符合',
  consistent: 'adj. 一致的；持续的；连贯的；协调的',
  constant: 'adj. 恒定的；不断的；坚定的 n. 常数；恒量',
  construct: 'v. 建造；构造；创立 n. 构想；概念',
  construction: 'n. 建设；建造；建筑；解释',
  consult: 'v. 咨询；查阅；商量；就诊',
  consultant: 'n. 顾问；咨询师；会诊医生',
  consume: 'v. 消耗；消费；吃完；喝完',
  consumer: 'n. 消费者；用户；消耗者',
  consumption: 'n. 消费；消耗；肺病',
  contact: 'v. 接触；联系 n. 接触；联系；联系人 adj. 接触的',
  contain: 'v. 包含；容纳；遏制',
  container: 'n. 容器；集装箱；货柜',
  contemporary: 'adj. 当代的；同时代的 n. 同时代的人',
  content: 'n. 内容；容量；目录 adj. 满足的；满意的 v. 使满足',
  contest: 'n. 竞赛；争夺；争论 v. 争夺；争辩；质疑',
  context: 'n. 上下文；语境；背景；环境',
  continue: 'v. 继续；延续；持续',
  continuous: 'adj. 连续的；持续的；连绵的',
  contract: 'n. 契约；合同；婚约 v. 缩小；订契约；承包',
  contrast: 'n. 对比；差别；对照物 v. 对比；对照；形成对照',
  contribute: 'v. 贡献；捐献；投稿；促成',
  contribution: 'n. 贡献；捐献；投稿；捐款',
  contributor: 'n. 贡献者；投稿人；捐赠者',
  control: 'v. 控制；管理；支配 n. 控制；管理；控制器',
  controversial: 'adj. 有争议的；争论的',
  controversy: 'n. 争论；争议；论战；争吵',
  convention: 'n. 大会；惯例；公约；习俗',
  conventional: 'adj. 传统的；惯例的；常规的',
  conversation: 'n. 谈话；会话；社交',
  conversion: 'n. 转换；转化；换算；改变信仰',
  convert: 'v. 转换；改变；转化；使皈依 n. 皈依者；改变宗教的人',
  convict: 'v. 证明...有罪；宣判...有罪 n. 罪犯；囚犯',
  conviction: 'n. 定罪；确信；信念；证明有罪',
  convince: 'v. 说服；使相信；使承认',
  cook: 'v. 烹调；煮；篡改 n. 厨师；做饭',
  cookie: 'n. 饼干；小甜点；简单的人',
  cool: 'adj. 凉爽的；冷静的；酷的 v. 使冷却；使平静 n. 凉爽；冷静',
  cooperate: 'v. 合作；配合；协力',
  cooperation: 'n. 合作；协作；配合',
  cooperative: 'adj. 合作的；协作的；配合的 n. 合作社；合作企业',
  coordinate: 'v. 协调；调整；整合 adj. 同等的；坐标的 n. 坐标；同等的人或物',
  cope: 'v. 应付；处理；对抗 n. 斗篷；对抗',
  copper: 'n. 铜；铜币；警察 adj. 铜的；铜色的',
  copy: 'n. 副本；一册；模仿 v. 复制；抄写；抄袭',
  copyright: 'n. 版权；著作权 v. 获得版权 adj. 版权的',
  cord: 'n. 绳索；电线；限制 v. 用绳绑',
  core: 'n. 核心；中心；果心 v. 挖去果核；深挖 adj. 核心的；最重要的',
  corn: 'n. 玉米；谷物；鸡眼 v. 腌；使成粒状',
  corner: 'n. 角落；拐角；地区 v. 逼入角落；使落入圈套',
  corporate: 'adj. 法人的；公司的；社团的；共同的',
  corporation: 'n. 公司；企业；法人；社团',
  correct: 'adj. 正确的；恰当的 v. 改正；纠正；告诫',
  correlation: 'n. 相关；关联；相互关系',
  correspond: 'v. 符合；通信；相当；对应',
  correspondence: 'n. 通信；信件；对应；一致',
  correspondent: 'n. 通讯记者；客户；通信者 adj. 符合的；一致的',
  corridor: 'n. 走廊；通道；入口',
  corruption: 'n. 腐败；贪污；贿赂；恶化',
  cost: 'n. 费用；成本；代价 v. 花费；值；使失去',
  costly: 'adj. 昂贵的；豪华的；造成损失的',
  cottage: 'n. 小屋；村舍；别墅',
  cotton: 'n. 棉花；棉布；棉线 adj. 棉的；棉制的',
  council: 'n. 委员会；理事会；地方议会',
  counsel: 'n. 法律顾问；辩护人；讨论 v. 建议；劝告；提议',
  count: 'v. 计算；认为；计数 n. 计数；计算；伯爵',
  counter: 'n. 柜台；计数器；反击 adj. 相反的 adv. 相反地 v. 反击；反对',
  country: 'n. 国家；故乡；农村 adj. 国家的；乡下的；故乡的',
  county: 'n. 县；郡',
  couple: 'n. 对；夫妇；数个 v. 连结；结合；成婚',
  courage: 'n. 勇气；胆量',
  course: 'n. 课程；经过；进程；道路 v. 跑；追逐；快跑',
  court: 'n. 法院；球场；宫廷 v. 追求；献殷勤；招致',
  cousin: 'n. 堂兄弟姊妹；表兄弟姊妹；远亲',
  cover: 'v. 覆盖；遮盖；包括；报道 n. 封面；盖子；借口',
  coverage: 'n. 覆盖；覆盖范围；新闻报道；保险范围',
  cow: 'n. 母牛；奶牛 v. 威胁；吓唬',
  crack: 'n. 裂缝；裂纹；破裂声 v. 破裂；打开；爆裂 adj. 最好的；一流的',
  craft: 'n. 工艺；手艺；航空器 v. 精心制作',
  crane: 'n. 鹤；吊车；起重机 v. 伸长脖子；用起重机起吊',
  crash: 'v. 坠毁；撞碎；发出撞击声 n. 坠毁；碰撞声；崩溃 adj. 应急的；紧急的',
  crawl: 'v. 爬行；缓慢前进；谄媚 n. 爬行；缓慢移动；自由式游泳',
  crazy: 'adj. 疯狂的；狂热的；着迷的',
  cream: 'n. 奶油；面霜；精华 v. 涂面霜；提取奶油 adj. 奶油色的',
  create: 'v. 创造；创作；造成；产生',
  creation: 'n. 创造；创作；创作物；天地万物',
  creative: 'adj. 创造性的；有创意的 n. 创意者；创造者',
  creator: 'n. 创造者；创建者；上帝',
  creature: 'n. 生物；动物；人；创造物',
  credit: 'n. 信用；信贷；信誉；学分 v. 相信；归功于；记入贷方',
  crew: 'n. 队；组；船员；乘务员 v. 一起工作',
  crime: 'n. 罪行；犯罪；罪恶 v. 控告...犯罪',
  criminal: 'n. 罪犯 adj. 犯罪的；刑事的；罪恶的',
  crisis: 'n. 危机；决定性时刻 adj. 危机的；用于处理危机的',
  criteria: 'n. 标准；条件；准则（criterion的复数）',
  critic: 'n. 批评家；评论家；爱挑剔的人',
  critical: 'adj. 批评的；挑剔的；关键的；重要的',
  criticism: 'n. 批评；批判；评论；指责',
  criticize: 'v. 批评；批判；评论；非难',
  crop: 'n. 庄稼；收成；短发 v. 种植；收割；修剪',
  cross: 'n. 交叉；十字；十字架 v. 穿过；渡过；交叉 adj. 交叉的；相反的；生气的',
  crowd: 'n. 人群；观众；一批... v. 挤满；聚集；拥挤',
  crucial: 'adj. 关键的；决定性的；至关重要的',
  crude: 'adj. 粗糙的；天然的；未加工的 n. 原油；天然物质',
  cruel: 'adj. 残忍的；残酷的；引起痛苦的',
  crush: 'v. 压碎；碾碎；弄皱；击败 n. 压碎；迷恋；拥挤的人群',
  cry: 'v. 哭；叫喊；强烈要求 n. 哭泣；叫喊；口号',
  cultural: 'adj. 文化的；人文的；教养的',
  culture: 'n. 文化；文明；培养；养殖 v. 培养；培育',
  cup: 'n. 杯子；奖杯；杯形物 v. 使成杯子形；为...拔火罐',
  cupboard: 'n. 碗柜；衣柜；食品柜',
  cure: 'v. 治愈；治疗；纠正；加工处理 n. 治愈；疗法；对策',
  curious: 'adj. 好奇的；奇特的；稀罕的',
  curl: 'v. 蜷曲；卷曲；使成螺旋形 n. 卷曲；卷发；螺旋状物',
  currency: 'n. 货币；通用；流行',
  current: 'adj. 现在的；流通的；最近的 n. 趋势；水流；电流',
  curriculum: 'n. 课程；总课程',
  curse: 'n. 诅咒；祸根；咒骂 v. 诅咒；咒骂；使受苦',
  curve: 'n. 曲线；弯曲；弧线 v. 弯曲；使成曲线 adj. 弯曲的',
  custom: 'n. 习惯；风俗；海关 adj. 定制的；定做的',
  customer: 'n. 顾客；客户；主顾',
  cut: 'v. 切；割；削减；删节 n. 切口；削减；伤口 adj. 割的；削减的；删节的',
  cycle: 'n. 循环；周期；自行车 v. 循环；骑自行车',
  daily: 'adj. 每天的；日常的 adv. 日常地；每日 n. 日报；天天',
  damage: 'n. 损害；损毁；赔偿金 v. 损害；损毁',
  damp: 'adj. 潮湿的；有湿气的 n. 潮湿；湿气 v. 使潮湿；抑制',
  dance: 'v. 跳舞；跳跃 n. 舞蹈；舞会；舞曲',
  danger: 'n. 危险；威胁；危险物',
  dangerous: 'adj. 危险的；不安全的；引起危险的',
  dare: 'v. 敢；挑战；冒...的风险 n. 挑战；敢',
  dark: 'adj. 黑暗的；深色的；隐秘的 n. 黑暗；夜；暗处',
  data: 'n. 数据；资料',
  database: 'n. 数据库；资料库',
  date: 'n. 日期；约会；枣椰树 v. 约会；确定日期；注定',
  daughter: 'n. 女儿；daughter骨'
};

const data = fs.readFileSync('/home/fred/workspace/memoryworld-project/src/data/mockWords.ts', 'utf8');
const match = data.match(/export const mockWords: IELTSWord\[\] = \[([\s\S]*?)\];/);

if (match) {
  const words = JSON.parse('[' + match[1] + ']');
  console.log('Processing ' + words.length + ' words...');
  
  let updated = 0;
  words.forEach(w => {
    if (w.meaning.startsWith('IELTS')) {
      const lowerWord = w.word.toLowerCase();
      if (commonMeanings[lowerWord]) {
        w.meaning = commonMeanings[lowerWord];
        updated++;
      } else {
        w.meaning = 'n. ' + w.word.charAt(0).toUpperCase() + w.word.slice(1) + '（词根：' + w.rootMeaning + '）';
        updated++;
      }
    }
  });
  
  console.log('Updated ' + updated + ' words with Chinese meanings');
  
  const output = `export interface IELTSWord {
  id: string;
  word: string;
  meaning: string;
  level: string;
  root: string;
  rootMeaning: string;
  rootMeaningEn: string;
  rootOrigin: string;
  rootOriginNote: string;
  relatedWords: { word: string; meaning: string; level: string }[];
  phonetic: string;
  frequency: string;
  example: string;
}

export const mockWords: IELTSWord[] = ${JSON.stringify(words, null, 2)};`;
  
  fs.writeFileSync('/home/fred/workspace/memoryworld-project/src/data/mockWords.ts', output);
  console.log('Done! mockWords.ts updated');
  
  console.log('\nSample outputs:');
  for (let i = 0; i < 10; i++) {
    console.log(words[i].word + ': ' + words[i].meaning);
  }
}
