const fs = require('fs');

const completeMeanings = {
  aback: 'adv. 向后；突然；吃惊地',
  abandon: 'v. 放弃；抛弃；离开；舍弃 n. 放任；狂热',
  abate: 'v. 减少；减轻；减弱；废止',
  abbey: 'n. 修道院；寺院；大教堂',
  abbot: 'n. 院长；修道院院长',
  abdomen: 'n. 腹部；下腹；腹腔',
  abide: 'v. 忍受；停留；遵守；持续',
  ability: 'n. 能力；才能；本领；技能',
  ablaze: 'adj. 燃烧的；闪耀的；激动的',
  able: 'adj. 能干的；能够的；有能力的；聪明的',
  aboard: 'adv. 在船上；在飞机上；上车 prep. 在...上',
  about: 'prep. 关于；大约；涉及；在...周围 adv. 大约；到处；在附近',
  above: 'prep. 在...上面；超过；多于 adv. 在上面；以上 adj. 上面的；上述的',
  abroad: 'adv. 到国外；在国外；四处；广泛',
  abrupt: 'adj. 突然的；唐突的；陡峭的；生硬的',
  absence: 'n. 缺席；缺乏；不存在；离开',
  absolute: 'adj. 绝对的；纯粹的；完全的；确实的',
  absolutely: 'adv. 绝对地；完全地；确实地；当然',
  absorb: 'v. 吸收；吸引；理解；承受；并入',
  abstract: 'adj. 抽象的；理论的 n. 摘要；抽象派作品',
  absurd: 'adj. 荒谬的；可笑的；不合理的；荒唐的',
  abundance: 'n. 丰富；充裕；大量；充足',
  abundant: 'adj. 丰富的；充裕的；大量的；充足的',
  academic: 'adj. 学术的；学院的；理论的；教学的 n. 学者；大学教师',
  accelerate: 'v. 加速；加快；促进；促进生长',
  accent: 'n. 口音；重音；强调；特征 v. 强调；重读',
  accept: 'v. 接受；承认；认可；同意；承担',
  access: 'n. 进入；通道；访问；使用权 v. 访问；接近；进入；获取',
  accessory: 'n. 配件；附件；从犯；饰品 adj. 附属的；副的',
  accident: 'n. 事故；意外；偶然；命运',
  accommodate: 'v. 容纳；使适应；提供住宿；调解',
  accommodation: 'n. 住宿；膳宿；适应；和解',
  accompany: 'v. 陪伴；陪同；伴随；为...伴奏',
  accomplish: 'v. 完成；实现；达到；成就',
  accord: 'v. 给予；一致；符合 n. 协议；条约；一致',
  accordance: 'n. 一致；和谐；按照；符合',
  account: 'n. 账户；解释；叙述；账目 v. 解释；认为；导致；计算',
  accountable: 'adj. 负有责任的；可解释的；可追究的',
  accuracy: 'n. 准确性；精确度；精确性',
  accurate: 'adj. 准确的；精确的；正确无误的',
  accuse: 'v. 指控；指责；谴责；控告',
  achieve: 'v. 完成；达到；实现；获得；成功',
  achievement: 'n. 成就；成绩；完成；达到',
  acid: 'n. 酸；酸性物质 adj. 酸的；讽刺的；刻薄的',
  acknowledge: 'v. 承认；确认；致意；感谢；告知收到',
  acquaintance: 'n. 认识的人；相识；了解；熟悉',
  acquire: 'v. 获得；学到；收购；得到；养成',
  acquisition: 'n. 获得；收购；获得物；习得',
  acre: 'n. 英亩；土地；大量',
  across: 'prep. 穿过；跨越；在...对面；从一边到另一边 adv. 到对面；横跨',
  active: 'adj. 积极的；活跃的；有效的；主动的',
  activist: 'n. 积极分子；行动主义者 adj. 积极行动的',
  activity: 'n. 活动；行动；活跃；活力；业务',
  actor: 'n. 演员；男演员；行动者；参与者',
  actress: 'n. 女演员',
  actual: 'adj. 实际的；真实的；现行的；实在的',
  actually: 'adv. 实际上；事实上；确实；竟然',
  acute: 'adj. 严重的；急性的；敏锐的；尖刻的',
  adapt: 'v. 使适应；改编；改写；调整',
  adaptation: 'n. 适应；改编；改编本；改写本',
  add: 'v. 添加；增加；补充；计算；加',
  addicted: 'adj. 上瘾的；沉迷的；入迷的',
  addition: 'n. 增加；添加；增加物；加法',
  additional: 'adj. 额外的；附加的；另外的',
  address: 'n. 地址；演讲；谈吐；称呼 v. 向...讲话；处理；解决；称呼',
  adequate: 'adj. 足够的；适当的；勉强够的',
  adhere: 'v. 粘附；遵守；坚持；追随；依附',
  adjacent: 'adj. 邻近的；毗连的；前后紧接着的',
  adjust: 'v. 调整；调节；校准；适应',
  administration: 'n. 管理；行政；行政机构；实施',
  administrative: 'adj. 行政的；管理的；后方勤务的',
  admire: 'v. 钦佩；欣赏；羡慕；赞美',
  admission: 'n. 承认；入场费；进入许可；录用',
  admit: 'v. 承认；准许进入；允许；容纳',
  adopt: 'v. 采取；收养；采纳；正式通过；采用',
  adult: 'n. 成年人 adj. 成年的；成熟的；成人的',
  advance: 'v. 前进；推进；上涨；预付；提出 n. 进展；提升；预付款；增长',
  advanced: 'adj. 先进的；高级的；年迈的；晚期的',
  advantage: 'n. 优势；好处；利益；优点 v. 有利于；使处于优势',
  adventure: 'n. 冒险；冒险精神；奇遇；风险 v. 冒险；大胆行事',
  adverse: 'adj. 不利的；相反的；敌对的；有害的',
  advertise: 'v. 做广告；宣传；公布；通知',
  advertisement: 'n. 广告；宣传；公告',
  advice: 'n. 建议；劝告；通知；情报',
  advisable: 'adj. 可取的；明智的；适当的',
  advise: 'v. 建议；劝告；通知；提供意见',
  advocate: 'v. 提倡；主张；拥护 n. 倡导者；辩护者；律师',
  aesthetic: 'adj. 美学的；审美的；有审美感的；美观的',
  affair: 'n. 事件；事务；风流韵事；公共活动',
  affect: 'v. 影响；感动；假装；侵袭 n. 情感；感情',
  affection: 'n. 喜爱；爱慕；感情；影响',
  affiliate: 'v. 使附属；接纳；加入；使并入 n. 附属机构；成员；分公司',
  affirm: 'v. 肯定；确认；断言；证实',
  afford: 'v. 负担得起；提供；抽出；给予；买得起',
  afraid: 'adj. 害怕的；担心的；恐怕；畏惧',
  after: 'prep. 在...之后；在...后面；寻找；追求 conj. 在...以后 adv. 以后；然后；后来',
  afternoon: 'n. 下午；午后',
  afterwards: 'adv. 之后；后来；以后',
  again: 'adv. 再；又；此外；再一次；重新',
  against: 'prep. 反对；靠着；倚在；违背；对比',
  age: 'n. 年龄；时代；时期；老年 v. 变老；成熟；使老',
  agency: 'n. 代理；代理处；机构；作用；中介',
  agenda: 'n. 议程；日程；待办事项',
  agent: 'n. 代理人；经纪人；特工；药剂；媒介',
  aggressive: 'adj. 侵略性的；进取的；激进的；好斗的',
  ago: 'adv. 以前；之前；过去',
  agony: 'n. 苦恼；极大的痛苦；挣扎；创伤',
  agree: 'v. 同意；赞成；认为；符合；达成一致',
  agreement: 'n. 协议；同意；一致；契约',
  agricultural: 'adj. 农业的；农艺的；农学的',
  agriculture: 'n. 农业；农学；农业技术；农艺',
  ahead: 'adv. 在前面；提前；向前；将来',
  aid: 'v. 帮助；援助；支持；资助 n. 帮助；援助；助手；辅助物',
  aim: 'v. 瞄准；针对；致力于；打算 n. 目标；目的；瞄准',
  aircraft: 'n. 飞机；航空器；飞船；飞行器',
  airline: 'n. 航空公司；航线；航空业',
  airport: 'n. 机场；航空站；航空港',
  alarm: 'n. 警报；惊恐；警告装置；闹钟 v. 使惊恐；警告；给...装警报',
  album: 'n. 相册；集邮册；音乐专辑；唱片集',
  alcohol: 'n. 酒精；酒；含酒精饮料；乙醇',
  alert: 'adj. 警觉的；灵敏的；生动的 v. 警告；使警觉；提醒 n. 警报；警戒',
  alien: 'n. 外星人；外国人 adj. 外国的；陌生的；相异的',
  alike: 'adj. 相似的；相同的；相像的 adv. 相似地；相同地；一样',
  alive: 'adj. 活着的；活跃的；存在的；有生气的',
  allegation: 'n. 指控；断言；主张；辩解',
  allege: 'v. 断言；宣称；指控；主张',
  allegedly: 'adv. 据称；据说；据说地',
  alleviate: 'v. 减轻；缓和；缓解；缓和',
  alliance: 'n. 联盟；同盟；联合；联姻；结盟',
  allocate: 'v. 分配；拨出；分派；指定',
  allow: 'v. 允许；给予；承认；让...得到；容许',
  allowance: 'n. 津贴；补贴；零用钱；允许；折扣',
  alloy: 'n. 合金 v. 使成合金；减轻；削弱',
  ally: 'n. 同盟国；盟友；伙伴 v. 联合；结盟',
  almost: 'adv. 几乎；差不多；将近；快要',
  alone: 'adj. 单独的；孤独的；独自的 adv. 独自；仅仅；单独地',
  along: 'prep. 沿着；顺着；靠在...身上 adv. 向前；一起；进展',
  alongside: 'prep. 在...旁边；与...并排 adv. 在旁边；并排地',
  aloud: 'adv. 大声地；出声地；响亮地',
  alphabet: 'n. 字母表；初步；入门；字母系统',
  already: 'adv. 已经；早已；先前',
  also: 'adv. 也；同样；而且；此外；同样地',
  alter: 'v. 改变；修改；更改；变动',
  alternate: 'v. 交替；轮流；改变；替代 adj. 交替的；轮流的；间隔的',
  alternative: 'n. 选择；替代物；替代方案 adj. 替代的；备选的；其他的',
  although: 'conj. 虽然；尽管；然而；但是',
  altitude: 'n. 高度；海拔；高处；高地',
  altogether: 'adv. 完全；总共；总之；总共',
  aluminium: 'n. 铝',
  always: 'adv. 总是；一直；永远；始终',
  amateur: 'n. 业余爱好者；外行 adj. 业余的；不熟练的',
  amaze: 'v. 使惊奇；使惊讶；使困惑',
  amazing: 'adj. 令人惊异的；了不起的；惊人的',
  ambassador: 'n. 大使；代表；使者；使节',
  ambiguous: 'adj. 模糊不清的；引起歧义的；不明确的',
  ambition: 'n. 雄心；抱负；野心；志向',
  ambitious: 'adj. 有雄心的；野心勃勃的；热望的',
  ambulance: 'n. 救护车；野战医院；流动医院',
  amend: 'v. 修改；修订；改进；改良；改善',
  amendment: 'n. 修正案；修改；改进；赔罪',
  amid: 'prep. 在...之中；在...之间；在...中间',
  amount: 'n. 数量；总额；数额；数量 v. 总计；等于；相当于',
  ample: 'adj. 充足的；丰富的；宽敞的；足够的',
  amuse: 'v. 娱乐；使愉快；使发笑；消遣',
  analyse: 'v. 分析；分解；研究；解析',
  analysis: 'n. 分析；分解；解析；分析结果',
  analyst: 'n. 分析员；化验员；心理分析师',
  analyze: 'v. 分析；分解；解释；对...进行心理分析',
  ancestor: 'n. 祖先；祖宗；先驱；原型',
  anchor: 'n. 锚；主持人；支柱；靠山 v. 抛锚；停泊；固定；主持',
  ancient: 'adj. 古代的；古老的；旧时的 n. 古人；古代文明',
  angel: 'n. 天使；守护神；可爱的人；善人',
  anger: 'n. 愤怒；怒火；愤慨；怒气 v. 使发怒；激怒；恼火',
  angle: 'n. 角度；观点；斜角；角 v. 钓鱼；使成角度；歪曲',
  angry: 'adj. 生气的；愤怒的；疼痛的；受感的',
  animal: 'n. 动物；兽类；畜生 adj. 动物的；野兽的',
  announce: 'v. 宣布；通知；公布；声称；预告',
  announcement: 'n. 公告；通知；宣告；预告',
  annoy: 'v. 使烦恼；打扰；使生气；骚扰',
  annual: 'adj. 年度的；每年的；一年一次的 n. 年刊；一年生植物',
  annually: 'adv. 每年；年度地；一年一次地',
  anonymous: 'adj. 匿名的；无名的；无特色的',
  another: 'adj. 另一的；再一个的；别的 pron. 另一个；又一；类似的',
  answer: 'v. 回答；答复；响应；解答 n. 回答；答案；响应；答复',
  ant: 'n. 蚂蚁',
  anticipate: 'v. 预期；预见；期待；先发制人；预料',
  anxiety: 'n. 焦虑；担心；渴望；忧虑',
  anxious: 'adj. 焦虑的；担忧的；渴望的；急切的',
  any: 'adj. 任何的；所有的；一点点的 pron. 任何一个；任何一些',
  anybody: 'pron. 任何人；无论谁；重要人物',
  anyone: 'pron. 任何人；无论谁',
  anything: 'pron. 任何事；某事；什么事',
  anyway: 'adv. 无论如何；总之；不过；反正',
  anywhere: 'adv. 在任何地方；向任何地方 n. 任何地方',
  apart: 'adv. 分开；分离；相隔；相距 adj. 分离的；不连贯的',
  apartment: 'n. 公寓；单元住宅；房间；套房',
  apologize: 'v. 道歉；谢罪；辩解；赔不是',
  apology: 'n. 道歉；谢罪；辩解；赔罪',
  apparatus: 'n. 装置；仪器；器官；机构',
  apparent: 'adj. 显然的；表面上的；清晰可见的',
  appeal: 'v. 呼吁；吸引；上诉；请求；恳求 n. 吸引力；呼吁；上诉；魅力',
  appear: 'v. 出现；显得；来到；产生；看起来',
  appearance: 'n. 外表；外观；出现；出场；露面',
  appetite: 'n. 食欲；胃口；欲望；爱好',
  apple: 'n. 苹果；苹果树；苹果公司',
  applicant: 'n. 申请人；应聘者；请求者',
  application: 'n. 应用；申请；应用程序；施用',
  apply: 'v. 申请；应用；涂；适用；请求',
  appoint: 'v. 任命；指定；约定；委派',
  appointment: 'n. 任命；约会；约定；职务',
  appreciate: 'v. 欣赏；感激；领会；涨价；增值',
  appreciation: 'n. 欣赏；鉴赏；感激；评价；增值',
  approach: 'v. 接近；靠近；处理；着手 n. 方法；途径；接近；建议',
  appropriate: 'adj. 适当的；恰当的；合适的 v. 拨出；占用；挪用',
  appropriately: 'adv. 适当地；恰当的；相称地',
  approval: 'n. 批准；同意；认可；赞成',
  approve: 'v. 批准；赞成；同意；认可；满意',
  approximate: 'adj. 大约的；近似的 v. 接近；近似；粗略估计',
  approximately: 'adv. 大约；近似地；接近地',
  arbitrary: 'adj. 任意的；武断的；随意的；专制的',
  architecture: 'n. 建筑学；建筑设计；建筑风格；结构',
  area: 'n. 区域；面积；领域；范围；地区',
  argue: 'v. 争论；辩论；主张；说服；表明',
  argument: 'n. 争论；论据；论证；参数；争吵',
  arise: 'v. 出现；产生；起身；起因于；发生',
  arm: 'n. 手臂；武器；装备；部门 v. 武装；装备；备战',
  army: 'n. 军队；陆军；大群；野战军',
  around: 'prep. 围绕；环绕；到处；大约 adv. 周围；四周；到处；大约',
  arrange: 'v. 安排；筹备；整理；调解；改编',
  arrangement: 'n. 安排；筹备；整理；商定；改编曲',
  arrest: 'v. 逮捕；拘留；阻止；吸引 n. 逮捕；拘留；停止',
  arrival: 'n. 到达；到来；出现；开始',
  arrive: 'v. 到达；到来；成功；达成；来临',
  arrow: 'n. 箭；箭头；箭状物 v. 箭形物；急升',
  article: 'n. 文章；论文；物品；条款；冠词',
  articulate: 'v. 清晰发音；表达；连接 adj. 发音清晰的；善于表达的',
  artificial: 'adj. 人造的；假的；虚伪的；不自然的',
  artist: 'n. 艺术家；美术家；表演者；大师',
  artistic: 'adj. 艺术的；美术的；精美的；艺术家的',
  artwork: 'n. 艺术品；美术品；插图；背景音乐',
  as: 'conj. 因为；当...时；像...一样；虽然 prep. 作为；像',
  ascend: 'v. 上升；攀登；追溯；登基',
  aspect: 'n. 方面；外观；朝向；形势',
  aspire: 'v. 渴望；追求；有志于',
  assault: 'v. 攻击；袭击；殴打 n. 攻击；袭击；冲击',
  assemble: 'v. 集合；组装；装配；召集',
  assembly: 'n. 集合；集会；装配；议会；立法机构',
  assess: 'v. 评估；评定；估算；征税',
  assessment: 'n. 评估；评定；估算；估价',
  asset: 'n. 资产；财产；有价值的人或物；优点',
  assign: 'v. 分配；指派；布置；确定；转让',
  assignment: 'n. 任务；作业；分配；指派；转让',
  assist: 'v. 帮助；协助；支持；促进 n. 帮助；助攻；协助',
  assistance: 'n. 帮助；协助；援助；支持',
  associate: 'v. 联系；交往；结交；联想 adj. 副的；联合的 n. 同事；伙伴',
  association: 'n. 协会；联盟；联系；交往；联合',
  assume: 'v. 假设；假定；承担；认为；假装',
  assumption: 'n. 假设；假定；承担；假装',
  assure: 'v. 保证；使确信；确保；保险',
  astonish: 'v. 使惊讶；使震惊；使难以置信',
  astronaut: 'n. 宇航员；航天员；太空人',
  at: 'prep. 在...；向...；对...；因为',
  athlete: 'n. 运动员；体育家；身强力壮的人',
  athletic: 'adj. 运动的；体育的；运动员的；体格健壮的',
  atmosphere: 'n. 大气；气氛；大气层；空气；环境',
  attach: 'v. 附上；贴上；连接；使依附；使附着',
  attack: 'v. 攻击；袭击；进攻；抨击 n. 攻击；袭击；进攻；疾病发作',
  attain: 'v. 达到；获得；实现；到达',
  attempt: 'v. 尝试；企图；试图 n. 尝试；企图；努力',
  attend: 'v. 参加；出席；照顾；护理；注意；陪伴',
  attendance: 'n. 出席；参加；出勤；参加人数',
  attention: 'n. 注意；注意力；关注；照看；殷勤',
  attitude: 'n. 态度；看法；姿势；姿态',
  attract: 'v. 吸引；引起；诱惑；有吸引力',
  attraction: 'n. 吸引力；吸引物；景点；魅力',
  attractive: 'adj. 吸引人的；有魅力的；迷人的；引起兴趣的',
  attribute: 'v. 把...归于；认为是...的缘故 n. 属性；特性；品质；象征',
  audience: 'n. 观众；听众；读者；接见；受众',
  audit: 'n. 审计；查账；审核 v. 审计；查账；旁听',
  aunt: 'n. 阿姨；姑妈；伯母；舅妈',
  author: 'n. 作者；作家；创始人 v. 创作；写作；编写',
  authority: 'n. 权威；权力；当局；权限；影响力',
  authorize: 'v. 授权；批准；许可；委托',
  automatic: 'adj. 自动的；无意识的；机械的 n. 自动装置；自动驾驶仪',
  automatically: 'adv. 自动地；无意识地；机械地',
  available: 'adj. 可用的；可获得的；有空的；有效的',
  avenue: 'n. 大街；途径；手段；林荫道',
  average: 'n. 平均；平均数；一般水平 adj. 平均的；一般的；中等的',
  avoid: 'v. 避免；避开；消除；预防',
  await: 'v. 等候；等待；期待；即将到来',
  wake: 'v. 醒来；唤醒；使认识；激发 n. 醒；守夜；痕迹',
  walk: 'v. 走；步行；散步；陪...走 n. 步行；散步；人行道',
  wall: 'n. 墙；墙壁；壁垒；护城河 v. 用墙围住；分隔',
  want: 'v. 想要；需要；希望 n. 需要；缺乏；欲望；贫困',
  war: 'n. 战争；斗争；冲突；军事行动 v. 打仗；作战；斗争',
  warm: 'adj. 温暖的；热情的；亲切的 v. 使温暖；使暖和；使兴奋',
  warmth: 'n. 温暖；热情；温馨；暖和',
  warn: 'v. 警告；提醒；通知；告诫',
  warning: 'n. 警告；警报；预警；前兆 adj. 警告的；提醒的',
  wash: 'v. 洗；洗涤；洗衣；冲刷 n. 洗；洗涤；要洗的衣物',
  waste: 'v. 浪费；消耗；使荒芜 n. 浪费；废物；废料 adj. 废弃的；荒芜的',
  watch: 'v. 观看；注视；看守；等待 n. 手表；监视；守护；值班',
  water: 'n. 水；海水；水位；雨水 v. 浇水；给...水喝；流泪',
  wave: 'n. 波浪；波涛；浪潮；挥动 v. 波动；挥手；飘动；汹涌',
  way: 'n. 道路；方法；方式；途径；方向；习惯 adv. 非常；大大地',
  we: 'pron. 我们',
  weak: 'adj. 弱的；虚弱的；无力的；不擅长的；差的',
  wealth: 'n. 财富；财产；丰富；大量',
  wealthy: 'adj. 富有的；富裕的；丰富的 n. 富人；有钱人',
  weapon: 'n. 武器；兵器；斗争工具 v. 武装',
  wear: 'v. 穿；戴；磨损；用旧；面露 n. 服装；穿戴；磨损；耐久性',
  weather: 'n. 天气；气象；气候 v. 经受住；风化；使褪色',
  web: 'n. 网；网络；蛛丝；织物 v. 用网覆盖；织网',
  website: 'n. 网站；网址',
  week: 'n. 周；星期；周工作日',
  weekend: 'n. 周末',
  weekly: 'adj. 每周的；一周一次的 adv. 每周一次地 n. 周刊；周报',
  weigh: 'v. 称...重量；权衡；考虑；重压；起锚',
  weight: 'n. 重量；体重；分量；砝码；重要 v. 加重量于；使负重',
  weird: 'adj. 奇怪的；不可思议的；超自然的 n. 命运；预言',
  welcome: 'v. 欢迎；迎接；乐于接受 n. 欢迎；迎接 adj. 受欢迎的',
  welfare: 'n. 福利；社会保障；安宁；幸福 adj. 福利的',
  well: 'adv. 好；很；相当；恰当地 adj. 健康的；良好的；适当的 n. 井；源泉',
  west: 'n. 西；西方；西部 adj. 西方的；西部的 adv. 向西；朝西',
  western: 'adj. 西方的；西洋的；来自西方的 n. 西方国家；美国西部片',
  wet: 'adj. 湿的；潮湿的；有雨的 v. 把...弄湿；弄潮 n. 潮湿；雨天',
  what: 'pron. 什么；...的东西；有多少 adj. 什么；哪个；尽可能多的',
  whatever: 'pron. 无论什么；任何...的事物 adj. 无论什么样的；任何的',
  wheat: 'n. 小麦；麦子',
  wheel: 'n. 轮子；方向盘；旋转；周期 v. 推；拉；用车运；旋转',
  when: 'conj. 当...时；一...就；在...情况下 adv. 什么时候；当时 pron. 什么时候',
  whenever: 'conj. 无论什么时候；每当；随时 adv. 无论如何；不管怎样',
  where: 'adv. 在哪里；向哪里；在...地方 pron. 哪里 n. 地点',
  whereas: 'conj. 然而；但是；鉴于；考虑到',
  whereby: 'adv. 凭此；由此；借以',
  whether: 'conj. 是否；不管；无论',
  which: 'pron. 哪个；...的（东西）；...的人 adj. 哪个；哪些',
  while: 'n. 一会儿；时间；时期 conj. 当...时；在...期间；然而；但是',
  whisper: 'v. 低语；私语；小声说；悄悄话 n. 耳语；私语；谣传',
  white: 'adj. 白色的；白种的；纯洁的 n. 白色；白种人；蛋白',
  who: 'pron. 谁；...的人；...的人们',
  whole: 'adj. 完整的；全部的；所有的 n. 整体；全部；整个世界',
  whom: 'pron. 谁（who的宾格）；...的人',
  whose: 'pron. 谁的；...的（东西）；...的人',
  why: 'adv. 为什么；...的原因 int. 哎呀；什么道理',
  wide: 'adj. 宽的；广阔的；广泛的；渊博的 adv. 广阔地；广大地；远离目标地',
  widely: 'adv. 广泛地；普遍地；大大地；广为人知地',
  wife: 'n. 妻子；太太；已婚妇女',
  wild: 'adj. 野生的；野蛮的；狂热的；荒凉的 n. 荒野；荒地；野生状态',
  will: 'v. aux. 将；会；愿意；必须 n. 意志；毅力；决心；遗嘱',
  willing: 'adj. 愿意的；乐意的；心甘情愿的；积极主动的',
  win: 'v. 赢；获胜；赢得；获得 n. 胜利；赢；获奖',
  wind: 'n. 风；呼吸；气息；卷绕 v. 绕；缠；上发条；嗅出',
  window: 'n. 窗户；窗口；窗玻璃；窗框 v. 给...装窗',
  wine: 'n. 葡萄酒；酒；紫红色 v. 喝酒；以酒款待',
  wing: 'n. 翅膀；翼；派系；侧厅 v. 飞过；使飞；安装翼',
  winner: 'n. 获胜者；赢家；成功者',
  winter: 'n. 冬天；冬季；冷淡期 v. 过冬 adj. 冬天的；冬季的',
  wire: 'n. 金属丝；电线；电报 v. 发电报；布线；用铁丝固定',
  wisdom: 'n. 智慧；明智；知识；学问；贤人',
  wise: 'adj. 智慧的；英明的；博学的；聪明的',
  wish: 'v. 希望；想要；祝愿；渴望 n. 愿望；希望；命令；祝愿',
  with: 'prep. 和...一起；用；具有；关于；随着',
  within: 'prep. 在...里面；在...内部 adv. 在内部；在里面 n. 内部',
  without: 'prep. 没有；无；不和...在一起 adv. 在外面；户外；在没有的情况下',
  witness: 'n. 证人；目击者；证据 v. 目击；见证；经历',
  woman: 'n. 女人；妇女；女性 adj. 女人的；女性的',
  wonder: 'n. 惊奇；惊愕；奇迹；奇观 v. 想知道；感到惊讶 adj. 神奇的',
  wonderful: 'adj. 精彩的；绝妙的；令人惊奇的；极好的',
  wood: 'n. 木材；木制品；森林；木料 v. 植林于；给...添木柴',
  wooden: 'adj. 木制的；木头做的；呆板的；生硬的',
  word: 'n. 单词；话语；消息；诺言 v. 用言语表达；措辞',
  work: 'n. 工作；劳动；操作；职业；作品 v. 工作；运作；起作用；创作',
  worker: 'n. 工人；劳动者；工作人员；工作者',
  workshop: 'n. 车间；工场；研讨会；讲习班',
  world: 'n. 世界；地球；领域；世人；人间',
  worldwide: 'adj. 全世界的；影响全球的 adv. 在全世界范围内',
  worry: 'v. 担心；烦恼；烦恼；困扰 n. 担心；烦恼；忧虑；令人担心的事',
  worse: 'adj. 更坏的；更差的；更糟的 adv. 更坏；更差；更糟',
  worship: 'n. 崇拜；敬仰；做礼拜 v. 崇拜；尊敬；爱慕；崇拜神',
  worst: 'adj. 最坏的；最差的；最糟的 adv. 最坏地；最差地 n. 最坏的人或事',
  worth: 'n. 价值；作用；值得...的 adj. 值...的；值钱的；值得的',
  worthless: 'adj. 无价值的；不值钱的；无用的；不足道的',
  worthwhile: 'adj. 值得的；值得做的；有价值的',
  worthy: 'adj. 值得的；应得的；有价值的；可敬的 n. 知名人士；杰出人物',
  would: 'v. aux. 将；愿意；可能；总是；大概',
  wound: 'n. 创伤；伤疤；伤害 v. 使受伤；伤害；损害',
  wrap: 'v. 包；裹；缠绕；覆盖；隐藏 n. 外套；披肩；围巾；约束',
  write: 'v. 写；写字；书写；写作；作曲；写信',
  writer: 'n. 作家；作者；撰写人',
  wrong: 'adj. 错误的；不正确的；有问题的 adv. 错误地；不正确地 n. 错误；坏事 v. 冤枉；委屈',
  yard: 'n. 院子；庭院；码（英制长度单位）；场地',
  year: 'n. 年；年度；年纪；一年的期间',
  yearly: 'adj. 每年的；一年一度的 adv. 每年；一年一次地 n. 年刊；年鉴',
  yellow: 'adj. 黄色的；黄皮肤的 n. 黄色；蛋黄 v. 变黄；发黄',
  yes: 'adv. 是；是的；对；真的吗 int. 是；好；请说',
  yesterday: 'n. 昨天；往昔 adv. 昨天',
  yet: 'adv. 还；已经；仍然；甚至 conj. 但是；然而',
  yield: 'v. 产生；让步；放弃；出产 n. 产量；收益；产出',
  you: 'pron. 你；您；你们',
  young: 'adj. 年轻的；青年人的；初期的 n. 青年人；孩子们',
  your: 'pron. 你的；您的；你们的',
  yours: 'pron. 你的；您的；你们的',
  yourself: 'pron. 你自己；您自己；你们自己',
  youth: 'n. 青年；青春；青年时期；青年人',
  zero: 'n. 零；零点；零度；最低点 num. 零 v. 瞄准；聚焦 adj. 零的；零点的'
};

const exampleTemplates = [
  { en: 'The {word} of modern technology has transformed daily life.', cn: '现代技术的{word}改变了日常生活。' },
  { en: 'Cultural diversity is an important {word} in contemporary society.', cn: '文化多样性是当代社会的重要{word}。' },
  { en: 'Environmental protection requires effective {word} at all levels.', cn: '环境保护需要各级有效的{word}。' },
  { en: 'Economic development depends on sustainable {word} practices.', cn: '经济发展依赖可持续的{word}实践。' },
  { en: 'Education plays a crucial {word} in shaping future generations.', cn: '教育在塑造未来一代中起着关键的{word}作用。' },
  { en: 'Globalization has led to increased {word} across different cultures.', cn: '全球化促进了不同文化之间的{word}增长。' },
  { en: 'Social media has become an essential {word} in communication.', cn: '社交媒体已成为沟通中的重要{word}。' },
  { en: 'Climate change is a significant {word} affecting our planet.', cn: '气候变化是影响我们星球的重大{word}。' },
  { en: 'Innovation is the driving {word} behind technological progress.', cn: '创新是技术进步的驱动{word}。' },
  { en: 'Teamwork is a key {word} for success in modern workplaces.', cn: '团队合作是现代职场成功的关键{word}。' }
];

function generateExample(word, meaning) {
  const template = exampleTemplates[Math.floor(Math.random() * exampleTemplates.length)];
  return {
    en: template.en.replace('{word}', word),
    cn: template.cn.replace('{word}', meaning ? meaning.split('；')[0].split(' ')[1] : word)
  };
}

const data = fs.readFileSync('/home/fred/workspace/memoryworld-project/src/data/mockWords.ts', 'utf8');
const match = data.match(/export const mockWords: IELTSWord\[\] = \[([\s\S]*?)\];/);

if (match) {
  const words = JSON.parse('[' + match[1] + ']');
  console.log('Processing ' + words.length + ' words...');
  
  let meaningUpdated = 0;
  let exampleUpdated = 0;
  
  words.forEach(w => {
    const lowerWord = w.word.toLowerCase();
    if (completeMeanings[lowerWord]) {
      w.meaning = completeMeanings[lowerWord];
      meaningUpdated++;
    }
    
    // 改进例句
    const example = generateExample(w.word, w.meaning);
    w.example = example.en + '\n' + example.cn;
    exampleUpdated++;
  });
  
  console.log('Updated ' + meaningUpdated + ' meanings');
  console.log('Updated ' + exampleUpdated + ' examples');
  
  const output = `export interface IELTSWord {
  id: string;
  word: string;
  meaning: string;
  level: string;
  root: string;
  rootMeaning: string;
  rootMeaningEn: string;
  rootOrigin: string;
  rootOriginNote: string;
  relatedWords: { word: string; meaning: string; level: string }[];
  phonetic: string;
  frequency: string;
  example: string;
}

export const mockWords: IELTSWord[] = ${JSON.stringify(words, null, 2)};`;
  
  fs.writeFileSync('/home/fred/workspace/memoryworld-project/src/data/mockWords.ts', output);
  console.log('Done!');
}
