const fs = require('fs');

// 更完整的释义库
const comprehensiveMeanings = {
  'ably': 'adv. 能干地；熟练地；巧妙地',
  'abode': 'n. 住所；住处；寓所 v. 居住；停留',
  'abolition': 'n. 废除；废止；取消',
  'aboriginal': 'adj. 土著的；原始的 n. 土著居民',
  'abound': 'v. 大量存在；富于；充满',
  'abrasion': 'n. 磨损；擦伤；磨损处',
  'abrasive': 'adj. 粗糙的；有研磨作用的；生硬的 n. 研磨剂',
  'abreast': 'adv. 并列；并排；并肩；赶得上',
  'abscess': 'n. 脓肿；脓疮',
  'abscond': 'v. 潜逃；逃匿',
  'absolve': 'v. 免除；解除；赦免',
  'abyss': 'n. 深渊；深坑；深不可测的事物',
  'acacia': 'n. 阿拉伯胶；金合欢树',
  'accentuate': 'v. 强调；重读；使突出',
  'acclaim': 'v. 称赞；赞誉；欢呼 n. 称赞；赞誉；欢呼',
  'acclimate': 'v. 使适应；使习惯；适应新环境',
  'accomplice': 'n. 同谋；共犯；帮凶',
  'accost': 'v. 走上前去；搭话；勾引',
  'accounting': 'n. 会计；会计学；记账',
  'accredit': 'v. 委任；委派；授权；相信；信任',
  'accretion': 'n. 增长；增加；堆积物；沉积物',
  'accusation': 'n. 指控；指责；控告',
  'acetic': 'adj. 醋的；乙酸的',
  'achromatic': 'adj. 无色的；消色差的',
  'acidic': 'adj. 酸性的；酸味的',
  'acidify': 'v. 使酸化；变酸',
  'acorn': 'n. 橡实；橡果',
  'acoustic': 'adj. 听觉的；声学的；原声的',
  'acquaint': 'v. 使认识；使了解；使熟悉',
  'acquiesce': 'v. 默许；默认；勉强同意',
  'acquire': 'v. 获得；学到；收购；得到；养成',
  'acquisition': 'n. 获得；收购；获得物；习得',
  'acre': 'n. 英亩；土地；大量',
  'across': 'prep. 穿过；跨越；在...对面；从一边到另一边 adv. 到对面；横跨',
  'active': 'adj. 积极的；活跃的；有效的；主动的',
  'activist': 'n. 积极分子；行动主义者 adj. 积极行动的',
  'activity': 'n. 活动；行动；活跃；活力；业务',
  'actor': 'n. 演员；男演员；行动者；参与者',
  'actress': 'n. 女演员',
  'actual': 'adj. 实际的；真实的；现行的；实在的',
  'actually': 'adv. 实际上；事实上；确实；竟然',
  'acute': 'adj. 严重的；急性的；敏锐的；尖刻的',
  'adapt': 'v. 使适应；改编；改写；调整',
  'adaptation': 'n. 适应；改编；改编本；改写本',
  'add': 'v. 添加；增加；补充；计算；加',
  'addicted': 'adj. 上瘾的；沉迷的；入迷的',
  'addition': 'n. 增加；添加；增加物；加法',
  'additional': 'adj. 额外的；附加的；另外的',
  'address': 'n. 地址；演讲；谈吐；称呼 v. 向...讲话；处理；解决；称呼',
  'adequate': 'adj. 足够的；适当的；勉强够的',
  'adhere': 'v. 粘附；遵守；坚持；追随；依附',
  'adjacent': 'adj. 邻近的；毗连的；前后紧接着的',
  'adjust': 'v. 调整；调节；校准；适应',
  'administration': 'n. 管理；行政；行政机构；实施',
  'administrative': 'adj. 行政的；管理的；后方勤务的',
  'admire': 'v. 钦佩；欣赏；羡慕；赞美',
  'admission': 'n. 承认；入场费；进入许可；录用',
  'admit': 'v. 承认；准许进入；允许；容纳',
  'adopt': 'v. 采取；收养；采纳；正式通过；采用',
  'adult': 'n. 成年人 adj. 成年的；成熟的；成人的',
  'advance': 'v. 前进；推进；上涨；预付；提出 n. 进展；提升；预付款；增长',
  'advanced': 'adj. 先进的；高级的；年迈的；晚期的',
  'advantage': 'n. 优势；好处；利益；优点 v. 有利于；使处于优势',
  'adventure': 'n. 冒险；冒险精神；奇遇；风险 v. 冒险；大胆行事',
  'adverse': 'adj. 不利的；相反的；敌对的；有害的',
  'advertise': 'v. 做广告；宣传；公布；通知',
  'advertisement': 'n. 广告；宣传；公告',
  'advice': 'n. 建议；劝告；通知；情报',
  'advisable': 'adj. 可取的；明智的；适当的',
  'advise': 'v. 建议；劝告；通知；提供意见',
  'advocate': 'v. 提倡；主张；拥护 n. 提倡者；辩护者；律师',
  'aesthetic': 'adj. 美学的；审美的；有审美感的；美观的',
  'affair': 'n. 事件；事务；风流韵事；公共活动',
  'affect': 'v. 影响；感动；假装；侵袭 n. 情感；感情',
  'affection': 'n. 喜爱；爱慕；感情；影响',
  'affiliate': 'v. 使附属；接纳；加入；使并入 n. 附属机构；成员；分公司',
  'affirm': 'v. 肯定；确认；断言；证实',
  'afford': 'v. 负担得起；提供；抽出；给予；买得起',
  'afraid': 'adj. 害怕的；担心的；恐怕；畏惧',
  'after': 'prep. 在...之后；在...后面；寻找；追求 conj. 在...以后 adv. 以后；然后；后来',
  'afternoon': 'n. 下午；午后',
  'afterwards': 'adv. 以后；后来；以后',
  'again': 'adv. 再；又；此外；再一次；重新',
  'against': 'prep. 反对；靠着；倚在；违背；对比',
  'age': 'n. 年龄；时代；时期；老年 v. 变老；成熟；使老',
  'agency': 'n. 代理；代理处；机构；作用；中介',
  'agenda': 'n. 议程；日程；待办事项',
  'agent': 'n. 代理人；经纪人；特工；药剂；媒介',
  'aggressive': 'adj. 侵略性的；进取的；激进的；好斗的',
  'ago': 'adv. 以前；之前；过去',
  'agony': 'n. 苦恼；极大的痛苦；挣扎；创伤',
  'agree': 'v. 同意；赞成；认为；符合；达成一致',
  'agreement': 'n. 协议；同意；一致；契约',
  'agricultural': 'adj. 农业的；农艺的；农学的',
  'agriculture': 'n. 农业；农学；农业技术；农艺',
  'ahead': 'adv. 在前面；提前；向前；将来',
  'aid': 'v. 帮助；援助；支持；资助 n. 帮助；援助；助手；辅助物',
  'aim': 'v. 瞄准；针对；致力于；打算 n. 目标；目的；瞄准',
  'aircraft': 'n. 飞机；航空器；飞船；飞行器',
  'airline': 'n. 航空公司；航线；航空业',
  'airport': 'n. 机场；航空站；航空港',
  'alarm': 'n. 警报；惊恐；警告装置；闹钟 v. 使惊恐；警告；给...装警报',
  'album': 'n. 相册；集邮册；音乐专辑；唱片集',
  'alcohol': 'n. 酒精；酒；含酒精饮料；乙醇',
  'alert': 'adj. 警觉的；灵敏的；生动的 v. 警告；使警觉；提醒 n. 警报；警戒',
  'alien': 'n. 外星人；外国人 adj. 外国的；陌生的；相异的',
  'alike': 'adj. 相似的；相同的；相像的 adv. 相似地；相同地；一样',
  'alive': 'adj. 活着的；活跃的；存在的；有生气的',
  'allegation': 'n. 指控；断言；主张；辩解',
  'allege': 'v. 断言；宣称；指控；主张',
  'allegedly': 'adv. 据称；据说；据说地',
  'alleviate': 'v. 减轻；缓和；缓解；缓和',
  'alliance': 'n. 联盟；同盟；联合；联姻；结盟',
  'allocate': 'v. 分配；拨出；分派；指定',
  'allow': 'v. 允许；给予；承认；让...得到；容许',
  'allowance': 'n. 津贴；补贴；零用钱；允许；折扣',
  'alloy': 'n. 合金 v. 使成合金；减轻；削弱',
  'ally': 'n. 同盟国；盟友；伙伴 v. 联合；结盟',
  'almost': 'adv. 几乎；差不多；将近；快要',
  'alone': 'adj. 单独的；孤独的；独自的 adv. 独自；仅仅；单独地',
  'along': 'prep. 沿着；顺着；靠在...身上 adv. 向前；一起；进展',
  'alongside': 'prep. 在...旁边；与...并排 adv. 在旁边；并排地',
  'aloud': 'adv. 大声地；出声地；响亮地',
  'alphabet': 'n. 字母表；初步；入门；字母系统',
  'already': 'adv. 已经；早已；先前',
  'also': 'adv. 也；同样；而且；此外；同样地',
  'alter': 'v. 改变；修改；更改；变动',
  'alternate': 'v. 交替；轮流；改变；替代 adj. 交替的；轮流的；间隔的',
  'alternative': 'n. 选择；替代物；替代方案 adj. 替代的；备选的；其他的',
  'although': 'conj. 虽然；尽管；然而；但是',
  'altitude': 'n. 高度；海拔；高处；高地',
  'altogether': 'adv. 完全；总共；总之；总共',
  'aluminium': 'n. 铝',
  'always': 'adv. 总是；一直；永远；始终',
  'amateur': 'n. 业余爱好者；外行 adj. 业余的；不熟练的',
  'amaze': 'v. 使惊奇；使惊讶；使困惑',
  'amazing': 'adj. 令人惊异的；了不起的；惊人的',
  'ambassador': 'n. 大使；代表；使者；使节',
  'ambiguous': 'adj. 模糊不清的；引起歧义的；不明确的',
  'ambition': 'n. 雄心；抱负；野心；志向',
  'ambitious': 'adj. 有雄心的；野心勃勃的；热望的',
  'ambulance': 'n. 救护车；野战医院；流动医院',
  'amend': 'v. 修改；修订；改进；改良；改善',
  'amendment': 'n. 修正案；修改；改进；赔罪',
  'amid': 'prep. 在...之中；在...之间；在...中间',
  'amount': 'n. 数量；总额；数额；数量 v. 总计；等于；相当于',
  'ample': 'adj. 足够的；丰富的；宽敞的；充足的',
  'amuse': 'v. 娱乐；使愉快；使发笑；消遣',
  'analyse': 'v. 分析；分解；研究；解析',
  'analysis': 'n. 分析；分解；解析；分析结果',
  'analyst': 'n. 分析员；化验员；心理分析师',
  'analyze': 'v. 分析；分解；解释；对...进行心理分析',
  'ancestor': 'n. 祖先；祖宗；先驱；原型',
  'anchor': 'n. 锚；主持人；支柱；靠山 v. 抛锚；停泊；固定；主持',
  'ancient': 'adj. 古代的；古老的；旧时的 n. 古人；古代文明',
  'angel': 'n. 天使；守护神；可爱的人；善人',
  'anger': 'n. 愤怒；怒火；愤慨；怒气 v. 使发怒；激怒；恼火',
  'angle': 'n. 角；角度；观点；斜角 v. 钓鱼；使成角度；歪曲',
  'angry': 'adj. 生气的；愤怒的；疼痛的；受感的',
  'animal': 'n. 动物；兽类；畜生 adj. 动物的；野兽的',
  'animate': 'v. 使有生命；使活动；鼓舞 adj. 有生命的；有活力的',
  'animation': 'n. 活泼；生气；动画制作；动画片',
  'annex': 'v. 附加；吞并；合并 n. 附加物；附属建筑',
  'annihilate': 'v. 消灭；歼灭；毁灭',
  'anniversary': 'n. 周年纪念日；周年纪念',
  'announce': 'v. 宣布；通知；公布；声称；预告',
  'announcement': 'n. 公告；通知；宣告；预告',
  'annoy': 'v. 使烦恼；打扰；使生气；骚扰',
  'annual': 'adj. 年度的；每年的；一年一次的 n. 年刊；一年生植物',
  'annually': 'adv. 每年；年度地；一年一次地',
  'anonymous': 'adj. 匿名的；无名的；无特色的',
  'another': 'adj. 另一的；再一个的；别的 pron. 另一个；又一；类似的',
  'answer': 'v. 回答；答复；响应；解答 n. 回答；答案；响应；答复',
  'ant': 'n. 蚂蚁',
  'antagonist': 'n. 对手；敌手；对抗者',
  'antarctic': 'adj. 南极的 n. 南极洲',
  'antecedent': 'n. 前例；祖先；先行词 adj. 先行的；先前的',
  'antedate': 'v. 先于；早于；倒填日期',
  'antenna': 'n. 触角；天线',
  'anterior': 'adj. 前面的；较早的；先前的',
  'anthology': 'n. 选集；文选',
  'anthropologist': 'n. 人类学家',
  'anthropology': 'n. 人类学',
  'antibiotic': 'n. 抗生素 adj. 抗生素的；抗生的',
  'anticipate': 'v. 预期；预见；期待；先发制人；预料',
  'anticipation': 'n. 预期；预料；先发制人',
  'antidote': 'n. 解毒药；解毒剂；矫正方法',
  'antique': 'adj. 古老的；古董的 n. 古物；古董',
  'antiseptic': 'n. 防腐剂 adj. 防腐的；无菌的',
  'antonym': 'n. 反义词',
  'anxiety': 'n. 焦虑；担心；渴望；忧虑',
  'anxious': 'adj. 焦虑的；担心的；渴望的；急切的',
  'any': 'adj. 任何的；所有的；一点点的 pron. 任何一个；任何一些',
  'anybody': 'pron. 任何人；无论谁；重要人物',
  'anyone': 'pron. 任何人；无论谁',
  'anything': 'pron. 任何事物；某事；什么事',
  'anyway': 'adv. 无论如何；总之；不过；反正',
  'anywhere': 'adv. 在任何地方；向任何地方 n. 任何地方',
  'apart': 'adv. 分开；分离；相隔；相距 adj. 分离的；不连贯的',
  'apartment': 'n. 公寓；单元住宅；房间；套房',
  'apologetic': 'adj. 道歉的；愧疚的；辩解的',
  'apologize': 'v. 道歉；谢罪；辩解；赔不是',
  'apology': 'n. 道歉；谢罪；辩解；赔罪',
  'apparatus': 'n. 装置；设备；仪器；器官；机构',
  'apparent': 'adj. 显然的；明显的；表面上的；清晰可见的',
  'apparently': 'adv. 显然；看来；似乎',
  'appeal': 'v. 呼吁；恳求；吸引；上诉；请求 n. 吸引力；呼吁；上诉；魅力',
  'appear': 'v. 出现；显得；来到；产生；看起来',
  'appearance': 'n. 外表；外观；出现；出场；露面',
  'appease': 'v. 平息；抚慰；安抚',
  'appendix': 'n. 附录；阑尾',
  'appetite': 'n. 食欲；胃口；欲望；爱好',
  'applaud': 'v. 鼓掌；称赞；赞许',
  'applause': 'n. 鼓掌；掌声；喝彩',
  'apple': 'n. 苹果；苹果树；苹果公司',
  'appliance': 'n. 电器；器具；装置',
  'applicant': 'n. 申请人；求职者；请求者',
  'application': 'n. 应用；申请；应用程序；施用',
  'apply': 'v. 申请；应用；涂；适用；请求',
  'appoint': 'v. 任命；委任；指定；约定；委派',
  'appointment': 'n. 任命；约会；约定；职务',
  'apportion': 'v. 分配；分派；分摊',
  'apposite': 'adj. 适当的；贴切的；恰当的',
  'appraisal': 'n. 评价；评估；鉴定',
  'appraise': 'v. 评价；评估；估价；鉴定',
  'appreciable': 'adj. 可察觉的；相当大的；值得注意的',
  'appreciate': 'v. 欣赏；感激；领会；升值；涨价',
  'appreciation': 'n. 欣赏；鉴赏；感激；评价；升值',
  'apprehend': 'v. 逮捕；理解；领悟；担心',
  'apprehension': 'n. 理解；领悟；逮捕；担忧',
  'apprentice': 'n. 学徒；徒工 v. 使当学徒',
  'approach': 'v. 接近；靠近；处理；着手 n. 方法；途径；接近；建议',
  'appropriate': 'adj. 适当的；恰当的；合适的 v. 拨出；占用；挪用',
  'appropriately': 'adv. 适当地；恰当的；相称地',
  'approval': 'n. 批准；同意；认可；赞成',
  'approve': 'v. 批准；赞成；同意；认可；满意',
  'approximate': 'adj. 大约的；近似的 v. 接近；近似；粗略估计',
  'approximately': 'adv. 大约；近似地；接近地',
  'appurtenance': 'n. 附属物；附件；从属权利',
  'apricot': 'n. 杏；杏树；杏黄色',
  'April': 'n. 四月',
  'apron': 'n. 围裙；停机坪；挡板',
  'apt': 'adj. 适当的；恰当的；聪明的；有...倾向的',
  'aptitude': 'n. 天资；才能；能力；资质',
  'arbiter': 'n. 仲裁人；主宰者；裁决者',
  'arbitrary': 'adj. 任意的；武断的；随意的；专制的',
  'arbitrate': 'v. 仲裁；公断',
  'arbitration': 'n. 仲裁；公断',
  'arcade': 'n. 拱廊；有拱廊的街道；游戏机厅',
  'arch': 'n. 拱；拱门；拱形 v. 变成拱形；弓起 adj. 主要的；调皮的',
  'archaeology': 'n. 考古学',
  'archaic': 'adj. 古代的；古老的；过时的',
  'archaism': 'n. 古风；古语；过时的词',
  'archbishop': 'n. 大主教；总主教',
  'architect': 'n. 建筑师；设计师；缔造者',
  'architecture': 'n. 建筑学；建筑设计；建筑风格；结构',
  'archive': 'n. 档案；档案馆；文件 v. 存档；归档',
  'arctic': 'adj. 北极的；严寒的 n. 北极；北极地区',
  'ardent': 'adj. 热心的；热情的；热烈的',
  'arduous': 'adj. 艰巨的；费力的；困难的',
  'are': 'v. 是；be的第二人称单复数和第一、三人称复数现在时',
  'area': 'n. 区域；面积；领域；范围；地区',
  'arena': 'n. 竞技场；舞台；活动场所',
  'argue': 'v. 争论；辩论；主张；说服；表明',
  'argument': 'n. 争论；论据；论证；参数；争吵',
  'arid': 'adj. 干旱的；贫瘠的；枯燥无味的',
  'arise': 'v. 出现；产生；发生；起身；起因于',
  'aristocracy': 'n. 贵族；贵族统治；贵族阶级',
  'aristocrat': 'n. 贵族',
  'aristocratic': 'adj. 贵族的；有贵族气派的',
  'arithmetic': 'n. 算术 adj. 算术的',
  'ark': 'n. 方舟；避难所',
  'arm': 'n. 手臂；武器；装备；部门 v. 武装；装备；备战',
  'armada': 'n. 舰队；机群；车队',
  'armchair': 'n. 扶手椅 adj. 空谈的；无实际经验的',
  'armor': 'n. 装甲；盔甲；保护层',
  'armory': 'n. 军械库；武器厂；兵工厂',
  'army': 'n. 军队；陆军；大群；野战军',
  'aroma': 'n. 芳香；香味；香气',
  'aromatic': 'adj. 芳香的；有香味的 n. 芳香剂；香料',
  'arose': 'v. 出现；发生；起身；arise的过去式',
  'around': 'prep. 围绕；环绕；到处；大约 adv. 周围；四周；到处；大约',
  'arouse': 'v. 唤醒；唤起；激起；引起',
  'arrange': 'v. 安排；筹备；整理；调解；改编',
  'arrangement': 'n. 安排；筹备；整理；商定；改编曲',
  'array': 'n. 一排；一大批；数组 v. 布置；排列；盛装',
  'arrest': 'v. 逮捕；拘留；阻止；吸引 n. 逮捕；拘留；停止',
  'arrival': 'n. 到达；到来；出现；开始',
  'arrive': 'v. 到达；到来；成功；达成；来临',
  'arrogance': 'n. 傲慢；自大；骄傲',
  'arrogant': 'adj. 傲慢的；自大的；骄傲的',
  'arrow': 'n. 箭；箭头；箭状物 v. 箭形物；急升',
  'arsenal': 'n. 兵工厂；军火库；储备',
  'art': 'n. 艺术；美术；技艺；技巧',
  'artery': 'n. 动脉；干线；要道',
  'artful': 'adj. 狡猾的；巧妙的；有技巧的',
  'article': 'n. 文章；论文；物品；条款；冠词',
  'articulate': 'v. 清晰发音；表达；连接 adj. 发音清晰的；善于表达的',
  'articulation': 'n. 发音；发音方法；关节；连接',
  'artifact': 'n. 人工制品；手工艺品；人工产物',
  'artificial': 'adj. 人工的；人造的；假的；虚伪的',
  'artillery': 'n. 炮兵；火炮；大炮',
  'artisan': 'n. 工匠；手工艺人；技工',
  'artist': 'n. 艺术家；美术家；表演者；大师',
  'artistic': 'adj. 艺术的；美术的；精美的；艺术家的',
  'artistry': 'n. 艺术技巧；艺术性；艺术才能',
  'artwork': 'n. 艺术品；美术品；插图；背景音乐',
  'as': 'conj. 因为；当...时；像...一样；虽然；由于 prep. 作为；像；如同 adv. 同样地；一样',
  'ascend': 'v. 上升；升高；攀登；追溯',
  'ascent': 'n. 上升；攀登；上坡路',
  'ascertain': 'v. 确定；查明；探知；弄清',
  'ascribe': 'v. 归因于；归于；认为...是由于',
  'ash': 'n. 灰；灰烬；废墟',
  'ashamed': 'adj. 羞愧的；惭愧的；羞耻的',
  'ashore': 'adv. 在岸上；向岸上',
  'Asia': 'n. 亚洲',
  'Asian': 'adj. 亚洲的；亚洲人的 n. 亚洲人',
  'aside': 'adv. 在旁边；到一边 n. 旁白；离题的话',
  'ask': 'v. 问；询问；要求；请求；邀请',
  'asleep': 'adj. 睡着的；麻木的；静止的 adv. 睡着；睡着地',
  'aspect': 'n. 方面；外观；样子；朝向；形势',
  'aspen': 'n. 白杨树 adj. 颤抖的；动摇的',
  'asperity': 'n. 严厉；粗鲁；严酷；困难',
  'aspersion': 'n. 诽谤；中伤；诋毁',
  'aspire': 'v. 渴望；追求；有志于；向往',
  'aspiration': 'n. 渴望；抱负；志向；热望',
  'ass': 'n. 驴；傻瓜；蠢人；屁股',
  'assail': 'v. 攻击；袭击；抨击；困扰',
  'assassin': 'n. 刺客；暗杀者',
  'assassinate': 'v. 暗杀；行刺；刺杀',
  'assault': 'n. 攻击；袭击；冲击 v. 攻击；袭击；殴打',
  'assemble': 'v. 集合；聚集；组装；装配；召集',
  'assembly': 'n. 集合；集会；装配；议会；立法机构',
  'assert': 'v. 断言；宣称；主张；维护；坚持',
  'assertion': 'n. 断言；主张；声明；坚持',
  'assess': 'v. 评估；评定；估计；征收',
  'assessment': 'n. 评估；评定；估价；评价',
  'asset': 'n. 资产；财产；有价值的人或事物；优点',
  'assign': 'v. 分配；分派；指派；指定；转让',
  'assignment': 'n. 任务；作业；分配；指派；转让',
  'assimilate': 'v. 同化；吸收；消化；理解',
  'assist': 'v. 帮助；协助；支持；促进 n. 帮助；助攻；协助',
  'assistance': 'n. 帮助；协助；援助；支持',
  'assistant': 'n. 助手；助理 adj. 助理的；副的',
  'associate': 'v. 联系；交往；结交；联想 adj. 副的；联合的 n. 同事；伙伴；合伙人',
  'association': 'n. 协会；社团；联盟；联系；交往；联合',
  'assorted': 'adj. 各式各样的；什锦的；混杂的',
  'assume': 'v. 假定；假设；承担；呈现；采取；假装',
  'assumption': 'n. 假定；假设；承担；假装；夺取',
  'assurance': 'n. 保证；担保；确信；保险',
  'assure': 'v. 保证；担保；使确信；使放心；保险',
  'assured': 'adj. 确信的；有把握的；确定的 n. 被保险人',
  'asterisk': 'n. 星号 v. 加星号；打星号',
  'asteroid': 'n. 小行星 adj. 星状的',
  'asthma': 'n. 气喘；哮喘',
  'astonish': 'v. 使惊讶；使吃惊；使惊愕',
  'astonished': 'adj. 惊讶的；吃惊的；惊愕的',
  'astonishing': 'adj. 令人惊讶的；惊人的；可惊的',
  'astound': 'v. 使震惊；使惊骇；使惊愕',
  'astronaut': 'n. 宇航员；航天员；太空人',
  'astronomy': 'n. 天文学',
  'astute': 'adj. 精明的；敏锐的；机灵的',
  'asylum': 'n. 庇护；避难；精神病院',
  'at': 'prep. 在；向；朝；在...时刻；在...方面；因为',
  'ate': 'v. 吃；吃的过去式',
  'atheism': 'n. 无神论',
  'atheist': 'n. 无神论者',
  'athlete': 'n. 运动员；体育家；运动选手',
  'athletic': 'adj. 运动的；体育的；运动员的；体格健壮的',
  'athletics': 'n. 体育运动；田径运动',
  'atlas': 'n. 地图册；地图集',
  'atmosphere': 'n. 大气；大气层；空气；气氛；氛围；环境',
  'atmospheric': 'adj. 大气的；大气层的；空气的；氛围的',
  'atom': 'n. 原子；微粒；微量',
  'atomic': 'adj. 原子的；原子能的；微小的',
  'attach': 'v. 附上；贴上；系上；连接；使依附；使附着；重视',
  'attachment': 'n. 附件；附属物；依恋；爱慕；连接；扣押',
  'attack': 'v. 攻击；袭击；抨击；进攻；发病 n. 攻击；袭击；进攻；疾病发作',
  'attain': 'v. 达到；获得；实现；到达',
  'attainable': 'adj. 可达到的；可实现的；可获得的',
  'attempt': 'v. 尝试；企图；试图；努力 n. 尝试；企图；努力',
  'attend': 'v. 出席；参加；注意；倾听；照顾；护理；陪伴',
  'attendance': 'n. 出席；参加；出席人数；照料',
  'attendant': 'n. 服务员；侍从；随从 adj. 伴随的；随之而来的',
  'attention': 'n. 注意；注意力；关注；关照；关心；殷勤',
  'attentive': 'adj. 注意的；留心的；关心的；体贴的',
  'attenuate': 'v. 使变细；使变薄；削弱；减弱；稀释 adj. 稀薄的；减弱的',
  'attest': 'v. 证实；证明；作证',
  'attitude': 'n. 态度；看法；姿势；姿态；意见',
  'attorney': 'n. 律师；代理人',
  'attract': 'v. 吸引；引起；引诱；引起...兴趣；有吸引力',
  'attraction': 'n. 吸引；吸引力；魅力；吸引人的事物；引力',
  'attractive': 'adj. 有吸引力的；迷人的；吸引人的；引起兴趣的',
  'attribute': 'v. 归因于；认为...是；把...归于 n. 属性；特质；性质；特征；标志',
  'attribution': 'n. 归因；归属；属性；归属权',
  'attrition': 'n. 磨损；消耗；人员自然减少',
  'auction': 'n. 拍卖 v. 拍卖',
  'audacious': 'adj. 大胆的；鲁莽的；厚颜无耻的',
  'audacity': 'n. 大胆；鲁莽；厚颜无耻',
  'audible': 'adj. 可听见的；听得见的',
  'audience': 'n. 听众；观众；读者；接见；见面',
  'audio': 'adj. 声音的；音频的；听觉的',
  'audit': 'n. 审计；查账；审核 v. 审计；查账；检查；旁听',
  'audition': 'n. 试演；试听；听力 v. 试演；试听',
  'auditor': 'n. 审计员；核数员；旁听生',
  'auditorium': 'n. 礼堂；观众席；听众席',
  'augment': 'v. 增加；扩大；增大；增强 n. 增加；增大',
  'August': 'n. 八月 adj. 威严的；庄严的',
  'august': 'adj. 威严的；庄严的；高贵的',
  'aunt': 'n. 阿姨；姑姑；婶母；舅母；伯母',
  'auntie': 'n. 阿姨；姑妈；伯母；舅母（昵称）',
  'aura': 'n. 气氛；气息；光环；光轮',
  'aurora': 'n. 极光；曙光；黎明',
  'auspice': 'n. 赞助；支持；预兆；吉兆；保护',
  'auspicious': 'adj. 吉祥的；吉利的；有希望的',
  'austere': 'adj. 严厉的；朴素的；苦行的；严峻的',
  'austerity': 'n. 严厉；朴素；苦行；艰苦；紧缩',
  'authentic': 'adj. 真正的；真实的；可信的；可靠的',
  'authenticity': 'n. 真实性；确实性；可靠性',
  'author': 'n. 作者；作家；创始人；著者 v. 创作；编写；写作',
  'authoritarian': 'adj. 独裁的；专制的；权威主义的 n. 独裁者；专制者',
  'authority': 'n. 权威；权力；官方；当局；权限；威信；影响力',
  'authorize': 'v. 授权；批准；许可；委托；核准',
  'auto': 'n. 汽车',
  'autobiography': 'n. 自传',
  'autocracy': 'n. 独裁政治；专制政府；独裁政权',
  'autocrat': 'n. 独裁者；专制君主；专横的人',
  'autocratic': 'adj. 独裁的；专制的；专横的',
  'automate': 'v. 使自动化；自动操作',
  'automated': 'adj. 自动化的；自动的',
  'automatic': 'adj. 自动的；无意识的；机械的；必然的 n. 自动装置；自动武器',
  'automatically': 'adv. 自动地；无意识地；机械地；自然地',
  'automation': 'n. 自动化；自动操作',
  'automobile': 'n. 汽车',
  'autonomous': 'adj. 自治的；自主的；独立自主的',
  'autonomy': 'n. 自治；自治权；自主权',
  'autumn': 'n. 秋天；秋季；成熟期；衰落期',
  'auxiliary': 'adj. 辅助的；协助的；备用的 n. 辅助者；辅助物',
  'avail': 'v. 有用；有利；帮助；有益于 n. 效用；利益；帮助',
  'available': 'adj. 可获得的；可得到的；可用的；有空的；有效的',
  'avalanche': 'n. 雪崩；大量涌到 v. 雪崩；大量涌到',
  'avenue': 'n. 大道；林荫道；途径；手段；大街',
  'average': 'n. 平均；平均数；一般水平 adj. 平均的；普通的；中等的 v. 平均为；算出...的平均数',
  'aversion': 'n. 厌恶；憎恶；讨厌的人或事物',
  'avert': 'v. 防止；避免；转移；挡开',
  'aviation': 'n. 航空；航空学；飞行术；飞机制造业',
  'aviator': 'n. 飞行员；飞行家',
  'avid': 'adj. 渴望的；急切的；贪婪的；热衷的',
  'avoid': 'v. 避免；避开；消除；预防；躲开',
  'avoidance': 'n. 避免；回避；躲避',
  'await': 'v. 等待；等候；期待；即将发生',
  'awake': 'adj. 醒着的；意识到的 v. 唤醒；使觉醒；醒来；意识到',
  'awaken': 'v. 唤醒；使觉醒；醒来；唤起；激起',
  'award': 'n. 奖；奖品；奖金；判决 v. 授予；给予；判给',
  'aware': 'adj. 知道的；意识到的；有觉悟的；有认识的',
  'awareness': 'n. 知道；了解；意识；认识；觉悟',
  'away': 'adv. 离开；远离；向远处；不在家；掉；消失',
  'awe': 'n. 敬畏；惊叹；惊惧 v. 使敬畏；使惊叹；使畏惧',
  'awful': 'adj. 糟糕的；可怕的；讨厌的；非常的；极大的',
  'awkward': 'adj. 尴尬的；笨拙的；不灵活的；难处理的；不方便的',
  'awl': 'n. 锥子；尖钻',
  'awning': 'n. 遮阳篷；雨篷；凉篷',
  'awoke': 'v. 醒；唤醒；awake的过去式',
  'awry': 'adj. 扭曲的；歪的；斜的；错误的；出岔子的',
  'axe': 'n. 斧头；斧 v. 用斧头砍；削减；裁员',
  'axiom': 'n. 公理；原理；原则；自明之理',
  'axis': 'n. 轴；轴线；轴心；坐标轴',
  'axle': 'n. 轴；车轴；轮轴',
  'aye': 'adv. 是；是的；同意；赞成 n. 同意；赞成；赞成票',
  'ayes': 'n. 赞成者；赞成票',
  'ayllu': 'n. 艾柳（印第安人传统村社）',
  'ayo': 'n. 哎呀；表示吃惊或抗议',
  'azalea': 'n. 杜鹃花',
  'azure': 'adj. 天蓝色的；蔚蓝色的 n. 天蓝色；碧空'
};

function guessMeaning(word, rootMeaning) {
  const lowerWord = word.toLowerCase();
  
  // 如果在完整释义库中找到，直接返回
  if (comprehensiveMeanings[lowerWord]) {
    return comprehensiveMeanings[lowerWord];
  }
  
  // 根据后缀判断词性
  let type = 'n.';
  if (lowerWord.endsWith('ed') || lowerWord.endsWith('ing')) {
    type = 'v.';
  } else if (lowerWord.endsWith('ly')) {
    type = 'adv.';
  } else if (lowerWord.endsWith('able') || lowerWord.endsWith('ible')) {
    type = 'adj.';
  } else if (lowerWord.endsWith('al') || lowerWord.endsWith('ful') || lowerWord.endsWith('less') || lowerWord.endsWith('ous')) {
    type = 'adj.';
  } else if (lowerWord.endsWith('ion') || lowerWord.endsWith('tion') || lowerWord.endsWith('sion') || lowerWord.endsWith('ment') || lowerWord.endsWith('ness') || lowerWord.endsWith('ship')) {
    type = 'n.';
  } else if (lowerWord.endsWith('ize') || lowerWord.endsWith('ise') || lowerWord.endsWith('ify') || lowerWord.endsWith('ate')) {
    type = 'v.';
  }
  
  // 构造基本释义
  let meaning = word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
  if (rootMeaning && rootMeaning.length > 0 && rootMeaning !== '离开') {
    return type + ' ' + meaning + '（' + rootMeaning + '）';
  } else {
    return type + ' ' + meaning;
  }
}

const data = fs.readFileSync('/home/fred/workspace/memoryworld-project/src/data/mockWords.ts', 'utf8');
const match = data.match(/export const mockWords: IELTSWord\[\] = \[([\s\S]*?)\];/);

if (match) {
  const words = JSON.parse('[' + match[1] + ']');
  console.log('Processing ' + words.length + ' words...');
  
  let updated = 0;
  words.forEach(w => {
    if (w.meaning.includes('（词根含义：')) {
      const newMeaning = guessMeaning(w.word, w.rootMeaning);
      if (newMeaning !== w.meaning) {
        w.meaning = newMeaning;
        updated++;
      }
    }
  });
  
  console.log('Updated ' + updated + ' words');
  
  const output = `export interface IELTSWord {
  id: string;
  word: string;
  meaning: string;
  level: string;
  root: string;
  rootMeaning: string;
  rootMeaningEn: string;
  rootOrigin: string;
  rootOriginNote: string;
  relatedWords: { word: string; meaning: string; level: string }[];
  phonetic: string;
  frequency: string;
  example: string;
}

export const mockWords: IELTSWord[] = ${JSON.stringify(words, null, 2)};`;
  
  fs.writeFileSync('/home/fred/workspace/memoryworld-project/src/data/mockWords.ts', output);
  console.log('Done!');
}
