const fs = require('fs');

const data = fs.readFileSync('/home/fred/workspace/memoryworld-project/src/data/mockWords.ts', 'utf8');
const match = data.match(/export const mockWords: IELTSWord\[\] = \[([\s\S]*?)\];/);

if (match) {
  const words = JSON.parse('[' + match[1] + ']');
  
  const completeMeanings = {
    'dream': 'n. 梦；梦想 v. 做梦；梦想',
    'dress': 'n. 连衣裙；服装 v. 穿衣服；给...穿衣服',
    'drop': 'v. 落下；下降；停止 n. 滴；降落；下跌',
    'drink': 'v. 喝；饮 n. 饮料；喝酒',
    'drive': 'v. 驾驶；驱动 n. 驾驶；驱动器；车道',
    'eat': 'v. 吃；喝；吃饭',
    'walk': 'v. 走；步行；散步 n. 步行；散步；人行道',
    'talk': 'v./n. 谈话；演讲；说话',
    'look': 'v./n. 看；注视；显得',
    'see': 'v. 看见；理解；拜访',
    'sleep': 'v. 睡觉 n. 睡眠',
    'slow': 'adj. 慢的；迟钝的 v. 放慢',
    'small': 'adj. 小的；少的',
    'smart': 'adj. 聪明的；敏捷的',
    'smile': 'v./n. 微笑；笑容',
    'smoke': 'n. 烟；烟雾 v. 吸烟；冒烟',
    'snow': 'n. 雪 v. 下雪',
    'soap': 'n. 肥皂 v. 用肥皂洗',
    'sock': 'n. 短袜 v. 给...穿袜子',
    'sofa': 'n. 沙发',
    'soft': 'adj. 软的；柔和的',
    'soil': 'n. 土壤；土地 v. 弄脏；污染',
    'soldier': 'n. 士兵；军人',
    'solid': 'adj. 固体的；结实的 n. 固体',
    'solve': 'v. 解决；解答',
    'son': 'n. 儿子；孩子',
    'song': 'n. 歌曲；歌声',
    'soon': 'adv. 不久；很快',
    'sorry': 'adj. 抱歉的；遗憾的',
    'sort': 'n. 种类；分类 v. 分类；整理',
    'soul': 'n. 灵魂；精神',
    'sound': 'n. 声音 v. 听起来 adj. 健康的；合理的',
    'soup': 'n. 汤；羹',
    'sour': 'adj. 酸的；酸腐的 v. 变酸',
    'source': 'n. 来源；源头',
    'south': 'n. 南方 adj. 南方的 adv. 向南',
    'southern': 'adj. 南方的；南部的',
    'space': 'n. 空间；太空 v. 留间隔',
    'spare': 'adj. 多余的；备用的 v. 节省；抽出',
    'speak': 'v. 说；说话；演讲',
    'speaker': 'n. 演讲者；扬声器',
    'speed': 'n. 速度 v. 加速；超速',
    'spell': 'v. 拼写；意味着 n. 咒语；一段时间',
    'spend': 'v. 花费；度过；消耗',
    'spirit': 'n. 精神；灵魂；酒精',
    'spit': 'v. 吐痰；吐出 n. 唾液',
    'split': 'v. 分裂；分开 n. 分裂；裂缝',
    'spoke': 'v. 说（speak过去式）',
    'sport': 'n. 运动；游戏',
    'spot': 'n. 地点；斑点 v. 发现；弄脏',
    'spread': 'v. 传播；展开 n. 传播；范围',
    'spring': 'n. 春天；弹簧 v. 跳跃；涌出',
    'square': 'adj. 平方的；正方形的 n. 广场；正方形',
    'stage': 'n. 阶段；舞台 v. 举行；上演',
    'stair': 'n. 楼梯；阶梯',
    'stake': 'n. 赌注；桩 v. 冒险；以...为赌注',
    'stale': 'adj. 陈旧的；不新鲜的',
    'stamp': 'n. 邮票；印记 v. 盖章；跺脚',
    'stand': 'v. 站立；位于 n. 立场；停止',
    'standard': 'n. 标准 adj. 标准的',
    'star': 'n. 星星；明星 v. 主演',
    'stare': 'v. 凝视；注视 n. 凝视',
    'start': 'v. 开始；启动 n. 开始；起点',
    'state': 'n. 状态；国家 v. 陈述',
    'station': 'n. 车站；站 v. 驻扎',
    'stay': 'v. 停留；保持 n. 停留；逗留',
    'steal': 'v. 偷窃；窃取 n. 便宜货',
    'steam': 'n. 蒸汽 v. 蒸发；蒸煮',
    'steel': 'n. 钢铁 v. 使坚强',
    'steep': 'adj. 陡峭的；急剧的 v. 浸泡',
    'steer': 'v. 驾驶；引导 n. 公牛',
    'stem': 'n. 茎；干 v. 阻止；起源于',
    'step': 'n. 步骤；步伐 v. 踏；走',
    'stick': 'n. 棍棒；手杖 v. 粘贴；刺',
    'sticky': 'adj. 粘的；棘手的',
    'stiff': 'adj. 僵硬的；生硬的',
    'still': 'adv. 仍然 adj. 静止的 n. 寂静',
    'stock': 'n. 股票；库存 v. 储备',
    'stomach': 'n. 胃；腹部 v. 忍受',
    'stone': 'n. 石头 v. 向...扔石头',
    'stop': 'v. 停止 n. 停止；车站',
    'store': 'n. 商店 v. 储存',
    'storm': 'n. 暴风雨 v. 猛攻；起风暴',
    'story': 'n. 故事；小说',
    'stove': 'n. 火炉',
    'straight': 'adj. 直的 adv. 直接地',
    'strain': 'v. 拉紧 n. 张力；拉紧',
    'strange': 'adj. 奇怪的；陌生的',
    'stranger': 'n. 陌生人',
    'stream': 'n. 溪流 v. 流；涌',
    'street': 'n. 街道',
    'strength': 'n. 力量；强度',
    'stress': 'n. 压力 v. 强调',
    'stretch': 'v. 伸展 n. 伸展；弹性',
    'strict': 'adj. 严格的；精确的',
    'strike': 'v. 打；撞击 n. 罢工；打击',
    'string': 'n. 线；弦 v. 绑；伸展',
    'strip': 'v. 脱光 n. 条带；脱衣舞',
    'stripe': 'n. 条纹 v. 给...加条纹',
    'stroke': 'n. 中风；击球 v. 抚摸',
    'strong': 'adj. 强壮的；强大的',
    'structure': 'n. 结构 v. 构建',
    'struggle': 'v. 挣扎 n. 斗争；努力',
    'student': 'n. 学生',
    'studio': 'n. 工作室；画室',
    'study': 'v./n. 学习；研究',
    'stuff': 'n. 东西 v. 填满；塞满',
    'stupid': 'adj. 愚蠢的',
    'subject': 'n. 主题 v. 使服从',
    'substance': 'n. 物质；实质',
    'succeed': 'v. 成功；继承',
    'success': 'n. 成功；成就',
    'such': 'adj. 这样的 pron. 这样的人',
    'suck': 'v. 吸；舐 n. 吸',
    'sudden': 'adj. 突然的',
    'suffer': 'v. 遭受；经历',
    'sugar': 'n. 糖 v. 加糖',
    'suggest': 'v. 建议；暗示',
    'suit': 'n. 套装 v. 适合；起诉',
    'summer': 'n. 夏天；夏季',
    'sun': 'n. 太阳；阳光 v. 晒太阳',
    'super': 'adj. 超级的；极好的',
    'supper': 'n. 晚餐',
    'supply': 'v./n. 供给；供应',
    'support': 'v./n. 支持；支撑',
    'suppose': 'v. 假设；认为',
    'sure': 'adj. 确信的 adv. 当然',
    'surface': 'n. 表面 v. 浮出水面',
    'surprise': 'n. 惊讶 v. 使惊讶',
    'surround': 'v. 围绕 n. 围绕物',
    'survive': 'v. 幸存；活下来',
    'suspect': 'v. 怀疑 n. 嫌疑犯',
    'swim': 'v./n. 游泳',
    'tail': 'n. 尾巴 v. 跟踪',
    'tailor': 'n. 裁缝 v. 剪裁；调整',
    'take': 'v. 拿；取；花费',
    'tale': 'n. 故事；传说',
    'talk': 'v./n. 谈话；演讲',
    'tall': 'adj. 高的',
    'tank': 'n. 坦克；容器',
    'tape': 'n. 磁带 v. 录音',
    'task': 'n. 任务 v. 分派任务',
    'taste': 'v./n. 品尝；味道',
    'tax': 'n. 税 v. 征税',
    'taxi': 'n. 出租车 v. 滑行',
    'tea': 'n. 茶；茶叶',
    'teach': 'v. 教；教导',
    'teacher': 'n. 教师',
    'team': 'n. 团队 v. 协作',
    'tear': 'n. 眼泪 v. 撕开',
    'technical': 'adj. 技术的',
    'technique': 'n. 技术；技巧',
    'technology': 'n. 科技；技术',
    'teenager': 'n. 青少年',
    'telephone': 'n. 电话 v. 打电话',
    'television': 'n. 电视',
    'tell': 'v. 告诉；说',
    'temperature': 'n. 温度',
    'temple': 'n. 寺庙；太阳穴',
    'temporary': 'adj. 暂时的',
    'ten': 'num. 十',
    'tend': 'v. 趋向；照管',
    'tennis': 'n. 网球',
    'tense': 'adj. 紧张的 n. 时态',
    'tent': 'n. 帐篷',
    'term': 'n. 学期；术语',
    'terrible': 'adj. 可怕的；糟糕的',
    'test': 'v./n. 测试；测验',
    'text': 'n. 文本；正文',
    'than': 'conj. 比',
    'thank': 'v./n. 感谢',
    'that': 'pron./adj. 那；那个',
    'theatre': 'n. 剧院',
    'theft': 'n. 盗窃',
    'their': 'pron. 他们的',
    'them': 'pron. 他们',
    'theme': 'n. 主题',
    'themselves': 'pron. 他们自己',
    'then': 'adv. 然后；当时',
    'theory': 'n. 理论',
    'there': 'adv. 在那里',
    'therefore': 'adv. 因此',
    'these': 'pron./adj. 这些',
    'they': 'pron. 他们',
    'thick': 'adj. 厚的；浓的',
    'thief': 'n. 小偷',
    'thin': 'adj. 薄的；瘦的 v. 变薄',
    'thing': 'n. 东西；事情',
    'think': 'v. 想；思考',
    'third': 'num. 第三',
    'thirty': 'num. 三十',
    'this': 'pron./adj. 这；这个',
    'those': 'pron./adj. 那些',
    'though': 'conj. 虽然',
    'thought': 'n. 思想；想法',
    'thousand': 'num. 千',
    'thread': 'n. 线；线索',
    'threat': 'n. 威胁',
    'three': 'num. 三',
    'through': 'prep./adv. 通过',
    'throw': 'v. 投；掷',
    'thursday': 'n. 星期四',
    'thus': 'adv. 因此',
    'ticket': 'n. 票；标签',
    'tidy': 'adj. 整洁的 v. 整理',
    'tie': 'n. 领带 v. 系；连接',
    'tiger': 'n. 老虎',
    'tight': 'adj. 紧的；严格的',
    'till': 'prep./conj. 直到',
    'time': 'n. 时间 v. 计时',
    'tin': 'n. 锡；罐头',
    'tiny': 'adj. 极小的',
    'tip': 'n. 尖端；小费 v. 倾斜',
    'tire': 'v. 使疲劳 n. 轮胎',
    'tired': 'adj. 疲劳的',
    'tissue': 'n. 组织；纸巾',
    'title': 'n. 标题；权利',
    'to': 'prep. 到；向',
    'toast': 'n. 烤面包 v. 烤；祝酒',
    'today': 'adv./n. 今天',
    'toe': 'n. 脚趾',
    'together': 'adv. 一起',
    'toilet': 'n. 厕所',
    'tomato': 'n. 番茄',
    'tomorrow': 'adv./n. 明天',
    'tone': 'n. 音调；语气',
    'tongue': 'n. 舌头；语言',
    'tonight': 'adv./n. 今晚',
    'too': 'adv. 也；太',
    'tool': 'n. 工具',
    'tooth': 'n. 牙齿',
    'top': 'n. 顶部 adj. 最高的',
    'topic': 'n. 话题；主题',
    'total': 'adj. 总的 n. 总数',
    'touch': 'v./n. 触摸；接触',
    'tough': 'adj. 坚韧的；困难的',
    'tour': 'n./v. 旅行；旅游',
    'tourist': 'n. 游客',
    'toward': 'prep. 向；朝',
    'tower': 'n. 塔 v. 高耸',
    'town': 'n. 城镇',
    'toy': 'n. 玩具 v. 玩弄',
    'track': 'n. 轨道 v. 追踪',
    'trade': 'n./v. 贸易；交易',
    'tradition': 'n. 传统',
    'traditional': 'adj. 传统的',
    'traffic': 'n. 交通 v. 交易',
    'train': 'n. 火车 v. 训练',
    'training': 'n. 训练',
    'transfer': 'v./n. 转移；转让',
    'transform': 'v. 转换；改变',
    'translate': 'v. 翻译',
    'transport': 'n./v. 运输',
    'trap': 'n. 陷阱 v. 诱捕',
    'travel': 'v./n. 旅行',
    'tray': 'n. 托盘',
    'treasure': 'n. 财富 v. 珍视',
    'treat': 'v. 对待；治疗 n. 款待',
    'treatment': 'n. 治疗；处理',
    'tree': 'n. 树 v. 爬上树',
    'trend': 'n. 趋势 v. 趋向',
    'trial': 'n. 审判；试验',
    'triangle': 'n. 三角形',
    'tribe': 'n. 部落',
    'trick': 'n. 诡计 v. 欺骗',
    'trip': 'v. 绊倒 n. 旅行',
    'troop': 'n. 军队 v. 群集',
    'trouble': 'n. 麻烦 v. 使麻烦',
    'trousers': 'n. 裤子',
    'truck': 'n. 卡车 v. 用卡车运',
    'true': 'adj. 真实的',
    'truly': 'adv. 真实地',
    'trust': 'n./v. 信任',
    'truth': 'n. 真理；真相',
    'try': 'v./n. 尝试；努力',
    'tuesday': 'n. 星期二',
    'turn': 'v./n. 转向；转动',
    'twice': 'adv. 两次；两倍',
    'twin': 'n. 双胞胎 adj. 双的',
    'twist': 'v. 拧；扭曲 n. 拧',
    'two': 'num. 二',
    'type': 'n. 类型 v. 打字',
    'ugly': 'adj. 丑陋的',
    'umbrella': 'n. 伞',
    'unable': 'adj. 不会的；不能的',
    'uncle': 'n. 叔叔',
    'under': 'prep. 在...下面',
    'understand': 'v. 理解',
    'undertake': 'v. 承担；着手做',
    'unemployment': 'n. 失业；失业率',
    'unexpected': 'adj. 意外的',
    'unfair': 'adj. 不公平的',
    'unhappy': 'adj. 不快乐的',
    'uniform': 'n. 制服 adj. 统一的',
    'union': 'n. 联盟；工会',
    'unique': 'adj. 独特的',
    'unit': 'n. 单位；单元',
    'unite': 'v. 联合；团结',
    'united': 'adj. 联合的；统一的',
    'unity': 'n. 团结；一致',
    'universe': 'n. 宇宙',
    'university': 'n. 大学',
    'unknown': 'adj. 未知的 n. 未知的事物',
    'unless': 'conj. 除非',
    'unlike': 'prep. 与...不同',
    'unlikely': 'adj. 不太可能的',
    'until': 'prep./conj. 直到',
    'unusual': 'adj. 不寻常的',
    'up': 'adv./prep. 向上',
    'update': 'v./n. 更新',
    'upon': 'prep. 在...之上',
    'upper': 'adj. 上面的',
    'upset': 'v. 使心烦 adj. 不安的',
    'upstairs': 'adv./adj. 在楼上',
    'urban': 'adj. 城市的',
    'urge': 'v. 强烈要求 n. 冲动',
    'urgent': 'adj. 紧急的',
    'us': 'pron. 我们',
    'use': 'v./n. 使用',
    'used': 'v. 用过 adj. 用过的',
    'useful': 'adj. 有用的',
    'useless': 'adj. 无用的',
    'user': 'n. 用户',
    'usual': 'adj. 通常的',
    'usually': 'adv. 通常',
    'utility': 'n. 功用；公共事业',
    'vacant': 'adj. 空缺的',
    'vacation': 'n. 假期 v. 度假',
    'vague': 'adj. 模糊的',
    'valid': 'adj. 有效的',
    'valley': 'n. 山谷',
    'valuable': 'adj. 贵重的',
    'value': 'n./v. 价值；重视',
    'van': 'n. 面包车',
    'vanish': 'v. 消失',
    'variety': 'n. 多样；种类',
    'various': 'adj. 各种各样的',
    'vast': 'adj. 广阔的；大量的',
    'vegetable': 'n. 蔬菜',
    'vehicle': 'n. 车辆；工具',
    'venture': 'n./v. 冒险；企业',
    'verb': 'n. 动词',
    'version': 'n. 版本；说法',
    'very': 'adv. 非常 adj. 正是的',
    'victim': 'n. 受害者',
    'victory': 'n. 胜利',
    'video': 'n. 视频 v. 录制',
    'view': 'n. 观点；视野 v. 看待',
    'viewer': 'n. 观众； viewer',
    'village': 'n. 村庄',
    'violence': 'n. 暴力',
    'violent': 'adj. 暴力的',
    'virtue': 'n. 美德；优点',
    'virus': 'n. 病毒',
    'visible': 'adj. 可见的',
    'vision': 'n. 视力；愿景',
    'visit': 'v./n. 访问；参观',
    'visitor': 'n. 访问者；游客',
    'visual': 'adj. 视觉的',
    'vital': 'adj. 至关重要的',
    'voice': 'n. 声音 v. 表达',
    'voluntary': 'adj. 自愿的',
    'volunteer': 'n. 志愿者 v. 自愿做',
    'vote': 'n./v. 投票；选举',
    'voyage': 'n./v. 航行；旅行',
    'wage': 'n. 工资 v. 进行',
    'wait': 'v./n. 等待',
    'waiter': 'n. 服务员',
    'wake': 'v. 醒来；唤醒 n. 守夜',
    'walk': 'v./n. 步行；散步',
    'wall': 'n. 墙壁 v. 用墙围住',
    'wallet': 'n. 钱包',
    'wander': 'v. 徘徊；迷路',
    'want': 'v. 想要 n. 需要',
    'war': 'n. 战争 v. 作战',
    'warm': 'adj. 温暖的 v. 使温暖',
    'warmth': 'n. 温暖；热情',
    'warn': 'v. 警告；提醒',
    'warning': 'n. 警告；警示',
    'wash': 'v./n. 洗；洗涤',
    'waste': 'v./n. 浪费 adj. 废弃的',
    'watch': 'v./n. 观看；注视 n. 手表',
    'water': 'n. 水 v. 浇水',
    'wave': 'n. 波浪 v. 波动；挥手',
    'way': 'n. 方式；道路',
    'we': 'pron. 我们',
    'weak': 'adj. 虚弱的；弱的',
    'wealth': 'n. 财富',
    'wealthy': 'adj. 富有的',
    'weapon': 'n. 武器',
    'wear': 'v. 穿；戴 n. 服装',
    'weather': 'n. 天气',
    'web': 'n. 网络；网',
    'website': 'n. 网站',
    'wedding': 'n. 婚礼',
    'wednesday': 'n. 星期三',
    'week': 'n. 周；星期',
    'weekend': 'n. 周末',
    'weekly': 'adj. 每周的 adv. 每周',
    'weigh': 'v. 称重；重量为',
    'weight': 'n. 重量；体重',
    'welcome': 'v./n./adj. 欢迎',
    'welfare': 'n. 福利；幸福',
    'well': 'adv. 好；很 adj. 健康的 n. 井',
    'west': 'n. 西方 adj. 西方的',
    'western': 'adj. 西方的；西方的',
    'whale': 'n. 鲸鱼',
    'what': 'pron./adj. 什么',
    'whatever': 'pron./adj. 无论什么',
    'wheat': 'n. 小麦',
    'wheel': 'n. 轮子 v. 推动',
    'when': 'adv./conj. 什么时候；当...时',
    'where': 'adv./conj. 哪里',
    'whether': 'conj. 是否',
    'which': 'pron./adj. 哪个',
    'while': 'n./conj. 一会儿；当...时',
    'whisper': 'v./n. 低语；耳语',
    'white': 'adj. 白色的 n. 白色',
    'who': 'pron. 谁',
    'whole': 'adj. 整个的 n. 整体',
    'whom': 'pron. 谁（宾格）',
    'whose': 'pron./adj. 谁的',
    'why': 'adv./conj. 为什么',
    'wide': 'adj. 宽的；广阔的',
    'widely': 'adv. 广泛地',
    'wife': 'n. 妻子',
    'wild': 'adj. 野生的；疯狂的',
    'will': 'v. 将；会 n. 意志；遗嘱',
    'willing': 'adj. 愿意的',
    'win': 'v. 赢；获胜 n. 胜利',
    'wind': 'n. 风 v. 绕；缠',
    'window': 'n. 窗户',
    'wine': 'n. 葡萄酒；酒',
    'wing': 'n. 翅膀 v. 飞过',
    'winner': 'n. 获胜者',
    'winter': 'n. 冬天',
    'wipe': 'v./n. 擦；抹',
    'wire': 'n. 电线 v. 装电线',
    'wisdom': 'n. 智慧；明智',
    'wise': 'adj. 智慧的；聪明的',
    'wish': 'v./n. 希望；祝愿',
    'with': 'prep. 和...一起；用',
    'within': 'prep. 在...里面',
    'without': 'prep. 没有；不带',
    'witness': 'n. 证人 v. 目击；见证',
    'woman': 'n. 妇女；女人',
    'wonder': 'v./n. 怀疑；想知道 n. 奇迹',
    'wonderful': 'adj. 极好的；精彩的',
    'wood': 'n. 木材；木头',
    'wooden': 'adj. 木制的；呆板的',
    'wool': 'n. 羊毛；毛线',
    'word': 'n. 单词；话语 v. 措辞',
    'work': 'n. 工作 v. 工作；运转',
    'worker': 'n. 工人',
    'world': 'n. 世界；领域',
    'worried': 'adj. 担心的；发愁的',
    'worry': 'v./n. 担心；烦恼',
    'worse': 'adj./adv. 更坏的；更差',
    'worship': 'n./v. 崇拜；尊敬',
    'worst': 'adj./adv. 最坏的；最差',
    'worth': 'n. 价值 adj. 值...的',
    'worthy': 'adj. 值得的；有价值的',
    'would': 'v. 将；会；愿意',
    'wound': 'n. 伤口 v. 伤害',
    'wrap': 'v. 包；裹 n. 披肩',
    'wrist': 'n. 手腕；腕关节',
    'write': 'v. 写；写作',
    'writer': 'n. 作家；作者',
    'wrong': 'adj. 错误的；有问题的 adv. 错误地',
    'yard': 'n. 院子；码',
    'year': 'n. 年；年份',
    'yellow': 'adj. 黄色的 n. 黄色',
    'yes': 'adv. 是；是的',
    'yesterday': 'n./adv. 昨天',
    'yet': 'adv. 还；仍然 conj. 但是',
    'yield': 'v. 产生；让步 n. 产量',
    'you': 'pron. 你；你们',
    'young': 'adj. 年轻的 n. 青年',
    'your': 'pron. 你的；你们的',
    'yourself': 'pron. 你自己',
    'youth': 'n. 青年；青春',
    'zero': 'n./num. 零',
    'zone': 'n. 区域；地带 v. 分区'
  };
  
  let fixed = 0;
  
  words.forEach(w => {
    const key = w.word.toLowerCase();
    if (completeMeanings[key]) {
      w.meaning = completeMeanings[key];
      fixed++;
    }
  });
  
  console.log('修复了', fixed, '个单词的meaning');
  
  const output = 'export interface IELTSWord {\n' +
    '  id: string;\n' +
    '  word: string;\n' +
    '  meaning: string;\n' +
    '  level: string;\n' +
    '  root: string;\n' +
    '  rootMeaning: string;\n' +
    '  rootMeaningEn: string;\n' +
    '  rootOrigin: string;\n' +
    '  rootOriginNote: string;\n' +
    '  relatedWords: { word: string; meaning: string; level: string }[];\n' +
    '  phonetic: string;\n' +
    '  frequency: string;\n' +
    '  example: string;\n' +
    '}\n\n' +
    'export const mockWords: IELTSWord[] = ' + JSON.stringify(words, null, 2) + ';';
  
  fs.writeFileSync('/home/fred/workspace/memoryworld-project/src/data/mockWords.ts', output);
  console.log('保存成功!');
}
