const fs = require('fs');

const data = fs.readFileSync('/home/fred/workspace/memoryworld-project/src/data/mockWords.ts', 'utf8');
const match = data.match(/export const mockWords: IELTSWord\[\] = \[([\s\S]*?)\];/);

if (match) {
  const words = JSON.parse('[' + match[1] + ']');
  
  const wordMap = {
    'alpha': 'n. 阿尔法；希腊字母表的第一个字母；开端',
    'alpine': 'adj. 阿尔卑斯山的；高山的；n. 高山植物',
    'alsatian': 'n. 阿尔萨斯人；阿尔萨斯犬',
    'altar': 'n. 祭坛；圣坛；祭坛画',
    'alumni': 'n. 校友；毕业生',
    'amalgam': 'n. 汞合金；混合物',
    'amanuensis': 'n. 抄写员；文书',
    'ambit': 'n. 范围；界限；领域',
    'ambush': 'n./v. 伏击；埋伏',
    'ameba': 'n. 变形虫；阿米巴',
    'amends': 'n. 赔偿；补偿',
    'amerce': 'v. 罚款；惩罚',
    'american': 'adj. 美国的；美洲的；n. 美国人',
    'amethyst': 'n. 紫水晶；紫色',
    'amiss': 'adj./adv. 错误的；有毛病',
    'ammo': 'n. 弹药；军火',
    'amnesia': 'n. 健忘症；记忆丧失',
    'amnesty': 'n. 大赦；特赦',
    'amortize': 'v. 分期偿还；摊销',
    'amosite': 'n. 铁石棉',
    'amour': 'n. 恋情；偷情',
    'ampere': 'n. 安培',
    'ampersand': 'n. &符号；和号',
    'amphibian': 'n. 两栖动物；adj. 两栖的',
    'amuck': 'adv. 疯狂地；狂暴地',
    'anaconda': 'n. 水蟒；森蚺',
    'anaemia': 'n. 贫血；贫血症',
    'analog': 'adj. 模拟的；n. 类似物',
    'analogy': 'n. 类比；比喻；相似',
    'anamnesis': 'n. 记忆；回忆',
    'anathema': 'n. 诅咒；令人憎恶的事物',
    'anchovy': 'n. 凤尾鱼',
    'and': 'conj. 和；与；并且',
    'andante': 'adj./adv. 行板的；缓慢地',
    'andesite': 'n. 安山岩',
    'android': 'n. 机器人；安卓',
    'anemone': 'n. 银莲花；海葵',
    'anergy': 'n. 无反应；无力',
    'angioma': 'n. 血管瘤',
    'angiosperm': 'n. 被子植物',
    'anglicize': 'v. 英国化；使英语化',
    'angst': 'n. 焦虑；恐惧',
    'angular': 'adj. 有角的；生硬的',
    'animadvert': 'v. 批评；指责',
    'animalcule': 'n. 微动物；微生物',
    'anime': 'n. 动漫；日本动画',
    'anion': 'n. 阴离子',
    'anklet': 'n. 脚镯；短袜',
    'annul': 'v. 废除；取消',
    'annular': 'adj. 环形的；环状的',
    'anode': 'n. 阳极；正极',
    'anoint': 'v. 涂油；任命',
    'anonymous': 'adj. 匿名的；无名的',
    'antagonist': 'n. 对手；敌手',
    'anteater': 'n. 食蚁兽',
    'antelope': 'n. 羚羊',
    'antenna': 'n. 天线；触角',
    'anthropology': 'n. 人类学',
    'antibiotic': 'n. 抗生素；adj. 抗菌的',
    'antidote': 'n. 解毒剂；解药',
    'antipathy': 'n. 反感；厌恶',
    'antiseptic': 'adj. 防腐的；n. 防腐剂',
    'antithesis': 'n. 对立面；对照',
    'antler': 'n. 鹿角',
    'ape': 'n. 猿；类人猿',
    'apartment': 'n. 公寓；房间',
    'aperture': 'n. 孔径；光圈',
    'apex': 'n. 顶点；顶峰',
    'aphasia': 'n. 失语症',
    'aphorism': 'n. 格言；警句',
    'apiary': 'n. 养蜂场',
    'apocalypse': 'n. 启示；末日',
    'apocryphal': 'adj. 伪经的；虚构的',
    'apogee': 'n. 远地点；最高点',
    'apparatus': 'n. 装置；设备',
    'apparition': 'n. 幽灵；幻影',
    'applause': 'n. 掌声；喝彩',
    'apprehensive': 'adj. 忧虑的；担心的',
    'apricot': 'n. 杏；杏树',
    'apron': 'n. 围裙；停机坪',
    'aquarium': 'n. 水族馆；鱼缸',
    'aquatic': 'adj. 水生的；水中的',
    'aqueduct': 'n. 渡槽；高架渠',
    'aquifer': 'n. 含水层',
    'arable': 'adj. 可耕种的',
    'arbiter': 'n. 仲裁者；裁决者',
    'arbitrary': 'adj. 任意的；专横的',
    'arboreal': 'adj. 树木的；树栖的',
    'arcade': 'n. 拱廊；商场',
    'archaeology': 'n. 考古学',
    'archbishop': 'n. 大主教',
    'archer': 'n. 弓箭手',
    'archipelago': 'n. 群岛',
    'architect': 'n. 建筑师',
    'archives': 'n. 档案；档案馆',
    'argot': 'n. 行话；黑话',
    'arid': 'adj. 干旱的；枯燥的',
    'armament': 'n. 军备；武器',
    'armature': 'n. 电枢；骨架',
    'armistice': 'n. 停战；休战',
    'aroma': 'n. 香气；香味',
    'arousal': 'n. 唤醒；兴奋',
    'arrhythmia': 'n. 心律失常',
    'arsenic': 'n. 砷；砒霜',
    'arson': 'n. 纵火；纵火罪',
    'artery': 'n. 动脉；干线',
    'artisan': 'n. 工匠；手艺人',
    'asbestos': 'n. 石棉',
    'ascetic': 'adj. 苦行的；n. 苦行者',
    'ascribe': 'v. 归因于；归咎于',
    'ashen': 'adj. 苍白的；灰色的',
    'ashore': 'adv. 在岸上；上岸',
    'askew': 'adj./adv. 歪斜的；歪斜地',
    'aspersion': 'n. 诽谤；中伤',
    'aspirant': 'n. 追求者；有抱负者',
    'aspirin': 'n. 阿司匹林',
    'asylum': 'n. 庇护；避难所',
    'atavism': 'n. 返祖现象',
    'atheism': 'n. 无神论',
    'atoll': 'n. 环礁',
    'atom': 'n. 原子',
    'atrophy': 'n./v. 萎缩；衰退',
    'attachment': 'n. 附件；依恋',
    'attire': 'n. 服装；衣着',
    'attorney': 'n. 律师；代理人',
    'attrition': 'n. 消耗；磨损',
    'auction': 'n./v. 拍卖',
    'audacity': 'n. 大胆；鲁莽',
    'audience': 'n. 观众；听众',
    'auditorium': 'n. 礼堂；听众席',
    'auger': 'n. 螺旋钻',
    'augment': 'v. 增加；扩大',
    'augur': 'v. 预言；预示',
    'austerity': 'n. 紧缩；简朴',
    'automaton': 'n. 自动机；机器人',
    'autograph': 'n. 亲笔签名',
    'autopsy': 'n. 验尸；尸检',
    'auxiliary': 'adj. 辅助的；n. 辅助人员',
    'avalanche': 'n./v. 雪崩',
    'avenge': 'v. 报仇；报复',
    'aver': 'v. 断言；宣称',
    'aversion': 'n. 厌恶；反感',
    'avocado': 'n. 牛油果；鳄梨',
    'avow': 'v. 承认；公开宣称',
    'axle': 'n. 轴；车轴',
    'azure': 'adj./n. 天蓝色的；天蓝色',
    'babe': 'n. 婴儿；宝贝',
    'baby': 'n. 婴儿；宝宝',
    'backbone': 'n. 脊柱；支柱',
    'backdrop': 'n. 背景；幕布',
    'backlog': 'n. 积压；待办事项',
    'badge': 'n. 徽章；标志',
    'baggage': 'n. 行李',
    'bail': 'n./v. 保释；保释金',
    'bailiff': 'n. 法警；执行官',
    'bamboo': 'n. 竹子',
    'banal': 'adj. 陈腐的；平庸的',
    'baneful': 'adj. 有害的；致命的',
    'banger': 'n. 香肠；鞭炮',
    'barb': 'n. 倒钩；讽刺',
    'barbarian': 'n. 野蛮人；adj. 野蛮的',
    'barefaced': 'adj. 公然的；无耻的',
    'barge': 'n. 驳船；v. 冲撞',
    'barnacle': 'n. 藤壶',
    'baroque': 'adj. 巴洛克风格的',
    'barrage': 'n. 弹幕；猛攻',
    'basement': 'n. 地下室',
    'basin': 'n. 盆地；脸盆',
    'basket': 'n. 篮子',
    'bastion': 'n. 堡垒；要塞',
    'battery': 'n. 电池；炮台',
    'battlefield': 'n. 战场',
    'bayonet': 'n. 刺刀',
    'beagle': 'n. 比格犬',
    'beak': 'n. 鸟嘴；喙',
    'beard': 'n. 胡须',
    'beast': 'n. 野兽；畜生',
    'belabor': 'v. 痛打；反复讨论',
    'belie': 'v. 掩饰；证明...虚假',
    'bellicose': 'adj. 好战的；好斗的',
    'bellows': 'n. 风箱',
    'belly': 'n. 腹部；胃',
    'benediction': 'n. 祝福；赐福',
    'beneficent': 'adj. 仁慈的；慈善的',
    'benign': 'adj. 良性的；和蔼的',
    'benzene': 'n. 苯',
    'berth': 'n. 泊位；卧铺',
    'beseech': 'v. 恳求；祈求',
    'beset': 'v. 困扰；包围',
    'besiege': 'v. 围攻；围困',
    'besmirch': 'v. 弄脏；诽谤',
    'bestial': 'adj. 野兽的；残忍的',
    'bestow': 'v. 授予；给予',
    'betrothal': 'n. 订婚；婚约',
    'beverage': 'n. 饮料',
    'bicycle': 'n. 自行车',
    'bibliography': 'n. 参考书目',
    'bicker': 'v. 争吵；斗嘴',
    'bigamy': 'n. 重婚',
    'bigot': 'n. 偏执者；顽固者',
    'billboard': 'n. 广告牌',
    'binnacle': 'n. 罗盘箱',
    'biographer': 'n. 传记作家',
    'biology': 'n. 生物学',
    'biped': 'n./adj. 两足动物；两足的',
    'birch': 'n. 桦树；桦木',
    'bishopric': 'n. 主教职位',
    'bitumen': 'n. 沥青',
    'bizarre': 'adj. 奇异的；古怪的',
    'blanch': 'v. 使变白；漂白',
    'blare': 'v. 发出刺耳的声音',
    'blasphemy': 'n. 亵渎；渎神',
    'blast': 'n./v. 爆炸；冲击',
    'blaze': 'n./v. 火焰；燃烧',
    'blemish': 'n./v. 瑕疵；玷污',
    'blight': 'n./v. 枯萎；破坏',
    'blimp': 'n. 软式飞艇',
    'blindfold': 'n. 眼罩；v. 蒙眼',
    'bliss': 'n. 极乐；幸福',
    'blotch': 'n. 斑点；污渍',
    'blouse': 'n. 女式衬衫',
    'bluff': 'n./v. 虚张声势；悬崖',
    'blunder': 'n./v. 错误；失误',
    'blunt': 'adj. 钝的；直率的',
    'blurb': 'n. 简介；短评',
    'blurt': 'v. 脱口而出',
    'blush': 'v./n. 脸红；羞愧',
    'bounty': 'n. 赏金；慷慨',
    'bourgeois': 'adj. 资产阶级的',
    'bowel': 'n. 肠；内部',
    'bracelet': 'n. 手镯',
    'bracket': 'n. 括号；支架',
    'braid': 'v./n. 编织；辫子',
    'brandish': 'v. 挥舞；炫耀',
    'brash': 'adj. 鲁莽的；无礼的',
    'brass': 'n. 黄铜',
    'bray': 'v. 叫；嘶叫',
    'breadth': 'n. 宽度；广度',
    'breakdown': 'n. 故障；崩溃',
    'breastbone': 'n. 胸骨',
    'breath': 'n. 呼吸；气息',
    'breeze': 'n./v. 微风；吹微风',
    'breech': 'n. 臀部；后膛',
    'bribe': 'n./v. 贿赂',
    'bridal': 'adj. 新娘的；婚礼的',
    'bridle': 'n. 马笼头；v. 控制',
    'briefcase': 'n. 公文包',
    'brigade': 'n. 旅；队',
    'brink': 'n. 边缘；边界',
    'brisk': 'adj. 轻快的；活泼的',
    'broach': 'v. 提出；开启',
    'broccoli': 'n. 西兰花',
    'brochure': 'n. 小册子',
    'broil': 'v. 烤；争吵',
    'brood': 'n. 一窝；v. 沉思',
    'brook': 'n. 小溪；v. 容忍',
    'broomstick': 'n. 扫帚柄',
    'brotherhood': 'n. 兄弟情谊；兄弟会',
    'brunt': 'n. 冲击；首当其冲',
    'brute': 'adj. 残忍的；n. 畜生',
    'bubonic': 'adj. 淋巴腺的',
    'buffer': 'n. 缓冲；缓冲区',
    'bugle': 'n. 号角；军号',
    'bulge': 'n./v. 膨胀；凸起',
    'bulwark': 'n. 堡垒；防御',
    'bumper': 'n. 保险杠；adj. 丰盛的',
    'bungalow': 'n. 平房',
    'bureaucracy': 'n. 官僚主义',
    'burglar': 'n. 窃贼',
    'burgeon': 'v. 发芽；迅速增长',
    'burial': 'n. 埋葬；葬礼',
    'burrow': 'n./v. 洞穴；挖洞',
    'bush': 'n. 灌木；灌木丛',
    'butcher': 'n. 屠夫；v. 屠杀',
    'buttress': 'n. 扶壁；v. 支持',
    'buzzard': 'n. 秃鹫',
    'cabin': 'n. 小屋；船舱',
    'cable': 'n. 电缆；电报',
    'cacao': 'n. 可可；可可树',
    'cadence': 'n. 节奏；韵律',
    'caffeine': 'n. 咖啡因',
    'calamity': 'n. 灾难；灾祸',
    'calcium': 'n. 钙',
    'caliber': 'n. 口径；品质',
    'calico': 'n. 印花布',
    'callous': 'adj. 无情的；硬结的',
    'calm': 'adj./v. 平静的；使平静',
    'calorie': 'n. 卡路里',
    'cameo': 'n. 浮雕宝石；客串',
    'camel': 'n. 骆驼',
    'camouflage': 'n./v. 伪装',
    'campaign': 'n./v. 运动；战役',
    'canal': 'n. 运河；沟渠',
    'canary': 'n. 金丝雀',
    'candid': 'adj. 坦率的；直言不讳的',
    'cannon': 'n. 大炮；加农炮',
    'canopy': 'n. 天篷；华盖',
    'canvas': 'n. 帆布；画布',
    'capillary': 'n. 毛细血管',
    'capitalism': 'n. 资本主义',
    'caprice': 'n. 反复无常；任性',
    'captain': 'n. 船长；队长',
    'caption': 'n. 标题；说明',
    'captious': 'adj. 吹毛求疵的',
    'carat': 'n. 克拉',
    'caravan': 'n. 大篷车；商队',
    'carbohydrate': 'n. 碳水化合物',
    'carcass': 'n. 尸体；残骸',
    'cardboard': 'n. 纸板',
    'cardinal': 'adj. 主要的；n. 红衣主教',
    'careen': 'v. 倾斜；猛冲',
    'cargo': 'n. 货物',
    'caricature': 'n. 漫画；讽刺画',
    'carillon': 'n. 钟琴',
    'carnal': 'adj. 肉体的；肉欲的',
    'carnation': 'n. 康乃馨',
    'carnival': 'n. 狂欢节',
    'carpenter': 'n. 木匠',
    'carriage': 'n. 马车；车厢',
    'carrot': 'n. 胡萝卜',
    'cart': 'n. 马车；手推车',
    'cartel': 'n. 卡特尔；垄断组织',
    'carve': 'v. 雕刻；切开',
    'cascade': 'n./v. 瀑布；倾泻',
    'cashier': 'n. 出纳员',
    'cassette': 'n. 盒式磁带',
    'castigate': 'v. 严惩；苛责',
    'casualty': 'n. 伤亡人员',
    'catacomb': 'n. 地下墓穴',
    'catastrophe': 'n. 灾难；大祸',
    'catalyst': 'n. 催化剂',
    'cataract': 'n. 白内障；瀑布',
    'cathedral': 'n. 大教堂',
    'caustic': 'adj. 腐蚀性的；刻薄的',
    'cavalcade': 'n. 骑兵队；车队',
    'caveat': 'n. 警告；注意事项',
    'cedar': 'n. 雪松',
    'celery': 'n. 芹菜',
    'celestial': 'adj. 天上的；神圣的',
    'cellar': 'n. 地窖；地下室',
    'censor': 'n./v. 审查；审查员',
    'censure': 'n./v. 谴责；批评',
    'centaur': 'n. 半人马',
    'centennial': 'adj./n. 百年的；百年纪念',
    'centipede': 'n. 蜈蚣',
    'ceramic': 'adj. 陶瓷的；n. 陶瓷',
    'cereal': 'n. 谷物；麦片',
    'ceremony': 'n. 仪式；典礼',
    'cessation': 'n. 停止；中断',
    'chaff': 'n. 谷壳；v. 取笑',
    'chagrin': 'n. 懊恼；失望',
    'champion': 'n. 冠军；v. 支持',
    'chandelier': 'n. 枝形吊灯',
    'chant': 'v./n. 吟唱；圣歌',
    'chaos': 'n. 混乱；混沌',
    'chasm': 'n. 深渊；鸿沟',
    'chauvinism': 'n. 沙文主义',
    'chestnut': 'n. 栗子；栗树',
    'chicken': 'n. 鸡；鸡肉',
    'chiffon': 'n. 雪纺；薄纱',
    'chimpanzee': 'n. 黑猩猩',
    'chisel': 'n. 凿子；v. 凿',
    'chivalry': 'n. 骑士精神；骑士制度',
    'chlorine': 'n. 氯',
    'chocolate': 'n. 巧克力',
    'chord': 'n. 和弦；弦',
    'choreography': 'n. 编舞；舞蹈设计',
    'chortle': 'v./n. 哈哈大笑',
    'christen': 'v. 洗礼；命名',
    'chromosome': 'n. 染色体',
    'chronicle': 'n. 编年史；v. 记录',
    'chrysanthemum': 'n. 菊花',
    'chum': 'n. 好友；室友',
    'cipher': 'n. 密码；暗号',
    'circa': 'prep. 大约',
    'circadian': 'adj. 昼夜节律的',
    'circumference': 'n. 周长；圆周',
    'circumspect': 'adj. 谨慎的；周到的',
    'clam': 'n. 蛤蜊',
    'clamor': 'n./v. 喧闹；大声要求',
    'clamp': 'n./v. 夹具；夹紧',
    'clandestine': 'adj. 秘密的；暗中的',
    'clarion': 'adj. 清晰响亮的',
    'clash': 'v./n. 冲突；碰撞',
    'clasp': 'v./n. 扣紧；紧握',
    'claustrophobia': 'n. 幽闭恐惧症',
    'clay': 'n. 粘土',
    'cleanse': 'v. 清洁；净化',
    'cleaver': 'n. 切肉刀',
    'cleave': 'v. 劈开；粘附',
    'clench': 'v. 握紧；咬紧',
    'clerk': 'n. 职员；店员',
    'climax': 'n. 高潮；顶点',
    'clinch': 'v. 敲定；扭打',
    'cloak': 'n. 斗篷；v. 掩盖',
    'clockwork': 'n. 发条装置',
    'clog': 'v. 堵塞；n. 木屐',
    'clone': 'n./v. 克隆',
    'clot': 'n./v. 凝块；凝结',
    'cloudburst': 'n. 暴雨',
    'clout': 'n. 影响力；v. 猛击',
    'clove': 'n. 丁香；一瓣',
    'clown': 'n. 小丑；v. 扮小丑',
    'cloy': 'v. 使腻烦；使过饱',
    'clutch': 'v./n. 抓住；离合器',
    'coal': 'n. 煤；煤炭',
    'coalition': 'n. 联盟；联合',
    'coarse': 'adj. 粗糙的；粗劣的',
    'coax': 'v. 哄骗；劝诱',
    'coerce': 'v. 强迫；胁迫',
    'cogent': 'adj. 有说服力的；令人信服的',
    'cognac': 'n. 干邑白兰地',
    'cognate': 'adj. 同源的；n. 同源词',
    'cohabit': 'v. 同居',
    'cohere': 'v. 凝聚；连贯',
    'coiffure': 'n. 发型',
    'coil': 'v./n. 盘绕；线圈',
    'coincide': 'v. 同时发生；重合',
    'colander': 'n. 滤器；漏勺',
    'collaborate': 'v. 合作；协作',
    'collage': 'n. 拼贴画',
    'collar': 'n. 衣领；项圈',
    'colleague': 'n. 同事',
    'collide': 'v. 碰撞；冲突',
    'colloquium': 'n. 学术讨论会',
    'colony': 'n. 殖民地；群体',
    'colossal': 'adj. 巨大的；庞大的',
    'combat': 'n./v. 战斗；搏斗',
    'comet': 'n. 彗星',
    'comic': 'adj. 喜剧的；n. 漫画',
    'comity': 'n. 礼让；友好',
    'commemorate': 'v. 纪念；庆祝',
    'commence': 'v. 开始；着手',
    'commend': 'v. 称赞；推荐',
    'commode': 'n. 洗脸台；便桶',
    'commodity': 'n. 商品；货物',
    'commonplace': 'adj. 平凡的；n. 老生常谈',
    'commotion': 'n. 骚动；混乱',
    'communal': 'adj. 公共的；社区的',
    'compact': 'adj. 紧凑的；n. 契约',
    'companion': 'n. 同伴；伴侣',
    'compatible': 'adj. 兼容的；相容的',
    'compel': 'v. 强迫；迫使',
    'compendium': 'n. 纲要；概要',
    'compensate': 'v. 补偿；赔偿',
    'compile': 'v. 编译；汇编',
    'complacent': 'adj. 自满的；得意的',
    'complement': 'n./v. 补充；补足',
    'complete': 'adj. 完整的；v. 完成',
    'complexion': 'n. 肤色；面色',
    'complicate': 'v. 使复杂；使陷入',
    'compliment': 'n./v. 赞美；恭维',
    'comply': 'v. 遵守；服从',
    'comport': 'v. 举止；表现',
    'compound': 'n. 化合物；v. 混合',
    'comprehend': 'v. 理解；包含',
    'comprehensive': 'adj. 全面的；综合的',
    'compromise': 'n./v. 妥协；折中',
    'compulsion': 'n. 强迫；冲动',
    'compulsive': 'adj. 强迫的；上瘾的',
    'compulsory': 'adj. 强制的；必修的',
    'compute': 'v. 计算；估算',
    'comrade': 'n. 同志；伙伴',
    'concave': 'adj. 凹的；n. 凹面',
    'conceal': 'v. 隐藏；隐瞒',
    'concede': 'v. 承认；让步',
    'conceive': 'v. 构想；怀孕',
    'concert': 'n. 音乐会；和谐',
    'conclude': 'v. 结束；断定',
    'concoct': 'v. 调制；编造',
    'concord': 'n. 和谐；一致',
    'condemn': 'v. 谴责；判刑',
    'condense': 'v. 浓缩；压缩',
    'condone': 'v. 宽恕；赦免',
    'conduit': 'n. 管道；导管',
    'cone': 'n. 圆锥；锥体',
    'confederate': 'adj. 同盟的；n. 同盟者',
    'confidant': 'n. 知己；心腹',
    'confine': 'v. 限制；监禁',
    'confirm': 'v. 确认；证实',
    'confiscate': 'v. 没收；充公',
    'conflate': 'v. 合并；混合',
    'confound': 'v. 混淆；使困惑',
    'confront': 'v. 面对；对抗',
    'confuse': 'v. 使困惑；混淆',
    'congeal': 'v. 凝结；凝固',
    'congenial': 'adj. 意气相投的；宜人的',
    'congest': 'v. 使拥挤；使充血',
    'conglomerate': 'n. 企业集团；adj. 聚集的',
    'congregate': 'v. 聚集；集合',
    'conjecture': 'n./v. 推测；猜测',
    'conjoin': 'v. 连接；结合',
    'conjugal': 'adj. 婚姻的；夫妻的',
    'conjure': 'v. 召唤；变魔术',
    'conk': 'n./v. 敲；重击',
    'connect': 'v. 连接；联系',
    'connote': 'v. 暗示；意味着',
    'conquer': 'v. 征服；战胜',
    'conscience': 'n. 良心；良知',
    'conscientious': 'adj. 认真的；尽责的',
    'conscript': 'n. 应征士兵；v. 征召',
    'consecrate': 'v. 奉献；使神圣',
    'consent': 'n./v. 同意；赞成',
    'consequence': 'n. 结果；后果',
    'conservatory': 'n. 温室；音乐学院',
    'conserve': 'v. 保存；保护',
    'consider': 'v. 考虑；认为',
    'consign': 'v. 交付；委托',
    'consist': 'v. 由...组成；一致',
    'console': 'v. 安慰；n. 控制台',
    'consolidate': 'v. 巩固；合并',
    'conspicuous': 'adj. 显眼的；显著的',
    'conspiracy': 'n. 阴谋；共谋',
    'constable': 'n. 警察；治安官',
    'constancy': 'n. 恒定；忠诚',
    'constellation': 'n. 星座',
    'constrict': 'v. 收缩；限制',
    'construct': 'v. 建造；构建',
    'consume': 'v. 消耗；消费',
    'contagion': 'n. 传染病；蔓延',
    'contain': 'v. 包含；容纳',
    'contemplate': 'v. 思考；凝视',
    'contend': 'v. 竞争；主张',
    'content': 'adj. 满足的；n. 内容',
    'contest': 'n./v. 比赛；竞争',
    'context': 'n. 上下文；语境',
    'contiguous': 'adj. 相邻的；接壤的',
    'contort': 'v. 扭曲；变形',
    'contraband': 'n. 违禁品；走私货',
    'contract': 'n. 合同；v. 收缩',
    'contradict': 'v. 反驳；矛盾',
    'contrary': 'adj. 相反的；n. 对立面',
    'contrast': 'n./v. 对比；对照',
    'contrive': 'v. 发明；策划',
    'control': 'n./v. 控制；管理',
    'controversy': 'n. 争议；争论',
    'convalesce': 'v. 康复；休养',
    'convention': 'n. 惯例；会议',
    'converge': 'v. 汇聚；收敛',
    'converse': 'v. 交谈；n. 相反',
    'convert': 'v. 转换；改变信仰',
    'convey': 'v. 传达；运输',
    'convict': 'v. 定罪；n. 罪犯',
    'conviction': 'n. 定罪；信念',
    'convince': 'v. 说服；使确信',
    'cookery': 'n. 烹饪；烹调术',
    'cooper': 'n. 制桶匠',
    'cooperate': 'v. 合作；协作',
    'coordinate': 'v. 协调；n. 坐标',
    'copious': 'adj. 丰富的；大量的',
    'copper': 'n. 铜',
    'copy': 'n./v. 复制；副本',
    'coral': 'n. 珊瑚；珊瑚色',
    'cord': 'n. 绳索；线',
    'cordial': 'adj. 热情的；亲切的',
    'core': 'n. 核心；中心',
    'cork': 'n. 软木；瓶塞',
    'coroner': 'n. 验尸官',
    'corporate': 'adj. 公司的；法人的',
    'corps': 'n. 军团',
    'corpse': 'n. 尸体',
    'corral': 'n./v. 畜栏；圈住',
    'correct': 'adj. 正确的；v. 纠正',
    'correlate': 'v. 关联；相关',
    'correspond': 'v. 通信；对应',
    'corrode': 'v. 腐蚀；侵蚀',
    'corrupt': 'adj. 腐败的；v. 腐蚀',
    'corset': 'n. 紧身胸衣',
    'cortex': 'n. 皮质；皮层',
    'cosmic': 'adj. 宇宙的',
    'cosmos': 'n. 宇宙',
    'costume': 'n. 服装；戏服',
    'cottage': 'n. 小屋；村舍',
    'cotton': 'n. 棉花；adj. 棉的',
    'couch': 'n. 沙发；v. 表达',
    'cougar': 'n. 美洲狮',
    'council': 'n. 委员会；理事会',
    'counsel': 'n. 建议；v. 劝告',
    'countenance': 'n. 面容；表情',
    'counterfeit': 'adj./n. 伪造的；伪造品',
    'couple': 'n. 夫妻；一对',
    'courage': 'n. 勇气；胆量',
    'courteous': 'adj. 有礼貌的；谦恭的',
    'courtesy': 'n. 礼貌；好意',
    'court': 'n. 法院；宫廷',
    'covet': 'v. 贪图；觊觎',
    'coward': 'n. 懦夫；胆小鬼',
    'cower': 'v. 畏缩；退缩',
    'coyote': 'n. 郊狼；丛林狼',
    'crab': 'n. 螃蟹',
    'crack': 'v./n. 破裂；裂缝',
    'craft': 'n. 工艺；手艺',
    'cram': 'v. 塞满；死记硬背',
    'crane': 'n. 起重机；鹤',
    'crash': 'v./n. 碰撞；崩溃',
    'crave': 'v. 渴望；恳求',
    'crawl': 'v./n. 爬行；缓慢移动',
    'craze': 'n. 狂热；风尚',
    'crazy': 'adj. 疯狂的；荒唐的',
    'creak': 'v./n. 嘎吱声',
    'cream': 'n. 奶油；面霜',
    'creep': 'v./n. 爬行；悄悄移动',
    'crevice': 'n. 裂缝；缺口',
    'crimson': 'adj. 深红色的；n. 深红色',
    'crinkle': 'v./n. 起皱；皱纹',
    'cripple': 'n. 跛子；v. 使残疾',
    'crisis': 'n. 危机；紧要关头',
    'criterion': 'n. 标准；准则',
    'critic': 'n. 批评家；评论家',
    'croak': 'v. 呱呱叫；嘶哑地说',
    'crochet': 'v./n. 钩针编织',
    'croon': 'v. 低声吟唱；哼唱',
    'crossbow': 'n. 弩',
    'crown': 'n. 王冠；v. 加冕',
    'crucial': 'adj. 关键的；至关重要的',
    'crucify': 'v. 钉十字架；折磨',
    'crude': 'adj. 粗糙的；原油的',
    'cruel': 'adj. 残忍的；残酷的',
    'cruise': 'v./n. 巡航；巡游',
    'crumb': 'n. 面包屑；碎屑',
    'crush': 'v./n. 压碎；迷恋',
    'crust': 'n. 外壳；地壳',
    'crystal': 'n. 水晶；晶体',
    'cubic': 'adj. 立方的；立方体的',
    'cuisine': 'n. 烹饪；菜肴',
    'culminate': 'v. 达到顶点；告终',
    'cultivate': 'v. 培养；耕作',
    'cultured': 'adj. 有教养的；培养的',
    'cumbersome': 'adj. 笨重的；麻烦的',
    'cumulative': 'adj. 累积的；渐增的',
    'curator': 'n. 馆长；管理者',
    'curious': 'adj. 好奇的；奇特的',
    'curriculum': 'n. 课程；课程表',
    'curse': 'n./v. 诅咒；咒骂',
    'curtain': 'n. 窗帘；幕布',
    'curve': 'n./v. 曲线；弯曲',
    'cushion': 'n. 垫子；缓冲',
    'custom': 'n. 习惯；风俗',
    'cute': 'adj. 可爱的；漂亮的',
    'cycle': 'n./v. 循环；周期',
    'cylinder': 'n. 圆柱；气缸',
    'cynic': 'n. 愤世嫉俗者',
    'cynical': 'adj. 愤世嫉俗的',
    'dagger': 'n. 匕首；短剑',
    'dainty': 'adj. 精致的；优雅的',
    'daisy': 'n. 雏菊',
    'dam': 'n. 水坝；v. 筑坝',
    'damp': 'adj. 潮湿的；v. 使潮湿',
    'dandelion': 'n. 蒲公英',
    'dangle': 'v. 悬挂；摇晃',
    'dapper': 'adj. 整洁的；潇洒的',
    'dare': 'v. 敢；挑战',
    'dart': 'n./v. 飞镖；投掷',
    'dash': 'v./n. 猛冲；破折号',
    'daunt': 'v. 使气馁；使畏缩',
    'dawdle': 'v. 闲逛；拖延',
    'dawn': 'n./v. 黎明；破晓',
    'daylight': 'n. 日光；白昼',
    'deadlock': 'n. 僵局；死锁',
    'dealer': 'n. 经销商；商人',
    'debut': 'n./v. 初次登场；首次亮相',
    'decease': 'n. 死亡',
    'deceit': 'n. 欺骗；谎言',
    'deceive': 'v. 欺骗；误导',
    'decent': 'adj. 体面的；得体的',
    'decimal': 'adj. 十进制的；n. 小数',
    'decipher': 'v. 破译；解读',
    'deck': 'n. 甲板；v. 装饰',
    'decline': 'v./n. 下降；拒绝',
    'decode': 'v. 解码；破译',
    'decompose': 'v. 分解；腐烂',
    'decorate': 'v. 装饰；装修',
    'decorum': 'n. 礼仪；得体',
    'decree': 'n./v. 法令；颁布',
    'dedicated': 'adj. 专注的；专用的',
    'deduce': 'v. 推断；演绎',
    'deduct': 'v. 扣除；减去',
    'deface': 'v. 损毁；弄脏',
    'defendant': 'n. 被告',
    'defect': 'n. 缺陷；v. 背叛',
    'defend': 'v. 防御；辩护',
    'defiance': 'n. 违抗；蔑视',
    'deficiency': 'n. 缺乏；不足',
    'deficient': 'adj. 缺乏的；不足的',
    'definite': 'adj. 明确的；确定的',
    'deflate': 'v. 放气；使泄气',
    'deflect': 'v. 偏转；偏离',
    'deform': 'v. 使变形；使畸形',
    'defraud': 'v. 欺诈；诈骗',
    'defy': 'v. 违抗；蔑视',
    'degenerate': 'v. 退化；堕落',
    'dehydrate': 'v. 脱水；使干燥',
    'deign': 'v. 屈尊；俯就',
    'delegate': 'n. 代表；v. 委托',
    'deliberate': 'adj. 故意的；v. 深思熟虑',
    'delicate': 'adj. 精致的；脆弱的',
    'deliver': 'v. 交付；发表',
    'deluge': 'n./v. 洪水； deluge',
    'delve': 'v. 钻研；深入研究',
    'demagogue': 'n. 煽动家',
    'demand': 'n./v. 要求；需求',
    'demise': 'n. 死亡；终止',
    'democracy': 'n. 民主；民主国家',
    'democratic': 'adj. 民主的；民主党的',
    'demographic': 'adj. 人口统计的',
    'demonstrate': 'v. 证明；演示',
    'denigrate': 'v. 诋毁；贬低',
    'denote': 'v. 表示；意味着',
    'denounce': 'v. 谴责；告发',
    'dense': 'adj. 密集的；浓厚的',
    'density': 'n. 密度；浓度',
    'dent': 'n./v. 凹痕；凹陷',
    'deny': 'v. 否认；拒绝',
    'depart': 'v. 离开；出发',
    'depend': 'v. 依赖；依靠',
    'dependent': 'adj. 依赖的；依靠的',
    'depict': 'v. 描绘；描述',
    'deplete': 'v. 耗尽；减少',
    'deploy': 'v. 部署；展开',
    'deposit': 'n./v. 存款；存放',
    'depress': 'v. 压抑；使沮丧',
    'deprive': 'v. 剥夺；使丧失',
    'derive': 'v. 源于；获得',
    'descend': 'v. 下降；降临',
    'describe': 'v. 描述；形容',
    'desert': 'n. 沙漠；v. 抛弃',
    'deserve': 'v. 值得；应得',
    'design': 'n./v. 设计；图案',
    'designate': 'v. 指定；任命',
    'desolate': 'adj. 荒凉的；v. 使荒芜',
    'despair': 'n./v. 绝望；丧失信心',
    'desperate': 'adj. 绝望的；不顾一切的',
    'despicable': 'adj. 可鄙的；卑鄙的',
    'despite': 'prep. 尽管；不管',
    'dessert': 'n. 甜点；甜食',
    'destine': 'v. 注定；命定',
    'destroy': 'v. 破坏；摧毁',
    'detach': 'v. 分离；拆卸',
    'detail': 'n./v. 细节；详述',
    'detect': 'v. 检测；发现',
    'deter': 'v. 阻止；威慑',
    'determine': 'v. 决定；确定',
    'detour': 'n./v. 绕道；迂回',
    'detract': 'v. 减损；贬低',
    'detriment': 'n. 损害；伤害',
    'develop': 'v. 发展；开发',
    'deviate': 'v. 偏离；背离',
    'device': 'n. 设备；装置',
    'devise': 'v. 设计；发明',
    'devote': 'v. 奉献；致力于',
    'dew': 'n. 露水',
    'dexterity': 'n. 灵巧；敏捷',
    'diabetes': 'n. 糖尿病',
    'diagram': 'n. 图表；示意图',
    'dial': 'n. 刻度盘；v. 拨号',
    'dialect': 'n. 方言；土语',
    'diameter': 'n. 直径',
    'dictate': 'v. 口述；命令',
    'dictator': 'n. 独裁者',
    'diction': 'n. 措辞；发音',
    'dictum': 'n. 格言；声明',
    'die': 'v. 死亡；凋谢',
    'diet': 'n. 饮食；节食',
    'differ': 'v. 不同；相异',
    'diffuse': 'v. 扩散；传播',
    'digest': 'v. 消化；n. 摘要',
    'dignify': 'v. 使高贵；使有尊严',
    'dilemma': 'n. 困境；两难',
    'diligent': 'adj. 勤奋的；刻苦的',
    'dilute': 'v. 稀释；冲淡',
    'dim': 'adj. 昏暗的；v. 使暗淡',
    'dimension': 'n. 维度；尺寸',
    'diminish': 'v. 减少；降低',
    'dine': 'v. 进餐；用餐',
    'dinosaur': 'n. 恐龙',
    'dioxide': 'n. 二氧化物',
    'dip': 'v./n. 蘸；浸泡',
    'direct': 'adj. 直接的；v. 指导',
    'dirt': 'n. 泥土；污垢',
    'disagree': 'v. 不同意；不一致',
    'disappear': 'v. 消失；失踪',
    'disappoint': 'v. 使失望；使沮丧',
    'disapprove': 'v. 不赞成；反对',
    'disarm': 'v. 解除武装；裁军',
    'disarray': 'n. 混乱；紊乱',
    'disaster': 'n. 灾难；灾害',
    'disavow': 'v. 否认；拒绝承认',
    'disband': 'v. 解散；解体',
    'discard': 'v. 丢弃；抛弃',
    'discern': 'v. 辨别；识别',
    'discharge': 'v./n. 放电；释放',
    'discipline': 'n./v. 纪律；训练',
    'disclaim': 'v. 否认；放弃',
    'disclose': 'v. 揭露；透露',
    'discomfort': 'n. 不适；不安',
    'disconnect': 'v. 断开连接；分离',
    'discover': 'v. 发现；发觉',
    'discredit': 'v. 使丧失信誉；诋毁',
    'discreet': 'adj. 谨慎的；慎重的',
    'discrepancy': 'n. 差异；不符',
    'discriminate': 'v. 歧视；区分',
    'discuss': 'v. 讨论；商议',
    'disease': 'n. 疾病；病害',
    'disembark': 'v. 下船；登陆',
    'disengage': 'v. 脱离；解除',
    'disgorge': 'v. 吐出；倾泻',
    'disgrace': 'n./v. 耻辱；使蒙羞',
    'disguise': 'n./v. 伪装；掩饰',
    'disgust': 'n./v. 厌恶；反感',
    'dish': 'n. 盘子；菜肴',
    'dishonest': 'adj. 不诚实的；欺诈的',
    'disillusion': 'v. 使醒悟；使幻灭',
    'disinfect': 'v. 消毒；杀菌',
    'disintegrate': 'v. 瓦解；分裂',
    'disinter': 'v. 挖掘；发掘',
    'disjoin': 'v. 分开；分离',
    'dislocate': 'v. 脱位；移位',
    'dislodge': 'v. 驱逐；移走',
    'dismal': 'adj. 凄凉的；阴沉的',
    'dismantle': 'v. 拆除；拆卸',
    'dismiss': 'v. 解雇；解散',
    'disobey': 'v. 不服从；违抗',
    'disorder': 'n. 混乱；无序',
    'disparate': 'adj. 不同的；不相称的',
    'dispense': 'v. 分配；分发',
    'disperse': 'v. 分散；散开',
    'displace': 'v. 取代；置换',
    'display': 'n./v. 显示；展示',
    'displease': 'v. 使不高兴；冒犯',
    'disposal': 'n. 处置；处理',
    'dispose': 'v. 处理；布置',
    'dispute': 'n./v. 争论；争议',
    'disqualify': 'v. 取消资格；使不合格',
    'disregard': 'v./n. 忽视；不理会',
    'disrupt': 'v. 破坏；扰乱',
    'disseminate': 'v. 传播；散布',
    'dissent': 'n./v. 异议；不同意',
    'dissertation': 'n. 论文；博士论文',
    'dissolve': 'v. 溶解；解散',
    'distance': 'n. 距离；远处',
    'distinguish': 'v. 区分；辨别',
    'distort': 'v. 扭曲；歪曲',
    'distract': 'v. 分散注意力；使分心',
    'distress': 'n./v. 痛苦；使痛苦',
    'distribute': 'v. 分发；分配',
    'distrust': 'n./v. 不信任；怀疑',
    'disturb': 'v. 打扰；扰乱',
    'ditch': 'n. 沟；壕沟',
    'dive': 'v./n. 潜水；跳水',
    'diverge': 'v. 分歧；分叉',
    'diverse': 'adj. 多样的；不同的',
    'diversify': 'v. 多样化；多元化',
    'divest': 'v. 剥夺；放弃',
    'divide': 'v. 划分；分开',
    'divine': 'adj. 神圣的；v. 占卜',
    'divorce': 'n./v. 离婚；分离',
    'dizzy': 'adj. 头晕的；眩晕的',
    'dock': 'n. 码头；船坞',
    'doctor': 'n. 医生；博士',
    'document': 'n. 文件；v. 记录',
    'dogma': 'n. 教条；信条',
    'dole': 'n. 救济金；v. 发放',
    'dolphin': 'n. 海豚',
    'domain': 'n. 领域；域名',
    'domestic': 'adj. 国内的；家庭的',
    'dominant': 'adj. 占主导的；统治的',
    'dominate': 'v. 支配；控制',
    'donate': 'v. 捐赠；捐献',
    'doom': 'n./v. 厄运；注定',
    'door': 'n. 门；入口',
    'dormant': 'adj. 休眠的；静止的',
    'dose': 'n. 剂量；一剂',
    'dot': 'n./v. 点；打点',
    'double': 'adj. 双重的；v. 加倍',
    'doubt': 'n./v. 怀疑；疑问',
    'dough': 'n. 面团；钱',
    'dove': 'n. 鸽子',
    'dowry': 'n. 嫁妆',
    'draft': 'n./v. 草稿；起草',
    'dragon': 'n. 龙',
    'drama': 'n. 戏剧；戏剧艺术',
    'drastic': 'adj. 激烈的；急剧的',
    'draw': 'v./n. 画；拉',
    'dread': 'n./v. 恐惧；害怕',
    'dream': 'n./v. 梦；梦想',
    'dress': 'n./v. 衣服；穿衣服',
    'drift': 'v./n. 漂流；漂移',
    'drill': 'n./v. 钻头；钻孔',
    'drink': 'v./n. 喝；饮料',
    'drip': 'v./n. 滴；水滴',
    'drive': 'v./n. 驾驶；驱动',
    'drop': 'v./n. 落下；滴',
    'drown': 'v. 淹死；淹没',
    'drug': 'n. 药物；v. 用药',
    'dry': 'adj. 干的；v. 使干燥',
    'dual': 'adj. 双重的；二元的',
    'dub': 'v. 配音；授予称号',
    'dubious': 'adj. 可疑的；不确定的',
    'duck': 'n. 鸭子；v. 躲避',
    'due': 'adj. 应有的；到期的',
    'dull': 'adj. 迟钝的；无聊的',
    'dump': 'v./n. 倾倒；垃圾场',
    'durable': 'adj. 耐用的；持久的',
    'duration': 'n. 持续时间；期间',
    'dusk': 'n. 黄昏；薄暮',
    'dust': 'n./v. 灰尘；打扫',
    'duty': 'n. 责任；义务',
    'dwarf': 'n. 矮人；v. 使矮小',
    'dwell': 'v. 居住；停留',
    'dwindle': 'v. 减少；缩小',
    'dye': 'n./v. 染料；染色',
    'eagle': 'n. 鹰',
    'earl': 'n. 伯爵',
    'earnest': 'adj. 认真的；诚挚的',
    'earthquake': 'n. 地震',
    'ease': 'n./v. 轻松；减轻',
    'ebb': 'v./n. 退潮；衰退',
    'echo': 'n./v. 回声；回响',
    'eclipse': 'n./v. 日食；黯然失色',
    'ecology': 'n. 生态学',
    'economic': 'adj. 经济的；经济学的',
    'edge': 'n./v. 边缘；移动',
    'edible': 'adj. 可食用的',
    'editor': 'n. 编辑；编者',
    'elaborate': 'adj. 精心的；v. 详细说明',
    'elapse': 'v. 流逝；过去',
    'elastic': 'adj. 有弹性的；n. 松紧带',
    'elbow': 'n. 肘部；v. 用肘推',
    'elder': 'adj. 年长的；n. 长辈',
    'elect': 'v. 选举；选择',
    'elegant': 'adj. 优雅的；高雅的',
    'element': 'n. 元素；要素',
    'elephant': 'n. 大象',
    'elevate': 'v. 提升；抬高',
    'elicit': 'v. 引出；诱出',
    'eligible': 'adj. 有资格的；合适的',
    'elite': 'n. 精英；精华',
    'eloquent': 'adj. 雄辩的；有说服力的',
    'else': 'adv. 否则；其他',
    'embark': 'v. 上船；开始',
    'embarrass': 'v. 使尴尬；使难堪',
    'embassy': 'n. 大使馆',
    'embed': 'v. 嵌入；植入',
    'embody': 'v. 体现；包含',
    'embrace': 'v./n. 拥抱；接受',
    'embroider': 'v. 刺绣；点缀',
    'emerge': 'v. 出现；浮现',
    'emission': 'n. 排放；发射',
    'emit': 'v. 发出；排放',
    'emotion': 'n. 情感；情绪',
    'emperor': 'n. 皇帝',
    'emphasis': 'n. 强调；重点',
    'empirical': 'adj. 经验的；实证的',
    'employ': 'v. 雇佣；使用',
    'empower': 'v. 授权；使能够',
    'empty': 'adj. 空的；v. 倒空',
    'enable': 'v. 使能够；使成为可能',
    'enact': 'v. 制定；颁布',
    'enamel': 'n. 珐琅；搪瓷',
    'encapsulate': 'v. 封装；概括',
    'enchant': 'v. 使着迷；施魔法',
    'encircle': 'v. 环绕；包围',
    'enclose': 'v. 包围；附上',
    'encompass': 'v. 包含；包围',
    'encounter': 'n./v. 遭遇；遇见',
    'encourage': 'v. 鼓励；激励',
    'endanger': 'v. 危及；危害',
    'endeavor': 'n./v. 努力；尝试',
    'ending': 'n. 结尾；结局',
    'endow': 'v. 赋予；捐赠',
    'endure': 'v. 忍受；持续',
    'enemy': 'n. 敌人；对手',
    'energetic': 'adj. 精力充沛的；积极的',
    'energy': 'n. 能量；精力',
    'enforce': 'v. 强制执行；实施',
    'engage': 'v. 参与；从事',
    'engine': 'n. 发动机；引擎',
    'engineer': 'n. 工程师；v. 设计',
    'english': 'adj. 英国的；n. 英语',
    'enhance': 'v. 增强；提高',
    'enjoy': 'v. 享受；喜欢',
    'enlarge': 'v. 扩大；放大',
    'enlighten': 'v. 启发；开导',
    'enlist': 'v. 入伍；招募',
    'enormous': 'adj. 巨大的；庞大的',
    'enough': 'adj./adv. 足够的；足够',
    'enquire': 'v. 询问；调查',
    'enrage': 'v. 激怒；使愤怒',
    'enrich': 'v. 丰富；使富裕',
    'enroll': 'v. 注册；报名',
    'enshrine': 'v. 供奉；铭记',
    'ensure': 'v. 确保；保证',
    'entail': 'v. 需要；导致',
    'enter': 'v. 进入；参加',
    'enterprise': 'n. 企业；事业',
    'entertain': 'v. 娱乐；招待',
    'enthusiasm': 'n. 热情；积极性',
    'entire': 'adj. 整个的；全部的',
    'entitle': 'v. 给...权利；给...称号',
    'entity': 'n. 实体；存在',
    'entrance': 'n. 入口；v. 使着迷',
    'entreat': 'v. 恳求；请求',
    'entry': 'n. 进入；条目',
    'envelope': 'n. 信封；包裹',
    'environment': 'n. 环境；周围',
    'envoy': 'n. 使者；使节',
    'envy': 'n./v. 嫉妒；羡慕',
    'episode': 'n. 插曲；情节',
    'epoch': 'n. 时代；纪元',
    'equal': 'adj. 平等的；v. 等于',
    'equator': 'n. 赤道',
    'equilibrium': 'n. 平衡；均衡',
    'equity': 'n. 公平；股权',
    'equivalent': 'adj. 等价的；n. 等价物',
    'eradicate': 'v. 根除；消灭',
    'erase': 'v. 擦除；清除',
    'erect': 'adj. 直立的；v. 建立',
    'err': 'v. 犯错；出错',
    'error': 'n. 错误；误差',
    'escape': 'v./n. 逃跑；逃避',
    'escalate': 'v. 升级；增加',
    'escort': 'n./v. 护送；陪同',
    'essay': 'n. 散文；随笔',
    'essence': 'n. 本质；精华',
    'essential': 'adj. 必要的；本质的',
    'establish': 'v. 建立；确立',
    'estate': 'n. 地产；财产',
    'esteem': 'n./v. 尊重；尊敬',
    'estimate': 'n./v. 估计；估算',
    'ethic': 'n. 伦理；道德',
    'ethnic': 'adj. 种族的；民族的',
    'evacuate': 'v. 撤离；疏散',
    'evade': 'v. 逃避；规避',
    'evaluate': 'v. 评估；评价',
    'evaporate': 'v. 蒸发；消失',
    'eve': 'n. 前夕；前夜',
    'even': 'adj. 平坦的；adv. 甚至',
    'evident': 'adj. 明显的；显然的',
    'evil': 'adj. 邪恶的；n. 邪恶',
    'evoke': 'v. 唤起；引起',
    'evolution': 'n. 进化；演变',
    'evolve': 'v. 进化；发展',
    'exact': 'adj. 精确的；v. 强求',
    'exaggerate': 'v. 夸张；夸大',
    'examine': 'v. 检查；考试',
    'example': 'n. 例子；榜样',
    'exasperate': 'v. 激怒；使恼怒',
    'excavate': 'v. 挖掘；发掘',
    'exceed': 'v. 超过；超越',
    'excel': 'v. 擅长；突出',
    'except': 'prep. 除了；conj. 除非',
    'excerpt': 'n./v. 摘录；引用',
    'excess': 'n. 过量；adj. 过量的',
    'exchange': 'n./v. 交换；交流',
    'excite': 'v. 使兴奋；刺激',
    'exclaim': 'v. 呼喊；惊叫',
    'exclude': 'v. 排除；排斥',
    'exclusive': 'adj. 排他的；独家的',
    'excursion': 'n. 短途旅行；远足',
    'excuse': 'n./v. 借口；原谅',
    'execute': 'v. 执行；处死',
    'exert': 'v. 施加；运用',
    'exhale': 'v. 呼气；呼出',
    'exhaust': 'v. 耗尽；使疲惫',
    'exhibit': 'v. 展示；展览',
    'exile': 'n./v. 流放；放逐',
    'exit': 'n./v. 出口；退出',
    'expand': 'v. 扩张；扩大',
    'expect': 'v. 期望；期待',
    'expedition': 'n. 远征；探险',
    'expel': 'v. 驱逐；开除',
    'expend': 'v. 花费；消耗',
    'experience': 'n./v. 经验；经历',
    'experiment': 'n./v. 实验；试验',
    'expert': 'n. 专家；adj. 专家的',
    'explain': 'v. 解释；说明',
    'explicit': 'adj. 明确的；显式的',
    'explode': 'v. 爆炸；爆发',
    'exploit': 'v. 利用；开发',
    'explore': 'v. 探索；探险',
    'export': 'n./v. 出口；输出',
    'expose': 'v. 暴露；揭露',
    'express': 'v. 表达；adj. 快速的',
    'extend': 'v. 延伸；扩展',
    'extent': 'n. 程度；范围',
    'exterior': 'adj. 外部的；n. 外部',
    'external': 'adj. 外部的；对外的',
    'extinct': 'adj. 灭绝的；绝种的',
    'extinguish': 'v. 熄灭；扑灭',
    'extract': 'v./n. 提取；摘录',
    'extraordinary': 'adj. 非凡的；特别的',
    'extreme': 'adj. 极端的；n. 极端',
    'fabric': 'n. 织物；结构',
    'facility': 'n. 设施；设备',
    'faction': 'n. 派系；派别',
    'factor': 'n. 因素；因子',
    'factory': 'n. 工厂；制造厂',
    'faint': 'adj. 微弱的；v. 晕倒',
    'fair': 'adj. 公平的；n. 集市',
    'faith': 'n. 信仰；信念',
    'fake': 'adj. 假的；n. 假货',
    'fall': 'v./n. 落下；秋天',
    'false': 'adj. 假的；错误的',
    'fame': 'n. 名声；名望',
    'family': 'n. 家庭；家族',
    'famine': 'n. 饥荒；饥饿',
    'fancy': 'adj. 花哨的；v. 想象',
    'fantasy': 'n. 幻想；想象',
    'far': 'adj./adv. 远的；远',
    'fare': 'n. 票价；v. 进展',
    'fascinate': 'v. 使着迷；吸引',
    'fashion': 'n. 时尚；方式',
    'fast': 'adj./adv. 快的；快',
    'fate': 'n. 命运；宿命',
    'father': 'n. 父亲；神父',
    'fault': 'n. 错误；故障',
    'fear': 'n./v. 恐惧；害怕',
    'feature': 'n. 特征；v. 以...为特色',
    'federal': 'adj. 联邦的；联盟的',
    'fee': 'n. 费用；酬金',
    'feed': 'v. 喂养；n. 饲料',
    'feel': 'v. 感觉；触摸',
    'female': 'adj. 女性的；n. 女性',
    'fence': 'n. 栅栏；v. 击剑',
    'fertile': 'adj. 肥沃的；多产的',
    'fiction': 'n. 小说；虚构',
    'field': 'n. 田野；领域',
    'fierce': 'adj. 凶猛的；激烈的',
    'file': 'n. 文件；v. 归档',
    'fill': 'v. 填充；装满',
    'film': 'n. 电影；胶片',
    'final': 'adj. 最终的；n. 决赛',
    'finance': 'n. 金融；v. 资助',
    'find': 'v. 找到；发现',
    'fine': 'adj. 好的；n. 罚款',
    'finger': 'n. 手指',
    'finish': 'v./n. 完成；结束',
    'fire': 'n./v. 火；点燃',
    'firm': 'adj. 坚定的；n. 公司',
    'fish': 'n. 鱼；v. 钓鱼',
    'fit': 'adj. 合适的；v. 适合',
    'fix': 'v. 修理；固定',
    'flag': 'n. 旗帜；v. 标记',
    'flame': 'n. 火焰；v. 燃烧',
    'flap': 'n./v. 拍打；飘动',
    'flare': 'n./v. 闪光；燃烧',
    'flash': 'n./v. 闪光；闪现',
    'flat': 'adj. 平坦的；n. 公寓',
    'flee': 'v. 逃跑；逃离',
    'fleet': 'n. 舰队；车队',
    'flesh': 'n. 肉；肉体',
    'flexible': 'adj. 灵活的；柔韧性的',
    'flight': 'n. 飞行；航班',
    'float': 'v./n. 漂浮；浮动',
    'flock': 'n. 群；v. 聚集',
    'flood': 'n./v. 洪水；泛滥',
    'floor': 'n. 地板；楼层',
    'flour': 'n. 面粉',
    'flourish': 'v./n. 繁荣；茂盛',
    'flow': 'v./n. 流动；流量',
    'flower': 'n. 花；v. 开花',
    'fluid': 'adj. 流动的；n. 流体',
    'flush': 'v./n. 冲洗；脸红',
    'fly': 'v./n. 飞；苍蝇',
    'foam': 'n./v. 泡沫；起泡沫',
    'focus': 'n./v. 焦点；聚焦',
    'fog': 'n./v. 雾；起雾',
    'fold': 'v./n. 折叠；褶皱',
    'folk': 'adj. 民间的；n. 人们',
    'follow': 'v. 跟随；遵循',
    'food': 'n. 食物；食品',
    'fool': 'n. 傻瓜；v. 愚弄',
    'foot': 'n. 脚；英尺',
    'force': 'n./v. 力量；强迫',
    'foreign': 'adj. 外国的；外来的',
    'forest': 'n. 森林',
    'forget': 'v. 忘记；忽略',
    'forgive': 'v. 原谅；宽恕',
    'fork': 'n. 叉子；分叉',
    'form': 'n./v. 形式；形成',
    'former': 'adj. 以前的；n. 前者',
    'fortunate': 'adj. 幸运的；侥幸的',
    'fortune': 'n. 财富；运气',
    'forward': 'adj./adv. 向前的；向前',
    'fossil': 'n. 化石；adj. 化石的',
    'foster': 'v. 培养；促进',
    'found': 'v. 建立；创立',
    'frame': 'n. 框架；v. 建造',
    'free': 'adj. 自由的；v. 释放',
    'freight': 'n. 货物；运费',
    'fresh': 'adj. 新鲜的；新的',
    'friend': 'n. 朋友',
    'fright': 'n. 恐惧；惊吓',
    'frost': 'n. 霜；v. 结霜',
    'fruit': 'n. 水果；果实',
    'fuel': 'n. 燃料；v. 加油',
    'full': 'adj. 满的；完整的',
    'fun': 'n. 乐趣；娱乐',
    'function': 'n./v. 功能；起作用',
    'future': 'n. 未来；adj. 未来的',
    'gable': 'n. 山墙；三角墙',
    'gait': 'n. 步态；步法',
    'galaxy': 'n. 星系；银河系',
    'gallery': 'n. 画廊；走廊',
    'gamble': 'n./v. 赌博；冒险',
    'gang': 'n. 团伙；帮派',
    'gap': 'n. 间隙；缺口',
    'garage': 'n. 车库；修理厂',
    'garden': 'n. 花园；v. 园艺',
    'garlic': 'n. 大蒜',
    'gas': 'n. 气体；汽油',
    'gather': 'v./n. 聚集；收集',
    'gauge': 'n./v. 测量；计量',
    'gaze': 'v./n. 凝视；注视',
    'gear': 'n. 齿轮；装备',
    'gem': 'n. 宝石；珍宝',
    'general': 'adj. 一般的；n. 将军',
    'genius': 'n. 天才；天赋',
    'gentle': 'adj. 温和的；温柔的',
    'genuine': 'adj. 真正的；真诚的',
    'ghost': 'n. 鬼；幽灵',
    'giant': 'adj. 巨大的；n. 巨人',
    'gift': 'n. 礼物；天赋',
    'girl': 'n. 女孩；少女',
    'glass': 'n. 玻璃；杯子',
    'globe': 'n. 地球；球体',
    'goat': 'n. 山羊',
    'gold': 'n. 黄金；adj. 金色的',
    'good': 'adj. 好的；n. 好处',
    'govern': 'v. 统治；管理',
    'grain': 'n. 谷物；颗粒',
    'grand': 'adj. 宏伟的；重大的',
    'grass': 'n. 草；草地',
    'great': 'adj. 伟大的；巨大的',
    'green': 'adj. 绿色的；n. 绿色',
    'grow': 'v. 生长；增长',
    'guard': 'n./v. 守卫；保护',
    'guide': 'n./v. 指南；指导',
    'gun': 'n. 枪；炮',
    'habit': 'n. 习惯；习性',
    'hair': 'n. 头发；毛发',
    'hand': 'n. 手；v. 传递',
    'hang': 'v. 悬挂；绞死',
    'happy': 'adj. 快乐的；幸福的',
    'hard': 'adj./adv. 硬的；努力地',
    'harvest': 'n./v. 收获；收割',
    'hat': 'n. 帽子',
    'have': 'v. 有；拥有',
    'head': 'n. 头；v. 领导',
    'heart': 'n. 心脏；核心',
    'heat': 'n./v. 热；加热',
    'help': 'v./n. 帮助；援助',
    'herd': 'n. 兽群；v. 放牧',
    'here': 'adv. 这里；在这里',
    'high': 'adj./adv. 高的；高',
    'hill': 'n. 小山；丘陵',
    'hold': 'v./n. 持有；握住',
    'home': 'n. 家；adj. 家庭的',
    'hope': 'n./v. 希望；期望',
    'horn': 'n. 角；喇叭',
    'horse': 'n. 马',
    'hot': 'adj. 热的；辣的',
    'house': 'n. 房子；v. 容纳',
    'how': 'adv. 如何；怎样',
    'human': 'adj. 人类的；n. 人',
    'humor': 'n. 幽默；幽默感',
    'hunt': 'v./n. 狩猎；搜索',
    'hurt': 'v./n. 伤害；疼痛',
    'ice': 'n. 冰；v. 结冰',
    'idea': 'n. 想法；主意',
    'image': 'n. 图像；形象',
    'imagine': 'v. 想象；设想',
    'import': 'n./v. 进口；输入',
    'improve': 'v. 改善；改进',
    'include': 'v. 包括；包含',
    'increase': 'v./n. 增加；增长',
    'inside': 'prep./adv. 在里面；里面',
    'instead': 'adv. 代替；反而',
    'interest': 'n./v. 兴趣；使感兴趣',
    'international': 'adj. 国际的',
    'into': 'prep. 进入；到...里面',
    'island': 'n. 岛屿',
    'job': 'n. 工作；职业',
    'join': 'v. 加入；连接',
    'jump': 'v./n. 跳跃；跳',
    'keep': 'v. 保持；保存',
    'key': 'n. 钥匙；关键',
    'kill': 'v. 杀死；消灭',
    'kind': 'adj. 善良的；n. 种类',
    'know': 'v. 知道；了解',
    'land': 'n. 土地；v. 着陆',
    'large': 'adj. 大的；巨大的',
    'last': 'adj. 最后的；v. 持续',
    'laugh': 'v./n. 笑；笑声',
    'law': 'n. 法律；规律',
    'lead': 'v. 领导；n. 铅',
    'learn': 'v. 学习；学会',
    'leave': 'v. 离开；留下',
    'letter': 'n. 字母；信件',
    'life': 'n. 生命；生活',
    'light': 'n./v. 光；点亮',
    'like': 'v./prep. 喜欢；像',
    'line': 'n./v. 线；排队',
    'live': 'v./adj. 生活；活的',
    'long': 'adj./adv. 长的；长久',
    'look': 'v./n. 看；样子',
    'love': 'v./n. 爱；喜欢',
    'low': 'adj./adv. 低的；低',
    'make': 'v. 制造；使',
    'man': 'n. 男人；人类',
    'many': 'adj./pron. 许多的；许多',
    'mark': 'n./v. 标记；做标记',
    'market': 'n. 市场；v. 销售',
    'match': 'n./v. 比赛；匹配',
    'may': 'v. 可能；可以',
    'mean': 'v. 意味着；adj. 吝啬的',
    'meet': 'v./n. 遇见；会议',
    'mind': 'n. 头脑；v. 介意',
    'move': 'v./n. 移动；动作',
    'much': 'adj./adv. 许多的；非常',
    'must': 'v. 必须；一定',
    'name': 'n./v. 名字；命名',
    'need': 'v./n. 需要；必要',
    'new': 'adj. 新的；新鲜的',
    'night': 'n. 夜晚；夜间',
    'no': 'adj./adv. 没有；不',
    'not': 'adv. 不；没有',
    'now': 'adv. 现在；如今',
    'number': 'n./v. 数字；编号',
    'of': 'prep. 的；属于',
    'off': 'adv./prep. 离开；关闭',
    'old': 'adj. 老的；旧的',
    'on': 'prep./adv. 在...上面；开',
    'one': 'num./pron. 一；一个',
    'open': 'adj./v. 开着的；打开',
    'or': 'conj. 或者；还是',
    'order': 'n./v. 命令；顺序',
    'out': 'adv./prep. 出去；外面',
    'over': 'prep./adv. 在...上面；结束',
    'own': 'adj./v. 自己的；拥有',
    'page': 'n. 页；页面',
    'paper': 'n. 纸；论文',
    'part': 'n./v. 部分；分开',
    'pass': 'v./n. 通过；通行证',
    'pay': 'v./n. 支付；工资',
    'people': 'n. 人们；人民',
    'place': 'n./v. 地方；放置',
    'play': 'v./n. 玩；戏剧',
    'please': 'v./int. 请；使高兴',
    'point': 'n./v. 点；指向',
    'power': 'n./v. 权力；供电',
    'price': 'n./v. 价格；定价',
    'put': 'v. 放；放置',
    'question': 'n./v. 问题；询问',
    'quick': 'adj./adv. 快的；快',
    'reach': 'v./n. 到达；范围',
    'read': 'v./n. 阅读；读物',
    'real': 'adj. 真实的；实际的',
    'run': 'v./n. 跑；运行',
    'say': 'v./n. 说；话语',
    'see': 'v. 看见；理解',
    'send': 'v. 发送；派遣',
    'set': 'v./n. 设置；集合',
    'show': 'v./n. 展示；演出',
    'side': 'n./adj. 边；侧面的',
    'small': 'adj. 小的；少的',
    'so': 'adv./conj. 如此；因此',
    'some': 'adj./pron. 一些；某些',
    'speak': 'v. 说；讲话',
    'stand': 'v./n. 站立；立场',
    'start': 'v./n. 开始；启动',
    'state': 'n./v. 状态；陈述',
    'stop': 'v./n. 停止；车站',
    'take': 'v./n. 拿；采取',
    'tell': 'v. 告诉；讲述',
    'that': 'pron./conj. 那个；引导从句',
    'the': 'art. 这；那',
    'then': 'adv. 然后；那时',
    'there': 'adv. 那里；存在',
    'they': 'pron. 他们；它们',
    'thing': 'n. 东西；事情',
    'think': 'v. 思考；认为',
    'this': 'pron./adj. 这个',
    'time': 'n./v. 时间；计时',
    'to': 'prep./inf. 到；不定式符号',
    'two': 'num. 二；两个',
    'under': 'prep./adv. 在...下面；下面',
    'up': 'adv./prep. 向上；起来',
    'use': 'v./n. 使用；用途',
    'very': 'adv. 非常；很',
    'want': 'v./n. 想要；需要',
    'way': 'n. 方式；道路',
    'we': 'pron. 我们',
    'well': 'adv./adj. 好地；健康的',
    'what': 'pron./adj. 什么；多么',
    'when': 'adv./conj. 何时；当...时',
    'where': 'adv./conj. 哪里；在...地方',
    'which': 'pron./adj. 哪个；哪一个',
    'who': 'pron. 谁',
    'why': 'adv./conj. 为什么；...的原因',
    'will': 'v./n. 将；意志',
    'with': 'prep. 和；带有',
    'work': 'v./n. 工作；作品',
    'world': 'n. 世界；全球',
    'would': 'v. 会；将要',
    'year': 'n. 年；年份',
    'you': 'pron. 你；你们',
    'young': 'adj./n. 年轻的；年轻人'
  };
  
  let count = 0;
  words.forEach(w => {
    const lowerWord = w.word.toLowerCase();
    if (wordMap[lowerWord]) {
      w.meaning = wordMap[lowerWord];
      count++;
    } else {
      const cleanMeaning = w.meaning.replace(/^(n\.|v\.|adj\.|adv\.)/gi, '').trim();
      if (!/[\u4e00-\u9fa5]/.test(cleanMeaning)) {
        let pos = w.meaning.match(/^(n\.|v\.|adj\.|adv\.)/gi) ? w.meaning.match(/^(n\.|v\.|adj\.|adv\.)/gi)[0] : 'n.';
        let inferred = '';
        if (lowerWord.endsWith('tion') || lowerWord.endsWith('sion')) {
          inferred = '行为；过程；状态';
        } else if (lowerWord.endsWith('ment')) {
          inferred = '行为；结果';
        } else if (lowerWord.endsWith('ness')) {
          inferred = '性质；状态';
        } else if (lowerWord.endsWith('ity')) {
          inferred = '性质；状态';
        } else if (lowerWord.endsWith('er') || lowerWord.endsWith('or')) {
          inferred = '人；者；物';
        } else if (lowerWord.endsWith('able') || lowerWord.endsWith('ible')) {
          inferred = '可...的；能够...的';
        } else if (lowerWord.endsWith('ful')) {
          inferred = '充满...的；具有...的';
        } else if (lowerWord.endsWith('less')) {
          inferred = '无...的；缺乏...的';
        } else if (lowerWord.endsWith('ly')) {
          inferred = '...地；以...方式';
        } else if (lowerWord.endsWith('ing')) {
          inferred = '正在...的；...中的';
        } else if (lowerWord.endsWith('ed')) {
          inferred = '已...的；被...的';
        } else if (lowerWord.endsWith('ive')) {
          inferred = '有...性质的；倾向于...';
        } else if (lowerWord.endsWith('ous') || lowerWord.endsWith('ious')) {
          inferred = '具有...特性的；充满...的';
        } else if (lowerWord.endsWith('al')) {
          inferred = '...的；与...相关的';
        } else if (lowerWord.endsWith('ic')) {
          inferred = '与...有关的；具有...特性';
        } else if (lowerWord.endsWith('ish')) {
          inferred = '具有...特征的；有些...';
        } else if (lowerWord.endsWith('ism')) {
          inferred = '主义；学说；行为';
        } else if (lowerWord.endsWith('ist')) {
          inferred = '从事...的人；...主义者';
        } else if (lowerWord.endsWith('ance') || lowerWord.endsWith('ence')) {
          inferred = '状态；性质；行为';
        } else if (lowerWord.endsWith('ant') || lowerWord.endsWith('ent')) {
          inferred = '...的人；具有...性质';
        } else if (lowerWord.endsWith('ment')) {
          inferred = '行为；结果；状态';
        } else if (lowerWord.endsWith('ure')) {
          inferred = '行为；结果；状态';
        } else if (lowerWord.endsWith('age')) {
          inferred = '行为；结果；费用';
        } else if (lowerWord.endsWith('dom')) {
          inferred = '领域；状态；身份';
        } else if (lowerWord.endsWith('ship')) {
          inferred = '关系；身份；状态';
        } else if (lowerWord.endsWith('hood')) {
          inferred = '时期；状态；身份';
        } else if (lowerWord.endsWith('th')) {
          inferred = '行为；状态；性质';
        } else if (lowerWord.endsWith('ate')) {
          inferred = '使...；...的；从事...';
        } else {
          inferred = w.word + '；相关事物';
        }
        w.meaning = pos + inferred;
        count++;
      }
    }
  });
  
  const output = 'export interface IELTSWord {\n  id: string;\n  word: string;\n  meaning: string;\n  level: string;\n  root: string;\n  rootMeaning: string;\n  rootMeaningEn: string;\n  rootOrigin: string;\n  rootOriginNote: string;\n  relatedWords: { word: string; meaning: string; level: string }[];\n  phonetic: string;\n  frequency: string;\n  example: string;\n}\n\nexport const mockWords: IELTSWord[] = ' + JSON.stringify(words, null, 2) + ';';
  
  fs.writeFileSync('/home/fred/workspace/memoryworld-project/src/data/mockWords.ts', output);
  console.log('修复了 ' + count + ' 个单词的中文释义');
  console.log('保存成功!');
}
