const fs = require('fs');

const data = fs.readFileSync('/home/fred/workspace/memoryworld-project/src/data/mockWords.ts', 'utf8');
const match = data.match(/export const mockWords: IELTSWord\[\] = \[([\s\S]*?)\];/);

if (match) {
  const words = JSON.parse('[' + match[1] + ']');
  
  const wordMap = {
    'aloft': 'adv. 在高处；在空中',
    'aloha': 'int. 你好；再见',
    'allay': 'v. 减轻；平息',
    'alliance': 'n. 联盟；联合',
    'almanac': 'n. 年鉴；历书',
    'alter': 'v. 改变；更改',
    'alternate': 'v. 交替；adj. 交替的',
    'ambassador': 'n. 大使',
    'ambiguous': 'adj. 模糊的；含糊的',
    'ambition': 'n. 野心；抱负',
    'amble': 'v./n. 漫步；缓行',
    'ammunition': 'n. 弹药',
    'amoral': 'adj. 非道德的',
    'amputate': 'v. 截肢；切除',
    'anatomy': 'n. 解剖学；结构',
    'ancestor': 'n. 祖先；祖宗',
    'angle': 'n. 角度；v. 钓鱼',
    'ankle': 'n. 脚踝',
    'anniversary': 'n. 周年纪念日',
    'annotate': 'v. 注释；注解',
    'antibiotic': 'n. 抗生素',
    'antidote': 'n. 解毒剂',
    'apparatus': 'n. 装置；设备',
    'apprehend': 'v. 逮捕；理解',
    'apprentice': 'n. 学徒',
    'archaic': 'adj. 古代的；过时的',
    'ardent': 'adj. 热情的；热烈的',
    'arena': 'n. 竞技场；舞台',
    'argue': 'v. 争论；辩论',
    'arise': 'v. 出现；产生',
    'armor': 'n. 盔甲；装甲',
    'aroma': 'n. 香气；芳香',
    'articulate': 'adj. 清晰的；v. 表达',
    'artifact': 'n. 人工制品',
    'ascend': 'v. 上升；攀登',
    'ascribe': 'v. 归因于',
    'ashore': 'adv. 在岸上',
    'aspire': 'v. 渴望；追求',
    'assault': 'n./v. 攻击；袭击',
    'assemble': 'v. 组装；集合',
    'assent': 'n./v. 同意',
    'assiduous': 'adj. 勤奋的',
    'astral': 'adj. 星的；星际的',
    'astride': 'prep. 跨骑；adv. 跨着',
    'astute': 'adj. 精明的；敏锐的',
    'asylum': 'n. 庇护；避难所',
    'atlas': 'n. 地图集',
    'atom': 'n. 原子',
    'attire': 'n. 服装；v. 打扮',
    'audit': 'n./v. 审计；审核',
    'august': 'adj. 威严的；八月',
    'aura': 'n. 光环；气息',
    'aurora': 'n. 极光',
    'authentic': 'adj. 真实的；正宗的',
    'avalanche': 'n./v. 雪崩',
    'avert': 'v. 避免；转移',
    'avow': 'v. 承认；宣称',
    'babble': 'v. 唠叨；含糊地说',
    'backlog': 'n. 积压；待办事项',
    'badge': 'n. 徽章；标志',
    'bait': 'n. 诱饵；v. 引诱',
    'balm': 'n. 香油；安慰',
    'bandit': 'n. 强盗；土匪',
    'banner': 'n. 旗帜；横幅',
    'barren': 'adj. 贫瘠的；不育的',
    'bastion': 'n. 堡垒；要塞',
    'bazaar': 'n. 集市；市场',
    'beacon': 'n. 灯塔；信号灯',
    'bead': 'n. 珠子；水珠',
    'behalf': 'n. 代表；利益',
    'bellow': 'v. 咆哮；怒吼',
    'benefit': 'n./v. 利益；受益',
    'beseech': 'v. 恳求；祈求',
    'bestow': 'v. 授予；给予',
    'betray': 'v. 背叛；出卖',
    'bibliography': 'n. 参考书目',
    'bid': 'n./v. 投标；出价',
    'bilingual': 'adj. 双语的',
    'billow': 'v. 汹涌；膨胀',
    'binnacle': 'n. 罗盘箱',
    'biodiversity': 'n. 生物多样性',
    'biographer': 'n. 传记作者',
    'bishop': 'n. 主教',
    'blaze': 'n./v. 火焰；燃烧',
    'blight': 'n./v. 枯萎；破坏',
    'bliss': 'n. 极乐；幸福',
    'blunder': 'n./v. 错误；失误',
    'blunt': 'adj. 钝的；直率的',
    'blush': 'v./n. 脸红；羞愧',
    'boast': 'v./n. 吹嘘；自夸',
    'bode': 'v. 预示；预兆',
    'boisterous': 'adj. 喧闹的；活泼的',
    'bold': 'adj. 大胆的；粗体的',
    'bond': 'n. 债券；纽带',
    'bonus': 'n. 奖金；红利',
    'boon': 'n. 恩惠；福利',
    'boost': 'v./n. 推动；提升',
    'bounty': 'n. 赏金；慷慨',
    'braid': 'v./n. 编织；辫子',
    'brandish': 'v. 挥舞；炫耀',
    'brash': 'adj. 鲁莽的；无礼的',
    'brink': 'n. 边缘； brink',
    'brisk': 'adj. 轻快的；活泼的',
    'broach': 'v. 提出；开启',
    'brood': 'n. 一窝；v. 沉思',
    'brook': 'n. 小溪；v. 容忍',
    'browse': 'v. 浏览；吃草',
    'brunt': 'n. 冲击；首当其冲',
    'bubble': 'n./v. 气泡；冒泡',
    'buffer': 'n. 缓冲；缓冲区',
    'bugle': 'n. 号角；军号',
    'bulge': 'n./v. 膨胀；凸起',
    'bulwark': 'n. 堡垒；防御',
    'bureaucracy': 'n. 官僚主义',
    'burglar': 'n. 窃贼',
    'burgeon': 'v. 发芽；迅速增长',
    'bust': 'n. 半身像；v. 打破',
    'buttress': 'n. 扶壁；v. 支持',
    'buzz': 'v./n. 嗡嗡声；闲聊',
    'cabin': 'n. 小屋；船舱',
    'cable': 'n. 电缆；电报',
    'cacao': 'n. 可可；可可树',
    'cadence': 'n. 节奏；韵律',
    'caffeine': 'n. 咖啡因',
    'calamity': 'n. 灾难；灾祸',
    'caliber': 'n. 口径；品质',
    'callous': 'adj. 无情的；硬结的',
    'calorie': 'n. 卡路里',
    'camouflage': 'n./v. 伪装；掩饰',
    'canal': 'n. 运河；沟渠',
    'canopy': 'n. 天篷；华盖',
    'capillary': 'n. 毛细血管',
    'caprice': 'n. 反复无常；任性',
    'caption': 'n. 标题；说明',
    'captive': 'adj. 被俘的；n. 俘虏',
    'caravan': 'n. 大篷车；商队',
    'carcass': 'n. 尸体；残骸',
    'cardinal': 'adj. 主要的；n. 红衣主教',
    'cargo': 'n. 货物',
    'caricature': 'n. 漫画；讽刺画',
    'carnal': 'adj. 肉体的；肉欲的',
    'carnival': 'n. 狂欢节',
    'carve': 'v. 雕刻；切开',
    'cascade': 'n./v. 瀑布；倾泻',
    'casualty': 'n. 伤亡人员',
    'catastrophe': 'n. 灾难；大祸',
    'caustic': 'adj. 腐蚀性的；刻薄的',
    'caveat': 'n. 警告；注意事项',
    'cedar': 'n. 雪松',
    'celestial': 'adj. 天上的；神圣的',
    'censor': 'n./v. 审查；审查员',
    'censure': 'n./v. 谴责；批评',
    'centennial': 'adj./n. 百年的；百年纪念',
    'cereal': 'n. 谷物；麦片',
    'cessation': 'n. 停止；中断',
    'chaff': 'n. 谷壳；v. 取笑',
    'chagrin': 'n. 懊恼；失望',
    'champion': 'n. 冠军；v. 支持',
    'chant': 'v./n. 吟唱；圣歌',
    'chasm': 'n. 深渊；鸿沟',
    'cheer': 'v./n. 欢呼；喝彩',
    'chisel': 'n. 凿子；v. 凿',
    'chord': 'n. 和弦；弦',
    'chore': 'n. 家务；杂务',
    'churn': 'v. 搅拌；翻腾',
    'cipher': 'n. 密码；暗号',
    'circadian': 'adj. 昼夜节律的',
    'circumstance': 'n. 情况；环境',
    'clamor': 'n./v. 喧闹；大声要求',
    'clamp': 'n./v. 夹具；夹紧',
    'clandestine': 'adj. 秘密的；暗中的',
    'clarify': 'v. 澄清；阐明',
    'clash': 'v./n. 冲突；碰撞',
    'clasp': 'v./n. 扣紧；紧握',
    'clatter': 'v./n. 咔嗒声；喧闹',
    'cleanse': 'v. 清洁；净化',
    'cleave': 'v. 劈开；粘附',
    'clench': 'v. 握紧；咬紧',
    'clerk': 'n. 职员；店员',
    'climax': 'n. 高潮；顶点',
    'clog': 'v. 堵塞；n. 木屐',
    'clout': 'n. 影响力；v. 猛击',
    'clutch': 'v./n. 抓住；离合器',
    'coerce': 'v. 强迫；胁迫',
    'cognitive': 'adj. 认知的',
    'cohabit': 'v. 同居',
    'cohere': 'v. 凝聚；连贯',
    'coil': 'v./n. 盘绕；线圈',
    'colander': 'n. 滤器；漏勺',
    'collaborate': 'v. 合作；协作',
    'collate': 'v. 整理；核对',
    'colleague': 'n. 同事',
    'colloquium': 'n. 学术讨论会',
    'colony': 'n. 殖民地；群体',
    'combat': 'n./v. 战斗；搏斗',
    'comedy': 'n. 喜剧',
    'commemorate': 'v. 纪念；庆祝',
    'commence': 'v. 开始；着手',
    'commend': 'v. 称赞；推荐',
    'commodity': 'n. 商品；货物',
    'commonplace': 'adj. 平凡的；n. 老生常谈',
    'commotion': 'n. 骚动；混乱',
    'communal': 'adj. 公共的；社区的',
    'commute': 'v. 通勤；减刑',
    'compact': 'adj. 紧凑的；n. 契约',
    'companion': 'n. 同伴；伴侣',
    'compatible': 'adj. 兼容的；相容的',
    'compel': 'v. 强迫；迫使',
    'compensate': 'v. 补偿；赔偿',
    'compile': 'v. 编译；汇编',
    'complacent': 'adj. 自满的；得意的',
    'complement': 'n./v. 补充；补足',
    'comply': 'v. 遵守；服从',
    'comport': 'v. 举止；表现',
    'comprehend': 'v. 理解；包含',
    'compromise': 'n./v. 妥协；折中',
    'compulsion': 'n. 强迫；冲动',
    'compulsory': 'adj. 强制的；必修的',
    'concede': 'v. 承认；让步',
    'conceive': 'v. 构想；怀孕',
    'concert': 'n. 音乐会；和谐',
    'concise': 'adj. 简洁的；简明的',
    'conclave': 'n. 秘密会议',
    'concoct': 'v. 调制；编造',
    'concord': 'n. 和谐；一致',
    'condemn': 'v. 谴责；判刑',
    'condone': 'v. 宽恕；赦免',
    'conduct': 'n. 行为；v. 指挥',
    'confidant': 'n. 知己；心腹',
    'confine': 'v. 限制；监禁',
    'confirm': 'v. 确认；证实',
    'confiscate': 'v. 没收；充公',
    'conflate': 'v. 合并；混合',
    'confound': 'v. 混淆；使困惑',
    'congest': 'v. 使拥挤；使充血',
    'congregate': 'v. 聚集；集合',
    'conjecture': 'n./v. 推测；猜测',
    'conjoin': 'v. 连接；结合',
    'conjugal': 'adj. 婚姻的；夫妻的',
    'conjure': 'v. 召唤；变魔术',
    'connote': 'v. 暗示；意味着',
    'conquer': 'v. 征服；战胜',
    'conscience': 'n. 良心；良知',
    'conscientious': 'adj. 认真的；尽责的',
    'consecrate': 'v. 奉献；使神圣',
    'consent': 'n./v. 同意；赞成',
    'conservation': 'n. 保护；保存',
    'conserve': 'v. 保存；保护',
    'consign': 'v. 交付；委托',
    'consist': 'v. 由...组成；一致',
    'console': 'v. 安慰；n. 控制台',
    'consolidate': 'v. 巩固；合并',
    'conspicuous': 'adj. 显眼的；显著的',
    'constable': 'n. 警察；治安官',
    'constraint': 'n. 约束；限制',
    'constrain': 'v. 限制；强迫',
    'consume': 'v. 消耗；消费',
    'contend': 'v. 竞争；主张',
    'contest': 'n./v. 比赛；竞争',
    'context': 'n. 上下文；语境',
    'contiguous': 'adj. 相邻的；接壤的',
    'contort': 'v. 扭曲；变形',
    'contraband': 'n. 违禁品；走私货',
    'contradict': 'v. 反驳；矛盾',
    'contrary': 'adj. 相反的；n. 对立面',
    'contrast': 'n./v. 对比；对照',
    'contrive': 'v. 发明；策划',
    'controversy': 'n. 争议；争论',
    'convalesce': 'v. 康复；休养',
    'convention': 'n. 惯例；会议',
    'converge': 'v. 汇聚；收敛',
    'converse': 'v. 交谈；n. 相反',
    'convert': 'v. 转换；改变信仰',
    'convey': 'v. 传达；运输',
    'convict': 'v. 定罪；n. 罪犯',
    'convince': 'v. 说服；使确信',
    'cooperate': 'v. 合作；协作',
    'coordinate': 'v. 协调；n. 坐标',
    'copious': 'adj. 丰富的；大量的',
    'coral': 'n. 珊瑚；珊瑚色',
    'cordial': 'adj. 热情的；亲切的',
    'corps': 'n. 军团； corps',
    'corpse': 'n. 尸体',
    'correlate': 'v. 关联；相关',
    'corrode': 'v. 腐蚀；侵蚀',
    'corrupt': 'adj. 腐败的；v. 腐蚀',
    'cosset': 'v. 宠爱；娇养',
    'coterie': 'n. 小圈子；小团体',
    'cottage': 'n. 小屋；村舍',
    'couch': 'n. 沙发；v. 表达',
    'council': 'n. 委员会；理事会',
    'counsel': 'n. 建议；v. 劝告',
    'countenance': 'n. 面容；表情',
    'courage': 'n. 勇气；胆量',
    'courteous': 'adj. 有礼貌的；谦恭的',
    'courtesy': 'n. 礼貌；好意',
    'covet': 'v. 贪图；觊觎',
    'coward': 'n. 懦夫；胆小鬼',
    'cower': 'v. 畏缩；退缩',
    'crackle': 'v./n. 噼啪声',
    'crafty': 'adj. 狡猾的；灵巧的',
    'crane': 'n. 起重机；鹤',
    'crave': 'v. 渴望；恳求',
    'crawl': 'v./n. 爬行；缓慢移动',
    'creak': 'v./n. 嘎吱声',
    'creep': 'v./n. 爬行；悄悄移动',
    'crevice': 'n. 裂缝；缺口',
    'crimson': 'adj. 深红色的；n. 深红色',
    'cripple': 'n. 跛子；v. 使残疾',
    'criterion': 'n. 标准；准则',
    'croak': 'v. 呱呱叫；嘶哑地说',
    'crochet': 'v./n. 钩针编织',
    'croon': 'v. 低声吟唱；哼唱',
    'crucial': 'adj. 关键的；至关重要的',
    'crude': 'adj. 粗糙的；原油的',
    'cruel': 'adj. 残忍的；残酷的',
    'cruise': 'v./n. 巡航；巡游',
    'crush': 'v./n. 压碎；迷恋',
    'crust': 'n. 外壳；地壳',
    'crystal': 'n. 水晶；晶体',
    'cubic': 'adj. 立方的；立方体的',
    'cuisine': 'n. 烹饪；菜肴',
    'culminate': 'v. 达到顶点；告终',
    'cult': 'n. 崇拜；教派',
    'curb': 'n./v. 限制；抑制',
    'curriculum': 'n. 课程；课程表',
    'curse': 'n./v. 诅咒；咒骂',
    'curtain': 'n. 窗帘；幕布',
    'cushion': 'n. 垫子；缓冲',
    'custody': 'n. 监护；保管',
    'customary': 'adj. 习惯的；惯常的',
    'cute': 'adj. 可爱的；漂亮的',
    'cylinder': 'n. 圆柱；气缸',
    'cynical': 'adj. 愤世嫉俗的',
    'dagger': 'n. 匕首；短剑',
    'daisy': 'n. 雏菊',
    'dam': 'n. 水坝；v. 筑坝',
    'damp': 'adj. 潮湿的；v. 使潮湿',
    'dangle': 'v. 悬挂；摇晃',
    'daredevil': 'n. 冒险者；adj. 大胆的',
    'darn': 'v. 缝补；织补',
    'dart': 'n./v. 飞镖；投掷',
    'dash': 'v./n. 猛冲；破折号',
    'dawdle': 'v. 闲逛；拖延',
    'deadlock': 'n. 僵局；死锁',
    'debut': 'n./v. 初次登场；首次亮相',
    'debacle': 'n. 崩溃；惨败',
    'debit': 'n./v. 借方；借记',
    'decade': 'n. 十年；十年期',
    'deceit': 'n. 欺骗；谎言',
    'decent': 'adj. 体面的；得体的',
    'decipher': 'v. 破译；解读',
    'decline': 'v./n. 下降；拒绝',
    'decompose': 'v. 分解；腐烂',
    'decorum': 'n. 礼仪；得体',
    'decree': 'n./v. 法令；颁布',
    'deduce': 'v. 推断；演绎',
    'deface': 'v. 损毁；弄脏',
    'defect': 'n. 缺陷；v. 背叛',
    'defiance': 'n. 违抗；蔑视',
    'deficiency': 'n. 缺乏；不足',
    'definite': 'adj. 明确的；确定的',
    'deflate': 'v. 放气；使泄气',
    'deflect': 'v. 偏转；偏离',
    'deform': 'v. 使变形；使畸形',
    'deft': 'adj. 灵巧的；熟练的',
    'defy': 'v. 违抗；蔑视',
    'degenerate': 'v. 退化；堕落',
    'dehydrate': 'v. 脱水；使干燥',
    'deign': 'v. 屈尊；俯就',
    'delegate': 'n. 代表；v. 委托',
    'deliberate': 'adj. 故意的；v. 深思熟虑',
    'delicate': 'adj. 精致的；脆弱的',
    'delirium': 'n. 谵妄；发狂',
    'delude': 'v. 欺骗；迷惑',
    'deluge': 'n./v. 洪水； deluge',
    'delve': 'v. 钻研；深入研究',
    'demise': 'n. 死亡；终止',
    'democracy': 'n. 民主；民主国家',
    'demographic': 'adj. 人口统计的',
    'denigrate': 'v. 诋毁；贬低',
    'denote': 'v. 表示；意味着',
    'denounce': 'v. 谴责；告发',
    'dense': 'adj. 密集的；浓厚的',
    'dental': 'adj. 牙齿的；牙科的',
    'dent': 'n./v. 凹痕；凹陷',
    'depart': 'v. 离开；出发',
    'dependable': 'adj. 可靠的；可信赖的',
    'depict': 'v. 描绘；描述',
    'deplete': 'v. 耗尽；减少',
    'deploy': 'v. 部署；展开',
    'deposit': 'n./v. 存款；存放',
    'depress': 'v. 压抑；使沮丧',
    'deprive': 'v. 剥夺；使丧失',
    'derive': 'v. 源于；获得',
    'descend': 'v. 下降；降临',
    'desert': 'n. 沙漠；v. 抛弃',
    'designate': 'v. 指定；任命',
    'desolate': 'adj. 荒凉的；v. 使荒芜',
    'despair': 'n./v. 绝望；丧失信心',
    'desperate': 'adj. 绝望的；不顾一切的',
    'despicable': 'adj. 可鄙的；卑鄙的',
    'dessert': 'n. 甜点；甜食',
    'destine': 'v. 注定；命定',
    'detach': 'v. 分离；拆卸',
    'detectable': 'adj. 可检测的；可察觉的',
    'deter': 'v. 阻止；威慑',
    'detour': 'n./v. 绕道；迂回',
    'detract': 'v. 减损；贬低',
    'detriment': 'n. 损害；伤害',
    'deviate': 'v. 偏离；背离',
    'devise': 'v. 设计；发明',
    'dew': 'n. 露水',
    'dexterity': 'n. 灵巧；敏捷',
    'diagonal': 'adj. 对角线的；n. 对角线',
    'dialect': 'n. 方言；土语',
    'dialogue': 'n. 对话；对白',
    'diameter': 'n. 直径',
    'dictate': 'v. 口述；命令',
    'diction': 'n. 措辞；发音',
    'diffuse': 'v. 扩散；传播',
    'dignity': 'n. 尊严；高贵',
    'dilemma': 'n. 困境；两难',
    'diligent': 'adj. 勤奋的；刻苦的',
    'dilute': 'v. 稀释；冲淡',
    'diminish': 'v. 减少；降低',
    'dine': 'v. 进餐；用餐',
    'diploma': 'n. 文凭；毕业证书',
    'diplomacy': 'n. 外交；外交手腕',
    'direct': 'adj. 直接的；v. 指导',
    'disagree': 'v. 不同意；不一致',
    'disappear': 'v. 消失；失踪',
    'disappoint': 'v. 使失望；使沮丧',
    'disapprove': 'v. 不赞成；反对',
    'disarm': 'v. 解除武装；裁军',
    'disarray': 'n. 混乱；紊乱',
    'disaster': 'n. 灾难；灾害',
    'disavow': 'v. 否认；拒绝承认',
    'disband': 'v. 解散；解体',
    'discard': 'v. 丢弃；抛弃',
    'discern': 'v. 辨别；识别',
    'discharge': 'v./n. 放电；释放',
    'discipline': 'n./v. 纪律；训练',
    'disclaim': 'v. 否认；放弃',
    'disclose': 'v. 揭露；透露',
    'discomfort': 'n. 不适；不安',
    'disconnect': 'v. 断开连接；分离',
    'discover': 'v. 发现；发觉',
    'discredit': 'v. 使丧失信誉；诋毁',
    'discreet': 'adj. 谨慎的；慎重的',
    'discrepancy': 'n. 差异；不符',
    'discriminate': 'v. 歧视；区分',
    'discuss': 'v. 讨论；商议',
    'disease': 'n. 疾病；病害',
    'disembark': 'v. 下船；登陆',
    'disengage': 'v. 脱离；解除',
    'disgrace': 'n./v. 耻辱；使蒙羞',
    'disguise': 'n./v. 伪装；掩饰',
    'disgust': 'n./v. 厌恶；反感',
    'dishonest': 'adj. 不诚实的；欺诈的',
    'disillusion': 'v. 使醒悟；使幻灭',
    'disinfect': 'v. 消毒；杀菌',
    'disintegrate': 'v. 瓦解；分裂',
    'dislocate': 'v. 脱位；移位',
    'dislodge': 'v. 驱逐；移走',
    'dismal': 'adj. 凄凉的；阴沉的',
    'dismantle': 'v. 拆除；拆卸',
    'dismiss': 'v. 解雇；解散',
    'disobey': 'v. 不服从；违抗',
    'disorder': 'n. 混乱；无序',
    'disparate': 'adj. 不同的；不相称的',
    'dispense': 'v. 分配；分发',
    'disperse': 'v. 分散；散开',
    'displace': 'v. 取代；置换',
    'display': 'n./v. 显示；展示',
    'displease': 'v. 使不高兴；冒犯',
    'disposal': 'n. 处置；处理',
    'dispose': 'v. 处理；布置',
    'dispute': 'n./v. 争论；争议',
    'disqualify': 'v. 取消资格；使不合格',
    'disregard': 'v./n. 忽视；不理会',
    'disrupt': 'v. 破坏；扰乱',
    'disseminate': 'v. 传播；散布',
    'dissent': 'n./v. 异议；不同意',
    'dissolve': 'v. 溶解；解散',
    'distract': 'v. 分散注意力；使分心',
    'distress': 'n./v. 痛苦；使痛苦',
    'distribute': 'v. 分发；分配',
    'distrust': 'n./v. 不信任；怀疑',
    'disturb': 'v. 打扰；扰乱',
    'dive': 'v./n. 潜水；跳水',
    'diverge': 'v. 分歧；分叉',
    'diverse': 'adj. 多样的；不同的',
    'diversify': 'v. 多样化；多元化',
    'divest': 'v. 剥夺；放弃',
    'divine': 'adj. 神圣的；v. 占卜',
    'divorce': 'n./v. 离婚；分离',
    'dizzy': 'adj. 头晕的；眩晕的',
    'doctrine': 'n. 教义；学说',
    'document': 'n. 文件；v. 记录',
    'dogma': 'n. 教条；信条',
    'dole': 'n. 救济金；v. 发放',
    'dolphin': 'n. 海豚',
    'domain': 'n. 领域；域名',
    'domestic': 'adj. 国内的；家庭的',
    'dominant': 'adj. 占主导的；统治的',
    'donate': 'v. 捐赠；捐献',
    'doom': 'n./v. 厄运；注定',
    'dormant': 'adj. 休眠的；静止的',
    'dose': 'n. 剂量；一剂',
    'doubt': 'n./v. 怀疑；疑问',
    'dough': 'n. 面团；钱',
    'dove': 'n. 鸽子',
    'draft': 'n./v. 草稿；起草',
    'drag': 'v./n. 拖；拉',
    'drain': 'v./n. 排水；消耗',
    'drama': 'n. 戏剧；戏剧艺术',
    'drastic': 'adj. 激烈的；急剧的',
    'drawl': 'v./n. 慢吞吞地说',
    'dread': 'n./v. 恐惧；害怕',
    'drift': 'v./n. 漂流；漂移',
    'drill': 'n./v. 钻头；钻孔',
    'drip': 'v./n. 滴；水滴',
    'drown': 'v. 淹死；淹没',
    'drunk': 'adj. 喝醉的；n. 醉汉',
    'dual': 'adj. 双重的；二元的',
    'dubious': 'adj. 可疑的；不确定的',
    'dull': 'adj. 迟钝的；无聊的',
    'dump': 'v./n. 倾倒；垃圾场',
    'durable': 'adj. 耐用的；持久的',
    'dusk': 'n. 黄昏；薄暮',
    'duty': 'n. 责任；义务',
    'dwarf': 'n. 矮人；v. 使矮小',
    'dwell': 'v. 居住；停留',
    'dwindle': 'v. 减少；缩小',
    'dye': 'n./v. 染料；染色',
    'eagle': 'n. 鹰',
    'earnest': 'adj. 认真的；诚挚的',
    'earthquake': 'n. 地震',
    'ease': 'n./v. 轻松；减轻',
    'ebb': 'v./n. 退潮；衰退',
    'echo': 'n./v. 回声；回响',
    'eclipse': 'n./v. 日食；黯然失色',
    'ecology': 'n. 生态学',
    'edible': 'adj. 可食用的',
    'elaborate': 'adj. 精心的；v. 详细说明',
    'elapse': 'v. 流逝；过去',
    'elastic': 'adj. 有弹性的；n. 松紧带',
    'elbow': 'n. 肘部；v. 用肘推',
    'elect': 'v. 选举；选择',
    'elegant': 'adj. 优雅的；高雅的',
    'elephant': 'n. 大象',
    'elevate': 'v. 提升；抬高',
    'elicit': 'v. 引出；诱出',
    'eligible': 'adj. 有资格的；合适的',
    'elite': 'n. 精英；精华',
    'eloquent': 'adj. 雄辩的；有说服力的',
    'embark': 'v. 上船；开始',
    'embarrass': 'v. 使尴尬；使难堪',
    'embassy': 'n. 大使馆',
    'embed': 'v. 嵌入；植入',
    'embody': 'v. 体现；包含',
    'embrace': 'v./n. 拥抱；接受',
    'emerge': 'v. 出现；浮现',
    'emission': 'n. 排放；发射',
    'emit': 'v. 发出；排放',
    'emperor': 'n. 皇帝',
    'emphasis': 'n. 强调；重点',
    'empirical': 'adj. 经验的；实证的',
    'employ': 'v. 雇佣；使用',
    'empower': 'v. 授权；使能够',
    'enable': 'v. 使能够；使成为可能',
    'enact': 'v. 制定；颁布',
    'encapsulate': 'v. 封装；概括',
    'enchant': 'v. 使着迷；施魔法',
    'encircle': 'v. 环绕；包围',
    'enclose': 'v. 包围；附上',
    'encompass': 'v. 包含；包围',
    'encounter': 'n./v. 遭遇；遇见',
    'encourage': 'v. 鼓励；激励',
    'endanger': 'v. 危及；危害',
    'endeavor': 'n./v. 努力；尝试',
    'endow': 'v. 赋予；捐赠',
    'endure': 'v. 忍受；持续',
    'enemy': 'n. 敌人；对手',
    'enforce': 'v. 强制执行；实施',
    'engage': 'v. 参与；从事',
    'engine': 'n. 发动机；引擎',
    'enhance': 'v. 增强；提高',
    'enjoy': 'v. 享受；喜欢',
    'enlarge': 'v. 扩大；放大',
    'enlighten': 'v. 启发；开导',
    'enlist': 'v. 入伍；招募',
    'enormous': 'adj. 巨大的；庞大的',
    'enquire': 'v. 询问；调查',
    'enrage': 'v. 激怒；使愤怒',
    'enrich': 'v. 丰富；使富裕',
    'enroll': 'v. 注册；报名',
    'enshrine': 'v. 供奉；铭记',
    'ensure': 'v. 确保；保证',
    'entail': 'v. 需要；导致',
    'enter': 'v. 进入；参加',
    'enterprise': 'n. 企业；事业',
    'entertain': 'v. 娱乐；招待',
    'enthusiasm': 'n. 热情；积极性',
    'entitle': 'v. 给...权利；给...称号',
    'entity': 'n. 实体；存在',
    'entrance': 'n. 入口；v. 使着迷',
    'entreat': 'v. 恳求；请求',
    'envelope': 'n. 信封；包裹',
    'environment': 'n. 环境；周围',
    'envoy': 'n. 使者；使节',
    'envy': 'n./v. 嫉妒；羡慕',
    'episode': 'n. 插曲；情节',
    'epoch': 'n. 时代；纪元',
    'equator': 'n. 赤道',
    'equity': 'n. 公平；股权',
    'equivalent': 'adj. 等价的；n. 等价物',
    'eradicate': 'v. 根除；消灭',
    'erase': 'v. 擦除；清除',
    'erect': 'adj. 直立的；v. 建立',
    'error': 'n. 错误；误差',
    'escape': 'v./n. 逃跑；逃避',
    'escalate': 'v. 升级；增加',
    'essay': 'n. 散文；随笔',
    'essence': 'n. 本质；精华',
    'essential': 'adj. 必要的；本质的',
    'establish': 'v. 建立；确立',
    'estate': 'n. 地产；财产',
    'esteem': 'n./v. 尊重；尊敬',
    'ethnic': 'adj. 种族的；民族的',
    'evacuate': 'v. 撤离；疏散',
    'evade': 'v. 逃避；规避',
    'evaluate': 'v. 评估；评价',
    'evaporate': 'v. 蒸发；消失',
    'even': 'adj. 平坦的；adv. 甚至',
    'evident': 'adj. 明显的；显然的',
    'evil': 'adj. 邪恶的；n. 邪恶',
    'evoke': 'v. 唤起；引起',
    'evolve': 'v. 进化；发展',
    'exact': 'adj. 精确的；v. 强求',
    'exaggerate': 'v. 夸张；夸大',
    'examine': 'v. 检查；考试',
    'exasperate': 'v. 激怒；使恼怒',
    'excavate': 'v. 挖掘；发掘',
    'exceed': 'v. 超过；超越',
    'excel': 'v. 擅长；突出',
    'except': 'prep. 除了；conj. 除非',
    'excerpt': 'n./v. 摘录；引用',
    'excess': 'n. 过量；adj. 过量的',
    'exchange': 'n./v. 交换；交流',
    'excite': 'v. 使兴奋；刺激',
    'exclaim': 'v. 呼喊；惊叫',
    'exclude': 'v. 排除；排斥',
    'exclusive': 'adj. 排他的；独家的',
    'excursion': 'n. 短途旅行；远足',
    'excuse': 'n./v. 借口；原谅',
    'execute': 'v. 执行；处死',
    'exert': 'v. 施加；运用',
    'exhale': 'v. 呼气；呼出',
    'exhaust': 'v. 耗尽；使疲惫',
    'exhibit': 'v. 展示；展览',
    'exile': 'n./v. 流放；放逐',
    'exit': 'n./v. 出口；退出',
    'expand': 'v. 扩张；扩大',
    'expect': 'v. 期望；期待',
    'expedition': 'n. 远征；探险',
    'expel': 'v. 驱逐；开除',
    'expend': 'v. 花费；消耗',
    'expensive': 'adj. 昂贵的；高价的',
    'experience': 'n./v. 经验；经历',
    'experiment': 'n./v. 实验；试验',
    'expert': 'n. 专家；adj. 专家的',
    'explain': 'v. 解释；说明',
    'explicit': 'adj. 明确的；显式的',
    'exploit': 'v. 利用；开发',
    'explore': 'v. 探索；探险',
    'export': 'n./v. 出口；输出',
    'expose': 'v. 暴露；揭露',
    'extend': 'v. 延伸；扩展',
    'extent': 'n. 程度；范围',
    'exterior': 'adj. 外部的；n. 外部',
    'external': 'adj. 外部的；对外的',
    'extinct': 'adj. 灭绝的；绝种的',
    'extinguish': 'v. 熄灭；扑灭',
    'extraordinary': 'adj. 非凡的；特别的',
    'extravagant': 'adj. 奢侈的；过分的',
    'extreme': 'adj. 极端的；n. 极端',
    'fabric': 'n. 织物；结构',
    'facility': 'n. 设施；设备',
    'faction': 'n. 派系；派别',
    'factor': 'n. 因素；因子',
    'faint': 'adj. 微弱的；v. 晕倒',
    'fake': 'adj. 假的；n. 假货',
    'fall': 'v./n. 落下；秋天',
    'false': 'adj. 假的；错误的',
    'fame': 'n. 名声；名望',
    'family': 'n. 家庭；家族',
    'famine': 'n. 饥荒；饥饿',
    'fancy': 'adj. 花哨的；v. 想象',
    'far': 'adj./adv. 远的；远',
    'fare': 'n. 票价；v. 进展',
    'fascinate': 'v. 使着迷；吸引',
    'fast': 'adj./adv. 快的；快',
    'fate': 'n. 命运；宿命',
    'father': 'n. 父亲；神父',
    'fault': 'n. 错误；故障',
    'fear': 'n./v. 恐惧；害怕',
    'fee': 'n. 费用；酬金',
    'feed': 'v. 喂养；n. 饲料',
    'feel': 'v. 感觉；触摸',
    'female': 'adj. 女性的；n. 女性',
    'fence': 'n. 栅栏；v. 击剑',
    'fertile': 'adj. 肥沃的；多产的',
    'fiction': 'n. 小说；虚构',
    'field': 'n. 田野；领域',
    'fierce': 'adj. 凶猛的；激烈的',
    'file': 'n. 文件；v. 归档',
    'fill': 'v. 填充；装满',
    'film': 'n. 电影；胶片',
    'final': 'adj. 最终的；n. 决赛',
    'finance': 'n. 金融；v. 资助',
    'fine': 'adj. 好的；n. 罚款',
    'finger': 'n. 手指',
    'fire': 'n./v. 火；点燃',
    'firm': 'adj. 坚定的；n. 公司',
    'fish': 'n. 鱼；v. 钓鱼',
    'flag': 'n. 旗帜；v. 标记',
    'flame': 'n. 火焰；v. 燃烧',
    'flap': 'n./v. 拍打；飘动',
    'flare': 'n./v. 闪光；燃烧',
    'flash': 'n./v. 闪光；闪现',
    'flat': 'adj. 平坦的；n. 公寓',
    'flee': 'v. 逃跑；逃离',
    'fleet': 'n. 舰队；车队',
    'flesh': 'n. 肉；肉体',
    'flexible': 'adj. 灵活的；柔韧性的',
    'flight': 'n. 飞行；航班',
    'float': 'v./n. 漂浮；浮动',
    'flock': 'n. 群；v. 聚集',
    'flood': 'n./v. 洪水；泛滥',
    'floor': 'n. 地板；楼层',
    'flour': 'n. 面粉',
    'flourish': 'v./n. 繁荣；茂盛',
    'flow': 'v./n. 流动；流量',
    'fly': 'v./n. 飞；苍蝇',
    'fog': 'n./v. 雾；起雾',
    'fold': 'v./n. 折叠；褶皱',
    'food': 'n. 食物；食品',
    'fool': 'n. 傻瓜；v. 愚弄',
    'foot': 'n. 脚；英尺',
    'foreign': 'adj. 外国的；外来的',
    'forest': 'n. 森林',
    'forget': 'v. 忘记；忽略',
    'forgive': 'v. 原谅；宽恕',
    'fork': 'n. 叉子；分叉',
    'form': 'n./v. 形式；形成',
    'former': 'adj. 以前的；n. 前者',
    'fortunate': 'adj. 幸运的；侥幸的',
    'fortune': 'n. 财富；运气',
    'forward': 'adj./adv. 向前的；向前',
    'fossil': 'n. 化石；adj. 化石的',
    'frame': 'n. 框架；v. 建造',
    'free': 'adj. 自由的；v. 释放',
    'freight': 'n. 货物；运费',
    'frequent': 'adj. 频繁的；v. 常去',
    'fresh': 'adj. 新鲜的；新的',
    'friend': 'n. 朋友',
    'fright': 'n. 恐惧；惊吓',
    'frost': 'n. 霜；v. 结霜',
    'frown': 'v./n. 皱眉；不满',
    'fruit': 'n. 水果；果实',
    'fuel': 'n. 燃料；v. 加油',
    'furnish': 'v. 提供；布置',
    'fury': 'n. 愤怒；狂怒',
    'future': 'n. 未来；adj. 未来的',
    'gable': 'n. 山墙；三角墙',
    'gait': 'n. 步态；步法',
    'gale': 'n. 大风；狂风',
    'gallery': 'n. 画廊；走廊',
    'galore': 'adj./adv. 大量的；丰富地',
    'gamble': 'n./v. 赌博；冒险',
    'gang': 'n. 团伙；帮派',
    'gap': 'n. 间隙；缺口',
    'garage': 'n. 车库；修理厂',
    'garment': 'n. 服装；衣服',
    'gasp': 'v./n. 喘气；喘息',
    'gauge': 'n./v. 测量；计量',
    'gaze': 'v./n. 凝视；注视',
    'gear': 'n. 齿轮；装备',
    'gem': 'n. 宝石；珍宝',
    'gene': 'n. 基因',
    'general': 'adj. 一般的；n. 将军',
    'genius': 'n. 天才；天赋',
    'gentle': 'adj. 温和的；温柔的',
    'genuine': 'adj. 真正的；真诚的',
    'geography': 'n. 地理学',
    'geometry': 'n. 几何学',
    'germ': 'n. 细菌；胚芽',
    'ghost': 'n. 鬼；幽灵',
    'giant': 'adj. 巨大的；n. 巨人',
    'gift': 'n. 礼物；天赋',
    'gild': 'v. 镀金；装饰',
    'gilt': 'n. 镀金；金边',
    'girdle': 'n. 腰带；带状物',
    'girth': 'n. 周长；围长',
    'glacier': 'n. 冰川',
    'glad': 'adj. 高兴的；乐意的',
    'glance': 'v./n. 一瞥；扫视',
    'glare': 'v./n. 瞪眼；强光',
    'glass': 'n. 玻璃；杯子',
    'glaze': 'v. 上釉；使光滑',
    'glide': 'v./n. 滑行；滑动',
    'glimmer': 'v./n. 闪烁；微光',
    'glimpse': 'v./n. 瞥见；一瞥',
    'glitter': 'v./n. 闪闪发光',
    'globe': 'n. 地球；球体',
    'gloom': 'n. 阴暗；忧郁',
    'glorious': 'adj. 光荣的；辉煌的',
    'glory': 'n. 荣耀；光荣',
    'glow': 'v./n. 发光；发热',
    'glue': 'n. 胶水；v. 粘贴',
    'goad': 'v. 刺激；驱使',
    'goal': 'n. 目标；球门',
    'god': 'n. 神；上帝',
    'gold': 'n. 黄金；adj. 金色的',
    'good': 'adj. 好的；n. 好处',
    'gossip': 'n./v. 八卦；闲聊',
    'govern': 'v. 统治；管理',
    'grace': 'n. 优雅；恩惠',
    'gradual': 'adj. 逐渐的；逐步的',
    'grain': 'n. 谷物；颗粒',
    'grand': 'adj. 宏伟的；重大的',
    'grant': 'n./v. 授予；同意',
    'grape': 'n. 葡萄',
    'graph': 'n. 图表；图形',
    'grasp': 'v./n. 抓住；理解',
    'grass': 'n. 草；草地',
    'grateful': 'adj. 感激的；感谢的',
    'grave': 'adj. 严肃的；n. 坟墓',
    'gravel': 'n. 砾石；碎石',
    'gravitate': 'v. 吸引；倾向',
    'gravity': 'n. 重力；严重性',
    'gray': 'adj./n. 灰色的；灰色',
    'great': 'adj. 伟大的；巨大的',
    'green': 'adj. 绿色的；n. 绿色',
    'grief': 'n. 悲伤；悲痛',
    'grill': 'n. 烤架；v. 烧烤',
    'grim': 'adj. 严峻的；冷酷的',
    'grind': 'v./n. 研磨；磨碎',
    'grip': 'v./n. 抓住；紧握',
    'groan': 'v./n. 呻吟；抱怨',
    'grope': 'v. 摸索；探寻',
    'gross': 'adj. 总的；粗俗的',
    'ground': 'n. 地面；v. 使搁浅',
    'group': 'n. 组；群',
    'grow': 'v. 生长；增长',
    'grudge': 'n./v. 怨恨； grudging',
    'guarantee': 'n./v. 保证；担保',
    'guard': 'n./v. 守卫；保护',
    'guilt': 'n. 内疚；罪责',
    'guilty': 'adj. 有罪的；内疚的',
    'guide': 'n./v. 指南；指导',
    'guild': 'n. 行会；协会',
    'guiltless': 'adj. 无罪的；无辜的',
    'gulf': 'n. 海湾；鸿沟',
    'gum': 'n. 口香糖；树胶',
    'gun': 'n. 枪；炮',
    'gust': 'n. 阵风；突发',
    'gut': 'n. 内脏；勇气',
    'habit': 'n. 习惯；习性',
    'hair': 'n. 头发；毛发',
    'half': 'adj./n. 一半的；一半',
    'hall': 'n. 大厅；礼堂',
    'hammer': 'n. 锤子；v. 锤击',
    'hand': 'n. 手；v. 传递',
    'hang': 'v. 悬挂；绞死',
    'happen': 'v. 发生；碰巧',
    'happy': 'adj. 快乐的；幸福的',
    'hard': 'adj./adv. 硬的；努力地',
    'harsh': 'adj. 严厉的；刺耳的',
    'harvest': 'n./v. 收获；收割',
    'haste': 'n. 匆忙；急忙',
    'hasty': 'adj. 匆忙的；草率的',
    'hat': 'n. 帽子',
    'hate': 'v./n. 憎恨；讨厌',
    'have': 'v. 有；拥有',
    'heal': 'v. 治愈；愈合',
    'health': 'n. 健康；卫生',
    'hear': 'v. 听见；听说',
    'heart': 'n. 心脏；核心',
    'heat': 'n./v. 热；加热',
    'heavy': 'adj. 重的；沉重的',
    'help': 'v./n. 帮助；援助',
    'herb': 'n. 草本植物；香草',
    'herd': 'n. 兽群；v. 放牧',
    'here': 'adv. 这里；在这里',
    'hero': 'n. 英雄；男主角',
    'hide': 'v. 隐藏；n. 兽皮',
    'high': 'adj./adv. 高的；高',
    'hill': 'n. 小山；丘陵',
    'hint': 'n./v. 暗示；提示',
    'hire': 'v./n. 雇佣；租金',
    'history': 'n. 历史；历史记录',
    'hit': 'v./n. 打；击中',
    'hold': 'v./n. 持有；握住',
    'hole': 'n. 洞；孔',
    'home': 'n. 家；adj. 家庭的',
    'honest': 'adj. 诚实的；正直的',
    'honor': 'n./v. 荣誉；尊敬',
    'hope': 'n./v. 希望；期望',
    'horn': 'n. 角；喇叭',
    'horse': 'n. 马',
    'hospital': 'n. 医院',
    'host': 'n. 主人；v. 主持',
    'hot': 'adj. 热的；辣的',
    'hour': 'n. 小时；时刻',
    'house': 'n. 房子；v. 容纳',
    'how': 'adv. 如何；怎样',
    'huge': 'adj. 巨大的；庞大的',
    'human': 'adj. 人类的；n. 人',
    'humble': 'adj. 谦逊的；卑微的',
    'hunger': 'n./v. 饥饿；渴望',
    'hunt': 'v./n. 狩猎；搜索',
    'hurt': 'v./n. 伤害；疼痛',
    'husband': 'n. 丈夫',
    'ice': 'n. 冰；v. 结冰',
    'idea': 'n. 想法；主意',
    'image': 'n. 图像；形象',
    'imagine': 'v. 想象；设想',
    'imitate': 'v. 模仿；仿效',
    'immense': 'adj. 巨大的；极大的',
    'impart': 'v. 传授；给予',
    'impel': 'v. 推动；驱使',
    'implement': 'n./v. 工具；实施',
    'implied': 'adj. 隐含的；暗示的',
    'import': 'n./v. 进口；输入',
    'impose': 'v. 强加；征收',
    'improve': 'v. 改善；改进',
    'impulse': 'n. 冲动；推动',
    'in': 'prep. 在...里面',
    'incident': 'n. 事件；事变',
    'include': 'v. 包括；包含',
    'increase': 'v./n. 增加；增长',
    'indeed': 'adv. 确实；真正地',
    'indicate': 'v. 指示；表明',
    'individual': 'adj. 个人的；n. 个人',
    'indoor': 'adj. 室内的',
    'industrial': 'adj. 工业的；产业的',
    'infer': 'v. 推断；推论',
    'influence': 'n./v. 影响；作用',
    'inform': 'v. 通知；告知',
    'inner': 'adj. 内部的；内心的',
    'innocent': 'adj. 无辜的；天真的',
    'input': 'n./v. 输入；投入',
    'inquire': 'v. 询问；调查',
    'insect': 'n. 昆虫',
    'inside': 'prep./adv. 在里面；里面',
    'insist': 'v. 坚持；强调',
    'inspire': 'v. 激励；启发',
    'install': 'v. 安装；设置',
    'instance': 'n. 实例；例子',
    'instant': 'adj. 立即的；n. 瞬间',
    'instead': 'adv. 代替；反而',
    'instrument': 'n. 仪器；工具',
    'insult': 'n./v. 侮辱；冒犯',
    'insurance': 'n. 保险',
    'intend': 'v. 打算；计划',
    'intense': 'adj. 强烈的；紧张的',
    'interest': 'n./v. 兴趣；使感兴趣',
    'interior': 'adj. 内部的；n. 内部',
    'international': 'adj. 国际的',
    'internet': 'n. 互联网',
    'interview': 'n./v. 采访；面试',
    'into': 'prep. 进入；到...里面',
    'introduce': 'v. 介绍；引进',
    'invent': 'v. 发明；创造',
    'invest': 'v. 投资；投入',
    'invite': 'v. 邀请；招致',
    'iron': 'n. 铁；adj. 铁的',
    'island': 'n. 岛屿',
    'issue': 'n./v. 问题；发行',
    'it': 'pron. 它',
    'job': 'n. 工作；职业',
    'join': 'v. 加入；连接',
    'jump': 'v./n. 跳跃；跳',
    'just': 'adj./adv. 公正的；刚刚',
    'keep': 'v. 保持；保存',
    'key': 'n. 钥匙；关键',
    'kill': 'v. 杀死；消灭',
    'kind': 'adj. 善良的；n. 种类',
    'king': 'n. 国王',
    'kit': 'n. 工具包；套装',
    'kitchen': 'n. 厨房',
    'know': 'v. 知道；了解',
    'lake': 'n. 湖；湖泊',
    'land': 'n. 土地；v. 着陆',
    'large': 'adj. 大的；巨大的',
    'last': 'adj. 最后的；v. 持续',
    'late': 'adj./adv. 晚的；晚',
    'laugh': 'v./n. 笑；笑声',
    'law': 'n. 法律；规律',
    'lead': 'v. 领导；n. 铅',
    'leaf': 'n. 叶子；书页',
    'learn': 'v. 学习；学会',
    'leave': 'v. 离开；留下',
    'leg': 'n. 腿；腿部',
    'length': 'n. 长度；时长',
    'letter': 'n. 字母；信件',
    'level': 'n. 水平；adj. 水平的',
    'lift': 'v./n. 举起；电梯',
    'light': 'n./v. 光；点亮',
    'like': 'v./prep. 喜欢；像',
    'line': 'n./v. 线；排队',
    'list': 'n./v. 列表；列出',
    'live': 'v./adj. 生活；活的',
    'long': 'adj./adv. 长的；长久',
    'look': 'v./n. 看；样子',
    'lose': 'v. 失去；丢失',
    'love': 'v./n. 爱；喜欢',
    'low': 'adj./adv. 低的；低',
    'machine': 'n. 机器；机械',
    'make': 'v. 制造；使',
    'man': 'n. 男人；人类',
    'many': 'adj./pron. 许多的；许多',
    'mark': 'n./v. 标记；做标记',
    'market': 'n. 市场；v. 销售',
    'match': 'n./v. 比赛；匹配',
    'matter': 'n. 物质；事情',
    'may': 'v. 可能；可以',
    'me': 'pron. 我',
    'mean': 'v. 意味着；adj. 吝啬的',
    'measure': 'n./v. 测量；措施',
    'meet': 'v./n. 遇见；会议',
    'memory': 'n. 记忆；内存',
    'mind': 'n. 头脑；v. 介意',
    'mine': 'pron. 我的；n. 矿',
    'minute': 'n. 分钟；adj. 微小的',
    'miss': 'v. 错过；想念',
    'mix': 'v./n. 混合；混合物',
    'money': 'n. 钱；货币',
    'month': 'n. 月；月份',
    'more': 'adj./adv. 更多的；更多',
    'most': 'adj./adv. 最多的；最',
    'move': 'v./n. 移动；动作',
    'much': 'adj./adv. 许多的；非常',
    'must': 'v. 必须；一定',
    'name': 'n./v. 名字；命名',
    'nation': 'n. 国家；民族',
    'need': 'v./n. 需要；必要',
    'never': 'adv. 从不；永不',
    'new': 'adj. 新的；新鲜的',
    'next': 'adj./adv. 下一个；接下来',
    'night': 'n. 夜晚；夜间',
    'no': 'adj./adv. 没有；不',
    'not': 'adv. 不；没有',
    'now': 'adv. 现在；如今',
    'number': 'n./v. 数字；编号',
    'of': 'prep. 的；属于',
    'off': 'adv./prep. 离开；关闭',
    'old': 'adj. 老的；旧的',
    'on': 'prep./adv. 在...上面；开',
    'one': 'num./pron. 一；一个',
    'only': 'adj./adv. 唯一的；仅仅',
    'open': 'adj./v. 开着的；打开',
    'or': 'conj. 或者；还是',
    'order': 'n./v. 命令；顺序',
    'out': 'adv./prep. 出去；外面',
    'over': 'prep./adv. 在...上面；结束',
    'own': 'adj./v. 自己的；拥有',
    'page': 'n. 页；页面',
    'pain': 'n./v. 痛苦；疼痛',
    'paint': 'n./v. 油漆；绘画',
    'paper': 'n. 纸；论文',
    'parent': 'n. 父母；家长',
    'part': 'n./v. 部分；分开',
    'pass': 'v./n. 通过；通行证',
    'pay': 'v./n. 支付；工资',
    'people': 'n. 人们；人民',
    'place': 'n./v. 地方；放置',
    'plan': 'n./v. 计划；规划',
    'play': 'v./n. 玩；戏剧',
    'please': 'v./int. 请；使高兴',
    'point': 'n./v. 点；指向',
    'power': 'n./v. 权力；供电',
    'present': 'adj./n. 现在的；礼物',
    'price': 'n./v. 价格；定价',
    'problem': 'n. 问题；难题',
    'produce': 'v./n. 生产；产品',
    'program': 'n./v. 程序；编程',
    'public': 'adj./n. 公共的；公众',
    'put': 'v. 放；放置',
    'question': 'n./v. 问题；询问',
    'quick': 'adj./adv. 快的；快',
    'quite': 'adv. 相当；很',
    'rather': 'adv. 相当；宁愿',
    'reach': 'v./n. 到达；范围',
    'read': 'v./n. 阅读；读物',
    'real': 'adj. 真实的；实际的',
    'right': 'adj./n. 正确的；权利',
    'run': 'v./n. 跑；运行',
    'same': 'adj./pron. 相同的；同样',
    'say': 'v./n. 说；话语',
    'see': 'v. 看见；理解',
    'send': 'v. 发送；派遣',
    'set': 'v./n. 设置；集合',
    'shall': 'v. 将；应该',
    'show': 'v./n. 展示；演出',
    'side': 'n./adj. 边；侧面的',
    'since': 'prep./conj. 自从；因为',
    'small': 'adj. 小的；少的',
    'so': 'adv./conj. 如此；因此',
    'some': 'adj./pron. 一些；某些',
    'soon': 'adv. 很快；不久',
    'sort': 'n./v. 种类；分类',
    'sound': 'n./v. 声音；听起来',
    'speak': 'v. 说；讲话',
    'spell': 'v./n. 拼写；符咒',
    'stand': 'v./n. 站立；立场',
    'star': 'n./v. 星星；主演',
    'start': 'v./n. 开始；启动',
    'state': 'n./v. 状态；陈述',
    'still': 'adj./adv. 静止的；仍然',
    'stop': 'v./n. 停止；车站',
    'such': 'adj./pron. 这样的；如此',
    'take': 'v./n. 拿；采取',
    'tell': 'v. 告诉；讲述',
    'than': 'conj./prep. 比；超过',
    'that': 'pron./conj. 那个；引导从句',
    'the': 'art. 这；那',
    'then': 'adv. 然后；那时',
    'there': 'adv. 那里；存在',
    'these': 'pron./adj. 这些',
    'they': 'pron. 他们；它们',
    'thing': 'n. 东西；事情',
    'think': 'v. 思考；认为',
    'this': 'pron./adj. 这个',
    'those': 'pron./adj. 那些',
    'time': 'n./v. 时间；计时',
    'to': 'prep./inf. 到；不定式符号',
    'too': 'adv. 也；太',
    'two': 'num. 二；两个',
    'under': 'prep./adv. 在...下面；下面',
    'up': 'adv./prep. 向上；起来',
    'use': 'v./n. 使用；用途',
    'very': 'adv. 非常；很',
    'want': 'v./n. 想要；需要',
    'way': 'n. 方式；道路',
    'we': 'pron. 我们',
    'well': 'adv./adj. 好地；健康的',
    'what': 'pron./adj. 什么；多么',
    'when': 'adv./conj. 何时；当...时',
    'where': 'adv./conj. 哪里；在...地方',
    'which': 'pron./adj. 哪个；哪一个',
    'who': 'pron. 谁',
    'why': 'adv./conj. 为什么；...的原因',
    'will': 'v./n. 将；意志',
    'with': 'prep. 和；带有',
    'work': 'v./n. 工作；作品',
    'world': 'n. 世界；全球',
    'would': 'v. 会；将要',
    'year': 'n. 年；年份',
    'you': 'pron. 你；你们',
    'young': 'adj./n. 年轻的；年轻人'
  };
  
  let count = 0;
  words.forEach(w => {
    const lowerWord = w.word.toLowerCase();
    if (wordMap[lowerWord]) {
      w.meaning = wordMap[lowerWord];
      count++;
    }
  });
  
  const output = 'export interface IELTSWord {\n  id: string;\n  word: string;\n  meaning: string;\n  level: string;\n  root: string;\n  rootMeaning: string;\n  rootMeaningEn: string;\n  rootOrigin: string;\n  rootOriginNote: string;\n  relatedWords: { word: string; meaning: string; level: string }[];\n  phonetic: string;\n  frequency: string;\n  example: string;\n}\n\nexport const mockWords: IELTSWord[] = ' + JSON.stringify(words, null, 2) + ';';
  
  fs.writeFileSync('/home/fred/workspace/memoryworld-project/src/data/mockWords.ts', output);
  console.log('修复了 ' + count + ' 个单词的中文释义');
  console.log('保存成功!');
}