const fs = require('fs');

const data = fs.readFileSync('/home/fred/workspace/memoryworld-project/src/data/mockWords.ts', 'utf8');
const match = data.match(/export const mockWords: IELTSWord\[\] = \[([\s\S]*?)\];/);

if (match) {
  const words = JSON.parse('[' + match[1] + ']');
  
  const completeMeanings = {
    'foam': 'n. 泡沫；泡沫材料 v. 起泡沫',
    'forge': 'n. 锻造车间；熔炉 v. 锻造；伪造',
    'foam': 'n. 泡沫；泡沫材料 v. 起泡沫',
    'fold': 'v. 折叠；合拢 n. 褶痕；折叠部分',
    'folk': 'n. 人们；民族；家属 adj. 民间的',
    'fond': 'adj. 喜欢的；喜爱的；宠爱的',
    'forbid': 'v. 禁止；不许；阻止',
    'force': 'n. 力量；武力；军队 v. 强迫；迫使',
    'forge': 'v. 锻造；伪造；缔造',
    'format': 'n. 格式；版式 v. 格式化；安排',
    'formula': 'n. 公式；配方；准则',
    'forth': 'adv. 向前；向外；继续',
    'fortnight': 'n. 两周；十四天',
    'forum': 'n. 论坛；讨论会；公共集会场所',
    'fossil': 'n. 化石；僵化的事物 adj. 化石的',
    'foster': 'v. 培养；促进；收养 adj. 收养的',
    'found': 'v. 建立；创立；创办',
    'foundation': 'n. 基础；地基；基金会',
    'founder': 'n. 创始人；建立者 v. 摔倒；沉没',
    'fountain': 'n. 喷泉；泉水；源泉',
    'fowl': 'n. 禽；家禽；鸟',
    'fraction': 'n. 分数；部分；小部分',
    'fragment': 'n. 碎片；片段 v. 使成碎片',
    'frame': 'n. 框架；结构 v. 给...装框子',
    'framework': 'n. 框架；结构；体系',
    'frank': 'adj. 坦白的；直率的 v. 免费邮寄',
    'fraud': 'n. 欺诈；骗局；骗子',
    'freak': 'n. 怪人；畸形；狂热爱好者 adj. 奇异的',
    'free': 'adj. 自由的；免费的 v. 使自由；释放',
    'freedom': 'n. 自由；自主',
    'freely': 'adv. 自由地；免费地；坦率地',
    'freeze': 'v. 冻结；冷冻；僵住 n. 冻结；冰冻',
    'freight': 'n. 货运；运费；货物 v. 运送；使负担',
    'frequency': 'n. 频率；频繁；次数',
    'frequent': 'adj. 频繁的；常见的 v. 常去；常到',
    'fresh': 'adj. 新鲜的；清新的；无经验的',
    'friction': 'n. 摩擦；摩擦力；冲突',
    'fridge': 'n. 电冰箱；冷藏室',
    'fried': 'adj. 油炸的；喝醉的',
    'friend': 'n. 朋友；伙伴',
    'friendly': 'adj. 友好的；亲切的',
    'friendship': 'n. 友谊；友好；友情',
    'fright': 'n. 惊吓；恐怖；恐怖事件',
    'frighten': 'v. 使惊吓；吓唬；害怕',
    'frog': 'n. 青蛙；蛙',
    'front': 'n. 前面；前线；方面 v. 面对；朝向',
    'frontier': 'n. 边境；边界；新领域',
    'frost': 'n. 霜；冰冻；严寒 v. 结霜；受冻',
    'frown': 'v. 皱眉；蹙眉 n. 皱眉；蹙眉',
    'fruit': 'n. 水果；果实；成果 v. 结果实',
    'fruitful': 'adj. 多产的；果实累累的；成功的',
    'frustrate': 'v. 挫败；使沮丧；使无效',
    'frustration': 'n. 挫折；沮丧；不满',
    'fuel': 'n. 燃料；刺激因素 v. 供给燃料；激起',
    'fulfil': 'v. 完成；履行；实现',
    'fulfillment': 'n. 完成；实现；满足感',
    'full': 'adj. 满的；完整的；充实的 adv. 完全地',
    'fully': 'adv. 完全地；充分地；全部地',
    'fume': 'n. 烟；气体；愤怒 v. 熏；冒烟；发怒',
    'function': 'n. 功能；职能；函数 v. 运作；起作用',
    'fund': 'n. 基金；资金 v. 资助；为...提供资金',
    'fundamental': 'adj. 基本的；根本的 n. 基本原则',
    'funeral': 'n. 葬礼；丧礼 adj. 葬礼的',
    'funny': 'adj. 可笑的；有趣的；滑稽的',
    'furnace': 'n. 火炉；熔炉；热不胜收的事',
    'furnish': 'v. 供给；装备；布置',
    'furniture': 'n. 家具；设备；附属品',
    'further': 'adv. 更远地；进一步 adj. 更远的；更多的',
    'furthermore': 'adv. 而且；此外；再者',
    'fury': 'n. 愤怒；狂暴；激烈',
    'fuse': 'n. 保险丝；导火线 v. 熔合；混合',
    'fuss': 'n. 大惊小怪；骚动 v. 忙乱；打扰',
    'future': 'n. 未来；前途 adj. 将来的；未来的',
    'gain': 'v. 获得；增加；获利 n. 收益；增益',
    'gallery': 'n. 美术馆；画廊；走廊',
    'gallon': 'n. 加仑（容量单位）',
    'gamble': 'v. 赌博；投机 n. 赌博；冒险',
    'game': 'n. 游戏；比赛；猎物 adj. 游戏的；勇敢的',
    'gang': 'n. 一帮；一群；团伙 v. 合伙；结伙',
    'gap': 'n. 缺口；差距；间隙 v. 拉开距离',
    'garage': 'n. 车库；汽车修理厂 v. 把车放入车库',
    'garbage': 'n. 垃圾；废物；无用信息',
    'garden': 'n. 花园；菜园 v. 从事园艺',
    'gardener': 'n. 园丁；花匠；园艺家',
    'garlic': 'n. 大蒜；蒜头',
    'garment': 'n. 衣服；服装；外衣',
    'garrison': 'n. 卫戍部队；驻军 v. 驻防；守卫',
    'gate': 'n. 大门；登机口 v. 给...装大门',
    'gather': 'v. 聚集；收集；推断 n. 聚集；收获',
    'gauge': 'n. 测量仪器；标准；规格 v. 测量；估计',
    'gaze': 'v. 凝视；注视 n. 凝视；注视',
    'gear': 'n. 齿轮；装置；排挡 v. 换挡；使适合',
    'gender': 'n. 性别；性 v. 产生',
    'gene': 'n. 基因；遗传因子',
    'general': 'adj. 一般的；普遍的 n. 将军；概要',
    'generate': 'v. 生成；产生；引起',
    'generation': 'n. 一代；产生；一代人',
    'generous': 'adj. 慷慨的；宽宏大量的；丰富的',
    'genetic': 'adj. 遗传的；基因的 n. 遗传学',
    'genius': 'n. 天才；天赋；精神',
    'gentle': 'adj. 温和的；轻柔的；文雅的',
    'gentleman': 'n. 绅士；先生；男人',
    'genuine': 'adj. 真实的；真正的；诚恳的',
    'geography': 'n. 地理；地形；地理学',
    'geology': 'n. 地质学；地质情况',
    'geometry': 'n. 几何学；几何形状',
    'gesture': 'n. 姿势；手势；姿态 v. 做手势',
    'ghost': 'n. 鬼；幽灵；一点点 v. 替...捉刀',
    'giant': 'n. 巨人；伟人 adj. 巨大的',
    'gift': 'n. 礼物；天赋；赠品 v. 赠送；赋予',
    'gifted': 'adj. 有天赋的；有才华的',
    'gigantic': 'adj. 巨大的；庞大的',
    'girl': 'n. 女孩；女儿；女朋友',
    'girlfriend': 'n. 女朋友；女性朋友',
    'give': 'v. 给；给予；付出；让步',
    'given': 'v. 给（give过去分词）adj. 特定的；假定的',
    'glad': 'adj. 高兴的；乐意的；令人高兴的',
    'glance': 'v. 扫视；匆匆一看 n. 一瞥；扫视',
    'glare': 'v. 怒目而视；发出刺眼光芒 n. 怒视；眩光',
    'glass': 'n. 玻璃；玻璃杯；镜子 v. 反映；装玻璃',
    'glimpse': 'v. 瞥见；开始领悟 n. 一瞥；模糊的感觉',
    'global': 'adj. 全球的；整体的；总括的',
    'globe': 'n. 地球；地球仪；球体 v. 成球状',
    'gloom': 'n. 黑暗；忧郁；阴影 v. 使黑暗；使忧郁',
    'gloomy': 'adj. 黑暗的；忧郁的；令人沮丧的',
    'glory': 'n. 光荣；荣誉；壮丽 v. 自豪；得意',
    'glossary': 'n. 词汇表；术语汇编',
    'glove': 'n. 手套 v. 给...戴手套',
    'goal': 'n. 目标；球门；进球 v. 射门得分',
    'goat': 'n. 山羊；替罪羊',
    'god': 'n. 上帝；神；偶像 v. 使神化',
    'gold': 'n. 金子；金币；金色 adj. 金的；金色的',
    'golden': 'adj. 金色的；宝贵的；得意的',
    'golf': 'n. 高尔夫球 v. 打高尔夫球',
    'good': 'adj. 好的；善良的；擅长的 n. 好处；善行',
    'goods': 'n. 商品；货物；动产',
    'goodwill': 'n. 善意；友好；商誉',
    'goose': 'n. 鹅；雌鹅；傻瓜 v. 突然催促',
    'govern': 'v. 统治；管理；支配；约束',
    'government': 'n. 政府；政体；统治',
    'governor': 'n. 州长；总督；管理者；董事',
    'grace': 'n. 优雅；恩典；魅力 v. 使优美；惠赐',
    'graceful': 'adj. 优雅的；得体的；好看的',
    'grade': 'n. 年级；等级；成绩 v. 分级；评分',
    'gradual': 'adj. 渐进的；逐步的；坡度平缓的',
    'gradually': 'adv. 逐步地；渐渐地',
    'graduate': 'v. 毕业；获得学位 n. 毕业生 adj. 毕业的',
    'grain': 'n. 谷物；粮食；颗粒 v. 使成谷粒',
    'gram': 'n. 克（重量单位）',
    'grammar': 'n. 语法；语法书；基本原理',
    'grand': 'adj. 宏伟的；壮丽的；主要的',
    'grandfather': 'n. 祖父；外祖父',
    'grandmother': 'n. 祖母；外祖母',
    'granite': 'n. 花岗岩； granite 冷酷无情的人',
    'grape': 'n. 葡萄；葡萄藤',
    'graph': 'n. 图表；曲线图 v. 用图表表示',
    'graphic': 'adj. 绘画的；生动的；图表的 n. 图表',
    'grasp': 'v. 抓住；领会；理解 n. 抓住；理解；控制',
    'grass': 'n. 草；草地；牧场 v. 喂草；使...长草',
    'grateful': 'adj. 感激的；感谢的；令人欣慰的',
    'grave': 'n. 坟墓；死亡 adj. 严肃的；沉重的',
    'gravity': 'n. 重力；引力；严重性；庄重',
    'gray': 'adj. 灰色的；苍白的；阴郁的 n. 灰色 v. 使变灰',
    'grease': 'n. 油脂；润滑油 v. 涂油脂；贿赂',
    'greasy': 'adj. 油腻的；滑的；谄媚的',
    'great': 'adj. 伟大的；重要的；好极了 adv. 很；极大地',
    'greatly': 'adv. 大大地；非常；很',
    'green': 'adj. 绿色的；环保的；无经验的 n. 绿色；草坪',
    'greenhouse': 'n. 温室；花房 adj. 温室效应的',
    'greet': 'v. 问候；迎接；致意',
    'greeting': 'n. 问候；招呼；祝贺',
    'grey': 'adj. 灰色的；苍白的 n. 灰色 v. 使变灰',
    'grief': 'n. 悲伤；痛苦；不幸',
    'grieve': 'v. 悲伤；哀悼；使伤心',
    'grim': 'adj. 冷酷的；残忍的；严肃的',
    'grin': 'v. 露齿而笑；咧着嘴笑 n. 露齿笑',
    'grind': 'v. 磨碎；折磨；压迫 n. 磨；苦差事',
    'grip': 'v. 紧握；夹紧；控制 n. 握紧；手柄；掌握',
    'groan': 'v. 呻吟；抱怨；发出吱嘎声 n. 呻吟声',
    'grocery': 'n. 杂货店；杂货；食品杂货',
    'groom': 'n. 马夫；新郎；男仆 v. 刷洗；打扮',
    'grope': 'v. 摸索；探索 n. 摸索；探索',
    'gross': 'adj. 总的；粗野的；令人作呕的 v. 总共收入 n. 总额',
    'ground': 'n. 地面；土地；场所 v. 搁浅；触地',
    'group': 'n. 组；团体；群体 v. 聚合；成群',
    'grove': 'n. 小树林；树丛；园林',
    'grow': 'v. 生长；成长；变成；培养',
    'growth': 'n. 增长；生长；发展',
    'guarantee': 'v. 保证；担保 n. 保证；保证书；担保人',
    'guard': 'v. 保卫；看守；警惕 n. 警卫；保卫；看守',
    'guess': 'v. 猜测；推测；猜中 n. 猜测；推测',
    'guest': 'n. 客人；宾客；旅客 v. 招待；作客',
    'guidance': 'n. 指导；引导；咨询',
    'guide': 'v. 引导；指导；管理 n. 导游；指南；向导',
    'guideline': 'n. 方针；指南；准则',
    'guilt': 'n. 犯罪；罪行；内疚',
    'guilty': 'adj. 有罪的；内疚的；心虚的',
    'guitar': 'n. 吉他；六弦琴 v. 弹吉他',
    'gulf': 'n. 海湾；鸿沟；分歧 v. 吞没',
    'gust': 'n. 阵风；一阵（雨、烟等） v. 风吹得阵阵响',
    'habit': 'n. 习惯；习性；气质',
    'habitat': 'n. 栖息地；产地；住所在',
    'hair': 'n. 头发；毛发；绒毛 v. 毛出现',
    'half': 'n. 半；一半 adj. 一半的 adv. 一半地',
    'hall': 'n. 大厅；礼堂；门厅',
    'halt': 'v. 停止；使停止；踌躇 n. 停止；暂停',
    'hammer': 'n. 锤子；榔头 v. 锤击；反复推敲',
    'hand': 'n. 手；人手；帮助 v. 递；给；交',
    'handful': 'n. 一把；少数；难管的人',
    'handicap': 'n. 障碍；不利条件 v. 妨碍；设置障碍',
    'handle': 'v. 处理；操作；触摸 n. 把手；柄',
    'handsome': 'adj. 英俊的；慷慨的；可观的',
    'handwriting': 'n. 笔迹；手写；手写稿',
    'hang': 'v. 悬挂；垂下；装饰 n. 悬挂；悬挂方式',
    'happen': 'v. 发生；碰巧；出现',
    'happy': 'adj. 高兴的；幸福的；乐意的',
    'harbour': 'n. 海港；港口 v. 藏匿；心怀；为...提供庇护',
    'hard': 'adj. 硬的；困难的；冷酷的 adv. 努力地；猛烈地',
    'hardly': 'adv. 几乎不；刚刚；仅仅',
    'hardware': 'n. 五金器具；硬件；装备',
    'harm': 'n./v. 伤害；损害；危害',
    'harmful': 'adj. 有害的；能造成损害的',
    'harmony': 'n. 和谐；和睦；协调',
    'harsh': 'adj. 粗糙的；刺耳的；严酷的',
    'harvest': 'n. 收获；产量；成果 v. 收获；收割',
    'haste': 'n. 匆忙；急忙；轻率 v. 赶紧；匆忙做',
    'hasty': 'adj. 匆忙的；草率的；轻率的',
    'hate': 'v. 恨；讨厌；憎恨 n. 厌恶；讨厌的事',
    'hatred': 'n. 仇恨；憎恨；敌意',
    'haul': 'v. 拖；拉；搬运 n. 拖；拉；捕获量',
    'haunt': 'v. 常去；缠住；萦绕 n. 常去的地方',
    'hawk': 'n. 鹰；隼；主战派 v. 沿街叫卖',
    'hazard': 'n. 危险；危害；冒险 v. 冒险；使遭受危险',
    'head': 'n. 头；头部；领袖 v. 率领；朝向；领先',
    'headline': 'n. 大字标题；新闻提要 v. 给...加标题',
    'headquarters': 'n. 总部；指挥部；大本营',
    'heal': 'v. 治愈；痊愈；和解',
    'health': 'n. 健康；卫生；保健',
    'healthy': 'adj. 健康的；健全的；有益健康的',
    'heap': 'n. 堆；大量；许多 v. 堆积；装满',
    'hear': 'v. 听到；听说；审理；倾听',
    'hearing': 'n. 听力；听觉；审讯；意见听取会',
    'heart': 'n. 心；心脏；中心；勇气 v. 把...放在中心',
    'heat': 'n. 热；热度；热烈 v. 加热；使激动',
    'heater': 'n. 加热器；暖气机',
    'heaven': 'n. 天堂；天空；极乐之地',
    'heavily': 'adv. 重重地；大量地；沉重地',
    'heavy': 'adj. 重的；沉重的；大量的 adv. 沉重地',
    'hedge': 'n. 树篱；障碍；防备 v. 用树篱围；回避',
    'heel': 'n. 脚后跟；足跟 v. 倾侧；追赶',
    'height': 'n. 高度；身高；高处',
    'heighten': 'v. 提高；增高；加强',
    'heir': 'n. 继承人；后嗣；传承者',
    'helicopter': 'n. 直升机 v. 用直升机运送',
    'hell': 'n. 地狱；极大的痛苦；混沌之地',
    'hello': 'int. 你好；喂 v. 说"喂"',
    'helmet': 'n. 头盔；防护帽',
    'help': 'v. 帮助；帮忙；有用 n. 帮助；援助；帮手',
    'helpful': 'adj. 有帮助的；有益的；愿意帮忙的',
    'hemisphere': 'n. 半球；大脑半球',
    'hen': 'n. 母鸡；雌鸟；女人',
    'hence': 'adv. 因此；所以；今后',
    'her': 'pron. 她；她的',
    'herb': 'n. 草本植物；药草；香草',
    'herd': 'n. 兽群；牧群；人群 v. 群集；使成群',
    'hero': 'n. 英雄；男主角；偶像',
    'heroic': 'adj. 英雄的；英勇的；冒险的',
    'heroin': 'n. 海洛因；女英雄',
    'heroine': 'n. 女英雄；女主角；女偶像',
    'hers': 'pron. 她的（东西）',
    'herself': 'pron. 她自己',
    'hesitate': 'v. 犹豫；踌躇；不情愿',
    'hide': 'v. 隐藏；隐瞒；躲藏 n. 兽皮；躲藏处',
    'hierarchy': 'n. 等级制度；层级；统治集团',
    'high': 'adj. 高的；高级的；高尚的 adv. 高；高价地',
    'highlight': 'n. 最精彩的部分；强光 v. 突出；强调',
    'highly': 'adv. 高度地；非常；赞许地',
    'highway': 'n. 公路；高速公路；主干道',
    'hijack': 'v. 劫持；绑架；拦路抢劫 n. 劫持；敲诈',
    'hike': 'v. 徒步旅行；上升；提高 n. 徒步旅行；涨价',
    'hill': 'n. 小山；丘陵；斜坡',
    'him': 'pron. 他（宾格）',
    'himself': 'pron. 他自己',
    'hint': 'n. 暗示；线索；提示 v. 暗示；示意',
    'hire': 'v. 租用；雇用；聘用 n. 租用；雇用；租金',
    'historian': 'n. 历史学家；编史者',
    'historic': 'adj. 历史上著名的；具有历史意义的',
    'historical': 'adj. 历史的；历史学的；基于史实的',
    'history': 'n. 历史；来历；历史学',
    'hold': 'v. 握住；持有；认为 n. 握住；控制；影响',
    'holder': 'n. 持有人；占有者；支持物',
    'hole': 'n. 洞；孔；穴 v. 凿洞；穿孔',
    'holiday': 'n. 假日；节日；假期 v. 度假',
    'hollow': 'adj. 空的；空洞的；虚伪的 n. 洞；山谷 v. 挖空',
    'holy': 'adj. 神圣的；圣洁的；虔诚的',
    'home': 'n. 家；家庭；故乡 adv. 在家；回家 adj. 家庭的',
    'homeland': 'n. 祖国；故乡',
    'homeless': 'adj. 无家可归的 n. 无家可归者',
    'homework': 'n. 家庭作业；准备工作',
    'honest': 'adj. 诚实的；正直的；坦率的',
    'honestly': 'adv. 诚实地；的确；说实在地',
    'honey': 'n. 蜂蜜；宝贝；甜蜜',
    'honour': 'n. 荣誉；尊敬；光荣 v. 尊敬；给...以荣誉',
    'honourable': 'adj. 荣誉的；可敬的；正直的',
    'hood': 'n. 头巾；覆盖物；罩 v. 给...加罩',
    'hoof': 'n. 蹄；足尖 v. 用蹄踢；走',
    'hook': 'n. 钩子；钩状物 v. 钩住；引诱上钩',
    'hope': 'v./n. 希望；期望；希望的东西',
    'hopeful': 'adj. 有希望的；抱有希望的 n. 希望成功的人',
    'hopefully': 'adv. 有希望地；满怀希望地；如果可以的话',
    'horizon': 'n. 地平线；视野；范围',
    'horizontal': 'adj. 水平的；横的 n. 水平线；水平面',
    'hormone': 'n. 激素；荷尔蒙；性激素',
    'horn': 'n. 喇叭；号角；角 v. 装角于；强行介入',
    'horrible': 'adj. 可怕的；极讨厌的；糟糕的',
    'horror': 'n. 恐怖；战栗；厌恶 adj. 恐怖电影的',
    'horse': 'n. 马；骑兵；支架 v. 骑；系马',
    'hospital': 'n. 医院；旅客招待所；慈善收容所',
    'hospitality': 'n. 好客；款待；殷勤',
    'host': 'n. 主人；主持人；主机 v. 主持；当主人招待',
    'hostage': 'n. 人质；抵押品',
    'hostile': 'adj. 敌对的；敌意的；不友好的',
    'hostility': 'n. 敌意；战争行动；愤怒',
    'hotel': 'n. 旅馆；酒店；饭店',
    'hound': 'n. 猎犬；卑劣的人 v. 追猎；烦扰',
    'hour': 'n. 小时；时间；时刻',
    'house': 'n. 房子；住宅；家庭 v. 给...房子住；容纳',
    'household': 'n. 家庭；户 adj. 家庭的；日常的',
    'housewife': 'n. 家庭主妇',
    'housing': 'n. 住房；住宅；外壳',
    'hover': 'v. 盘旋；徘徊；悬停 n. 盘旋；悬停',
    'however': 'adv. 然而；可是；无论如何 conj. 无论以何种方式',
    'huge': 'adj. 巨大的；庞大的；无限的',
    'hull': 'n. 外壳；船体；豆荚 v. 去壳',
    'human': 'adj. 人的；人类的 n. 人；人类',
    'humble': 'adj. 谦逊的；简陋的；卑下的 v. 使谦卑',
    'humid': 'adj. 潮湿的；湿润的；多湿气的',
    'humour': 'n. 幽默；诙谐；心情 v. 迁就；迎合',
    'hundred': 'num. 百；一百；许多 adj. 一百的；许多的',
    'hunger': 'n. 饥饿；渴望 v. 挨饿；渴望',
    'hungry': 'adj. 饥饿的；渴望的',
    'hunt': 'v. 狩猎；追捕；搜寻 n. 狩猎；追捕',
    'hunter': 'n. 猎人；搜寻者；猎犬',
    'hurricane': 'n. 飓风；暴风',
    'hurry': 'v. 匆忙；赶紧；加快 n. 匆忙；急事',
    'hurt': 'v. 伤害；损害；使疼痛 adj. 受伤的；痛苦的',
    'husband': 'n. 丈夫 v. 节约使用；管理',
    'hut': 'n. 小屋；茅屋；临时建筑 v. 提供小屋',
    'hydrogen': 'n. 氢；氢气'
  };
  
  let fixed = 0;
  
  words.forEach(w => {
    const key = w.word.toLowerCase();
    if (completeMeanings[key]) {
      w.meaning = completeMeanings[key];
      fixed++;
    }
  });
  
  console.log('修复了', fixed, '个单词的meaning');
  
  const output = 'export interface IELTSWord {\n' +
    '  id: string;\n' +
    '  word: string;\n' +
    '  meaning: string;\n' +
    '  level: string;\n' +
    '  root: string;\n' +
    '  rootMeaning: string;\n' +
    '  rootMeaningEn: string;\n' +
    '  rootOrigin: string;\n' +
    '  rootOriginNote: string;\n' +
    '  relatedWords: { word: string; meaning: string; level: string }[];\n' +
    '  phonetic: string;\n' +
    '  frequency: string;\n' +
    '  example: string;\n' +
    '}\n\n' +
    'export const mockWords: IELTSWord[] = ' + JSON.stringify(words, null, 2) + ';';
  
  fs.writeFileSync('/home/fred/workspace/memoryworld-project/src/data/mockWords.ts', output);
  console.log('保存成功!');
}
