const fs = require('fs');

const data = fs.readFileSync('/home/fred/workspace/memoryworld-project/src/data/mockWords.ts', 'utf8');
const match = data.match(/export const mockWords: IELTSWord\[\] = \[([\s\S]*?)\];/);

if (match) {
  const words = JSON.parse('[' + match[1] + ']');
  
  const completeMeanings = {
    'polar': 'adj. 极地的；正好相反的；磁极的 n. 极地',
    'pole': 'n. 杆；柱；极；磁极 v. 用杆支撑',
    'polish': 'v. 擦亮；磨光；改进 n. 光泽；优雅；擦亮剂',
    'policy': 'n. 政策；方针；保险单',
    'polite': 'adj. 有礼貌的；客气的；优雅的',
    'political': 'adj. 政治的；党派的',
    'politician': 'n. 政治家；政客',
    'politics': 'n. 政治；政治学；政见',
    'poll': 'n. 投票；民意调查；投票数 v. 投票；进行民意调查',
    'pollute': 'v. 污染；玷污；破坏',
    'pollution': 'n. 污染；污染物；腐败',
    'pond': 'n. 池塘；鱼塘 v. 筑成池塘',
    'ponder': 'v. 考虑；沉思；衡量',
    'pool': 'n. 水池；撞球；联营 v. 合伙经营；共用',
    'poor': 'adj. 贫穷的；可怜的；贫乏的',
    'pop': 'v. 突然出现；爆开 n. 流行音乐；砰声 adj. 流行的',
    'popular': 'adj. 流行的；受欢迎的；通俗的',
    'popularity': 'n. 流行；普及；受欢迎',
    'population': 'n. 人口；种群；全体居民',
    'porch': 'n. 门廊；走廊；阳台',
    'pore': 'n. 毛孔；气孔；细孔 v. 注视；凝视；深思',
    'pork': 'n. 猪肉；猪皮',
    'port': 'n. 港口；端口；门户网站 v. 搬运；持枪',
    'portal': 'n. 门户；大门；入口',
    'portion': 'n. 部分；一份；命运 v. 分配；分摊',
    'portrait': 'n. 肖像；描写；雕像',
    'portray': 'v. 描绘；扮演；描写',
    'pose': 'v. 摆姿势；造成；提出 n. 姿势；假装',
    'position': 'n. 位置；职位；立场 v. 安置；定位',
    'positive': 'adj. 积极的；肯定的；阳性的 n. 积极；正面',
    'possess': 'v. 拥有；控制；掌握',
    'possession': 'n. 拥有；财产；所有物',
    'possibility': 'n. 可能性；可能的事',
    'possible': 'adj. 可能的；合理的 n. 可能；可能性',
    'post': 'n. 岗位；邮件；标杆 v. 张贴；公布；邮寄',
    'postage': 'n. 邮资；邮费',
    'postcard': 'n. 明信片',
    'poster': 'n. 海报；张贴者',
    'postpone': 'v. 延期；推迟；延迟',
    'pot': 'n. 锅；罐；壶 v. 装罐；射中',
    'potato': 'n. 土豆；马铃薯',
    'potential': 'adj. 潜在的；可能的 n. 潜力；可能性',
    'potion': 'n. 一剂；药水；饮料',
    'pottery': 'n. 陶器；陶艺；陶器厂',
    'poultry': 'n. 家禽；禽肉',
    'pound': 'n. 磅；英镑；重击 v. 捣碎；连续敲打',
    'pour': 'v. 倾倒；灌注；倾泻 n. 倾泻；流出',
    'poverty': 'n. 贫困；贫穷；贫乏',
    'powder': 'n. 粉末；粉；火药 v. 撒粉；使成粉末',
    'power': 'n. 力量；能力；电力；权力 v. 供以动力',
    'powerful': 'adj. 强大的；有力的；权力大的',
    'practical': 'adj. 实际的；实用的；实践的',
    'practice': 'n. 实践；练习；惯例 v. 实践；练习',
    'practise': 'v. 实践；练习；从事',
    'practitioner': 'n. 从业者；练习者；开业医生',
    'praise': 'v. 赞扬；称赞；崇拜 n. 赞扬；赞美；称赞',
    'pray': 'v. 祈祷；请求；祈求',
    'prayer': 'n. 祈祷；恳求；祈祷文',
    'preach': 'v. 传道；说教；鼓吹 n. 说教；讲道',
    'precious': 'adj. 珍贵的；宝贵的；贵重的',
    'precise': 'adj. 精确的；准确的；明确的',
    'precision': 'n. 精确；精度；严谨',
    'predict': 'v. 预言；预测；预报',
    'prediction': 'n. 预言；预测；预报',
    'predominant': 'adj. 主要的；突出的；盛行的',
    'preface': 'n. 前言；序言；开端 v. 为...写序言',
    'prefer': 'v. 更喜欢；宁愿；倾向于',
    'preferable': 'adj. 更好的；更可取的；更优越的',
    'preference': 'n. 偏爱；优先；喜爱物',
    'pregnant': 'adj. 怀孕的；重要的；孕育的',
    'prejudice': 'n. 偏见；成见；侵害 v. 使有偏见；损害',
    'preliminary': 'adj. 初步的；预备的 n. 初步；预选赛',
    'premier': 'adj. 首要的；最前的 n. 总理；首相',
    'premise': 'n. 前提；房屋；企业不动产 v. 以...为前提',
    'premium': 'n. 保险费；额外费用；奖金 adj. 优质的；高昂的',
    'preparation': 'n. 准备；预备；准备工作',
    'prepare': 'v. 准备；使准备好；制定',
    'preposition': 'n. 介词；前置词',
    'prescribe': 'v. 规定；开处方；命令',
    'prescription': 'n. 处方；药方；指示',
    'presence': 'n. 存在；出席；到场',
    'present': 'adj. 现在的；出席的；在场的 v. 呈现；赠送；提出',
    'presentation': 'n. 展示；描述；报告；发布会',
    'presently': 'adv. 目前；马上；一会儿',
    'preserve': 'v. 保存；保护；维持 n. 保护区；蜜饯',
    'preside': 'v. 主持；担任主席；管理',
    'president': 'n. 总统；校长；会长',
    'presidential': 'adj. 总统的；首长的；支配的',
    'press': 'v. 压；按；逼迫 n. 压；按；新闻；出版社',
    'pressure': 'n. 压力；压迫；压强 v. 对...施压；迫使',
    'prestigious': 'adj. 有声望的；受尊敬的；权威的',
    'presumably': 'adv. 推测地；大概；可能',
    'pretend': 'v. 假装；装作；自称 adj. 假装的；伪称的',
    'pretty': 'adj. 漂亮的；可爱的；优美的 adv. 相当；颇',
    'prevail': 'v. 流行；战胜；占优势',
    'prevailing': 'adj. 流行的；普遍的；主要的',
    'prevent': 'v. 预防；阻止；防止',
    'previous': 'adj. 以前的；早先的；过快的 adv. 在...之前',
    'previously': 'adv. 之前；从前；预先',
    'prey': 'n. 猎物；受害者；捕获 v. 捕食；掠夺；折磨',
    'price': 'n. 价格；代价；价值 v. 标价；定价；比较价格',
    'priceless': 'adj. 无价的；极贵重的；无法估价的',
    'pride': 'n. 自豪；骄傲；自尊 v. 以...自豪；得意',
    'priest': 'n. 牧师；神父；祭司',
    'primarily': 'adv. 主要地；首先；根本上',
    'primary': 'adj. 主要的；初级的；基本的 n. 首要； Primary',
    'prime': 'adj. 主要的；最好的；最初的 n. 青春；精华 v. 准备；预先指导',
    'primitive': 'adj. 原始的；简单的；落后的 n. 原始人； primitive',
    'prince': 'n. 王子；亲王；巨头',
    'princess': 'n. 公主；王妃；贵妇',
    'principal': 'adj. 主要的；资本的 n. 校长；主角；本金',
    'principle': 'n. 原理；原则；信条；本质',
    'print': 'v. 印刷；打印；出版 n. 印刷品；字体；版画',
    'printer': 'n. 打印机；印刷工；印刷者',
    'printing': 'n. 印刷；印刷术；印花',
    'prior': 'adj. 在前的；优先的 n. 预先；在先',
    'priority': 'n. 优先；优先权；优先考虑的事',
    'prison': 'n. 监狱；监禁；牢笼 v. 监禁；关押',
    'prisoner': 'n. 囚犯；俘虏；拘留犯',
    'privacy': 'n. 隐私；秘密；隐居',
    'private': 'adj. 私人的；个人的；秘密的 n. 士兵；私下',
    'privilege': 'n. 特权；优待；恩典 v. 给予...特权；特免',
    'prize': 'n. 奖品；奖赏；奖金 v. 珍视；捕获 adj. 获奖的',
    'probable': 'adj. 可能的；大概的；可信的',
    'probably': 'adv. 大概；或许；很可能',
    'probe': 'v. 探索；调查；探测 n. 探针；探测器；调查',
    'problem': 'n. 问题；难题；疑问 adj. 问题的；有难点的',
    'procedural': 'adj. 程序上的；手续的；过程的',
    'procedure': 'n. 程序；步骤；手续',
    'proceed': 'v. 继续进行；发生；起诉 n. 收入；获利',
    'proceeding': 'n. 进程；进行；诉讼程序',
    'process': 'n. 过程；工序；方法 v. 加工；处理；列队行进',
    'procession': 'n. 行列；队伍；行进 v. 排队行进',
    'processor': 'n. 处理器；加工者',
    'proclaim': 'v. 宣告；宣布；声明；表明',
    'produce': 'v. 生产；产生；制造；引起 n. 产品；农产品',
    'producer': 'n. 生产者；制造者；制片人',
    'product': 'n. 产品；产物；结果；乘积',
    'production': 'n. 生产；制作；产量；作品',
    'productive': 'adj. 多产的；生产的；富有成效的',
    'productivity': 'n. 生产力；生产率；多产',
    'profession': 'n. 职业；专业；声明；表白',
    'professional': 'adj. 专业的；职业的 n. 专业人员；职业选手',
    'professor': 'n. 教授；教师；声称者',
    'proficient': 'adj. 熟练的；精通的 n. 熟练；能手',
    'profit': 'n. 利润；利益；盈利 v. 获利；有益于',
    'profitable': 'adj. 有利可图的；赚钱的；有益的',
    'profound': 'adj. 深刻的；意义深远的；渊博的',
    'program': 'n. 程序；计划；节目 v. 编程；安排；制定',
    'programme': 'n. 节目；计划；方案 v. 计划；安排',
    'programmer': 'n. 程序员；编程者',
    'progress': 'n. 进步；进展；前进 v. 进步；进行；发展',
    'progressive': 'adj. 进步的；先进的；渐进的 n. 进步人士',
    'prohibit': 'v. 禁止；阻止；使不可能',
    'project': 'n. 项目；工程；计划 v. 计划；投射；投影',
    'projection': 'n. 投影；投射；预测；凸出',
    'projector': 'n. 投影仪；放映机；计划者',
    'prolong': 'v. 延长；延伸；拖延',
    'prominent': 'adj. 突出的；著名的；显著的',
    'promise': 'v. 答应；许诺；有指望 n. 许诺；指望；承诺',
    'promising': 'adj. 有希望的；有前途的；有指望的',
    'promote': 'v. 促进；提升；推销；发起',
    'promotion': 'n. 提升；晋升；推销；促进',
    'prompt': 'adj. 立刻的；迅速的；准时的 v. 促使；提示 n. 提示；催促',
    'promptly': 'adv. 迅速地；立即；准时地',
    'prone': 'adj. 易于...的；俯卧的；有倾向的',
    'pronounce': 'v. 发音；宣告；断言；宣判',
    'pronounced': 'adj. 明确的；显著的；发出的',
    'pronunciation': 'n. 发音；读音；发音方法',
    'proof': 'n. 证据；证明；校稿 adj. 防...的；耐...的 v. 校对；检验',
    'propaganda': 'n. 宣传；传道；公关活动',
    'propagate': 'v. 繁殖；传播；普及；宣传',
    'proper': 'adj. 适当的；正确的；恰当的；特有的',
    'properly': 'adv. 适当地；正确地；恰当地',
    'property': 'n. 财产；资产；性质；所有权',
    'proportion': 'n. 比例；部分；均衡 v. 使成比例；分摊',
    'proposal': 'n. 提议；建议；求婚；提案',
    'propose': 'v. 提议；建议；计划；求婚',
    'proposition': 'n. 提议；建议；主张；命题 v. 提出；提议',
    'prosecutor': 'n. 检察官；公诉人；原告',
    'prospect': 'n. 前景；期望；可能性 v. 勘探；寻找',
    'prospective': 'adj. 未来的；预期的；可能的',
    'prosper': 'v. 繁荣；成功；兴旺',
    'prosperity': 'n. 繁荣；成功；兴旺；幸福',
    'prosperous': 'adj. 繁荣的；成功的；兴旺的',
    'protect': 'v. 保护；警戒；防止',
    'protection': 'n. 保护；警戒；防护物',
    'protective': 'adj. 保护的；防护的 n. 保护物',
    'protein': 'n. 蛋白质；朊 adj. 蛋白质的',
    'protest': 'n. 抗议；反对；郑重声明 v. 抗议；反对；主张',
    'proud': 'adj. 自豪的；骄傲的；有自尊心的',
    'prove': 'v. 证明；证实；检验；显示',
    'provide': 'v. 提供；供应；规定；准备',
    'provided': 'conj. 倘若；假如；在...条件下',
    'provider': 'n. 供应者；提供者；服务商',
    'province': 'n. 省；领域；职权范围',
    'provincial': 'adj. 省的；地方性的；偏狭的 n. 乡下人；粗野的人',
    'provision': 'n. 供应；规定；条款；准备 v. 供给；为...提供所需物品',
    'provisional': 'adj. 临时的；暂时的；暂定的',
    'provoke': 'v. 激怒；刺激；引起；驱使',
    'prudent': 'adj. 谨慎的；精明的；节俭的',
    'psychiatric': 'adj. 精神病学的；精神病治疗的',
    'psychological': 'adj. 心理的；心理学的',
    'psychologist': 'n. 心理学家；心理学者',
    'psychology': 'n. 心理学；心理；心理状态',
    'pub': 'n. 酒馆；客栈；公共场所',
    'public': 'adj. 公众的；公共的；公开的 n. 公众；社会；公共场所',
    'publication': 'n. 出版；发行；出版物；发表',
    'publicity': 'n. 公开；宣传；注意；曝光',
    'publicize': 'v. 公开；宣传；公布',
    'publish': 'v. 出版；发行；公开；发表',
    'publisher': 'n. 出版者；出版商；发行人',
    'pudding': 'n. 布丁；甜点心；肉馅',
    'puff': 'n. 泡芙；吸入；吹气 v. 吹；喷；膨胀',
    'pull': 'v. 拉；拖；拔；牵引 n. 拉；拖；拉力；影响力',
    'punch': 'v. 击打；冲压；按 n. 冲压机；拳打；力量',
    'punctual': 'adj. 准时的；守时的；精确的',
    'punish': 'v. 惩罚；处罚；严厉对待',
    'punishment': 'n. 惩罚；刑罚；处罚',
    'pupil': 'n. 学生；瞳孔；小学生',
    'puppet': 'n. 木偶；傀儡；玩偶',
    'purchase': 'v. 购买；赢得 n. 购买；购买之物；支点',
    'pure': 'adj. 纯的；纯洁的；纯粹的',
    'purely': 'adv. 纯粹地；单纯地；完全地',
    'purple': 'adj. 紫色的；华美的 n. 紫色；皇族',
    'purpose': 'n. 目的；意图；目标 v. 打算；企图；致力于',
    'purposely': 'adv. 故意地；有意地；目的明确地',
    'pursue': 'v. 追求；追捕；继续；从事',
    'pursuit': 'n. 追求；追捕；寻求；工作',
    'push': 'v. 推；推动；逼迫 n. 推；奋力；攻击',
    'put': 'v. 放；安置；提出；赋予 n. 掷；期货',
    'puzzle': 'n. 难题；谜；困惑 v. 使困惑；使为难',
    'pyramid': 'n. 金字塔；角锥体；堆积 v. 成金字塔状；堆成锥形'
  };
  
  let fixed = 0;
  
  words.forEach(w => {
    const lower = w.word.toLowerCase();
    if (completeMeanings[lower] && (w.meaning === w.word || w.meaning === w.word.charAt(0).toUpperCase() + w.word.slice(1) || w.meaning === 'n. ' + w.word)) {
      w.meaning = completeMeanings[lower];
      fixed++;
    }
  });
  
  console.log('修复了', fixed, '个polar/pole类单词');
  
  const output = 'export interface IELTSWord {\n' +
    '  id: string;\n' +
    '  word: string;\n' +
    '  meaning: string;\n' +
    '  level: string;\n' +
    '  root: string;\n' +
    '  rootMeaning: string;\n' +
    '  rootMeaningEn: string;\n' +
    '  rootOrigin: string;\n' +
    '  rootOriginNote: string;\n' +
    '  relatedWords: { word: string; meaning: string; level: string }[];\n' +
    '  phonetic: string;\n' +
    '  frequency: string;\n' +
    '  example: string;\n' +
    '}\n\n' +
    'export const mockWords: IELTSWord[] = ' + JSON.stringify(words, null, 2) + ';';
  
  fs.writeFileSync('/home/fred/workspace/memoryworld-project/src/data/mockWords.ts', output);
  console.log('保存成功!');
}
