const fs = require('fs');

const data = fs.readFileSync('/home/fred/workspace/memoryworld-project/src/data/mockWords.ts', 'utf8');
const match = data.match(/export const mockWords: IELTSWord\[\] = \[([\s\S]*?)\];/);

if (match) {
  const words = JSON.parse('[' + match[1] + ']');
  
  const wordMap = {
    'acquit': 'v. 宣告无罪；开释',
    'acrid': 'adj. 辛辣的；刻薄的',
    'acumen': 'n. 敏锐；精明',
    'addendum': 'n. 附录；补遗',
    'addle': 'v. 使混乱；使腐坏',
    'adduce': 'v. 引证；举出',
    'adept': 'adj. 熟练的；精通的',
    'adjoin': 'v. 毗邻；邻接',
    'adjourn': 'v. 休会；延期',
    'adjunct': 'n. 附属物；助手',
    'adman': 'n. 广告人',
    'adobe': 'n. 土坯；Adobe公司',
    'adorn': 'v. 装饰；修饰',
    'adrift': 'adj. 漂泊的；漫无目的的',
    'adroit': 'adj. 灵巧的；机敏的',
    'adsorb': 'v. 吸附',
    'affidavit': 'n. 宣誓书',
    'affix': 'v. 粘贴；n. 词缀',
    'afflict': 'v. 使痛苦；折磨',
    'aficionado': 'n. 爱好者；迷',
    'afield': 'adv. 在野外；远离',
    'afloat': 'adj. 漂浮的；流通的',
    'aforesaid': 'adj. 上述的',
    'afresh': 'adv. 重新；再度',
    'african': 'adj. 非洲的；n. 非洲人',
    'afterlife': 'n. 来世；来生',
    'afterward': 'adv. 后来；以后',
    'aggrandize': 'v. 扩大；夸大',
    'aggrieve': 'v. 使悲痛；使受屈',
    'agile': 'adj. 敏捷的；灵活的',
    'aground': 'adj. 搁浅的',
    'albedo': 'n. 反照率',
    'albumen': 'n. 蛋白；蛋清',
    'alchemy': 'n. 炼金术',
    'alcove': 'n. 壁龛；凹室',
    'aldehyde': 'n. 醛；乙醛',
    'alderman': 'n. 市议员',
    'alerts': 'n. 警报；提醒',
    'alias': 'n. 别名；化名',
    'alibi': 'n. 不在场证明',
    'align': 'v. 对齐；排成一行',
    'aline': 'v. 排列；对齐',
    'all': 'adj. 全部的；pron. 所有',
    'allay': 'v. 减轻；平息',
    'alley': 'n. 小巷；胡同',
    'allot': 'v. 分配；分派',
    'allude': 'v. 暗示；暗指',
    'almanac': 'n. 年鉴；历书',
    'almighty': 'adj. 全能的；极大的',
    'aloe': 'n. 芦荟',
    'amass': 'v. 积累；积聚',
    'amen': 'int. 阿门',
    'amicable': 'adj. 友好的；和睦的',
    'amulet': 'n. 护身符',
    'anagram': 'n. 变位词',
    'anarchy': 'n. 无政府状态',
    'ancestry': 'n. 祖先；血统',
    'anecdote': 'n. 轶事；趣闻',
    'anemic': 'adj. 贫血的；无力的',
    'angelic': 'adj. 天使般的；纯洁的',
    'animosity': 'n. 敌意；仇恨',
    'annals': 'n. 编年史；年鉴',
    'anoint': 'v. 涂油；任命',
    'anonymous': 'adj. 匿名的',
    'antagonist': 'n. 对手；敌人',
    'anthem': 'n. 国歌；赞歌',
    'antique': 'adj. 古老的；n. 古董',
    'apartment': 'n. 公寓；房间',
    'aperture': 'n. 孔径；开口',
    'apex': 'n. 顶点；顶峰',
    'aphorism': 'n. 格言；警句',
    'apiary': 'n. 养蜂场',
    'apocryphal': 'adj. 伪经的；虚构的',
    'apogee': 'n. 远地点；最高点',
    'apology': 'n. 道歉；辩解',
    'apparel': 'n. 服装；衣着',
    'apparition': 'n. 幽灵；幻影',
    'appease': 'v. 安抚；平息',
    'appellation': 'n. 名称；称号',
    'apprentice': 'n. 学徒；新手',
    'apprise': 'v. 通知；告知',
    'aptitude': 'n. 天资；才能',
    'arcade': 'n. 拱廊；商场',
    'archer': 'n. 弓箭手',
    'archipelago': 'n. 群岛',
    'archive': 'n. 档案；档案馆',
    'arena': 'n. 竞技场；舞台',
    'argot': 'n. 行话；黑话',
    'armament': 'n. 军备；武器',
    'armistice': 'n. 停战；休战',
    'aroma': 'n. 芳香；香气',
    'arouse': 'v. 唤醒；激起',
    'arrange': 'v. 安排；整理',
    'arrears': 'n. 欠款；拖欠',
    'arson': 'n. 纵火；纵火罪',
    'artery': 'n. 动脉；干线',
    'artisan': 'n. 工匠；手艺人',
    'ascend': 'v. 上升；攀登',
    'ascetic': 'adj. 苦行的；n. 苦行者',
    'ascribe': 'v. 归因于；归咎于',
    'ashore': 'adv. 在岸上；上岸',
    'askew': 'adj. 歪斜的；adv. 歪斜地',
    'aspersion': 'n. 诽谤；中伤',
    'aspire': 'v. 渴望；追求',
    'assent': 'n./v. 同意；赞成',
    'assiduous': 'adj. 勤奋的；刻苦的',
    'assuage': 'v. 缓和；减轻',
    'astound': 'v. 使震惊；使惊讶',
    'astray': 'adj./adv. 迷路的；误入歧途',
    'astute': 'adj. 精明的；敏锐的',
    'asylum': 'n. 庇护；避难所',
    'atheist': 'n. 无神论者',
    'atrophy': 'n./v. 萎缩；衰退',
    'attest': 'v. 证明；证实',
    'attribute': 'n. 属性；v. 归因于',
    'auction': 'n./v. 拍卖',
    'audacity': 'n. 大胆；鲁莽',
    'audible': 'adj. 听得见的',
    'augment': 'v. 增加；扩大',
    'augur': 'v. 预言；预示',
    'austerity': 'n. 紧缩；简朴',
    'autograph': 'n. 亲笔签名',
    'autopsy': 'n. 验尸；尸检',
    'avalanche': 'n. 雪崩；v. 大量涌来',
    'avenge': 'v. 报仇；报复',
    'aver': 'v. 断言；宣称',
    'aversion': 'n. 厌恶；反感',
    'avow': 'v. 承认；公开宣称',
    'babble': 'v. 唠叨；含糊不清地说',
    'bacchanal': 'n. 狂欢；酒神节',
    'bailiff': 'n. 法警；执行官',
    'balm': 'n. 香油；安慰',
    'baneful': 'adj. 有害的；致命的',
    'barb': 'n. 倒钩；讽刺',
    'barefaced': 'adj. 公然的；无耻的',
    'barge': 'n. 驳船；v. 冲撞',
    'bark': 'v. 吠叫；n. 树皮',
    'barnacle': 'n. 藤壶',
    'barrage': 'n. 弹幕；猛烈攻击',
    'barren': 'adj. 贫瘠的；不育的',
    'bastion': 'n. 堡垒；要塞',
    'batten': 'v. 钉住；养肥',
    'bazaar': 'n. 集市；商店',
    'beacon': 'n. 灯塔；信号灯',
    'bead': 'n. 珠子；水珠',
    'beak': 'n. 鸟嘴；喙',
    'belabor': 'v. 痛打；反复讨论',
    'belie': 'v. 掩饰；证明...虚假',
    'bellicose': 'adj. 好战的；好斗的',
    'bellow': 'v. 咆哮；怒吼',
    'belly': 'n. 腹部；胃',
    'benediction': 'n. 祝福；赐福',
    'beneficent': 'adj. 仁慈的；慈善的',
    'benign': 'adj. 良性的；和蔼的',
    'berth': 'n. 泊位；卧铺',
    'beseech': 'v. 恳求；祈求',
    'beset': 'v. 困扰；包围',
    'besiege': 'v. 围攻；围困',
    'besmirch': 'v. 弄脏；诽谤',
    'betray': 'v. 背叛；出卖',
    'beverage': 'n. 饮料',
    'bibliography': 'n. 参考书目；文献目录',
    'bicker': 'v. 争吵；斗嘴',
    'bigot': 'n. 偏执者；顽固者',
    'billow': 'v. 汹涌；膨胀',
    'binoculars': 'n. 双筒望远镜',
    'biography': 'n. 传记',
    'bizarre': 'adj. 奇异的；古怪的',
    'blanch': 'v. 使变白；漂白',
    'blare': 'v. 发出刺耳的声音',
    'blasphemy': 'n. 亵渎；渎神',
    'blaze': 'n. 火焰；v. 燃烧',
    'bleak': 'adj. 荒凉的；无望的',
    'blend': 'v./n. 混合；融合',
    'blight': 'n. 枯萎病；v. 使枯萎',
    'blindfold': 'n. 眼罩；v. 蒙住眼睛',
    'bliss': 'n. 极乐；幸福',
    'blotch': 'n. 斑点；污渍',
    'blunder': 'n./v. 错误；跌跌撞撞',
    'blunt': 'adj. 钝的；直率的',
    'blurb': 'n. 简介；短评',
    'blurt': 'v. 脱口而出',
    'blush': 'v./n. 脸红；羞愧',
    'boast': 'v. 吹嘘；n. 自夸',
    'bode': 'v. 预示；预兆',
    'bogus': 'adj. 假的；伪造的',
    'bolster': 'n. 支撑；v. 支持',
    'bombard': 'v. 轰炸；炮击',
    'bondage': 'n. 奴役；束缚',
    'boon': 'n. 恩惠；福利',
    'boost': 'v./n. 推动；提升',
    'bore': 'v. 钻孔；使厌烦',
    'botch': 'v. 搞糟；拙劣地修补',
    'bound': 'adj. 受约束的；v. 跳跃',
    'bounty': 'n. 赏金；慷慨',
    'bourgeois': 'adj. 资产阶级的',
    'bowel': 'n. 肠；内部',
    'brace': 'v. 支撑；n. 支架',
    'braid': 'v. 编织；n. 辫子',
    'brandish': 'v. 挥舞；炫耀',
    'brash': 'adj. 鲁莽的；无礼的',
    'bray': 'v. 叫；嘶叫',
    'breech': 'n. 臀部；后膛',
    'bribe': 'n./v. 贿赂',
    'bridle': 'n. 马笼头；v. 控制',
    'brink': 'n. 边缘； brink',
    'brisk': 'adj. 轻快的；活泼的',
    'broach': 'v. 提出；开启',
    'brood': 'n. 一窝；v. 沉思',
    'brook': 'n. 小溪；v. 容忍',
    'broom': 'n. 扫帚',
    'brunt': 'n. 冲击；首当其冲',
    'brute': 'adj. 残忍的；n. 畜生',
    'buccaneer': 'n. 海盗',
    'buffet': 'n. 自助餐；v. 打击',
    'bugle': 'n. 号角；军号',
    'bulwark': 'n. 堡垒；防御',
    'bumper': 'n. 保险杠；adj. 丰盛的',
    'bungalow': 'n. 平房',
    'bureaucracy': 'n. 官僚主义；官僚机构',
    'burglar': 'n. 窃贼；夜盗',
    'burgeon': 'v. 发芽；迅速增长',
    'burst': 'v./n. 爆发；突发',
    'buttress': 'n. 扶壁；v. 支持',
    'buzz': 'v./n. 嗡嗡声；闲聊',
    'cadence': 'n. 节奏；韵律',
    'cajole': 'v. 哄骗；诱骗',
    'calamity': 'n. 灾难；灾祸',
    'calibre': 'n. 口径；品质',
    'callus': 'n. 老茧；愈合组织',
    'calumny': 'n. 诽谤；中伤',
    'candid': 'adj. 坦率的；直言不讳的',
    'cannon': 'n. 大炮；加农炮',
    'canopy': 'n. 天篷；华盖',
    'caprice': 'n. 反复无常；任性',
    'captain': 'n. 船长；队长',
    'caption': 'n. 标题；说明',
    'captious': 'adj. 吹毛求疵的',
    'carat': 'n. 克拉；开',
    'caravan': 'n. 大篷车；商队',
    'carcass': 'n. 尸体；残骸',
    'cardinal': 'adj. 主要的；n. 红衣主教',
    'careen': 'v. 倾斜；猛冲',
    'cargo': 'n. 货物',
    'caricature': 'n. 漫画；讽刺画',
    'carnal': 'adj. 肉体的；肉欲的',
    'carnival': 'n. 狂欢节',
    'carp': 'v. 吹毛求疵；n. 鲤鱼',
    'carve': 'v. 雕刻；切开',
    'cascade': 'n./v. 瀑布；倾泻',
    'castigate': 'v. 严惩；苛责',
    'casualty': 'n. 伤亡人员；受害者',
    'catastrophe': 'n. 灾难；大祸',
    'caustic': 'adj. 腐蚀性的；刻薄的',
    'cavalcade': 'n. 骑兵队；车队',
    'caveat': 'n. 警告；注意事项',
    'cede': 'v. 割让；放弃',
    'celestial': 'adj. 天上的；神圣的',
    'cellar': 'n. 地窖；地下室',
    'censor': 'n./v. 审查；审查员',
    'censure': 'n./v. 谴责；批评',
    'ceramic': 'adj. 陶瓷的；n. 陶瓷',
    'cereal': 'n. 谷物；麦片',
    'cessation': 'n. 停止；中断',
    'chaff': 'n. 谷壳；v. 取笑',
    'chagrin': 'n. 懊恼；失望',
    'champ': 'v. 咀嚼；n. 冠军',
    'chant': 'v./n. 吟唱；圣歌',
    'chasm': 'n. 深渊；鸿沟',
    'chauvinism': 'n. 沙文主义',
    'cheer': 'v./n. 欢呼；喝彩',
    'chef': 'n. 厨师；主厨',
    'cherish': 'v. 珍惜；爱护',
    'chide': 'v. 责备；斥责',
    'chisel': 'n. 凿子；v. 凿',
    'chord': 'n. 和弦；弦',
    'chore': 'n. 家务；杂务',
    'chortle': 'v./n. 哈哈大笑',
    'churn': 'v. 搅拌；翻腾',
    'cipher': 'n. 密码；暗号',
    'circumference': 'n. 周长；圆周',
    'circumspect': 'adj. 谨慎的；周到的',
    'clamor': 'n./v. 喧闹；大声要求',
    'clamp': 'n./v. 夹具；夹紧',
    'clandestine': 'adj. 秘密的；暗中的',
    'clarion': 'adj. 清晰响亮的',
    'clash': 'v./n. 冲突；碰撞',
    'clasp': 'v./n. 扣紧；紧握',
    'clatter': 'v./n. 咔嗒声；喧闹',
    'claustrophobia': 'n. 幽闭恐惧症',
    'cleanse': 'v. 清洁；净化',
    'cleave': 'v. 劈开；粘附',
    'clench': 'v. 握紧；咬紧',
    'clerk': 'n. 职员；店员',
    'clinch': 'v. 敲定；扭打',
    'clog': 'v. 堵塞；n. 木屐',
    'clout': 'n. 影响力；v. 猛击',
    'cloy': 'v. 使腻烦；使过饱',
    'clutch': 'v./n. 抓住；离合器',
    'coalition': 'n. 联盟；联合',
    'coerce': 'v. 强迫；胁迫',
    'cogent': 'adj. 有说服力的；令人信服的',
    'cognate': 'adj. 同源的；n. 同源词',
    'cohabit': 'v. 同居',
    'cohere': 'v. 凝聚；连贯',
    'coiffure': 'n. 发型',
    'coil': 'v./n. 盘绕；线圈',
    'coincide': 'v. 同时发生；重合',
    'colander': 'n. 滤器；漏勺',
    'collaborate': 'v. 合作；协作',
    'collate': 'v. 整理；核对',
    'collateral': 'adj. 附属的；n. 抵押品',
    'colloquy': 'n. 谈话；对话',
    'colony': 'n. 殖民地；群体',
    'colossal': 'adj. 巨大的；庞大的',
    'combat': 'n./v. 战斗；搏斗',
    'comestible': 'adj. 可食用的；n. 食物',
    'comic': 'adj. 喜剧的；n. 漫画',
    'commemorate': 'v. 纪念；庆祝',
    'commence': 'v. 开始；着手',
    'commend': 'v. 称赞；推荐',
    'commodity': 'n. 商品；货物',
    'commonplace': 'adj. 平凡的；n. 老生常谈',
    'commotion': 'n. 骚动；混乱',
    'communal': 'adj. 公共的；社区的',
    'commute': 'v. 通勤；减刑',
    'compact': 'adj. 紧凑的；n. 契约',
    'companion': 'n. 同伴；伴侣',
    'compatible': 'adj. 兼容的；相容的',
    'compel': 'v. 强迫；迫使',
    'compendious': 'adj. 简洁的；扼要的',
    'compensate': 'v. 补偿；赔偿',
    'compile': 'v. 编译；汇编',
    'complacent': 'adj. 自满的；得意的',
    'complement': 'n./v. 补充；补足',
    'complete': 'adj. 完整的；v. 完成',
    'complex': 'adj. 复杂的；n. 复合体',
    'complicate': 'v. 使复杂；使陷入',
    'compliment': 'n./v. 赞美；恭维',
    'comply': 'v. 遵守；服从',
    'comport': 'v. 举止；表现',
    'compose': 'v. 组成；创作',
    'comprehend': 'v. 理解；包含',
    'compromise': 'n./v. 妥协；折中',
    'compulsion': 'n. 强迫；冲动',
    'compulsory': 'adj. 强制的；必修的',
    'compute': 'v. 计算；估算',
    'comrade': 'n. 同志；伙伴',
    'conceal': 'v. 隐藏；隐瞒',
    'concede': 'v. 承认；让步',
    'conceive': 'v. 构想；怀孕',
    'concert': 'n. 音乐会；和谐',
    'concise': 'adj. 简洁的；简明的',
    'conclave': 'n. 秘密会议',
    'conclude': 'v. 结束；断定',
    'concoct': 'v. 调制；编造',
    'concord': 'n. 和谐；一致',
    'condemn': 'v. 谴责；判刑',
    'condone': 'v. 宽恕；赦免',
    'conduit': 'n. 管道；导管',
    'confidant': 'n. 知己；心腹',
    'confine': 'v. 限制；监禁',
    'confirm': 'v. 确认；证实',
    'confiscate': 'v. 没收；充公',
    'conflate': 'v. 合并；混合',
    'confound': 'v. 混淆；使困惑',
    'confront': 'v. 面对；对抗',
    'confuse': 'v. 使困惑；混淆',
    'congeal': 'v. 凝结；凝固',
    'congenial': 'adj. 意气相投的；宜人的',
    'congest': 'v. 使拥挤；使充血',
    'congregate': 'v. 聚集；集合',
    'conjecture': 'n./v. 推测；猜测',
    'conjoin': 'v. 连接；结合',
    'conjugal': 'adj. 婚姻的；夫妻的',
    'conjure': 'v. 召唤；变魔术',
    'connect': 'v. 连接；联系',
    'connote': 'v. 暗示；意味着',
    'conquer': 'v. 征服；战胜',
    'conscience': 'n. 良心；良知',
    'conscientious': 'adj. 认真的；尽责的',
    'conscript': 'n. 应征士兵；v. 征召',
    'consecrate': 'v. 奉献；使神圣',
    'consent': 'n./v. 同意；赞成',
    'consequence': 'n. 结果；后果',
    'conserve': 'v. 保存；保护',
    'consider': 'v. 考虑；认为',
    'consign': 'v. 交付；委托',
    'consist': 'v. 由...组成；一致',
    'console': 'v. 安慰；n. 控制台',
    'consolidate': 'v. 巩固；合并',
    'conspicuous': 'adj. 显眼的；显著的',
    'conspiracy': 'n. 阴谋；共谋',
    'constable': 'n. 警察；治安官',
    'constancy': 'n. 恒定；忠诚',
    'constrain': 'v. 限制；强迫',
    'construct': 'v. 建造；构建',
    'consume': 'v. 消耗；消费',
    'contend': 'v. 竞争；主张',
    'content': 'adj. 满足的；n. 内容',
    'contest': 'n./v. 比赛；竞争',
    'context': 'n. 上下文；语境',
    'contiguous': 'adj. 相邻的；接壤的',
    'contort': 'v. 扭曲；变形',
    'contraband': 'n. 违禁品；走私货',
    'contradict': 'v. 反驳；矛盾',
    'contrary': 'adj. 相反的；n. 对立面',
    'contrast': 'n./v. 对比；对照',
    'contrive': 'v. 发明；策划',
    'control': 'n./v. 控制；管理',
    'controversy': 'n. 争议；争论',
    'convalesce': 'v. 康复；休养',
    'convention': 'n. 惯例；会议',
    'converge': 'v. 汇聚；收敛',
    'converse': 'v. 交谈；n. 相反',
    'convert': 'v. 转换；改变信仰',
    'convey': 'v. 传达；运输',
    'convict': 'v. 定罪；n. 罪犯',
    'convince': 'v. 说服；使确信',
    'cook': 'v. 烹饪；n. 厨师',
    'cooperate': 'v. 合作；协作',
    'coordinate': 'v. 协调；n. 坐标',
    'copious': 'adj. 丰富的；大量的',
    'copy': 'n./v. 复制；副本',
    'coral': 'n. 珊瑚；珊瑚色',
    'cordial': 'adj. 热情的；亲切的',
    'core': 'n. 核心；中心',
    'corps': 'n. 军团； corps',
    'corpse': 'n. 尸体',
    'correlate': 'v. 关联；相关',
    'corrode': 'v. 腐蚀；侵蚀',
    'corrupt': 'adj. 腐败的；v. 腐蚀',
    'cosset': 'v. 宠爱；娇养',
    'costume': 'n. 服装；戏服',
    'coterie': 'n. 小圈子；小团体',
    'cottage': 'n. 小屋；村舍',
    'cotton': 'n. 棉花；adj. 棉的',
    'couch': 'n. 沙发；v. 表达',
    'cough': 'v./n. 咳嗽',
    'council': 'n. 委员会；理事会',
    'counsel': 'n. 建议；v. 劝告',
    'countenance': 'n. 面容；表情',
    'couple': 'n. 夫妻；一对',
    'courage': 'n. 勇气；胆量',
    'courteous': 'adj. 有礼貌的；谦恭的',
    'courtesy': 'n. 礼貌；好意',
    'court': 'n. 法院；宫廷',
    'covet': 'v. 贪图；觊觎',
    'coward': 'n. 懦夫；胆小鬼',
    'cower': 'v. 畏缩；退缩',
    'cozy': 'adj. 舒适的；温暖的',
    'crack': 'v./n. 破裂；裂缝',
    'craft': 'n. 工艺；手艺',
    'cram': 'v. 塞满；死记硬背',
    'crane': 'n. 起重机；鹤',
    'crave': 'v. 渴望；恳求',
    'crawl': 'v./n. 爬行；缓慢移动',
    'creak': 'v./n. 嘎吱声',
    'creep': 'v./n. 爬行；悄悄移动',
    'crevice': 'n. 裂缝；缺口',
    'crimson': 'adj. 深红色的；n. 深红色',
    'cripple': 'n. 跛子；v. 使残疾',
    'crisis': 'n. 危机；紧要关头',
    'criterion': 'n. 标准；准则',
    'critic': 'n. 批评家；评论家',
    'croak': 'v. 呱呱叫；嘶哑地说',
    'crochet': 'v./n. 钩针编织',
    'croon': 'v. 低声吟唱；哼唱',
    'cross': 'n. 十字架；v. 穿过',
    'crow': 'n. 乌鸦；v. 啼叫',
    'crucial': 'adj. 关键的；至关重要的',
    'crude': 'adj. 粗糙的；原油的',
    'cruel': 'adj. 残忍的；残酷的',
    'cruise': 'v./n. 巡航；巡游',
    'crush': 'v./n. 压碎；迷恋',
    'crust': 'n. 外壳；地壳',
    'crystal': 'n. 水晶；晶体',
    'cubic': 'adj. 立方的；立方体的',
    'cuisine': 'n. 烹饪；菜肴',
    'culminate': 'v. 达到顶点；告终',
    'cultivate': 'v. 培养；耕作',
    'cultured': 'adj. 有教养的；培养的',
    'cumulative': 'adj. 累积的；渐增的',
    'curious': 'adj. 好奇的；奇特的',
    'curriculum': 'n. 课程；课程表',
    'curse': 'n./v. 诅咒；咒骂',
    'curtain': 'n. 窗帘；幕布',
    'curve': 'n./v. 曲线；弯曲',
    'cushion': 'n. 垫子；缓冲',
    'custom': 'n. 习惯；风俗',
    'cute': 'adj. 可爱的；漂亮的',
    'cycle': 'n./v. 循环；周期',
    'cylinder': 'n. 圆柱；气缸',
    'cynic': 'n. 愤世嫉俗者',
    'damp': 'adj. 潮湿的；v. 使潮湿',
    'dangle': 'v. 悬挂；摇晃',
    'dapper': 'adj. 整洁的；潇洒的',
    'dare': 'v. 敢；挑战',
    'dart': 'n./v. 飞镖；投掷',
    'dash': 'v./n. 猛冲；破折号',
    'daunt': 'v. 使气馁；使畏缩',
    'dawdle': 'v. 闲逛；拖延',
    'dawn': 'n./v. 黎明；破晓',
    'daylight': 'n. 日光；白昼',
    'deadlock': 'n. 僵局；死锁',
    'dealing': 'n. 交易；行为',
    'debacle': 'n. 崩溃；惨败',
    'debar': 'v. 排除；禁止',
    'debase': 'v. 贬低；降低',
    'debate': 'n./v. 辩论；争论',
    'debit': 'n./v. 借方；借记',
    'debonair': 'adj. 温文尔雅的；潇洒的',
    'debt': 'n. 债务；欠债',
    'decade': 'n. 十年；十年期',
    'decay': 'n./v. 腐烂；衰退',
    'deceit': 'n. 欺骗；谎言',
    'deceive': 'v. 欺骗；误导',
    'decent': 'adj. 体面的；得体的',
    'deception': 'n. 欺骗；诡计',
    'decide': 'v. 决定；裁决',
    'decimal': 'adj. 十进制的；n. 小数',
    'decipher': 'v. 破译；解读',
    'declare': 'v. 宣布；声明',
    'decline': 'v./n. 下降；拒绝',
    'decode': 'v. 解码；破译',
    'decompose': 'v. 分解；腐烂',
    'decorate': 'v. 装饰；装修',
    'decree': 'n./v. 法令；颁布',
    'dedicate': 'v. 奉献；致力于',
    'deduce': 'v. 推断；演绎',
    'deduct': 'v. 扣除；减去',
    'deface': 'v. 损毁；弄脏',
    'defect': 'n. 缺陷；v. 背叛',
    'defend': 'v. 防御；辩护',
    'defiance': 'n. 违抗；蔑视',
    'deficiency': 'n. 缺乏；不足',
    'deficient': 'adj. 缺乏的；不足的',
    'definite': 'adj. 明确的；确定的',
    'deflate': 'v. 放气；使泄气',
    'deflect': 'v. 偏转；偏离',
    'deform': 'v. 使变形；使畸形',
    'defraud': 'v. 欺诈；诈骗',
    'defy': 'v. 违抗；蔑视',
    'degenerate': 'v. 退化；堕落',
    'dehydrate': 'v. 脱水；使干燥',
    'deign': 'v. 屈尊；俯就',
    'delegate': 'n. 代表；v. 委托',
    'deliberate': 'adj. 故意的；v. 深思熟虑',
    'delicate': 'adj. 精致的；脆弱的',
    'deliver': 'v. 交付；发表',
    'delude': 'v. 欺骗；迷惑',
    'deluge': 'n./v. 洪水； deluge',
    'delve': 'v. 钻研；深入研究',
    'demand': 'n./v. 要求；需求',
    'demise': 'n. 死亡；终止',
    'democrat': 'n. 民主党人；民主主义者',
    'democratic': 'adj. 民主的；民主党的',
    'demonstrate': 'v. 证明；演示',
    'denigrate': 'v. 诋毁；贬低',
    'denote': 'v. 表示；意味着',
    'denounce': 'v. 谴责；告发',
    'dense': 'adj. 密集的；浓厚的',
    'density': 'n. 密度；浓度',
    'dent': 'n./v. 凹痕；凹陷',
    'deny': 'v. 否认；拒绝',
    'depart': 'v. 离开；出发',
    'depend': 'v. 依赖；依靠',
    'depict': 'v. 描绘；描述',
    'deploy': 'v. 部署；展开',
    'deposit': 'n./v. 存款；存放',
    'depress': 'v. 压抑；使沮丧',
    'deprive': 'v. 剥夺；使丧失',
    'dept': 'n. 部门；系',
    'derive': 'v. 源于；获得',
    'descend': 'v. 下降；降临',
    'describe': 'v. 描述；形容',
    'desert': 'n. 沙漠；v. 抛弃',
    'deserve': 'v. 值得；应得',
    'design': 'n./v. 设计；图案',
    'designate': 'v. 指定；任命',
    'desolate': 'adj. 荒凉的；v. 使荒芜',
    'despair': 'n./v. 绝望；丧失信心',
    'desperate': 'adj. 绝望的；不顾一切的',
    'despicable': 'adj. 可鄙的；卑鄙的',
    'despite': 'prep. 尽管；不管',
    'dessert': 'n. 甜点；甜食',
    'destine': 'v. 注定；命定',
    'destroy': 'v. 破坏；摧毁',
    'detach': 'v. 分离；拆卸',
    'detail': 'n./v. 细节；详述',
    'detect': 'v. 检测；发现',
    'deter': 'v. 阻止；威慑',
    'determine': 'v. 决定；确定',
    'detour': 'n./v. 绕道；迂回',
    'detract': 'v. 减损；贬低',
    'detriment': 'n. 损害；伤害',
    'develop': 'v. 发展；开发',
    'deviate': 'v. 偏离；背离',
    'device': 'n. 设备；装置',
    'devise': 'v. 设计；发明',
    'devote': 'v. 奉献；致力于',
    'dew': 'n. 露水',
    'dexterity': 'n. 灵巧；敏捷',
    'diagram': 'n. 图表；示意图',
    'dial': 'n. 刻度盘；v. 拨号',
    'dialogue': 'n. 对话；对白',
    'diameter': 'n. 直径',
    'dictate': 'v. 口述；命令',
    'diction': 'n. 措辞；发音',
    'dictum': 'n. 格言；声明',
    'die': 'v. 死亡；凋谢',
    'diet': 'n. 饮食；节食',
    'differ': 'v. 不同；相异',
    'diffuse': 'v. 扩散；传播',
    'digest': 'v. 消化；n. 摘要',
    'dignify': 'v. 使高贵；使有尊严',
    'dilemma': 'n. 困境；两难',
    'diligent': 'adj. 勤奋的；刻苦的',
    'dilute': 'v. 稀释；冲淡',
    'dim': 'adj. 昏暗的；v. 使暗淡',
    'dimension': 'n. 维度；尺寸',
    'diminish': 'v. 减少；降低',
    'dine': 'v. 进餐；用餐',
    'dip': 'v./n. 蘸；浸泡',
    'direct': 'adj. 直接的；v. 指导',
    'dirt': 'n. 泥土；污垢',
    'disagree': 'v. 不同意；不一致',
    'disappear': 'v. 消失；失踪',
    'disappoint': 'v. 使失望；使沮丧',
    'disapprove': 'v. 不赞成；反对',
    'disarm': 'v. 解除武装；裁军',
    'disarray': 'n. 混乱；紊乱',
    'disaster': 'n. 灾难；灾害',
    'disavow': 'v. 否认；拒绝承认',
    'disband': 'v. 解散；解体',
    'discard': 'v. 丢弃；抛弃',
    'discern': 'v. 辨别；识别',
    'discharge': 'v./n. 放电；释放',
    'discipline': 'n./v. 纪律；训练',
    'disclaim': 'v. 否认；放弃',
    'disclose': 'v. 揭露；透露',
    'discomfort': 'n. 不适；不安',
    'disconnect': 'v. 断开连接；分离',
    'discover': 'v. 发现；发觉',
    'discredit': 'v. 使丧失信誉；诋毁',
    'discreet': 'adj. 谨慎的；慎重的',
    'discrepancy': 'n. 差异；不符',
    'discriminate': 'v. 歧视；区分',
    'discuss': 'v. 讨论；商议',
    'disease': 'n. 疾病；病害',
    'disembark': 'v. 下船；登陆',
    'disengage': 'v. 脱离；解除',
    'disgorge': 'v. 吐出；倾泻',
    'disgrace': 'n./v. 耻辱；使蒙羞',
    'disguise': 'n./v. 伪装；掩饰',
    'disgust': 'n./v. 厌恶；反感',
    'dish': 'n. 盘子；菜肴',
    'dishonest': 'adj. 不诚实的；欺诈的',
    'disillusion': 'v. 使醒悟；使幻灭',
    'disinfect': 'v. 消毒；杀菌',
    'disintegrate': 'v. 瓦解；分裂',
    'disinter': 'v. 挖掘；发掘',
    'disjoin': 'v. 分开；分离',
    'dislocate': 'v. 脱位；移位',
    'dislodge': 'v. 驱逐；移走',
    'dismal': 'adj. 凄凉的；阴沉的',
    'dismantle': 'v. 拆除；拆卸',
    'dismiss': 'v. 解雇；解散',
    'disobey': 'v. 不服从；违抗',
    'disorder': 'n. 混乱；无序',
    'disparate': 'adj. 不同的；不相称的',
    'dispense': 'v. 分配；分发',
    'disperse': 'v. 分散；散开',
    'displace': 'v. 取代；置换',
    'display': 'n./v. 显示；展示',
    'displease': 'v. 使不高兴；冒犯',
    'disposal': 'n. 处置；处理',
    'dispose': 'v. 处理；布置',
    'dispute': 'n./v. 争论；争议',
    'disqualify': 'v. 取消资格；使不合格',
    'disregard': 'v./n. 忽视；不理会',
    'disrupt': 'v. 破坏；扰乱',
    'disseminate': 'v. 传播；散布',
    'dissent': 'n./v. 异议；不同意',
    'dissert': 'v. 论述；写论文',
    'dissolve': 'v. 溶解；解散',
    'distance': 'n. 距离；远处',
    'distinguish': 'v. 区分；辨别',
    'distort': 'v. 扭曲；歪曲',
    'distract': 'v. 分散注意力；使分心',
    'distress': 'n./v. 痛苦；使痛苦',
    'distribute': 'v. 分发；分配',
    'distrust': 'n./v. 不信任；怀疑',
    'disturb': 'v. 打扰；扰乱',
    'ditch': 'n. 沟；壕沟',
    'dive': 'v./n. 潜水；跳水',
    'diverge': 'v. 分歧；分叉',
    'diverse': 'adj. 多样的；不同的',
    'diversify': 'v. 多样化；多元化',
    'divest': 'v. 剥夺；放弃',
    'divide': 'v. 划分；分开',
    'divine': 'adj. 神圣的；v. 占卜',
    'divorce': 'n./v. 离婚；分离',
    'dizzy': 'adj. 头晕的；眩晕的',
    'dock': 'n. 码头；船坞',
    'doctrine': 'n. 教义；学说',
    'document': 'n. 文件；v. 记录',
    'dogma': 'n. 教条；信条',
    'dole': 'n. 救济金；v. 发放',
    'dolphin': 'n. 海豚',
    'domain': 'n. 领域；域名',
    'domestic': 'adj. 国内的；家庭的',
    'dominant': 'adj. 占主导的；统治的',
    'dominate': 'v. 支配；控制',
    'donate': 'v. 捐赠；捐献',
    'doom': 'n./v. 厄运；注定',
    'door': 'n. 门；入口',
    'dormant': 'adj. 休眠的；静止的',
    'dose': 'n. 剂量；一剂',
    'dot': 'n./v. 点；打点',
    'double': 'adj. 双重的；v. 加倍',
    'doubt': 'n./v. 怀疑；疑问',
    'dough': 'n. 面团；钱',
    'dove': 'n. 鸽子',
    'dowry': 'n. 嫁妆',
    'dozen': 'n. 一打；十二个',
    'draft': 'n./v. 草稿；起草',
    'drag': 'v./n. 拖；拉',
    'drain': 'v./n. 排水；消耗',
    'drama': 'n. 戏剧；戏剧艺术',
    'drastic': 'adj. 激烈的；急剧的',
    'draw': 'v./n. 画；拉',
    'dread': 'n./v. 恐惧；害怕',
    'dream': 'n./v. 梦；梦想',
    'dress': 'n./v. 衣服；穿衣服',
    'drift': 'v./n. 漂流；漂移',
    'drill': 'n./v. 钻头；钻孔',
    'drink': 'v./n. 喝；饮料',
    'drip': 'v./n. 滴；水滴',
    'drive': 'v./n. 驾驶；驱动',
    'drop': 'v./n. 落下；滴',
    'drown': 'v. 淹死；淹没',
    'drum': 'n. 鼓；v. 击鼓',
    'drunk': 'adj. 喝醉的；n. 醉汉',
    'dry': 'adj. 干的；v. 使干燥',
    'dual': 'adj. 双重的；二元的',
    'dub': 'v. 配音；授予称号',
    'dubious': 'adj. 可疑的；不确定的',
    'duck': 'n. 鸭子；v. 躲避',
    'due': 'adj. 应有的；到期的',
    'dull': 'adj. 迟钝的；无聊的',
    'dumb': 'adj. 哑的；愚蠢的',
    'dump': 'v./n. 倾倒；垃圾场',
    'durable': 'adj. 耐用的；持久的',
    'duration': 'n. 持续时间；期间',
    'dusk': 'n. 黄昏；薄暮',
    'dust': 'n./v. 灰尘；打扫',
    'duty': 'n. 责任；义务',
    'dwarf': 'n. 矮人；v. 使矮小',
    'dwell': 'v. 居住；停留',
    'dwindle': 'v. 减少；缩小',
    'dye': 'n./v. 染料；染色',
    'eagle': 'n. 鹰',
    'earl': 'n. 伯爵',
    'earnest': 'adj. 认真的；诚挚的',
    'earth': 'n. 地球；土地',
    'ease': 'n./v. 轻松；减轻',
    'eastern': 'adj. 东方的；东部的',
    'easy': 'adj. 容易的；舒适的',
    'echo': 'n./v. 回声；回响',
    'eclipse': 'n./v. 日食；黯然失色',
    'ecstasy': 'n. 狂喜；迷醉',
    'edge': 'n./v. 边缘；移动',
    'edible': 'adj. 可食用的',
    'edit': 'v. 编辑；校订',
    'elaborate': 'adj. 精心的；v. 详细说明',
    'elapse': 'v. 流逝；过去',
    'elastic': 'adj. 有弹性的；n. 松紧带',
    'elbow': 'n. 肘部；v. 用肘推',
    'elder': 'adj. 年长的；n. 长辈',
    'elect': 'v. 选举；选择',
    'elegant': 'adj. 优雅的；高雅的',
    'element': 'n. 元素；要素',
    'elephant': 'n. 大象',
    'elevate': 'v. 提升；抬高',
    'elicit': 'v. 引出；诱出',
    'eligible': 'adj. 有资格的；合适的',
    'elite': 'n. 精英；精华',
    'eloquent': 'adj. 雄辩的；有说服力的',
    'else': 'adv. 否则；其他',
    'embark': 'v. 上船；开始',
    'embarrass': 'v. 使尴尬；使难堪',
    'embassy': 'n. 大使馆',
    'embed': 'v. 嵌入；植入',
    'embody': 'v. 体现；包含',
    'embrace': 'v./n. 拥抱；接受',
    'embroider': 'v. 刺绣；点缀',
    'emerge': 'v. 出现；浮现',
    'emission': 'n. 排放；发射',
    'emit': 'v. 发出；排放',
    'emotion': 'n. 情感；情绪',
    'emperor': 'n. 皇帝',
    'emphasis': 'n. 强调；重点',
    'empirical': 'adj. 经验的；实证的',
    'employ': 'v. 雇佣；使用',
    'empower': 'v. 授权；使能够',
    'empty': 'adj. 空的；v. 倒空',
    'enable': 'v. 使能够；使成为可能',
    'enact': 'v. 制定；颁布',
    'enamel': 'n. 珐琅；搪瓷',
    'encapsulate': 'v. 封装；概括',
    'enchant': 'v. 使着迷；施魔法',
    'encircle': 'v. 环绕；包围',
    'enclose': 'v. 包围；附上',
    'encompass': 'v. 包含；包围',
    'encounter': 'n./v. 遭遇；遇见',
    'encourage': 'v. 鼓励；激励',
    'endanger': 'v. 危及；危害',
    'endeavor': 'n./v. 努力；尝试',
    'ending': 'n. 结尾；结局',
    'endow': 'v. 赋予；捐赠',
    'endure': 'v. 忍受；持续',
    'enemy': 'n. 敌人；对手',
    'energetic': 'adj. 精力充沛的；积极的',
    'energy': 'n. 能量；精力',
    'enforce': 'v. 强制执行；实施',
    'engage': 'v. 参与；从事',
    'engine': 'n. 发动机；引擎',
    'engineer': 'n. 工程师；v. 设计',
    'english': 'adj. 英国的；n. 英语',
    'enhance': 'v. 增强；提高',
    'enjoy': 'v. 享受；喜欢',
    'enlarge': 'v. 扩大；放大',
    'enlighten': 'v. 启发；开导',
    'enlist': 'v. 入伍；招募',
    'enormous': 'adj. 巨大的；庞大的',
    'enough': 'adj./adv. 足够的；足够',
    'enquire': 'v. 询问；调查',
    'enrage': 'v. 激怒；使愤怒',
    'enrich': 'v. 丰富；使富裕',
    'enroll': 'v. 注册；报名',
    'enshrine': 'v. 供奉；铭记',
    'ensign': 'n. 旗；徽章',
    'ensure': 'v. 确保；保证',
    'entail': 'v. 需要；导致',
    'enter': 'v. 进入；参加',
    'enterprise': 'n. 企业；事业',
    'entertain': 'v. 娱乐；招待',
    'enthusiasm': 'n. 热情；积极性',
    'entire': 'adj. 整个的；全部的',
    'entitle': 'v. 给...权利；给...称号',
    'entity': 'n. 实体；存在',
    'entrance': 'n. 入口；v. 使着迷',
    'entreat': 'v. 恳求；请求',
    'entry': 'n. 进入；条目',
    'envelope': 'n. 信封；包裹',
    'environment': 'n. 环境；周围',
    'envoy': 'n. 使者；使节',
    'envy': 'n./v. 嫉妒；羡慕',
    'episode': 'n. 插曲；情节',
    'epoch': 'n. 时代；纪元',
    'equal': 'adj. 平等的；v. 等于',
    'equator': 'n. 赤道',
    'equity': 'n. 公平；股权',
    'equivalent': 'adj. 等价的；n. 等价物',
    'eradicate': 'v. 根除；消灭',
    'erase': 'v. 擦除；清除',
    'erect': 'adj. 直立的；v. 建立',
    'err': 'v. 犯错；出错',
    'error': 'n. 错误；误差',
    'escape': 'v./n. 逃跑；逃避',
    'escalate': 'v. 升级；增加',
    'escort': 'n./v. 护送；陪同',
    'essay': 'n. 散文；随笔',
    'essence': 'n. 本质；精华',
    'essential': 'adj. 必要的；本质的',
    'establish': 'v. 建立；确立',
    'estate': 'n. 地产；财产',
    'esteem': 'n./v. 尊重；尊敬',
    'estimate': 'n./v. 估计；估算',
    'ethic': 'n. 伦理；道德',
    'ethnic': 'adj. 种族的；民族的',
    'evacuate': 'v. 撤离；疏散',
    'evade': 'v. 逃避；规避',
    'evaluate': 'v. 评估；评价',
    'evaporate': 'v. 蒸发；消失',
    'eve': 'n. 前夕；前夜',
    'even': 'adj. 平坦的；adv. 甚至',
    'evident': 'adj. 明显的；显然的',
    'evil': 'adj. 邪恶的；n. 邪恶',
    'evoke': 'v. 唤起；引起',
    'evolution': 'n. 进化；演变',
    'evolve': 'v. 进化；发展',
    'exact': 'adj. 精确的；v. 强求',
    'exaggerate': 'v. 夸张；夸大',
    'examine': 'v. 检查；考试',
    'example': 'n. 例子；榜样',
    'exasperate': 'v. 激怒；使恼怒',
    'excavate': 'v. 挖掘；发掘',
    'exceed': 'v. 超过；超越',
    'excel': 'v. 擅长；突出',
    'except': 'prep. 除了；conj. 除非',
    'excerpt': 'n./v. 摘录；引用',
    'excess': 'n. 过量；adj. 过量的',
    'exchange': 'n./v. 交换；交流',
    'excite': 'v. 使兴奋；刺激',
    'exclaim': 'v. 呼喊；惊叫',
    'exclude': 'v. 排除；排斥',
    'exclusive': 'adj. 排他的；独家的',
    'excursion': 'n. 短途旅行；远足',
    'excuse': 'n./v. 借口；原谅',
    'execute': 'v. 执行；处死',
    'exert': 'v. 施加；运用',
    'exhale': 'v. 呼气；呼出',
    'exhaust': 'v. 耗尽；使疲惫',
    'exhibit': 'v. 展示；展览',
    'exile': 'n./v. 流放；放逐',
    'exist': 'v. 存在；生存',
    'exit': 'n./v. 出口；退出',
    'expand': 'v. 扩张；扩大',
    'expect': 'v. 期望；期待',
    'expedition': 'n. 远征；探险',
    'expel': 'v. 驱逐；开除',
    'expend': 'v. 花费；消耗',
    'expense': 'n. 费用；开支',
    'expensive': 'adj. 昂贵的；高价的',
    'experience': 'n./v. 经验；经历',
    'experiment': 'n./v. 实验；试验',
    'expert': 'n. 专家；adj. 专家的',
    'explain': 'v. 解释；说明',
    'explicit': 'adj. 明确的；显式的',
    'explode': 'v. 爆炸；爆发',
    'exploit': 'v. 利用；开发',
    'explore': 'v. 探索；探险',
    'export': 'n./v. 出口；输出',
    'expose': 'v. 暴露；揭露',
    'express': 'v. 表达；adj. 快速的',
    'extend': 'v. 延伸；扩展',
    'extent': 'n. 程度；范围',
    'exterior': 'adj. 外部的；n. 外部',
    'external': 'adj. 外部的；对外的',
    'extinct': 'adj. 灭绝的；绝种的',
    'extinguish': 'v. 熄灭；扑灭',
    'extra': 'adj. 额外的；n. 额外',
    'extract': 'v./n. 提取；摘录',
    'extraordinary': 'adj. 非凡的；特别的',
    'extravagant': 'adj. 奢侈的；过分的',
    'extreme': 'adj. 极端的；n. 极端',
    'eye': 'n. 眼睛；v. 注视',
    'fabric': 'n. 织物；结构',
    'facility': 'n. 设施；设备',
    'faction': 'n. 派系；派别',
    'factor': 'n. 因素；因子',
    'factory': 'n. 工厂；制造厂',
    'faint': 'adj. 微弱的；v. 晕倒',
    'fair': 'adj. 公平的；n. 集市',
    'faith': 'n. 信仰；信念',
    'fake': 'adj. 假的；n. 假货',
    'fall': 'v./n. 落下；秋天',
    'false': 'adj. 假的；错误的',
    'fame': 'n. 名声；名望',
    'family': 'n. 家庭；家族',
    'famine': 'n. 饥荒；饥饿',
    'fancy': 'adj. 花哨的；v. 想象',
    'fantasy': 'n. 幻想；想象',
    'far': 'adj./adv. 远的；远',
    'fare': 'n. 票价；v. 进展',
    'fascinate': 'v. 使着迷；吸引',
    'fashion': 'n. 时尚；方式',
    'fast': 'adj./adv. 快的；快',
    'fate': 'n. 命运；宿命',
    'father': 'n. 父亲；神父',
    'fault': 'n. 错误；故障',
    'favour': 'n./v. 支持；恩惠',
    'fear': 'n./v. 恐惧；害怕',
    'feature': 'n. 特征；v. 以...为特色',
    'federal': 'adj. 联邦的；联盟的',
    'fee': 'n. 费用；酬金',
    'feed': 'v. 喂养；n. 饲料',
    'feel': 'v. 感觉；触摸',
    'female': 'adj. 女性的；n. 女性',
    'fence': 'n. 栅栏；v. 击剑',
    'fertile': 'adj. 肥沃的；多产的',
    'fiction': 'n. 小说；虚构',
    'field': 'n. 田野；领域',
    'fierce': 'adj. 凶猛的；激烈的',
    'file': 'n. 文件；v. 归档',
    'fill': 'v. 填充；装满',
    'film': 'n. 电影；胶片',
    'final': 'adj. 最终的；n. 决赛',
    'finance': 'n. 金融；v. 资助',
    'find': 'v. 找到；发现',
    'fine': 'adj. 好的；n. 罚款',
    'finger': 'n. 手指',
    'finish': 'v./n. 完成；结束',
    'fire': 'n./v. 火；点燃',
    'firm': 'adj. 坚定的；n. 公司',
    'first': 'adj./adv. 第一的；首先',
    'fish': 'n. 鱼；v. 钓鱼',
    'fit': 'adj. 合适的；v. 适合',
    'fix': 'v. 修理；固定',
    'flag': 'n. 旗帜；v. 标记',
    'flame': 'n. 火焰；v. 燃烧',
    'flap': 'n./v. 拍打；飘动',
    'flare': 'n./v. 闪光；燃烧',
    'flash': 'n./v. 闪光；闪现',
    'flat': 'adj. 平坦的；n. 公寓',
    'flavor': 'n. 味道；风味',
    'flee': 'v. 逃跑；逃离',
    'fleet': 'n. 舰队；车队',
    'flesh': 'n. 肉；肉体',
    'flexible': 'adj. 灵活的；柔韧性的',
    'flight': 'n. 飞行；航班',
    'float': 'v./n. 漂浮；浮动',
    'flock': 'n. 群；v. 聚集',
    'flood': 'n./v. 洪水；泛滥',
    'floor': 'n. 地板；楼层',
    'flour': 'n. 面粉',
    'flourish': 'v./n. 繁荣；茂盛',
    'flow': 'v./n. 流动；流量',
    'flower': 'n. 花；v. 开花',
    'flu': 'n. 流感',
    'fluid': 'adj. 流动的；n. 流体',
    'flush': 'v./n. 冲洗；脸红',
    'flute': 'n. 长笛',
    'fly': 'v./n. 飞；苍蝇',
    'foam': 'n./v. 泡沫；起泡沫',
    'focus': 'n./v. 焦点；聚焦',
    'fog': 'n./v. 雾；起雾',
    'fold': 'v./n. 折叠；褶皱',
    'folk': 'adj. 民间的；n. 人们',
    'follow': 'v. 跟随；遵循',
    'food': 'n. 食物；食品',
    'fool': 'n. 傻瓜；v. 愚弄',
    'foot': 'n. 脚；英尺',
    'force': 'n./v. 力量；强迫',
    'foreign': 'adj. 外国的；外来的',
    'forest': 'n. 森林',
    'forget': 'v. 忘记；忽略',
    'forgive': 'v. 原谅；宽恕',
    'fork': 'n. 叉子；分叉',
    'form': 'n./v. 形式；形成',
    'former': 'adj. 以前的；n. 前者',
    'fortunate': 'adj. 幸运的；侥幸的',
    'fortune': 'n. 财富；运气',
    'forward': 'adj./adv. 向前的；向前',
    'fossil': 'n. 化石；adj. 化石的',
    'foster': 'v. 培养；促进',
    'found': 'v. 建立；创立'
  };
  
  let count = 0;
  words.forEach(w => {
    const lowerWord = w.word.toLowerCase();
    if (wordMap[lowerWord]) {
      w.meaning = wordMap[lowerWord];
      count++;
    }
  });
  
  const output = 'export interface IELTSWord {\n  id: string;\n  word: string;\n  meaning: string;\n  level: string;\n  root: string;\n  rootMeaning: string;\n  rootMeaningEn: string;\n  rootOrigin: string;\n  rootOriginNote: string;\n  relatedWords: { word: string; meaning: string; level: string }[];\n  phonetic: string;\n  frequency: string;\n  example: string;\n}\n\nexport const mockWords: IELTSWord[] = ' + JSON.stringify(words, null, 2) + ';';
  
  fs.writeFileSync('/home/fred/workspace/memoryworld-project/src/data/mockWords.ts', output);
  console.log('修复了 ' + count + ' 个单词的中文释义');
  console.log('保存成功!');
}